#!/bin/bash

trap "/home/pip/pip/pipstop" SIGTERM

cd `dirname $0`
rm -f *.mj[oe]
SCA_ERROR_DIR=$PWD/extcall_V1.2/alerts ; export SCA_ERROR_DIR
ALERT_SCRIPT=$PWD/extcall_V1.2/alerts/sca_alert.sh ; export ALERT_SCRIPT
. ./gtmenv
./mtm/PIPMTM
sleep 5
$gtm_dist/mupip journal -recover -backward gbls/pip.mjl \
 && $gtm_dist/mupip set -journal="enable,on,before" -file gbls/pip.dat \
 && ./dm <<EOF
do JOB^PBSUTL("SCA\$IBS",2)
halt
EOF
find gbls -iname pip.mjl_* -mtime +3 -exec rm -v {} \;

# Create a fifo so that bash can read from it to
# catch signals from docker
rm -f ~/fifo
mkfifo ~/fifo || exit
chmod 400 ~/fifo
read < ~/fifo
