CMSCONV(String DATA,String CONV)	//Public;PROFILE/CMS Conversion Routine
	/*
	   ORIG: BAILDONC - 12/15/97
	   DESC: PROFILE/CMS Conversion Routine

	   KEYWORDS:

	   ARGUMENTS:
	   . DATA Value to be converted /TYP=T/REQ/MECH=VAL

	   . CONV Conversion Method /TYP=T/REQ/MECH=VAL

	   INPUTS:
	   . INCFL Incoming Flag
	   . OUTFL Out-going Flag
	   RETURNS:
	   . DATA  Converted Value  /TYP=T

	   RELATED:
	   . $$func^rtn - description of how related

	   EXAMPLE:
	   Text of example (line one)

	   -------- Revision History ---------------------------------------------
	  
	    12/12/05 - SPR - 18555
		       Card Management - General DBI3 system area cleanup.

		
	   -----------------------------------------------------------------------

	*/
	
	if CONV.get()="" quit DATA.get()
	if CONV.get()=1 do TYPE(.DATA) quit DATA.get()
	if CONV.get()=2 do FRSTNM(.DATA) quit DATA.get()
	if CONV.get()=3 do DATE2(.DATA) quit DATA.get()
	if CONV.get()=4 do STATO(.DATA) quit DATA.get()
	if CONV.get()=5 do AMT(.DATA) quit DATA.get()
	if CONV.get()=6 do CRDSTATO(.DATA) quit DATA.get()
	if CONV.get()=7 do DATE1(.DATA) quit DATA.get()
	if CONV.get()=8 do CRDSTATI(.DATA) quit DATA.get()
	if CONV.get()=9 do STATI(.DATA) quit DATA.get()
	if CONV.get()=10 do NATION(.DATA) quit DATA.get()
	if CONV.get()=11 do BALANCE quit DATA.get()
	if CONV.get()=12 do DATE3(.DATA) quit DATA.get()
	if CONV.get()=13 do ACCTTYP(.DATA) quit DATA.get()
	if CONV.get()=14 do BRCD(.DATA) quit DATA.get()
	
	do DATE1(.DATA)
	
	quit
	

DATE1(String DATA)	// YDDD - Four digit Julian Date

	/*
	   This is a check on the direction of the file.  For files that go
	   both ways, the converted value must be the opposite for one direction
	   of what it is for the other.
	*/

	type public String INCFL
	type Number FRST,LST
	type String TJD1
	
	
	set TJD1=%SystemDate
	
	set FRST=TJD1.extract(1,1)
	set LST=TJD1.extract(2,TJD1.length())

	// Add some testing in case we are close to the first digit changing
	if INCFL.get()=1 set DATA=FRST_DATA
	else  set DATA=DATA.extract(2,DATA.length())

	quit


TYPE(String DATA)	// Customer Type
	/*
	   Only Personal accounts are considered Private, "01".  All other
	   customer types will be considered Company, "02"
	*/

	if DATA=0 set DATA="01"
	else  set DATA="02"

	quit


FRSTNM(String DATA)	//
	
	type String STRTFNM

	set STRTFNM=$find(DATA," ")
	set DATA=DATA.extract(STRTFNM,DATA.length())

	quit
	
	

DATE2(String DATA)	// YEARMMDD

	type String YR,MNTH,DAY

	set DATA=DATA.toString("YEAR/MM/DD")
	set YR=DATA.piece("/",1)
	set MNTH=DATA.piece("/",2)
	set DAY=DATA.piece("/",3)
	set DATA=YR_MNTH_DAY

	quit


DATE3(String DATA)	/* Julian from YYMM - Since PROFILE will only be given the last two digits
	   of the expiration year, this will assume that there will be no
	   back dated expiration dates, and this will only work for the next
	   century.
	*/

	type String YR,MONTH,YEAR,ENDDAY,NEWDATE

	set YR=DATA.extract(1,2)
	set MONTH=DATA.extract(3,4)
	set YEAR=$select(YR<98:"20"_YR,1:"19"_YR)
	set ENDDAY=$select("04,06,09,11"[MONTH:30,"01,03,05,07,08,10,12"[MONTH:31,(YR#4=0)&("00"'[YR):29,(YEAR.length()=4)&("000"[YEAR.extract(2,YEAR.length())):29,1:28)
	set NEWDATE=MONTH_"/"_ENDDAY_"/"_YEAR

	set DATA=NEWDATE.toDate("MM/DD/YEAR")

	quit


STATO(String DATA)	// Account Status Out

	//Active
	if DATA=0 set DATA="02" quit

	//Closed
	if DATA=4 set DATA="05"

	//Suspended
	else  set DATA="04"

	quit


AMT(String DATA)	// Removes the decimal point or adds implied two decimal position

	if DATA["." set DATA=DATA.piece(".",1)_DATA.piece(".",2) quit

	if DATA["," set DATA=DATA.piece(",",1)_DATA.piece(",",2)

	else  set DATA=DATA_"00"

	quit


CRDSTATO(String DATA)	//

	// Active
	if DATA=0 set DATA="02" quit

	// Canceled/Closed
	if DATA=5 set DATA="05"

	// Restricted
	else  set DATA="04"

	quit


CRDSTATI(String DATA)	//

	// Active
	if DATA="02" set DATA=0 quit

	// Canceled/Closed
	if DATA="05" set DATA=5

	// Active
	else  set DATA=0

	quit


STATI(String DATA)	//

	// Active
	if DATA="02" set DATA=0 quit

	// Canceled/Closed
	if DATA="05" set DATA=4

	// Inactive
	else  set DATA=1

	quit


BALANCE	//

	quit


NATION(String DATA)	//

	type RecordUTBLCMSNAT utblnat=Db.getRecord("UTBLCMSNAT","CNTRY=:DATA",1)

	set DATA=utblnat.cmscntry

	quit


ACCTTYP(String DATA)	//

	type RecordUTBLCMSATYP utblatyp=Db.getRecord("UTBLCMSATYP","ACCTTYP=:DATA",1)
	set DATA=utblatyp.cmsatyp

	if DATA.get()="" set DATA="01"

	quit


BRCD(String DATA)	//
	
	type RecordUTBLCMSBRCD utblbrcd=Db.getRecord("UTBLCMSBRCD","BRCD=:DATA",1)
	set DATA=utblbrcd.cmsbrcd

	quit

vSIG()	quit "60254^34123^Renga SP^4302"	// Signature - LTD^TIME^USER^SIZE
