CRTTOGL		//; Teller Posting Toggle utility (Multi/Non Multicurrency)
	/*
	       ORIG:  ROTELLA - 10 JAN 1992
	       DESC:
	
	
	    Routine Documentation:
	
	    This utility is used as a toggle at the teller key prompt to move
	    a teller between a multicurrency environment and a non
	    multicurrency environment.  This will be based upon the value of
	    ^CUVAR("CURRENV".
	
	   Values of "CURRENV" as follow:
	
	    0 = Totally non multicurrency
	    1 = Totally Multicurrency
	    2 = Toggle between the two environment
	
	
	    This utility should control ALL initialization that needs done for
	    either posting environment.  The use of the toggle key is supported
	    via a new function added to ^DBSCRT to support remapping of a key
	    on the keyboard map.  This function enables any key to be controlled
	    at a DATA QWIK prompt by using the following calls.
	
	   DATA QWIK field pre-processor should have: (Required)
	   (Use "SEL" key as example)
	
	   D REMAP^DBSCRT("SEL","ZSEL","D ^CRTTOGL")
	
	   parameters:
	
	    P1  =  Original key ("SEL")     -   Req
	    P2  =  Alternate key ("ZSEL")   -   Req
	    P3  =  Code tied to key ("D ^CRTTOGL")  -  Not Req
	
	
	   This function resets the keyboard map for the select key
	   "SEL" (ie. the scan code returned from the keyboard)
	   to be mapped to the alternate key ("ZSEL").  While the
	   map is there for "ZSEL" anytime the select key is depressed
	   the DATA QWIK will execute the code passed in parameter 3)
	   This is also used on the CRTOVR screen to support help
	   documentation when select is depressed.
	
	   DATA-QWIK field post-processor should have: (Required)
	
	   D REMAP^DBSCRT("SEL","ZSEL")
	
	   In this call the key will be reset back to the original map
	   since no code (parameter 3) is being passed to the remap
	   utility.  THIS SHOULD ALWAYS BE DONE TO ENSURE THAT NORMAL
	   KEYBOARD KEYS ARE NOT CLOBBERED !!!
	
	
	   --------------- Revision History -------------------------------------

	   10/10/01 - SCOTTC - 43583 Convert to PSL
	
	
	*/
	quit

public DFTENV(UID)

	/* Return default environment

	Arguments:
 
	. User ID					/TYP=T/REQ/MECH=VAL
 
	Returns:
 
	. User's default environment			/TYP=?
 
	Example:
 
	W $$DFTENV(123)
 
	*/

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")
	type RecordSCAU scau=Db.getRecord("SCAU","UID")

	if scau.currenv="" quit cuvar.dftenv
	quit scau.currenv
	

ENVDFT(UID)

	/*
	    This utility requires %UID to be passed to it to
	    determine if the user has a default environment or
	    should they be prompted when doing teller signon.
	    ie.  Is the user allowed (by User ID - %UID) to
	    redefine their default environment.
	
	    If this returns 0 then the system wide default will
	    be used ([CUVAR]DFTENV).

	Arguments:
 
	. User ID					/TYP=T/REQ/MECH=VAL
 
	Returns:
 
	. Current environment				/TYP=N
 
	Example:
 
	W $$DFTENV(123)
 
	*/	

	
	//User id not defined
	if '$G(UID) quit ""
	
	//Multi-currency not turned on
	if '%MCP quit 0

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")
	type RecordSCAU scau=Db.getRecord("SCAU","UID")

	//Dual currency not allowed
	if 'cuvar.currenv quit 0
	//Use the teller's definition
	quit scau.currenv
	
	

vSIG()	quit "59886^43501^Sanchez SCM Administrator^3017"	// Signature - LTD^TIME^USER^SIZE
