DEPBCC(CID) //Combined Collected Balance Calculation

	/* DESC: Combined Collected Balance Calculation includes linked Investment
        Account Balances.
	THis function is called from procedure BALCCL^DEPCDI and is used to
	compute [DEP]BALCCL Combined Collected Balance.
	
	ARGUMENTS:
	. CID		Account Number			/TYP=N/REQ/MECH=VAL
	
	RETURNS:
	. $$		Combined Collected Balance		/TYP=$

	EXAMPLE:	
	set XBALCCL=$$^DEPBCC(CID) Q: ER

	-----------Revision History--------------------------------------------

	11/22/05 - NATRAJAH - 13734
		   General DBI3 cleanup.

	02/29/00 - LUS - 35974 
		   Modified to pass CID to linkage rather than pass .dep.

	ORIG: LUS - Feburary,10,2000 - 35974
	
	*/

		 
        // Calculation Combined Collected Balance.
        type Number BALCOL
        type RecordDEP dep=Db.getRecord("DEP","CID=:CID")        
        set BALCOL=dep.balcol
 
        quit BALCOL+$$linkage(CID)
 
linkage(CID)  // - Total linked investment account collected balance
 
	/*       
        This function is used to total the Collected Balances of investment
        accounts linked the core account (CID).
        ARGUMENTS:
        CID             Account Number (Core)   /TYP=N/REQ/MECH=VAL
        RETURNS:
        $$          Total linked balance    /TYP=$
        EXAMPLE:
        set XBALCOL=BALCOL+$$linkage(CID)
        */
 
        type Number BALCOL,icidcbl,icid,ICID
        set BALCOL=0
  
        // Loop through DEP101, get account then its collected balance,
        // get next account & balance add each to BALCOL.
 	
	type ResultSet icid=Db.select("ICID","DEP101","CID=:CID")
        if icid.isEmpty() quit BALCOL
        while icid.next() do {
                set ICID=icid.getCol(1)
                type RecordDEP dep=Db.getRecord("DEP","CID=:ICID")
                set icidcbl=dep.balcol
                set BALCOL=BALCOL+icidcbl
                }
        quit BALCOL

vSIG()	quit "60226^33695^Hari Natrajan^1786"	// Signature - LTD^TIME^USER^SIZE
