DEPFIL1 // DEP DATA-QWIK filer, part (3)
 // Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:24 - shetyes

	quit		// Not called from top


vddver // Validate data dictionary attributes

	type public Number %O
	type public String vpar,vx()

	type String vRM,X
	type public RecordDEP dep

	if (%O = 2) do vload^DEPFILE

	if vobj(dep,1).exists() do {

		if dep.acctname.length()>25 set vRM = $$^MSG(1076,25) do vdderr("ACCTNAME", vRM) quit
		if dep.title1.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE1", vRM) quit
		if dep.title2.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE2", vRM) quit
		if dep.title3.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE3", vRM) quit
		if dep.title4.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE4", vRM) quit
	}

	if vobj(dep,49).exists() do {

		set X = dep.flg if 'X.isNull(),'Db.isDefined("STBLFLG","X") set vRM = $$^MSG(1485,X) do vdderr("FLG", vRM) quit
		if '("01"[dep.FNBODP) set vRM=$$^MSG(742,"L") do vdderr("FNBODP", vRM) quit
		if dep.iacm.length()>2 set vRM = $$^MSG(1076,2) do vdderr("IACM", vRM) quit
		set X = dep.iaf if 'X.isNull(),'Db.isDefined("STBLIAF","X") set vRM = $$^MSG(1485,X) do vdderr("IAF", vRM) quit
		set X = dep.icf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]ICF",0) if 'vRM.get().isNull() do vdderr("ICF", vRM) quit
		set X = dep.inccr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INCCR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.incdr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INCDR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intgrc if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("INTGRC", vRM) quit
		set X = dep.ircb if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("IRCB", vRM) quit
		set X = dep.maxacr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxcr if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXCR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxdr if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXDR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxdrct if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("MAXDRCT", vRM) quit
		set X = dep.minacr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MINACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.minbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MINBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mincr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MINCR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mindr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MINDR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.minopt if 'X.isNull(),'Db.isDefined("STBLMINOPT","X") set vRM = $$^MSG(1485,X) do vdderr("MINOPT", vRM) quit
		set X = dep.negacrpo if 'X.isNull(),'Db.isDefined("STBLNEGACRPO","X") set vRM = $$^MSG(1485,X) do vdderr("NEGACRPO", vRM) quit
		set X = dep.negbalop if 'X.isNull(),'Db.isDefined("STBLNEGBALOP","X") set vRM = $$^MSG(1485,X) do vdderr("NEGBALOP", vRM) quit
		set X = dep.negipo if 'X.isNull(),'Db.isDefined("STBLNIPO","X") set vRM = $$^MSG(1485,X) do vdderr("NEGIPO", vRM) quit
		set X = dep.negminint if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGMININT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negminop if 'X.isNull(),'Db.isDefined("STBLNIMIN","X") set vRM = $$^MSG(1485,X) do vdderr("NEGMINOP", vRM) quit
		set X = dep.notice if 'X.isNull(),'Db.isDefined("STBLNOTICE","X") set vRM = $$^MSG(1485,X) do vdderr("NOTICE", vRM) quit
		set X = dep.notmax if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NOTMAX", vRM) quit
		set X = dep.notmin if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NOTMIN", vRM) quit
		set X = dep.notnbc if 'X.isNull(),'Db.isDefined("UTBLNBD","X") set vRM = $$^MSG(1485,X) do vdderr("NOTNBC", vRM) quit
		set X = dep.odo if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("ODO", vRM) quit
		if '("01"[dep.ODSF) set vRM=$$^MSG(742,"L") do vdderr("ODSF", vRM) quit
		set X = dep.odsm if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ODSM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if dep.pdag.length()>8 set vRM = $$^MSG(1076,8) do vdderr("PDAG", vRM) quit
		set X = dep.pdys if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("PDYS", vRM) quit
		set X = dep.popt if 'X.isNull(),'Db.isDefined("STBLPOPT","X") set vRM = $$^MSG(1485,X) do vdderr("POPT", vRM) quit
		if dep.scc.length()>3 set vRM = $$^MSG(1076,3) do vdderr("SCC", vRM) quit
		set X = dep.trb if 'X.isNull(),'Db.isDefined("STBLDC","X") set vRM = $$^MSG(1485,X) do vdderr("TRB", vRM) quit
	}

	if vobj(dep,50).exists() do {

		set X = dep.acngrp if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("ACNGRP", vRM) quit
		if '("01"[dep.ANLSYS) set vRM=$$^MSG(742,"L") do vdderr("ANLSYS", vRM) quit
		set X = dep.aomcode if 'X.isNull(),'Db.isDefined("STBLCINTMET","X") set vRM = $$^MSG(1485,X) do vdderr("AOMCODE", vRM) quit
		if dep.atn.length()>50 set vRM = $$^MSG(1076,50) do vdderr("ATN", vRM) quit
		set X = dep.cc if 'X.isNull(),'Db.isDefined("UTBLCCNTR","X") set vRM = $$^MSG(1485,X) do vdderr("CC", vRM) quit
		set X = dep.ccode if 'X.isNull(),'Db.isDefined("UTBLCC","X") set vRM = $$^MSG(1485,X) do vdderr("CCODE", vRM) quit
		set X = dep.cls if 'X.isNull(),'Db.isDefined("STBLCLS","X") set vRM = $$^MSG(1485,X) do vdderr("CLS", vRM) quit
		set X = dep.co if 'X.isNull(),'Db.isDefined("UTBLCO","X") set vRM = $$^MSG(1485,X) do vdderr("CO", vRM) quit
		if '("01"[dep.COMM) set vRM=$$^MSG(742,"L") do vdderr("COMM", vRM) quit
		set X = dep.commfper if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.COMMFPER"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if dep.crcd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("CRCD", vRM) quit
		if '("01"[dep.CUSTOM1) set vRM=$$^MSG(742,"L") do vdderr("CUSTOM1", vRM) quit
		if '("01"[dep.CUSTOM2) set vRM=$$^MSG(742,"L") do vdderr("CUSTOM2", vRM) quit
		if '("01"[dep.CUSTOM3) set vRM=$$^MSG(742,"L") do vdderr("CUSTOM3", vRM) quit
		if '("01"[dep.EMPLBEN) set vRM=$$^MSG(742,"L") do vdderr("EMPLBEN", vRM) quit
		set X = dep.emplno if 'X.isNull(),'Db.isDefined("UTBLEMPLOYER","X") set vRM = $$^MSG(1485,X) do vdderr("EMPLNO", vRM) quit
		if dep.feepln.length()>5 set vRM = $$^MSG(1076,5) do vdderr("FEEPLN", vRM) quit
		set X = dep.fldstaff if 'X.isNull(),'Db.isDefined("UTBLFLDSTAFF","X") set vRM = $$^MSG(1485,X) do vdderr("FLDSTAFF", vRM) quit
		set X = dep.glsc if 'X.isNull(),'Db.isDefined("UTBLGLSC","X") set vRM = $$^MSG(1485,X) do vdderr("GLSC", vRM) quit
		set X = dep.grp if 'X.isNull(),'Db.isDefined("STBLGRP","CLS=""D"",GRP=:X") set vRM = $$^MSG(1485,X) do vdderr("GRP", vRM) quit
		if '("01"[dep.HIGHVOL) set vRM=$$^MSG(742,"L") do vdderr("HIGHVOL", vRM) quit
		if dep.lnm.length()>20 set vRM = $$^MSG(1076,20) do vdderr("LNM", vRM) quit
		set X = dep.mf if 'X.isNull(),'Db.isDefined("UTBLMF","X") set vRM = $$^MSG(1485,X) do vdderr("MF", vRM) quit
		if '("01"[dep.OID) set vRM=$$^MSG(742,"L") do vdderr("OID", vRM) quit
		set X = dep.pers if 'X.isNull(),'Db.isDefined("STBLPERS","X") set vRM = $$^MSG(1485,X) do vdderr("PERS", vRM) quit
		if '("01"[dep.REGCC) set vRM=$$^MSG(742,"L") do vdderr("REGCC", vRM) quit
		set X = dep.regccexc if 'X.isNull(),'Db.isDefined("STBLREGCCX","X") set vRM = $$^MSG(1485,X) do vdderr("REGCCEXC", vRM) quit
		set X = dep.regccexp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("REGCCEXP", vRM) quit
		set X = dep.regd if 'X.isNull(),'Db.isDefined("STBLREGD1","X") set vRM = $$^MSG(1485,X) do vdderr("REGD", vRM) quit
		set X = dep.secgrp if 'X.isNull(),'Db.isDefined("UTBLSECGRP","X") set vRM = $$^MSG(1485,X) do vdderr("SECGRP", vRM) quit
		set X = dep.type if 'X.isNull(),'Db.isDefined("PRODCTL","X") set vRM = $$^MSG(1485,X) do vdderr("TYPE", vRM) quit
	}

	if vobj(dep,51).exists() do {

		if '("01"[dep.ADF) set vRM=$$^MSG(742,"L") do vdderr("ADF", vRM) quit
		if '("01"[dep.ARS) set vRM=$$^MSG(742,"L") do vdderr("ARS", vRM) quit
		set X = dep.bal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.BAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.balcol if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.BALCOL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ccld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CCLD", vRM) quit
		set X = dep.chkhld if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CHKHLD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cntcr if 'X.isNull(),X'?1.10N,X'?1"-"1.9N set vRM=$$^MSG(742,"N") do vdderr("CNTCR", vRM) quit
		set X = dep.cntdr if 'X.isNull(),X'?1.10N,X'?1"-"1.9N set vRM=$$^MSG(742,"N") do vdderr("CNTDR", vRM) quit
		if '("01"[dep.COLELG) set vRM=$$^MSG(742,"L") do vdderr("COLELG", vRM) quit
		set X = dep.dclrsk if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DCLRSK"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.donrsk if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DONRSK"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.flttbl if 'X.isNull(),'Db.isDefined("UTBLRTTBL","X") set vRM = $$^MSG(1485,X) do vdderr("FLTTBL", vRM) quit
		set X = dep.fmld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("FMLD", vRM) quit
		set X = dep.gcrrsk if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.GCRRSK"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.hldtbl if 'X.isNull(),'Db.isDefined("UTBLRTTBL","X") set vRM = $$^MSG(1485,X) do vdderr("HLDTBL", vRM) quit
		set X = dep.intavl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTAVL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intavlncr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTAVLNCR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intprior if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTPRIOR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ira if 'X.isNull(),'Db.isDefined("UTBLRSPDEF","X") set vRM = $$^MSG(1485,X) do vdderr("IRA", vRM) quit
		if '("01"[dep.LPDUE) set vRM=$$^MSG(742,"L") do vdderr("LPDUE", vRM) quit
		if '("01"[dep.LPSWP) set vRM=$$^MSG(742,"L") do vdderr("LPSWP", vRM) quit
		set X = dep.netdep if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NETDEP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.notdat if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NOTDAT", vRM) quit
		if '("01"[dep.ODSI) set vRM=$$^MSG(742,"L") do vdderr("ODSI", vRM) quit
		if '("01"[dep.PBI) set vRM=$$^MSG(742,"L") do vdderr("PBI", vRM) quit
		if '("01"[dep.PHLD) set vRM=$$^MSG(742,"L") do vdderr("PHLD", vRM) quit
		if '("01"[dep.PLDG) set vRM=$$^MSG(742,"L") do vdderr("PLDG", vRM) quit
		if '("01"[dep.RFLG) set vRM=$$^MSG(742,"L") do vdderr("RFLG", vRM) quit
		set X = dep.rpaseq if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("RPASEQ", vRM) quit
		set X = dep.rskopt if 'X.isNull(),'Db.isDefined("STBLRSKOPT","X") set vRM = $$^MSG(1485,X) do vdderr("RSKOPT", vRM) quit
		if dep.rskpln.length()>12 set vRM = $$^MSG(1076,12) do vdderr("RSKPLN", vRM) quit
		set X = dep.sdavl if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SDAVL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.secrsk if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SECRSK"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.secval if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SECVAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.stat if 'X.isNull(),'Db.isDefined("STBLSTAT","X") set vRM = $$^MSG(1485,X) do vdderr("STAT", vRM) quit
		set X = dep.stfnet if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.STFNET"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if dep.stp.length()>40 set vRM = $$^MSG(1076,40) do vdderr("STP", vRM) quit
		set X = dep.stp1 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP1", vRM) quit
		set X = dep.stp2 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP2", vRM) quit
		set X = dep.stp3 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP3", vRM) quit
		set X = dep.stp4 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP4", vRM) quit
		set X = dep.stp5 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP5", vRM) quit
		set X = dep.stp6 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP6", vRM) quit
		set X = dep.stp7 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP7", vRM) quit
		set X = dep.stp8 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP8", vRM) quit
		set X = dep.stp9 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP9", vRM) quit
		set X = dep.tld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("TLD", vRM) quit
	}

	if vobj(dep,52).exists() do {

		set X = dep.boo if 'X.isNull(),'Db.isDefined("UTBLBRCD","X") set vRM = $$^MSG(1485,X) do vdderr("BOO", vRM) quit
		if dep.convacn.length()>40 set vRM = $$^MSG(1076,40) do vdderr("CONVACN", vRM) quit
		set X = dep.convawt if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVAWT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.convbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.convcmp if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVCMP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.convdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CONVDT", vRM) quit
		set X = dep.convna if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVNA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.convnau if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVNAU"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.convpa if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVPA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.convua if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVUA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dtc if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DTC", vRM) quit
		set X = dep.hisctf if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("HISCTF", vRM) quit
		if '("01"[dep.IRAEXC) set vRM=$$^MSG(742,"L") do vdderr("IRAEXC", vRM) quit
		set X = dep.iro if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IRO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxfta if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXFTA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxftd if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("MAXFTD", vRM) quit
		set X = dep.odt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ODT", vRM) quit
		set X = dep.off if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("OFF", vRM) quit
		set X = dep.off2 if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("OFF2", vRM) quit
		set X = dep.onp if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ONP", vRM) quit
		if dep.osf.length()>30 set vRM = $$^MSG(1076,30) do vdderr("OSF", vRM) quit
		if dep.pid.length()>20 set vRM = $$^MSG(1076,20) do vdderr("PID", vRM) quit
		if dep.refnum.length()>12 set vRM = $$^MSG(1076,12) do vdderr("REFNUM", vRM) quit
		set X = dep.rescd if 'X.isNull(),'Db.isDefined("UTBLRESCD","X") set vRM = $$^MSG(1485,X) do vdderr("RESCD", vRM) quit
		if '("01"[dep.TRUNC) set vRM=$$^MSG(742,"L") do vdderr("TRUNC", vRM) quit
	}

	if vobj(dep,53).exists() do {

		set X = dep.busopt if 'X.isNull(),'Db.isDefined("STBLBUSOPT","X") set vRM = $$^MSG(1485,X) do vdderr("BUSOPT", vRM) quit
		set X = dep.dftmdt if 'X.isNull(),'Db.isDefined("UTBLDFT1","DFTTYP=""MDT"",DFTGRP=:X") set vRM = $$^MSG(1485,X) do vdderr("DFTMDT", vRM) quit
		set X = dep.dlr if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DLR", vRM) quit
		set X = dep.ero if 'X.isNull(),'Db.isDefined("STBLERO","X") set vRM = $$^MSG(1485,X) do vdderr("ERO", vRM) quit
		set X = dep.gopt if 'X.isNull(),'Db.isDefined("STBLGOPT","X") set vRM = $$^MSG(1485,X) do vdderr("GOPT", vRM) quit
		set X = dep.intavlr if 'X.isNull(),'Db.isDefined("STBLINTAVLR","X") set vRM = $$^MSG(1485,X) do vdderr("INTAVLR", vRM) quit
		set X = dep.irlm if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IRLM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("MDT", vRM) quit
		if '("01"[dep.MDTEXT) set vRM=$$^MSG(742,"L") do vdderr("MDTEXT", vRM) quit
		set X = dep.mld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("MLD", vRM) quit
		set X = dep.nbdc if 'X.isNull(),'Db.isDefined("UTBLNBD","X") set vRM = $$^MSG(1485,X) do vdderr("NBDC", vRM) quit
		set X = dep.ntr if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NTR", vRM) quit
		set X = dep.org if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ORG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.orgdisc if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ORGDISC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmedat if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PMEDAT", vRM) quit
		set X = dep.pmo if 'X.isNull(),'Db.isDefined("STBLPMO","X") set vRM = $$^MSG(1485,X) do vdderr("PMO", vRM) quit
		set X = dep.racn if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("RACN", vRM) quit
		set X = dep.rencd if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("RENCD", vRM) quit
		set X = dep.rro if 'X.isNull(),'Db.isDefined("STBLRRO","X") set vRM = $$^MSG(1485,X) do vdderr("RRO", vRM) quit
		set X = dep.salesprc if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SALESPRC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if dep.trm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("TRM", vRM) quit
	}

	if vobj(dep,54).exists() do {

		set X = dep.acs if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ACS", vRM) quit
		if dep.aecamt.length()>40 set vRM = $$^MSG(1076,40) do vdderr("AECAMT", vRM) quit
		set X = dep.bnot1dt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BNOT1DT", vRM) quit
		set X = dep.bnot2dt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BNOT2DT", vRM) quit
		if '("01"[dep.BWF) set vRM=$$^MSG(742,"L") do vdderr("BWF", vRM) quit
		set X = dep.bwp if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.BWP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.bwy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.BWY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cmp if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CMP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cmp1 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CMP1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cmp2 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CMP2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cmp3 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CMP3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cmp4 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CMP4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cnotdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CNOTDT", vRM) quit
		set X = dep.daa if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.daa1 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAA1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.daa2 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAA2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.daa3 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAA3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.daa4 if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAA4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dbi if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DBI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dbi1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DBI1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dbi2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DBI2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dbi3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DBI3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dbi4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DBI4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.fwp if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.FWP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.fwy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.FWY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.hirn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.HIRN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intchk if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("INTCHK", vRM) quit
		set X = dep.intdef if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTDEF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intwcalc if 'X.isNull(),'Db.isDefined("UTBLWCALC","X") set vRM = $$^MSG(1485,X) do vdderr("INTWCALC", vRM) quit
		set X = dep.intwr if 'X.isNull(),'Db.isDefined("UTBLINTWR","X") set vRM = $$^MSG(1485,X) do vdderr("INTWR", vRM) quit
		set X = dep.iopt if 'X.isNull(),'Db.isDefined("STBLIOPT","X") set vRM = $$^MSG(1485,X) do vdderr("IOPT", vRM) quit
		set X = dep.ipda if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPDA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipdaadj if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPDAADJ"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipdtrf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPDTRF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipl if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipnd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPND"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipy if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.itrf if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("ITRF", vRM) quit
		set X = dep.itro if 'X.isNull(),'Db.isDefined("STBLITROCAN","X") set vRM = $$^MSG(1485,X) do vdderr("ITRO", vRM) quit
		if '("01"[dep.IWCP) set vRM=$$^MSG(742,"L") do vdderr("IWCP", vRM) quit
		set X = dep.iytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbacrdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LBACRDT", vRM) quit
		if dep.lifjur.length()>12 set vRM = $$^MSG(1076,12) do vdderr("LIFJUR", vRM) quit
		set X = dep.minavg if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MINAVG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.minint if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MININT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negacr if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negacrun if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGACRUN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negipl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGIPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negipy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGIPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negiytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGIYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.NR) set vRM=$$^MSG(742,"L") do vdderr("NR", vRM) quit
		set X = dep.nrnegicy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRNEGICY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrnegipy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRNEGIPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrpcy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPCY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrposicy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPOSICY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrposipy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPOSIPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwacy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWACY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwapy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWAPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwhcy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWHCY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwhpy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWHPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.posacr if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.POSACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.probal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PROBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.proind if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("PROIND", vRM) quit
		if dep.promat.length()>7 set vRM = $$^MSG(1076,7) do vdderr("PROMAT", vRM) quit
		if dep.prornd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("PRORND", vRM) quit
		if dep.prospr.length()>9 set vRM = $$^MSG(1076,9) do vdderr("PROSPR", vRM) quit
		set X = dep.resint if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RESINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.swp if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SWP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.swy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SWY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.trate if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TRATE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.trexd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("TREXD", vRM) quit
	}

	if vobj(dep,55).exists() do {

		set X = dep.darcexpd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DARCEXPD", vRM) quit
		set X = dep.darcls if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DARCLS", vRM) quit
		set X = dep.darcovr if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DARCOVR", vRM) quit
		set X = dep.penpw if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PENPW"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pindex if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("PINDEX", vRM) quit
		set X = dep.pint if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.PIPW) set vRM=$$^MSG(742,"L") do vdderr("PIPW", vRM) quit
		set X = dep.ppl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.prate if 'X.isNull() set vRM = $$VAL^DBSVER("$",8,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PRATE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.prm if 'X.isNull(),'Db.isDefined("STBLPRM","X") set vRM = $$^MSG(1485,X) do vdderr("PRM", vRM) quit
		set X = dep.prs if 'X.isNull(),'Db.isDefined("UTBLRATE","X") set vRM = $$^MSG(1485,X) do vdderr("PRS", vRM) quit
		set X = dep.pthresh if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PTHRESH"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pxd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PXD", vRM) quit
		if dep.pxtrm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("PXTRM", vRM) quit
		set X = dep.pytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.suspect if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("SUSPECT", vRM) quit
	}

	if vobj(dep,57).exists() do {

		set X = dep.eod if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EOD", vRM) quit
		set X = dep.ichld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ICHLD", vRM) quit
		set X = dep.ichnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ICHND", vRM) quit
		set X = dep.icpf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]ICPF",0) if 'vRM.get().isNull() do vdderr("ICPF", vRM) quit
		set X = dep.ilc if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ILC", vRM) quit
		set X = dep.inc if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INC", vRM) quit
		set X = dep.inp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INP", vRM) quit
		set X = dep.intaf if 'X.isNull() set vRM = $$VAL^DBSVER("N",10,0,,,,,6) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTAF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intmn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTMN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intmx if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTMX"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intramt1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTRAMT1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intramt2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTRAMT2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intramt3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTRAMT3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intrexp1 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTREXP1", vRM) quit
		set X = dep.intrexp2 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTREXP2", vRM) quit
		set X = dep.intrexp3 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTREXP3", vRM) quit
		set X = dep.intrrat1 if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTRRAT1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intrrat2 if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTRRAT2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intrrat3 if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTRRAT3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("IPLD", vRM) quit
		set X = dep.irf if 'X.isNull(),'Db.isDefined("STBLIRF","X") set vRM = $$^MSG(1485,X) do vdderr("IRF", vRM) quit
		set X = dep.irn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IRN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.irsexm if 'X.isNull(),'Db.isDefined("STBLIRS1099","X") set vRM = $$^MSG(1485,X) do vdderr("IRSEXM", vRM) quit
		set X = dep.neginp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGINP", vRM) quit
		set X = dep.negipld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGIPLD", vRM) quit
		set X = dep.sch if 'X.isNull(),'Db.isDefined("UTBLRATE","X") set vRM = $$^MSG(1485,X) do vdderr("SCH", vRM) quit
		if '("01"[dep.SEGFLG) set vRM=$$^MSG(742,"L") do vdderr("SEGFLG", vRM) quit
	}

	if vobj(dep,60).exists() do {

		if dep.compirn.length()>10 set vRM = $$^MSG(1076,10) do vdderr("COMPIRN", vRM) quit
		set X = dep.deldt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DELDT", vRM) quit
		set X = dep.index if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX", vRM) quit
		set X = dep.index1 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX1", vRM) quit
		set X = dep.index10 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX10", vRM) quit
		set X = dep.index2 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX2", vRM) quit
		set X = dep.index3 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX3", vRM) quit
		set X = dep.index4 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX4", vRM) quit
		set X = dep.index5 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX5", vRM) quit
		set X = dep.index6 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX6", vRM) quit
		set X = dep.index7 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX7", vRM) quit
		set X = dep.index8 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX8", vRM) quit
		set X = dep.index9 if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX9", vRM) quit
		set X = dep.intchkbkt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTCHKBKT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intchkfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]INTCHKFRE",0) if 'vRM.get().isNull() do vdderr("INTCHKFRE", vRM) quit
		set X = dep.intchkld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTCHKLD", vRM) quit
		set X = dep.intchkmin if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTCHKMIN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intchknd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTCHKND", vRM) quit
		set X = dep.intfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]INTFRE",0) if 'vRM.get().isNull() do vdderr("INTFRE", vRM) quit
		set X = dep.intmat if 'X.isNull(),'Db.isDefined("UTBLMATATT","X") set vRM = $$^MSG(1485,X) do vdderr("INTMAT", vRM) quit
		set X = dep.intmxdc if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTMXDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intmxdl if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTMXDL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intmxic if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTMXIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intmxil if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INTMXIL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.intoff if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("INTOFF", vRM) quit
		if dep.intspr.length()>9 set vRM = $$^MSG(1076,9) do vdderr("INTSPR", vRM) quit
		set X = dep.ipf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]IPF",0) if 'vRM.get().isNull() do vdderr("IPF", vRM) quit
		set X = dep.negipf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]NEGIPF",0) if 'vRM.get().isNull() do vdderr("NEGIPF", vRM) quit
		set X = dep.odexp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ODEXP", vRM) quit
		set X = dep.odlim if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,"0.00",,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ODLIM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.odstart if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ODSTART", vRM) quit
		if dep.odterm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("ODTERM", vRM) quit
		set X = dep.pmxddc if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXDDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmxddl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXDDL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmxdic if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXDIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmxdil if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXDIL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmxpdc if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXPDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmxpdl if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXPDL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmxpic if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXPIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pmxpil if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PMXPIL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.prcb if 'X.isNull(),'Db.isDefined("STBLPRCB","X") set vRM = $$^MSG(1485,X) do vdderr("PRCB", vRM) quit
		if dep.rndmtd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("RNDMTD", vRM) quit
		if dep.trmmx.length()>8 set vRM = $$^MSG(1076,8) do vdderr("TRMMX", vRM) quit
	}

	if vobj(dep,61).exists() do {

		if '("01"[dep.CHKACTF) set vRM=$$^MSG(742,"L") do vdderr("CHKACTF", vRM) quit
		set X = dep.chkcnt if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CHKCNT", vRM) quit
		if '("01"[dep.CHKEURO) set vRM=$$^MSG(742,"L") do vdderr("CHKEURO", vRM) quit
		if '("01"[dep.CHKISS) set vRM=$$^MSG(742,"L") do vdderr("CHKISS", vRM) quit
		set X = dep.chkout if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("CHKOUT", vRM) quit
		set X = dep.chks if 'X.isNull(),'Db.isDefined("UTBLCHKS","X") set vRM = $$^MSG(1485,X) do vdderr("CHKS", vRM) quit
		set X = dep.fltd1 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD1", vRM) quit
		set X = dep.fltd2 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD2", vRM) quit
		set X = dep.fltd3 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD3", vRM) quit
		set X = dep.fltd4 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD4", vRM) quit
		set X = dep.fltd5 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD5", vRM) quit
		set X = dep.fltp1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP1", vRM) quit
		set X = dep.fltp2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP2", vRM) quit
		set X = dep.fltp3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP3", vRM) quit
		set X = dep.fltp4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP4", vRM) quit
		set X = dep.fltp5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP5", vRM) quit
		set X = dep.hldd1 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD1", vRM) quit
		set X = dep.hldd2 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD2", vRM) quit
		set X = dep.hldd3 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD3", vRM) quit
		set X = dep.hldd4 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD4", vRM) quit
		set X = dep.hldd5 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD5", vRM) quit
		set X = dep.hldp1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP1", vRM) quit
		set X = dep.hldp2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP2", vRM) quit
		set X = dep.hldp3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP3", vRM) quit
		set X = dep.hldp4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP4", vRM) quit
		set X = dep.hldp5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP5", vRM) quit
	}

	if vobj(dep,62).exists() do {

		if '("01"[dep.ACTIBPAY) set vRM=$$^MSG(742,"L") do vdderr("ACTIBPAY", vRM) quit
		set X = dep.cnfld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CNFLD", vRM) quit
		set X = dep.commefd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("COMMEFD", vRM) quit
		set X = dep.commfee if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.COMMFEE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.EFTDD) set vRM=$$^MSG(742,"L") do vdderr("EFTDD", vRM) quit
		if '("01"[dep.EFTDEB) set vRM=$$^MSG(742,"L") do vdderr("EFTDEB", vRM) quit
		if '("01"[dep.EFTREQ) set vRM=$$^MSG(742,"L") do vdderr("EFTREQ", vRM) quit
		if '("01"[dep.ELIGBPAY) set vRM=$$^MSG(742,"L") do vdderr("ELIGBPAY", vRM) quit
		set X = dep.feeopt if 'X.isNull(),'Db.isDefined("STBLFEEF","X") set vRM = $$^MSG(1485,X) do vdderr("FEEOPT", vRM) quit
		set X = dep.feewvd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("FEEWVD", vRM) quit
		set X = dep.ftrf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.FTRF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxtrf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXTRF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mintrf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MINTRF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.otrtrf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.OTRTRF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.scfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]SCFRE",0) if 'vRM.get().isNull() do vdderr("SCFRE", vRM) quit
		set X = dep.scld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SCLD", vRM) quit
		set X = dep.scnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SCND", vRM) quit
		if '("01"[dep.SMET) set vRM=$$^MSG(742,"L") do vdderr("SMET", vRM) quit
		if dep.stmdscd.length()>30 set vRM = $$^MSG(1076,30) do vdderr("STMDSCD", vRM) quit
		set X = dep.svcfeecid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("SVCFEECID", vRM) quit
		set X = dep.swpbo if 'X.isNull(),'Db.isDefined("STBLBBO","X") set vRM = $$^MSG(1485,X) do vdderr("SWPBO", vRM) quit
		set X = dep.swpf if 'X.isNull(),'Db.isDefined("STBLSWPF","X") set vRM = $$^MSG(1485,X) do vdderr("SWPF", vRM) quit
		set X = dep.swpile if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SWPILE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.SWPNI) set vRM=$$^MSG(742,"L") do vdderr("SWPNI", vRM) quit
		set X = dep.swpopt if 'X.isNull(),'Db.isDefined("STBLSWPO","X") set vRM = $$^MSG(1485,X) do vdderr("SWPOPT", vRM) quit
		set X = dep.swppln if 'X.isNull(),'Db.isDefined("UTBLINVPLN","X") set vRM = $$^MSG(1485,X) do vdderr("SWPPLN", vRM) quit
		set X = dep.swpt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SWPT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,63).exists() do {

		set X = dep.anlacm if 'X.isNull(),'Db.isDefined("STBLIACM","X") set vRM = $$^MSG(1485,X) do vdderr("ANLACM", vRM) quit
		set X = dep.anlchg if 'X.isNull(),'Db.isDefined("STBLANLC","X") set vRM = $$^MSG(1485,X) do vdderr("ANLCHG", vRM) quit
		set X = dep.anlicf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]ANLICF",0) if 'vRM.get().isNull() do vdderr("ANLICF", vRM) quit
		set X = dep.anlidx if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("ANLIDX", vRM) quit
		set X = dep.anlirf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]ANLIRF",0) if 'vRM.get().isNull() do vdderr("ANLIRF", vRM) quit
		set X = dep.anlirn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ANLIRN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.anlmba if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ANLMBA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.anlmbo if 'X.isNull(),'Db.isDefined("STBLANLM","X") set vRM = $$^MSG(1485,X) do vdderr("ANLMBO", vRM) quit
		set X = dep.anlrcb if 'X.isNull(),'Db.isDefined("STBLANLI","X") set vRM = $$^MSG(1485,X) do vdderr("ANLRCB", vRM) quit
		set X = dep.upfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]UPFRE",0) if 'vRM.get().isNull() do vdderr("UPFRE", vRM) quit
		set X = dep.upldt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("UPLDT", vRM) quit
		set X = dep.upndt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("UPNDT", vRM) quit
		if dep.uspl.length()>5 set vRM = $$^MSG(1076,5) do vdderr("USPL", vRM) quit
	}

	if vobj(dep,65).exists() do {

		if dep.ckc.length()>10 set vRM = $$^MSG(1076,10) do vdderr("CKC", vRM) quit
		if dep.cktyp.length()>10 set vRM = $$^MSG(1076,10) do vdderr("CKTYP", vRM) quit
		set X = dep.cod if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("COD", vRM) quit
		set X = dep.nock if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("NOCK", vRM) quit
		set X = dep.scn if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("SCN", vRM) quit
	}

	if vobj(dep,66).exists() do {

		set X = dep.vosdate if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("VOSDATE", vRM) quit
		if '("01"[dep.VOSELEC) set vRM=$$^MSG(742,"L") do vdderr("VOSELEC", vRM) quit
		set X = dep.vosfreq if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]VOSFREQ",0) if 'vRM.get().isNull() do vdderr("VOSFREQ", vRM) quit
		set X = dep.vosnsdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("VOSNSDT", vRM) quit
		set X = dep.vosnum if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("VOSNUM", vRM) quit
		if '("01"[dep.VOSSTMT) set vRM=$$^MSG(742,"L") do vdderr("VOSSTMT", vRM) quit
		if '("01"[dep.VOSTRO) set vRM=$$^MSG(742,"L") do vdderr("VOSTRO", vRM) quit
	}

	if vobj(dep,67).exists() do {

		set X = dep.ddbal1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal10 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL10"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal11 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL11"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal12 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL12"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal6 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL6"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal7 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL7"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal8 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL8"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbal9 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBAL9"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ddbalcur if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DDBALCUR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,68).exists() do {

		set X = dep.mebal1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal10 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL10"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal11 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL11"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal12 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL12"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal6 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL6"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal7 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL7"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal8 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL8"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.mebal9 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MEBAL9"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef10 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF10"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef6 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF6"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef7 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF7"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef8 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF8"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.usrdef9 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.USRDEF9"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,70).exists() do {

		if '("01"[dep.CMSFLG) set vRM=$$^MSG(742,"L") do vdderr("CMSFLG", vRM) quit
	}

	if vobj(dep,90).exists() do {

		set X = dep.dci if 'X.isNull(),'Db.isDefined("STBLDCI","X") set vRM = $$^MSG(1485,X) do vdderr("DCI", vRM) quit
		if dep.treascid.length()>20 set vRM = $$^MSG(1076,20) do vdderr("TREASCID", vRM) quit
	}

	if vobj(dep,98).exists() do {

		set X = dep.corre if 'X.isNull(),'Db.isDefined("UTBLCORRE","X") set vRM = $$^MSG(1485,X) do vdderr("CORRE", vRM) quit
		if dep.correacn.length()>35 set vRM = $$^MSG(1076,35) do vdderr("CORREACN", vRM) quit
	}

	if vobj(dep,99).exists() do {

		set X = dep.acn if 'X.isNull(),'Db.isDefined("CIF","X") set vRM = $$^MSG(1485,X) do vdderr("ACN", vRM) quit
		if dep.acnrelc.length()>2 set vRM = $$^MSG(1076,2) do vdderr("ACNRELC", vRM) quit
		if dep.aplid.length()>25 set vRM = $$^MSG(1076,25) do vdderr("APLID", vRM) quit
	}

	if vobj(dep,100).exists() do {

		set X = dep.mmda1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("MMDA1", vRM) quit
		set X = dep.mmda2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("MMDA2", vRM) quit
		set X = dep.mmda3 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("MMDA3", vRM) quit
		set X = dep.mmda4 if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]MMDA4",0) if 'vRM.get().isNull() do vdderr("MMDA4", vRM) quit
		set X = dep.nbodplm if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NBODPLM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nsflim if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NSFLIM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nsfold if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NSFOLD", vRM) quit
		set X = dep.ntodplm if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NTODPLM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.odbb if 'X.isNull(),'Db.isDefined("STBLODBB","X") set vRM = $$^MSG(1485,X) do vdderr("ODBB", vRM) quit
		if '("01"[dep.ODFLG) set vRM=$$^MSG(742,"L") do vdderr("ODFLG", vRM) quit
		set X = dep.odld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ODLD", vRM) quit
		set X = dep.odsbb if 'X.isNull(),'Db.isDefined("STBLODBB","X") set vRM = $$^MSG(1485,X) do vdderr("ODSBB", vRM) quit
		set X = dep.rc if 'X.isNull(),'Db.isDefined("STBLRC","X") set vRM = $$^MSG(1485,X) do vdderr("RC", vRM) quit
		set X = dep.retold if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("RETOLD", vRM) quit
		set X = dep.wcc if 'X.isNull(),'Db.isDefined("STBLWCC","X") set vRM = $$^MSG(1485,X) do vdderr("WCC", vRM) quit
	}

	if vobj(dep,103).exists() do {

		set X = dep.nsfi1 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI1", vRM) quit
		set X = dep.nsfi10 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI10", vRM) quit
		set X = dep.nsfi11 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI11", vRM) quit
		set X = dep.nsfi12 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI12", vRM) quit
		set X = dep.nsfi13 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI13", vRM) quit
		set X = dep.nsfi14 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI14", vRM) quit
		set X = dep.nsfi15 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI15", vRM) quit
		set X = dep.nsfi16 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI16", vRM) quit
		set X = dep.nsfi17 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI17", vRM) quit
		set X = dep.nsfi18 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI18", vRM) quit
		set X = dep.nsfi19 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI19", vRM) quit
		set X = dep.nsfi2 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI2", vRM) quit
		set X = dep.nsfi20 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI20", vRM) quit
		set X = dep.nsfi21 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI21", vRM) quit
		set X = dep.nsfi22 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI22", vRM) quit
		set X = dep.nsfi23 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI23", vRM) quit
		set X = dep.nsfi24 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI24", vRM) quit
		set X = dep.nsfi3 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI3", vRM) quit
		set X = dep.nsfi4 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI4", vRM) quit
		set X = dep.nsfi5 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI5", vRM) quit
		set X = dep.nsfi6 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI6", vRM) quit
		set X = dep.nsfi7 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI7", vRM) quit
		set X = dep.nsfi8 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI8", vRM) quit
		set X = dep.nsfi9 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NSFI9", vRM) quit
		set X = dep.nsfo1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO1", vRM) quit
		set X = dep.nsfo10 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO10", vRM) quit
		set X = dep.nsfo11 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO11", vRM) quit
		set X = dep.nsfo12 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO12", vRM) quit
		set X = dep.nsfo13 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO13", vRM) quit
		set X = dep.nsfo14 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO14", vRM) quit
		set X = dep.nsfo15 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO15", vRM) quit
		set X = dep.nsfo16 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO16", vRM) quit
		set X = dep.nsfo17 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO17", vRM) quit
		set X = dep.nsfo18 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO18", vRM) quit
		set X = dep.nsfo19 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO19", vRM) quit
		set X = dep.nsfo2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO2", vRM) quit
		set X = dep.nsfo20 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO20", vRM) quit
		set X = dep.nsfo21 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO21", vRM) quit
		set X = dep.nsfo22 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO22", vRM) quit
		set X = dep.nsfo23 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO23", vRM) quit
		set X = dep.nsfo24 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO24", vRM) quit
		set X = dep.nsfo3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO3", vRM) quit
		set X = dep.nsfo4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO4", vRM) quit
		set X = dep.nsfo5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO5", vRM) quit
		set X = dep.nsfo6 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO6", vRM) quit
		set X = dep.nsfo7 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO7", vRM) quit
		set X = dep.nsfo8 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO8", vRM) quit
		set X = dep.nsfo9 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSFO9", vRM) quit
	}

	if vobj(dep,104).exists() do {

		set X = dep.convnbt if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CONVNBT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negi1 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI1", vRM) quit
		set X = dep.negi10 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI10", vRM) quit
		set X = dep.negi11 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI11", vRM) quit
		set X = dep.negi12 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI12", vRM) quit
		set X = dep.negi13 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI13", vRM) quit
		set X = dep.negi14 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI14", vRM) quit
		set X = dep.negi15 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI15", vRM) quit
		set X = dep.negi16 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI16", vRM) quit
		set X = dep.negi17 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI17", vRM) quit
		set X = dep.negi18 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI18", vRM) quit
		set X = dep.negi19 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI19", vRM) quit
		set X = dep.negi2 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI2", vRM) quit
		set X = dep.negi20 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI20", vRM) quit
		set X = dep.negi21 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI21", vRM) quit
		set X = dep.negi22 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI22", vRM) quit
		set X = dep.negi23 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI23", vRM) quit
		set X = dep.negi24 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI24", vRM) quit
		set X = dep.negi3 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI3", vRM) quit
		set X = dep.negi4 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI4", vRM) quit
		set X = dep.negi5 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI5", vRM) quit
		set X = dep.negi6 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI6", vRM) quit
		set X = dep.negi7 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI7", vRM) quit
		set X = dep.negi8 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI8", vRM) quit
		set X = dep.negi9 if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("NEGI9", vRM) quit
		set X = dep.nego1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO1", vRM) quit
		set X = dep.nego10 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO10", vRM) quit
		set X = dep.nego11 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO11", vRM) quit
		set X = dep.nego12 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO12", vRM) quit
		set X = dep.nego13 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO13", vRM) quit
		set X = dep.nego14 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO14", vRM) quit
		set X = dep.nego15 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO15", vRM) quit
		set X = dep.nego16 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO16", vRM) quit
		set X = dep.nego17 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO17", vRM) quit
		set X = dep.nego18 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO18", vRM) quit
		set X = dep.nego19 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO19", vRM) quit
		set X = dep.nego2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO2", vRM) quit
		set X = dep.nego20 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO20", vRM) quit
		set X = dep.nego21 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO21", vRM) quit
		set X = dep.nego22 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO22", vRM) quit
		set X = dep.nego23 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO23", vRM) quit
		set X = dep.nego24 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO24", vRM) quit
		set X = dep.nego3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO3", vRM) quit
		set X = dep.nego4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO4", vRM) quit
		set X = dep.nego5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO5", vRM) quit
		set X = dep.nego6 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO6", vRM) quit
		set X = dep.nego7 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO7", vRM) quit
		set X = dep.nego8 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO8", vRM) quit
		set X = dep.nego9 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NEGO9", vRM) quit
	}

	if vobj(dep,105).exists() do {

		set X = dep.reti1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI1", vRM) quit
		set X = dep.reti10 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI10", vRM) quit
		set X = dep.reti11 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI11", vRM) quit
		set X = dep.reti12 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI12", vRM) quit
		set X = dep.reti13 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI13", vRM) quit
		set X = dep.reti14 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI14", vRM) quit
		set X = dep.reti15 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI15", vRM) quit
		set X = dep.reti16 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI16", vRM) quit
		set X = dep.reti17 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI17", vRM) quit
		set X = dep.reti18 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI18", vRM) quit
		set X = dep.reti19 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI19", vRM) quit
		set X = dep.reti2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI2", vRM) quit
		set X = dep.reti20 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI20", vRM) quit
		set X = dep.reti21 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI21", vRM) quit
		set X = dep.reti22 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI22", vRM) quit
		set X = dep.reti23 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI23", vRM) quit
		set X = dep.reti24 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI24", vRM) quit
		set X = dep.reti3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI3", vRM) quit
		set X = dep.reti4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI4", vRM) quit
		set X = dep.reti5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI5", vRM) quit
		set X = dep.reti6 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI6", vRM) quit
		set X = dep.reti7 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI7", vRM) quit
		set X = dep.reti8 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI8", vRM) quit
		set X = dep.reti9 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETI9", vRM) quit
		set X = dep.reto1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO1", vRM) quit
		set X = dep.reto10 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO10", vRM) quit
		set X = dep.reto11 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO11", vRM) quit
		set X = dep.reto12 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO12", vRM) quit
		set X = dep.reto13 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO13", vRM) quit
		set X = dep.reto14 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO14", vRM) quit
		set X = dep.reto15 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO15", vRM) quit
		set X = dep.reto16 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO16", vRM) quit
		set X = dep.reto17 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO17", vRM) quit
		set X = dep.reto18 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO18", vRM) quit
		set X = dep.reto19 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO19", vRM) quit
		set X = dep.reto2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO2", vRM) quit
		set X = dep.reto20 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO20", vRM) quit
		set X = dep.reto21 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO21", vRM) quit
		set X = dep.reto22 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO22", vRM) quit
		set X = dep.reto23 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO23", vRM) quit
		set X = dep.reto24 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO24", vRM) quit
		set X = dep.reto3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO3", vRM) quit
		set X = dep.reto4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO4", vRM) quit
		set X = dep.reto5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO5", vRM) quit
		set X = dep.reto6 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO6", vRM) quit
		set X = dep.reto7 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO7", vRM) quit
		set X = dep.reto8 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO8", vRM) quit
		set X = dep.reto9 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RETO9", vRM) quit
	}

	if vobj(dep,106).exists() do {

		set X = dep.negbd1 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD1", vRM) quit
		set X = dep.negbd10 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD10", vRM) quit
		set X = dep.negbd11 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD11", vRM) quit
		set X = dep.negbd12 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD12", vRM) quit
		set X = dep.negbd13 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD13", vRM) quit
		set X = dep.negbd14 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD14", vRM) quit
		set X = dep.negbd15 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD15", vRM) quit
		set X = dep.negbd2 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD2", vRM) quit
		set X = dep.negbd3 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD3", vRM) quit
		set X = dep.negbd4 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD4", vRM) quit
		set X = dep.negbd5 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD5", vRM) quit
		set X = dep.negbd6 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD6", vRM) quit
		set X = dep.negbd7 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD7", vRM) quit
		set X = dep.negbd8 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD8", vRM) quit
		set X = dep.negbd9 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NEGBD9", vRM) quit
	}

	if vobj(dep,107).exists() do {

		set X = dep.balfwd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.BALFWD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.bgtcontr if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]BGTCONTR",0) if 'vRM.get().isNull() do vdderr("BGTCONTR", vRM) quit
		set X = dep.bgtfreq if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]BGTFREQ",0) if 'vRM.get().isNull() do vdderr("BGTFREQ", vRM) quit
		set X = dep.bgtlcdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BGTLCDT", vRM) quit
		set X = dep.bgtncdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BGTNCDT", vRM) quit
		set X = dep.bgtoffst if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("BGTOFFST", vRM) quit
		if '("01"[dep.BGTPRO) set vRM=$$^MSG(742,"L") do vdderr("BGTPRO", vRM) quit
		set X = dep.bgtrvudt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BGTRVUDT", vRM) quit
		set X = dep.bgtyrnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BGTYRND", vRM) quit
		set X = dep.bgtyrsd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BGTYRSD", vRM) quit
		set X = dep.colcdte if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("COLCDTE", vRM) quit
		set X = dep.nsfd1 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NSFD1", vRM) quit
		set X = dep.nsfd2 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NSFD2", vRM) quit
		set X = dep.pcollst if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("PCOLLST", vRM) quit
		set X = dep.promamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PROMAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.prombrd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROMBRD", vRM) quit
		set X = dep.prommd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROMMD", vRM) quit
		set X = dep.promsd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROMSD", vRM) quit
	}

	if vobj(dep,108).exists() do {

		set X = dep.mmdac1 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC1", vRM) quit
		set X = dep.mmdac10 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC10", vRM) quit
		set X = dep.mmdac11 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC11", vRM) quit
		set X = dep.mmdac12 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC12", vRM) quit
		set X = dep.mmdac2 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC2", vRM) quit
		set X = dep.mmdac3 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC3", vRM) quit
		set X = dep.mmdac4 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC4", vRM) quit
		set X = dep.mmdac5 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC5", vRM) quit
		set X = dep.mmdac6 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC6", vRM) quit
		set X = dep.mmdac7 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC7", vRM) quit
		set X = dep.mmdac8 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC8", vRM) quit
		set X = dep.mmdac9 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAC9", vRM) quit
		set X = dep.mmdat1 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT1", vRM) quit
		set X = dep.mmdat10 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT10", vRM) quit
		set X = dep.mmdat11 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT11", vRM) quit
		set X = dep.mmdat12 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT12", vRM) quit
		set X = dep.mmdat2 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT2", vRM) quit
		set X = dep.mmdat3 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT3", vRM) quit
		set X = dep.mmdat4 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT4", vRM) quit
		set X = dep.mmdat5 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT5", vRM) quit
		set X = dep.mmdat6 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT6", vRM) quit
		set X = dep.mmdat7 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT7", vRM) quit
		set X = dep.mmdat8 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT8", vRM) quit
		set X = dep.mmdat9 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("MMDAT9", vRM) quit
	}

	if vobj(dep,111).exists() do {

		set X = dep.calacls if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CALACLS", vRM) quit
		set X = dep.provbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PROVBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.provcat if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PROVCAT", vRM) quit
		set X = dep.provexpd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROVEXPD", vRM) quit
		set X = dep.provoamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PROVOAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.provopct if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PROVOPCT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.racovr if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RACOVR", vRM) quit
		set X = dep.whexr if 'X.isNull(),'Db.isDefined("STBLEXR","X") set vRM = $$^MSG(1485,X) do vdderr("WHEXR", vRM) quit
	}

	if vobj(dep,114).exists() do {

		set X = dep.cusha if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CUSHA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cushf if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,9) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CUSHF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cusho if 'X.isNull(),'Db.isDefined("STBLCUSHO","X") set vRM = $$^MSG(1485,X) do vdderr("CUSHO", vRM) quit
		set X = dep.ddmg if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("DDMG", vRM) quit
		set X = dep.ddml if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("DDML", vRM) quit
		set X = dep.dfda if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DFDA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.oda if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ODA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.odmg if 'X.isNull(),'Db.isDefined("STBLODM","X") set vRM = $$^MSG(1485,X) do vdderr("ODMG", vRM) quit
		set X = dep.odml if 'X.isNull(),'Db.isDefined("STBLODM","X") set vRM = $$^MSG(1485,X) do vdderr("ODML", vRM) quit
		set X = dep.sda if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SDA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.sdmg if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("SDMG", vRM) quit
		set X = dep.sdml if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("SDML", vRM) quit
		set X = dep.sdo if 'X.isNull(),'Db.isDefined("STBLSDO","X") set vRM = $$^MSG(1485,X) do vdderr("SDO", vRM) quit
	}

	if vobj(dep,115).exists() do {

		if '("01"[dep.SHAREACCT) set vRM=$$^MSG(742,"L") do vdderr("SHAREACCT", vRM) quit
	}

	if vobj(dep,210).exists() do {

		set X = dep.abmc if 'X.isNull(),'Db.isDefined("STBLABMC","X") set vRM = $$^MSG(1485,X) do vdderr("ABMC", vRM) quit
		set X = dep.andt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANDT", vRM) quit
		if '("01"[dep.ANFLG) set vRM=$$^MSG(742,"L") do vdderr("ANFLG", vRM) quit
		set X = dep.anpdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANPDT", vRM) quit
		set X = dep.aref if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("AREF", vRM) quit
		if '("01"[dep.AUBBF) set vRM=$$^MSG(742,"L") do vdderr("AUBBF", vRM) quit
		set X = dep.aubcu if 'X.isNull(),'Db.isDefined("UTBLECT","X") set vRM = $$^MSG(1485,X) do vdderr("AUBCU", vRM) quit
		set X = dep.autaf if 'X.isNull(),'Db.isDefined("STBLAUO","X") set vRM = $$^MSG(1485,X) do vdderr("AUTAF", vRM) quit
		set X = dep.clamo if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CLAMO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.curramt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CURRAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if dep.esc.length()>6 set vRM = $$^MSG(1076,6) do vdderr("ESC", vRM) quit
		set X = dep.odeao if 'X.isNull(),'Db.isDefined("STBLAUO","X") set vRM = $$^MSG(1485,X) do vdderr("ODEAO", vRM) quit
		set X = dep.recamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RECAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.remtot if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.REMTOT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.SPF) set vRM=$$^MSG(742,"L") do vdderr("SPF", vRM) quit
	}

	if vobj(dep,300).exists() do {

		set X = dep.pbkbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PBKBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pbkld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PBKLD", vRM) quit
		set X = dep.pbklin if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("PBKLIN", vRM) quit
		set X = dep.pbkseq if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("PBKSEQ", vRM) quit
		set X = dep.pbksn if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("PBKSN", vRM) quit
	}

	if vobj(dep,400).exists() do {

		set X = dep.lbbdo if 'X.isNull(),'Db.isDefined("STBLLBBDO","X") set vRM = $$^MSG(1485,X) do vdderr("LBBDO", vRM) quit
		set X = dep.lbcm if 'X.isNull(),'Db.isDefined("STBLLBCM","X") set vRM = $$^MSG(1485,X) do vdderr("LBCM", vRM) quit
		set X = dep.lbcp if 'X.isNull(),'Db.isDefined("STBLLBCP","X") set vRM = $$^MSG(1485,X) do vdderr("LBCP", vRM) quit
		set X = dep.lbgpna if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("LBGPNA", vRM) quit
	}

	if vobj(dep,402).exists() do {

		set X = dep.lbb10mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB10MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb11mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB11MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb12mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB12MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb13mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB13MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb14mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB14MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb15mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB15MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb16mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB16MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb17mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB17MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb18mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB18MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb19mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB19MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb1mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB1MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb20mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB20MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb21mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB21MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb22mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB22MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb23mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB23MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb2mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB2MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb3mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB3MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb4mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB4MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb5mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB5MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb6mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB6MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb7mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB7MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb8mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB8MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbb9mp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBB9MP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lbbcm if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LBBCM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,425).exists() do {

		set X = dep.ithlddays if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("ITHLDDAYS", vRM) quit
	}

	if vobj(dep,426).exists() do {

		set X = dep.cngrs if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("CNGRS", vRM) quit
		set X = dep.dscrtbl if 'X.isNull(),'Db.isDefined("UTBLGCRDS","X") set vRM = $$^MSG(1485,X) do vdderr("DSCRTBL", vRM) quit
		set X = dep.dsopt if 'X.isNull(),'Db.isDefined("STBLDSOPT","X") set vRM = $$^MSG(1485,X) do vdderr("DSOPT", vRM) quit
		set X = dep.gcrcd if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("GCRCD", vRM) quit
		set X = dep.gcrcv if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.GCRCV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.GCRDOD) set vRM=$$^MSG(742,"L") do vdderr("GCRDOD", vRM) quit
		set X = dep.gcrlmnt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("GCRLMNT", vRM) quit
		set X = dep.gcrpmnt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("GCRPMNT", vRM) quit
		set X = dep.gcrs if 'X.isNull(),'Db.isDefined("STBLGCROPT","X") set vRM = $$^MSG(1485,X) do vdderr("GCRS", vRM) quit
		set X = dep.gcrtfcid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("GCRTFCID", vRM) quit
		set X = dep.hsovrdm if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HSOVRDM", vRM) quit
		set X = dep.inicvopt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.INICVOPT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lsdate if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LSDATE", vRM) quit
		set X = dep.lsovrdm if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("LSOVRDM", vRM) quit
		set X = dep.mscrtbl if 'X.isNull(),'Db.isDefined("UTBLGCRBALT","X") set vRM = $$^MSG(1485,X) do vdderr("MSCRTBL", vRM) quit
		set X = dep.nsdate if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NSDATE", vRM) quit
		set X = dep.odlimopt if 'X.isNull(),'Db.isDefined("UTBLODOPTT","X") set vRM = $$^MSG(1485,X) do vdderr("ODLIMOPT", vRM) quit
		set X = dep.origopd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ORIGOPD", vRM) quit
		set X = dep.retfcpy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RETFCPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.retfcytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RETFCYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.retfwpy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RETFWPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.retfwytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RETFWYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.retmxfee if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RETMXFEE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.rnamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RNAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.rnamtdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("RNAMTDT", vRM) quit
		set X = dep.scrfreq if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]SCRFREQ",0) if 'vRM.get().isNull() do vdderr("SCRFREQ", vRM) quit
		set X = dep.sddepcvr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SDDEPCVR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,427).exists() do {

		set X = dep.odcnt if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT", vRM) quit
		set X = dep.odcnt1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT1", vRM) quit
		set X = dep.odcnt10 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT10", vRM) quit
		set X = dep.odcnt11 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT11", vRM) quit
		set X = dep.odcnt12 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT12", vRM) quit
		set X = dep.odcnt13 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT13", vRM) quit
		set X = dep.odcnt14 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT14", vRM) quit
		set X = dep.odcnt15 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT15", vRM) quit
		set X = dep.odcnt16 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT16", vRM) quit
		set X = dep.odcnt17 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT17", vRM) quit
		set X = dep.odcnt18 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT18", vRM) quit
		set X = dep.odcnt19 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT19", vRM) quit
		set X = dep.odcnt2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT2", vRM) quit
		set X = dep.odcnt20 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT20", vRM) quit
		set X = dep.odcnt21 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT21", vRM) quit
		set X = dep.odcnt22 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT22", vRM) quit
		set X = dep.odcnt23 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT23", vRM) quit
		set X = dep.odcnt24 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT24", vRM) quit
		set X = dep.odcnt25 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT25", vRM) quit
		set X = dep.odcnt26 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT26", vRM) quit
		set X = dep.odcnt27 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT27", vRM) quit
		set X = dep.odcnt28 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT28", vRM) quit
		set X = dep.odcnt29 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT29", vRM) quit
		set X = dep.odcnt3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT3", vRM) quit
		set X = dep.odcnt30 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT30", vRM) quit
		set X = dep.odcnt31 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT31", vRM) quit
		set X = dep.odcnt32 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT32", vRM) quit
		set X = dep.odcnt33 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT33", vRM) quit
		set X = dep.odcnt34 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT34", vRM) quit
		set X = dep.odcnt35 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT35", vRM) quit
		set X = dep.odcnt36 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT36", vRM) quit
		set X = dep.odcnt4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT4", vRM) quit
		set X = dep.odcnt5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT5", vRM) quit
		set X = dep.odcnt6 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT6", vRM) quit
		set X = dep.odcnt7 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT7", vRM) quit
		set X = dep.odcnt8 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT8", vRM) quit
		set X = dep.odcnt9 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ODCNT9", vRM) quit
	}

	if vobj(dep,428).exists() do {

		set X = dep.aiacr if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.AIACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.AIACRF) set vRM=$$^MSG(742,"L") do vdderr("AIACRF", vRM) quit
		set X = dep.aiextacn if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("AIEXTACN", vRM) quit
		set X = dep.aiextseq if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("AIEXTSEQ", vRM) quit
		set X = dep.aiichld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("AIICHLD", vRM) quit
		set X = dep.aiichnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("AIICHND", vRM) quit
		if dep.aiindex.length()>20 set vRM = $$^MSG(1076,20) do vdderr("AIINDEX", vRM) quit
		set X = dep.aiinp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("AIINP", vRM) quit
		set X = dep.aiintfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]AIINTFRE",0) if 'vRM.get().isNull() do vdderr("AIINTFRE", vRM) quit
		set X = dep.aiintmat if 'X.isNull(),'Db.isDefined("UTBLMATATT","X") set vRM = $$^MSG(1485,X) do vdderr("AIINTMAT", vRM) quit
		if dep.aiintspr.length()>9 set vRM = $$^MSG(1076,9) do vdderr("AIINTSPR", vRM) quit
		set X = dep.aiinttrf if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("AIINTTRF", vRM) quit
		set X = dep.aiiopt if 'X.isNull(),'Db.isDefined("STBLIOPT","X") set vRM = $$^MSG(1485,X) do vdderr("AIIOPT", vRM) quit
		set X = dep.aiipf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]AIIPF",0) if 'vRM.get().isNull() do vdderr("AIIPF", vRM) quit
		set X = dep.aiipld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("AIIPLD", vRM) quit
		set X = dep.aiirn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.AIIRN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.airdet if 'X.isNull(),'Db.isDefined("STBLAIRD","X") set vRM = $$^MSG(1485,X) do vdderr("AIRDET", vRM) quit
		if dep.airndmtd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("AIRNDMTD", vRM) quit
		set X = dep.emprytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EMPRYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.empytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EMPYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.extacn if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("EXTACN", vRM) quit
		set X = dep.extseq if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("EXTSEQ", vRM) quit
		set X = dep.imo if 'X.isNull(),'Db.isDefined("STBLIMO","X") set vRM = $$^MSG(1485,X) do vdderr("IMO", vRM) quit
		set X = dep.ipimppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPIMPPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipimpytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPIMPYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipimrl if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPIMRL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipinmpl if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPINMPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipinmpy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPINMPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipinmytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPINMYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipmpl if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPMPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipmppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPMPPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipmpytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPMPYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipnmpl if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPNMPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipnmppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPNMPPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipnmpytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPNMPYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxempc if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXEMPC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxemprc if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXEMPRC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxseg if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("MAXSEG", vRM) quit
		if '("01"[dep.OFFPROC) set vRM=$$^MSG(742,"L") do vdderr("OFFPROC", vRM) quit
		set X = dep.pengr if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("PENGR", vRM) quit
		set X = dep.pratio if 'X.isNull() set vRM = $$VAL^DBSVER("N",6,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PRATIO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.prena if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PRENA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.segacr if 'X.isNull(),'Db.isDefined("STBLSAOP","X") set vRM = $$^MSG(1485,X) do vdderr("SEGACR", vRM) quit
		set X = dep.segmdd if 'X.isNull(),'Db.isDefined("STBLSMDO","X") set vRM = $$^MSG(1485,X) do vdderr("SEGMDD", vRM) quit
		if dep.segper.length()>8 set vRM = $$^MSG(1076,8) do vdderr("SEGPER", vRM) quit
		set X = dep.segpopt if 'X.isNull(),'Db.isDefined("STBLSEGPOPT","X") set vRM = $$^MSG(1485,X) do vdderr("SEGPOPT", vRM) quit
		set X = dep.segzirn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SEGZIRN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.swpi if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SWPI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.swri if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SWRI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.taiams if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TAIAMS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.taianms if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TAIANMS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.taims if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TAIMS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.tainms if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TAINMS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.taspm if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TASPM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.taspnm if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TASPNM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.tnums if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("TNUMS", vRM) quit
		set X = dep.totwfr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TOTWFR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.tsmpb if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TSMPB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.tsnmpb if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.TSNMPB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.wdord if 'X.isNull(),'Db.isDefined("STBLWDORD","X") set vRM = $$^MSG(1485,X) do vdderr("WDORD", vRM) quit
		set X = dep.wdprio if 'X.isNull(),'Db.isDefined("STBLWDPRIOR","X") set vRM = $$^MSG(1485,X) do vdderr("WDPRIO", vRM) quit
	}

	if vobj(dep,429).exists() do {

		set X = dep.lmtatm if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LMTATM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lmtcjd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LMTCJD", vRM) quit
		set X = dep.lmtpos if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LMTPOS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,430).exists() do {

		set X = dep.eurbatch if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("EURBATCH", vRM) quit
		set X = dep.eurcnvd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EURCNVD", vRM) quit
		set X = dep.eurcvinbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EURCVINBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eurefd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EUREFD", vRM) quit
		set X = dep.eureqdat if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EUREQDAT", vRM) quit
		set X = dep.eurevdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EUREVDT", vRM) quit
		set X = dep.eurstat if 'X.isNull(),'Db.isDefined("STBLEURSTAT","X") set vRM = $$^MSG(1485,X) do vdderr("EURSTAT", vRM) quit
		set X = dep.eurudrq if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("EURUDRQ", vRM) quit
		if dep.orgcrcd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("ORGCRCD", vRM) quit
		if dep.orgindex.length()>20 set vRM = $$^MSG(1076,20) do vdderr("ORGINDEX", vRM) quit
		set X = dep.orgsch if 'X.isNull(),'Db.isDefined("UTBLRATE","X") set vRM = $$^MSG(1485,X) do vdderr("ORGSCH", vRM) quit
	}

	if vobj(dep,431).exists() do {

		if '("01"[dep.PAYEFT) set vRM=$$^MSG(742,"L") do vdderr("PAYEFT", vRM) quit
		set X = dep.sfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]SFRE",0) if 'vRM.get().isNull() do vdderr("SFRE", vRM) quit
	}

	if vobj(dep,432).exists() do {

		set X = dep.cnvtyp if 'X.isNull(),'Db.isDefined("STBLCNVTYP","X") set vRM = $$^MSG(1485,X) do vdderr("CNVTYP", vRM) quit
		if '("01"[dep.COLLQUE) set vRM=$$^MSG(742,"L") do vdderr("COLLQUE", vRM) quit
		set X = dep.collst if 'X.isNull(),'Db.isDefined("UTBLCOLLST","X") set vRM = $$^MSG(1485,X) do vdderr("COLLST", vRM) quit
		set X = dep.comppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.COMPPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.compytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.COMPYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.DEFINADJ) set vRM=$$^MSG(742,"L") do vdderr("DEFINADJ", vRM) quit
		if '("01"[dep.DLKFLG) set vRM=$$^MSG(742,"L") do vdderr("DLKFLG", vRM) quit
		set X = dep.fisbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.FISBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.fisint if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.FISINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ipty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.itytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ITYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negitrf if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("NEGITRF", vRM) quit
		set X = dep.penpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PENPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.pentytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PENTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.restyp if 'X.isNull(),'Db.isDefined("STBLRESTYP","X") set vRM = $$^MSG(1485,X) do vdderr("RESTYP", vRM) quit
		set X = dep.wrkdte if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("WRKDTE", vRM) quit
	}

	if vobj(dep,434).exists() do {

		set X = dep.afdep if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.AFDEP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dfdep if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DFDEP", vRM) quit
		set X = dep.dgrace if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DGRACE", vRM) quit
		if '("01"[dep.GIS) set vRM=$$^MSG(742,"L") do vdderr("GIS", vRM) quit
		set X = dep.intdisetc if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("INTDISETC", vRM) quit
		set X = dep.intdisets if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("INTDISETS", vRM) quit
		set X = dep.intmatetc if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("INTMATETC", vRM) quit
		set X = dep.intmatets if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("INTMATETS", vRM) quit
		set X = dep.intmatita if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("INTMATITA", vRM) quit
		set X = dep.isn if 'X.isNull(),X'?1.9N,X'?1"-"1.8N set vRM=$$^MSG(742,"N") do vdderr("ISN", vRM) quit
		set X = dep.negundaa if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGUNDAA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.PIS) set vRM=$$^MSG(742,"L") do vdderr("PIS", vRM) quit
		set X = dep.primatetc if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("PRIMATETC", vRM) quit
		set X = dep.primatets if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("PRIMATETS", vRM) quit
		if '("01"[dep.SWPDELIP) set vRM=$$^MSG(742,"L") do vdderr("SWPDELIP", vRM) quit
	}

	if vobj(dep,435).exists() do {

		if '("01"[dep.MINBALFL) set vRM=$$^MSG(742,"L") do vdderr("MINBALFL", vRM) quit
	}

	if vobj(dep,436).exists() do {

		set X = dep.convdd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CONVDD", vRM) quit
		set X = dep.convodex if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CONVODEX", vRM) quit
		set X = dep.convodst if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CONVODST", vRM) quit
		set X = dep.dumi if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DUMI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.idomi if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IDOMI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.niao if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("NIAO", vRM) quit
		if '("01"[dep.PDIV) set vRM=$$^MSG(742,"L") do vdderr("PDIV", vRM) quit
		set X = dep.sdomi if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SDOMI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.ufindex if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("UFINDEX", vRM) quit
		set X = dep.uncacr if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.UNCACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,437).exists() do {

		set X = dep.aepy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.AEPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.aeytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.AEYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if dep.bldg.length()>15 set vRM = $$^MSG(1076,15) do vdderr("BLDG", vRM) quit
		set X = dep.iep if 'X.isNull() set vRM = $$VAL^DBSVER("N",6,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.IEP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lafm if 'X.isNull(),'Db.isDefined("STBLLAFO","X") set vRM = $$^MSG(1485,X) do vdderr("LAFM", vRM) quit
		set X = dep.laftfr if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("LAFTFR", vRM) quit
		if '("01"[dep.LSP) set vRM=$$^MSG(742,"L") do vdderr("LSP", vRM) quit
		set X = dep.oborirp if 'X.isNull() set vRM = $$VAL^DBSVER("N",6,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.OBORIRP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if dep.prop.length()>15 set vRM = $$^MSG(1076,15) do vdderr("PROP", vRM) quit
		if dep.unit.length()>15 set vRM = $$^MSG(1076,15) do vdderr("UNIT", vRM) quit
		set X = dep.usrestat if 'X.isNull(),'Db.isDefined("STBLUSRESTAT","X") set vRM = $$^MSG(1485,X) do vdderr("USRESTAT", vRM) quit
	}

	if vobj(dep,438).exists() do {

		if '("01"[dep.MT320) set vRM=$$^MSG(742,"L") do vdderr("MT320", vRM) quit
		if dep.mt320a.length()>11 set vRM = $$^MSG(1076,11) do vdderr("MT320A", vRM) quit
		if '("01"[dep.MT900) set vRM=$$^MSG(742,"L") do vdderr("MT900", vRM) quit
		set X = dep.mt900a if 'X.isNull(),'Db.isDefined("UTBLCORRE","X") set vRM = $$^MSG(1485,X) do vdderr("MT900A", vRM) quit
		set X = dep.mt900prd if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("MT900PRD", vRM) quit
		set X = dep.mt900thr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MT900THR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.MT910) set vRM=$$^MSG(742,"L") do vdderr("MT910", vRM) quit
		set X = dep.mt910a if 'X.isNull(),'Db.isDefined("UTBLCORRE","X") set vRM = $$^MSG(1485,X) do vdderr("MT910A", vRM) quit
		set X = dep.mt910prd if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("MT910PRD", vRM) quit
		set X = dep.mt910thr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MT910THR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.MT940) set vRM=$$^MSG(742,"L") do vdderr("MT940", vRM) quit
		if dep.mt940a.length()>11 set vRM = $$^MSG(1076,11) do vdderr("MT940A", vRM) quit
		if '("01"[dep.MT942) set vRM=$$^MSG(742,"L") do vdderr("MT942", vRM) quit
		if dep.mt942a.length()>11 set vRM = $$^MSG(1076,11) do vdderr("MT942A", vRM) quit
		set X = dep.mt942crth if 'X.isNull(),X'?1.18N,X'?1"-"1.17N set vRM=$$^MSG(742,"N") do vdderr("MT942CRTH", vRM) quit
		set X = dep.mt942drth if 'X.isNull(),X'?1.18N,X'?1"-"1.17N set vRM=$$^MSG(742,"N") do vdderr("MT942DRTH", vRM) quit
		set X = dep.mt942g1 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"C") do vdderr("MT942G1", vRM) quit
		set X = dep.mt942g2 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"C") do vdderr("MT942G2", vRM) quit
		set X = dep.mt942lrd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("MT942LRD", vRM) quit
		set X = dep.mt942lrt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"C") do vdderr("MT942LRT", vRM) quit
		set X = dep.mt942prd if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("MT942PRD", vRM) quit
		set X = dep.mt942stmt if 'X.isNull(),X'?1.10N,X'?1"-"1.9N set vRM=$$^MSG(742,"N") do vdderr("MT942STMT", vRM) quit
		if '("01"[dep.MT950) set vRM=$$^MSG(742,"L") do vdderr("MT950", vRM) quit
		if dep.mt950a.length()>11 set vRM = $$^MSG(1076,11) do vdderr("MT950A", vRM) quit
		set X = dep.sw940freq if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]SW940FREQ",0) if 'vRM.get().isNull() do vdderr("SW940FREQ", vRM) quit
		set X = dep.sw940lsdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SW940LSDT", vRM) quit
		set X = dep.sw940lstm if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"C") do vdderr("SW940LSTM", vRM) quit
		set X = dep.sw940nsdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SW940NSDT", vRM) quit
		set X = dep.sw940num if 'X.isNull(),X'?1.10N,X'?1"-"1.9N set vRM=$$^MSG(742,"N") do vdderr("SW940NUM", vRM) quit
		set X = dep.sw940prd if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("SW940PRD", vRM) quit
		set X = dep.sw950lstm if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"C") do vdderr("SW950LSTM", vRM) quit
	}

	if vobj(dep,439).exists() do {

		set X = dep.lcamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LCAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lcdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LCDT", vRM) quit
		set X = dep.ldamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LDAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.lddt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LDDT", vRM) quit
	}

	if vobj(dep,440).exists() do {

		set X = dep.anico if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ANICO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.anir if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ANIR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.codel if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CODEL", vRM) quit
		if '("01"[dep.COF) set vRM=$$^MSG(742,"L") do vdderr("COF", vRM) quit
		if dep.cogs.length()>4 set vRM = $$^MSG(1076,4) do vdderr("COGS", vRM) quit
		set X = dep.com if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("COM", vRM) quit
		set X = dep.cot if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("COT", vRM) quit
		set X = dep.dtco if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DTCO", vRM) quit
		set X = dep.rico if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RICO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.rir if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RIR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.unico if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.UNICO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.unir if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.UNIR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.unpbc if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.UNPBC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.unpbr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.UNPBR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,442).exists() do {

		set X = dep.bwpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.BWPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.bwtytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.BWTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negipty if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGIPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.negitytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NEGITYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrnegipty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,1,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRNEGIPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrnegitytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRNEGITYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrposipty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,1,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPOSIPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrpositytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPOSITYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrppty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,1,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrptytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRPTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwapty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWAPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwatytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWATYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwhpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,1,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWHPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.nrwhtytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NRWHTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,444).exists() do {

		set X = dep.anlbalrf if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("ANLBALRF", vRM) quit
		set X = dep.anlbalrm if 'X.isNull(),'Db.isDefined("STBLRNDMTH","X") set vRM = $$^MSG(1485,X) do vdderr("ANLBALRM", vRM) quit
		set X = dep.anlbefe if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ANLBEFE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.anlcid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("ANLCID", vRM) quit
		if '("01"[dep.ANLFPR) set vRM=$$^MSG(742,"L") do vdderr("ANLFPR", vRM) quit
		set X = dep.anlled if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANLLED", vRM) quit
		set X = dep.anllsd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANLLSD", vRM) quit
		set X = dep.anloffdy if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ANLOFFDY", vRM) quit
		set X = dep.anloffed if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANLOFFED", vRM) quit
		set X = dep.anlsnl if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ANLSNL", vRM) quit
		set X = dep.anlstchg if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.ANLSTCHG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.anltyp if 'X.isNull(),'Db.isDefined("STBLANLTYP","X") set vRM = $$^MSG(1485,X) do vdderr("ANLTYP", vRM) quit
		if '("01"[dep.DEDINTPD) set vRM=$$^MSG(742,"L") do vdderr("DEDINTPD", vRM) quit
	}

	if vobj(dep,446).exists() do {

		if '("01"[dep.IRFL) set vRM=$$^MSG(742,"L") do vdderr("IRFL", vRM) quit
		if '("01"[dep.REGDD) set vRM=$$^MSG(742,"L") do vdderr("REGDD", vRM) quit
		set X = dep.rmtbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RMTBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.rmtthr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.RMTTHR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.swpropt if 'X.isNull(),'Db.isDefined("STBLSWPROPT","X") set vRM = $$^MSG(1485,X) do vdderr("SWPROPT", vRM) quit
		set X = dep.swptr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SWPTR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(dep,447).exists() do {

		set X = dep.pcidstat if 'X.isNull(),'Db.isDefined("STBLPCIDDEP","X") set vRM = $$^MSG(1485,X) do vdderr("PCIDSTAT", vRM) quit
	}

	if vobj(dep,448).exists() do {

		set X = dep.npiaab if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.NPIAAB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[dep.OSGNCRDC) set vRM=$$^MSG(742,"L") do vdderr("OSGNCRDC", vRM) quit
		set X = dep.psgncrdr if 'X.isNull(),'Db.isDefined("STBLPSGNCRDR","X") set vRM = $$^MSG(1485,X) do vdderr("PSGNCRDR", vRM) quit
		set X = dep.sgncrd if 'X.isNull(),'Db.isDefined("STBLSGNCRD","X") set vRM = $$^MSG(1485,X) do vdderr("SGNCRD", vRM) quit
		set X = dep.sgncrdchgdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SGNCRDCHGDT", vRM) quit
	}

	if vobj(dep,450).exists() do {

		set X = dep.awt if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.AWT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.awti if 'X.isNull(),'Db.isDefined("UTBLAWTI","X") set vRM = $$^MSG(1485,X) do vdderr("AWTI", vRM) quit
		if '("01"[dep.AWTP) set vRM=$$^MSG(742,"L") do vdderr("AWTP", vRM) quit
		set X = dep.awtr if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.AWTR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.bwsched if 'X.isNull(),'Db.isDefined("UTBLRATE","X") set vRM = $$^MSG(1485,X) do vdderr("BWSCHED", vRM) quit
		set X = dep.dawa if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAWA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dawa1 if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAWA1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dawa2 if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAWA2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dawa3 if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAWA3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dawa4 if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DAWA4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.erracct if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("ERRACCT", vRM) quit
		if '("01"[dep.ERRFLG) set vRM=$$^MSG(742,"L") do vdderr("ERRFLG", vRM) quit
	}

	if vobj(dep,452).exists() do {

		set X = dep.rce if 'X.isNull(),'Db.isDefined("STBLSRCE","X") set vRM = $$^MSG(1485,X) do vdderr("RCE", vRM) quit
		if dep.rsintspr.length()>9 set vRM = $$^MSG(1076,9) do vdderr("RSINTSPR", vRM) quit
		if dep.rsrndmtd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("RSRNDMTD", vRM) quit
	}

	if vobj(dep,454).exists() do {

		set X = dep.precard if 'X.isNull(),X'?1.20N,X'?1"-"1.19N set vRM=$$^MSG(742,"N") do vdderr("PRECARD", vRM) quit
		if dep.prepin.length()>20 set vRM = $$^MSG(1076,20) do vdderr("PREPIN", vRM) quit
	}

	if vobj(dep,456).exists() do {

		if '("01"[dep.BLPROC) set vRM=$$^MSG(742,"L") do vdderr("BLPROC", vRM) quit
		set X = dep.colexthrsh if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.COLEXTHRSH"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.colextrdys if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("COLEXTRDYS", vRM) quit
		set X = dep.regeamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.REGEAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.stmtsrt if 'X.isNull(),'Db.isDefined("STBLSTMTSRT","X") set vRM = $$^MSG(1485,X) do vdderr("STMTSRT", vRM) quit
	}

	if vobj(dep,458).exists() do {

		set X = dep.clr if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("CLR", vRM) quit
		set X = dep.slc if 'X.isNull(),'Db.isDefined("STBLSBSLC","X") set vRM = $$^MSG(1485,X) do vdderr("SLC", vRM) quit
	}

	if vobj(dep,460).exists() do {

		set X = dep.eodbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbal2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBAL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbal3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBAL3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbal4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBAL4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbal5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBAL5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalav if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALAV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalavl2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALAVL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalavl3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALAVL3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalavl4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALAVL4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalavl5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALAVL5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalco if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALCO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalcol2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALCOL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalcol3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALCOL3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalcol4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALCOL4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodbalcol5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODBALCOL5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodhldam if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODHLDAM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodhldam2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODHLDAM2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodhldam3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODHLDAM3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodhldam4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODHLDAM4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.eodhldam5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.EODHLDAM5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.fdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("FDT", vRM) quit
	}

	if vobj(dep,462).exists() do {

		if dep.intspra.length()>9 set vRM = $$^MSG(1076,9) do vdderr("INTSPRA", vRM) quit
		if dep.intsprp.length()>9 set vRM = $$^MSG(1076,9) do vdderr("INTSPRP", vRM) quit
		if dep.intspru.length()>9 set vRM = $$^MSG(1076,9) do vdderr("INTSPRU", vRM) quit
	}

	if vobj(dep,464).exists() do {

		if '("01"[dep.CUMDEP) set vRM=$$^MSG(742,"L") do vdderr("CUMDEP", vRM) quit
		if '("01"[dep.DAPARWD) set vRM=$$^MSG(742,"L") do vdderr("DAPARWD", vRM) quit
		set X = dep.lfeepr if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.LFEEPR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxsaadv if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.MAXSAADV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.maxsnadv if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("MAXSNADV", vRM) quit
		set X = dep.minnsreq if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("MINNSREQ", vRM) quit
		set X = dep.nscdepdd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NSCDEPDD", vRM) quit
		set X = dep.nschdeps if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NSCHDEPS", vRM) quit
		set X = dep.prclfee if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.PRCLFEE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.schdepa if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SCHDEPA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.schdepf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[DEP]SCHDEPF",0) if 'vRM.get().isNull() do vdderr("SCHDEPF", vRM) quit
		set X = dep.schdepld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SCHDEPLD", vRM) quit
		set X = dep.schdepn if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("SCHDEPN", vRM) quit
		set X = dep.schdepnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SCHDEPND", vRM) quit
		if '("01"[dep.SCHPROC) set vRM=$$^MSG(742,"L") do vdderr("SCHPROC", vRM) quit
		set X = dep.totnosdp if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("TOTNOSDP", vRM) quit
	}

	if vobj(dep,466).exists() do {

		if dep.ctfgrp.length()>8 set vRM = $$^MSG(1076,8) do vdderr("CTFGRP", vRM) quit
	}

	if vobj(dep,468).exists() do {

		set X = dep.fundact if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("FUNDACT", vRM) quit
		set X = dep.fundrsn if 'X.isNull(),'Db.isDefined("UTBLIRACON","X") set vRM = $$^MSG(1485,X) do vdderr("FUNDRSN", vRM) quit
	}

	if vobj(dep,470).exists() do {

		set X = dep.balavlcode if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("BALAVLCODE", vRM) quit
	}

	if vobj(dep,500).exists() do {

		if dep.acycode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("ACYCODE", vRM) quit
		if dep.agcode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("AGCODE", vRM) quit
		if dep.agtypec.length()>15 set vRM = $$^MSG(1076,15) do vdderr("AGTYPEC", vRM) quit
		if dep.busadv.length()>15 set vRM = $$^MSG(1076,15) do vdderr("BUSADV", vRM) quit
		set X = dep.cptag if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CPTAG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cptbadv if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CPTBADV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cptiae if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CPTIAE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.cptrefr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.CPTREFR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dcptag if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DCPTAG", vRM) quit
		set X = dep.dcptbadv if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.DCPTBADV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.dcptiae if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DCPTIAE", vRM) quit
		set X = dep.dcptrefr if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DCPTREFR", vRM) quit
		if dep.ilcode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("ILCODE", vRM) quit
		if dep.refrep.length()>15 set vRM = $$^MSG(1076,15) do vdderr("REFREP", vRM) quit
		if dep.sofcode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("SOFCODE", vRM) quit
		if dep.subscode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("SUBSCODE", vRM) quit
	}

	if vobj(dep,901).exists() do {

		if dep.papln.length()>6 set vRM = $$^MSG(1076,6) do vdderr("PAPLN", vRM) quit
		set X = dep.roidindex if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("ROIDINDEX", vRM) quit
		set X = dep.roidrate if 'X.isNull(),X'?1.8N,X'?1"-"1.7N set vRM=$$^MSG(742,"N") do vdderr("ROIDRATE", vRM) quit
		set X = dep.sfecy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SFECY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.sfelf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SFELF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = dep.sfepy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"DEP.SFEPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}
	set X = dep.cid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("CID", vRM) quit
	quit

vdderr(di, vRM) // Column attribute error

	type public Boolean ER = 0
	type public String RM
	do SETERR^DBSEXECU("DEP","MSG",979,"DEP."_di_" "_vRM)
	if ER throw Class.new("Error","%PSL-E-DBFILER,"_RM.get().replace(",","~"))
	quit
