DEPSGCDI		/*
	   Public;The values of the computed data items DSSEND,MSSEND and YSSEND
	   for DEPSEG are calculated here.

	   Revision History

	   05/07/03 - CARROLLJ - 51349
		      Removed the use of %A array in CHKEND section and removed
		      GETVAL section.
			
	*/

	quit

CHKEND(SEGEND,DATE,FLAG)
	/*
	
	   Retrieve value of SEGEND (segment end date) and check for its 
	   validity.
	
	   ARGUMENTS:
	
	   . DATE	Date to be subtracted from segment end date
	   . FLAG	Flag indicates if SEGEND (segment end date) is 
			NULL or in future
	   . SEGEND	Segment End Date
	
	*/
	
	Type RecordDEPSEG depseg=Db.getRecord("DEPSEG","CID=:CID,SEGMENT=:SEGMENT",1)
	set SEGEND=depseg.segend

	if $G(EFD)="" set DATE=%SystemDate
	else  set DATE=EFD
	
	if DATE<SEGEND set FLAG=0 quit			// End date in future
	set FLAG=1

	quit


DSSEND(CID,SEGMENT)

	/*	
	   ARGUMENTS:
	
	   CID  Account Number
	   SEGMENT   Segment Number
	*/

	new DATE,FLAG,SEGEND
	
	//Retrieve value of SEGEND(segment end date) and checking for its validity
	do CHKEND(.SEGEND,.DATE,.FLAG)
	if 'FLAG quit 0
	quit DATE-SEGEND				//End date is past or present
	
	
MSSEND(CID,SEGMENT)

	/*	
	   ARGUMENTS:
	
	   CID           Account Number
	   SEGMENT       Segment Number	
	*/

	new DATE,FLAG,SEGEND
	
	//Retrieve value of SEGEND(segment end date) and checking for its validity
	do CHKEND(.SEGEND,.DATE,.FLAG)
	if 'FLAG quit 0
	
	quit $$NOM^SCADAT(DATE,SEGEND)			// End date is past or present
	
	
YSSEND(CID,SEGMENT)
	/*	
	   ARGUMENTS:
	
	   CID           Account Number
	   SEGMENT       Segment Number	
	*/

	new DATE,FLAG,SEGEND
	
	//Retrieve value of SEGEND(segment end date) and checking for its validity
	do CHKEND(.SEGEND,.DATE,.FLAG)
	if 'FLAG quit 0
	quit $$NOY^SCADAT(DATE,SEGEND)			// End date is past or present
	

vSIG()	quit "59886^43512^Sanchez SCM Administrator^1696"	// Signature - LTD^TIME^USER^SIZE
