public I18NMLDM //Add/Mod/Delete MLD Entry
  /*
	ORIG: kumarb - 10/21/2005
	DESC: Add/Mod/Delete MLD Entry

	 I18N=QUIT     This program does not need to follow I18N standards 
	 DESC:		This program is responsible for maintaining the  content
			of the MLD outside of interactive translation.
	 
			After setting up some variables the program invokes the
			MLD maintenance Screen.
	 
			After returning from this screen the program updates
			the MLD with any new entrys.
	
			Finaly it builds a function return message in RM
	
	 CALLED BY:	Menusystem. No other routines.
	 CALL TO:      MLD Screen program I18NMLD
			GETPHR^I18NUTL
			NRMPHR^I18NNRM
	
	 GLOBALS READ:
			I18NMLD			- Master Language Dictionary
			I18NMLDX		- MLD Crossreference
	 GLOBALS SET:
			I18NMLD			- Master Language Dictionary
			I18NMLDX		- MLD Crossreference
	
	 ARGUMENTS:
	 INPUTS:
	
	 RETURNS:
	 EXAMPLE:
	 LIBRARY:
	
	---Revision History-------------------------------------------
	
	10/21/05 - KUMARB - CR 16921
        	Converted to PSL.
	
	--------------------------------------------------------------
	*/
	
	type Boolean mldex,mldxex
	type Number %ODELETE
	type String oldpref,oldtarg,srcphr,targphr,xtab

	do ADD
	
	quit
	
public ADD // Add
	
	set %ProcessMode=0 do INIT
	
	quit
	
public MOD // Modify
	
	set %ProcessMode=1 do INIT
	
	quit
	
public DEL // DBSMENU expects all index to be ready when going
	// in with %ProcessMode=3 use %ODELETE inside screen
	
	type public Number %ODELETE

	set %ProcessMode=1,%ODELETE=1 do INIT
	
	quit
	
INIT	// Init

	type String VFMQ,OLNTB 
	
	do VPG
	
	quit
	
VPG	// Page control

	type public String %LINK,%PGM,VFMQ
	
	type RecordI18NMLD fMLD=Class.new("RecordI18NMLD")
	
	if VFMQ.get(),"DFQ"[VFMQ do VER(.fMLD) quit

	do SCREEN(.fMLD)

	if %PGM.get() set %PGM=%PGM_$S(%LINK.get():"VPG0^",1:"VPG^")_$T(+0)_","
	if "DFQ"[VFMQ do VER(.fMLD) quit

	quit
	
SCREEN(RecordI18NMLD fMLD) // Screen
	
	type public Number %OSAVE

	type String SID
	
	set SID="I18NMLD"

	set %OSAVE=%ProcessMode
	do DRV^USID(.%ProcessMode,SID,.fMLD)
	set %ProcessMode=%OSAVE
	
	quit
	
VER(RecordI18NMLD fMLD)	// Verify filing action

	type public String srcphr,targphr,VFMQ
	
	set srcphr=srcphr.get()
	set targphr=targphr.get()
	
	if %ProcessMode=2!(%ProcessMode=4)!(VFMQ="Q") do END quit

	do FILE(.fMLD)

	quit
	
FILE(RecordI18NMLD fMLD)	// File data

	type public String oldtarg,oldpref,srcphr,targphr,xtab
	
	type Number xtabcnt
	
	if %ProcessMode=3 do { do END quit
		do Db.delete("I18NMLD","SRCPHR=:srcphr AND TARGPHR=:targphr")
		do Db.delete("I18NMLDX","TARGPHR=:$$NRMPHR^I18NNRM(targphr,1) AND SRCPHR=:srcphr")
		}
	
	if (%ProcessMode=1),(targphr'=oldtarg) do {
		// If modifying, and old target phrase is not equal
		// to new target phrase, then delete the old target
		do Db.delete("I18NMLD","SRCPHR=:srcphr AND TARGPHR=:oldtarg")
		do Db.delete("I18NMLDX","TARGPHR=:$$NRMPHR^I18NNRM(oldtarg,1) AND SRCPHR=:srcphr")
		}
	
	type RecordI18NMLD i18nmld=Db.getRecord("I18NMLD","SRCPHR=:srcphr,TARGPHR=:targphr",1)
	set i18nmld.prefphr=fMLD.prefphr
	set i18nmld.transuid=%UserID
	set i18nmld.transdt=fMLD.transdt
	set i18nmld.transtime=fMLD.transtime
	
	// Test if preferd already exist
	if (i18nmld.prefphr="1"),(xtab.exists()) do {
		set oldpref=$$GETPHR^I18NUTL("S",srcphr,.xtab,.xtabcnt)
		// Yes we have an old one !!!
		if xtab(oldpref)="*" do {
			type RecordI18NMLD i18nmld1=Db.getRecord("I18NMLD","SRCPHR=:srcphr,TARGPHR=:oldpref",1)
			set i18nmld1.prefphr=0
			do i18nmld1.save()
			}
		}
		
	do i18nmld.save()
	
	type RecordI18NMLDX i18nmldx=Db.getRecord("I18NMLDX","SRCPHR=:srcphr,TARGPHR=:targphr",1)
	set i18nmldx.targphr=$$NRMPHR^I18NNRM(targphr,1)
	do i18nmldx.save()
	
	do END

	quit
	
END	// Finish up ...

	type public String dsrcphr,ER,RM,srcphr,VFMQ
	
	if (ER.get())!(%ProcessMode=2)!(%ProcessMode=4) quit

	set ER="W"
	// MLD entry ~p1 ~p2 ~p3
	set RM=$$^MSG(5452,srcphr,$S(VFMQ="Q":" not ",1:" "),$S(%ProcessMode=0:"created",%ProcessMode=1:"modified",1:"deleted"))
	if srcphr="" set RM=""
	
	set dsrcphr=srcphr
	if (%ProcessMode=0),(VFMQ="F") do ADD quit
	if (%ProcessMode=1),(VFMQ="F") do MOD quit
	if (%ProcessMode=3),(VFMQ="D") set srcphr=dsrcphr do DEL quit

	kill dsrcphr

	quit

vSIG()	quit "60236^17791^Balasubramonian Sankar^3986"	// Signature - LTD^TIME^USER^SIZE
