LETCIFD	  /*
ORIG: ofaltr - 06/20/2000
DESC: Customer Mintenance Letters

---- Comments --------------------------------------------------------

---- Revision History ------------------------------------------------

	01/30/06 Radhika - CR 17423
		 .Eliminated PSL deprecated features and warnings.
		 .Removed revision history prior to 2004.

 */
 	type public String %FN
	type Date FORMTJD
	type Number DAY
	type String SAVFN,XFORM,XFID,XTJD(),zz
	
	set XFID="CIFD"
	set SAVFN=%FN
	type ResultSet rs=Db.select("FORM","STBLFORMBCH","FID=:XFID")

	if rs.isEmpty() quit
 	while rs.next() do {
		set XFORM=rs.getCol("FORM")	
		type ResultSet rs1=Db.select("TJDVAL","UTBLFORMVAR","FORM=:XFORM")
                if rs1.isEmpty() quit
                while rs1.next() do {
                        set XTJD=rs1.getCol("TJDVAL")
                        set XTJD(XTJD)=""
                        }
		}
	
	set zz=""
	for  set zz=XTJD(zz).order() quit:zz.isNull()  do {
                set DAY=zz.piece("T",2)
                set FORMTJD=%SystemDate+DAY
		set %FN=SAVFN_"_"_zz
                do DRV^UBCHID("BCHLETCIFD")
                }

        quit

vSIG()	quit "60295^31125^Radhika Panchanathan^1090"	// Signature - LTD^TIME^USER^SIZE
