LETSPV	  /*
ORIG: burnsm - 06/20/2000
DESC: Supervisor Override Letters

---- Comments --------------------------------------------------------

---- Revision History ------------------------------------------------

	02/01/06 Radhika - CR 17423
		 .Eliminated PSL deprecated features and warnings.
		 .Removed revision history prior to 2004.

 */
	//Variable Definition
	type public String %FN
	type Date FORMTJD
	type Number DAY
	type String SAVFN,XFORM,XFID,XTJD(),zz
	
        set XFID="SPV"
	set SAVFN=%FN
        type ResultSet rs=Db.select("FORM","STBLFORMBCH","FID=:XFID")
        if rs.isEmpty() quit
        while rs.next() do {
                set XFORM=rs.getCol("FORM")
 
                type ResultSet rs1=Db.select("TJDVAL","UTBLFORMVAR","FORM=:XFORM")
                if rs1.isEmpty() quit
                while rs1.next() do {
                        set XTJD=rs1.getCol("TJDVAL")
                        set XTJD(XTJD)=""
                        } //end of nested while
                } //end of while
                
	set zz=""
	for  set zz=XTJD(zz).order() quit:zz.isNull()  do {
                set DAY=zz.piece("T",2)
                set FORMTJD=%SystemDate+DAY
		set %FN=SAVFN_"_"_zz
		do DRV^UBCHID("BCHLETSPV")
                } //end of for
        quit
 

vSIG()	quit "60298^29303^Radhika Panchanathan^1230"	// Signature - LTD^TIME^USER^SIZE
