LNAEU5		

	//Private;Loan Single Account Auto Escrow Adjustment Inquiry
	//Copyright(c)1994 Sanchez Computer Associates, Inc.  All Rights Reserved - 10/14/94 13:32:52 - ZENGF

	/*
	//ORIG:	Srinivar - 01/23/06
	//DESC:	User inputs loan account.  System returns required transactions
	   	to bring escrow account balances in line with percentages
	       	found in auto-escrow processing fields.
	       	
	 ---- Revision History ------------------------------------------------
	 01/23/06 - Srinivar -CR 19137
	 	    
	 	    Removed the old Revision Histories.
	 	    Converted to PSL 
	----------------------------------------------------------------------   
	*/
	
	do INQ
	
	quit	
	
INQ	
	type public Number %O
	
	set %O=2
	do INIT
	
	quit
	
INIT	
	
	type public String VFMQ
	type Number %PG,%PAGE,OLNTB
	
	set %PG=0,%PAGE=1
	
	type RecordLN ln
	do VPG(.ln)
	
	K OLNTB,VFMQ
	quit
	
VPG(RecordLN ln)	// Page control
	
	type public Boolean ER
	type public Number %PG
	type public String VFMQ
		
	type Boolean FINISH
	
	set FINISH=0
	for  do { quit:FINISH
		if %PG=0 do VPG00(.ln) if ER!(VFMQ="Q") set FINISH=1 quit

		if %PG>0 do VPG01(.ln)

		if "DFQ"[VFMQ do VER set FINISH=1 quit

		set %PG=%PG+1
		}
	quit	
	
	
VPG00(RecordLN ln)	 //Set up
	
	type public Number CID,%O
	type public String IO,OPT(),%READ,VFMQ	
	type String %TAB
	
	set %TAB("CID")=".CID1/HLP=[LN]CID/XPP=D CIDPP^LNAEU5(.ln)"
	 //DES=Processing Option",OPT=0/TYP=N/LEN=1
	set %TAB("OPT")=".OPT11/TBL=OPT("
	 //DES=Option Override/TYP=N/LEN=1
	set %TAB("AEUO")=".AEUO/TBL=[STBLAUO]"
	set %TAB("IO")=$$IO^SCATAB($I)
	
	//Look up table
	 //Use account's on-line auto escrow processing option.
	set OPT(0)=$$^MSG(7486)
	//Use account's on-demand auto escrow processing option.
	set OPT(1)=$$^MSG(7485)
	
	set %READ="@@%FN,,,CID/REQ,OPT/REQ,AEUO,IO"
	do ^UTLREAD if VFMQ="Q" quit

	if %O=2,IO'=$I do OPEN^SCAIO
	
	quit
	
	
CIDPP(RecordLN ln)				// Account prompt post processor
	
	type public Number CID,X
	type public Boolean ER
	
	type String CLS,ZCLS,ET
	type Number %EXT
	
	if X="" Q
	
	set %EXT=1,(CLS,ZCLS)="L" do ^UACN quit:ER!(X="")
	
	set ln=Db.getRecord("LN","CID=:CID",1)
	
	if 'ln.auo set ET="LNAEU5" do ERR quit
	
	quit
	
	
VPG01(RecordLN ln)	 //Screen
	
	type public Number CID,OPT
	type public String LNAEU(),TR()
	type public Number BALCMP,ADJBAL,AUADJ,AEUO
	type public Boolean ER
	
	type Number N,CNT
	
	set ln=Db.getRecord("LN","CID=:CID",1)
	type RecordTTX ttx=Class.new("RecordTTX")
	N SID
	
	do EXEC^LNAEU(.ln,.ttx,CID,2001_+OPT,1,,AEUO,.AUADJ) Q:ER
	
	set N=1,CNT="" for  set N=TR(N).order() quit:N=""  do {
		set CNT=CNT+1
		set LNAEU(CNT).piece("|",1)=TR(N).piece("|",1)
		set LNAEU(CNT).piece("|",2)=TR(N).piece("|",3)
		set LNAEU(CNT).piece("|",3)=TR(N).piece("|",4)
		set LNAEU(CNT).piece("|",4)=TR(N).piece("|",7)
	}
	set BALCMP=ln.bal
	if ln.aruf set BALCMP=BALCMP-ln.udbal
	
	//Compute adjusted balance required for screen
	set ADJBAL=BALCMP+AUADJ
	
	set SID="LNESCADJ5" 
	
	do DRV^USID(%ProcessMode,SID,.ln)
	
	quit
	
ERR	
	type public Boolean ER
	type public String VFMQ

	set ER=1 
	do ^UTLERR
	set VFMQ="Q"
	quit
	
	
VER	 //Verification
	  
	  quit
	  		
FILE	 //File data
	
	 quit
	 
END	//End of processing
	
	 quit
	

vSIG()	quit "60304^31253^Srinivasan, Rajesh^3044"	// Signature - LTD^TIME^USER^SIZE
