LNCNP	/*
	   Uses stored values to initialize transaction code values in product
	   types.

	   Data is stored in the values field stored in the group name label.
	   The corresponding data item name is stored in the FIELDS variable.
	   Changes can be made by adding a new data item to the end of the list
	   and the corresponding data value to the end of values.

	   *** Please Note: By calling this routine at the top (as would be
	       the case with a conversion routine) the tran codes will be
	       directly initialized.

	       By calling the INIT line tag, a function could be used to call
	       this routine.

	---- Revision History ------------------------------------------------

	03/02/06 - TITOVE - CR 19733
		   Modified LNFEE section to instantiate an LNFEEP object with
		   a "create-if-needed" qualifier.

	*/

	do FILE 
	quit

INIT	//
	set (%PG,%PAGE)=1
	kill VFMQ,OLNTB

VPG	// Page control
	if %PG=1 do VPG00 do VPG0 quit

VPG0 	//
	if "DFQ"[VFMQ do VER quit
	set %PG=%PG+1
	do VPG 
	quit

VPG00	// Set up
	set %TAB("YN")=".YN1"
	set %READ="@@%FN,,,YN/REQ"

	do ^UTLREAD 
	if VFMQ="Q" quit
	if 'YN set VFMQ="Q"

	quit


ERR	//
	set ER=1 
	do ^UTLERR
	set VFMQ="Q"
	quit

VER 	//
	if VFMQ="Q" do END quit
	do FILE

END	
	kill %TAB 
	if $G(ER) quit

	// Transaction codes not initialized
	if VFMQ="Q" set RM=$$^MSG(2711)

	// Transaction codes initialized
	else  set RM=$$^MSG(2710)
	
	set ER="W"

	quit

FILE	// File date

	do PROD2

	do LNFEE

	quit


PROD2	//Define type and tag
	
	new CLASS,TAG,TYP 
	type ResultSet rs=Db.select("CLS,GRP,TYPE","PRODCTL")
	if rs.isEmpty() quit
        while rs.next() do {
		set CLASS=rs.getCol(1)
		if CLASS'="D",CLASS'="L" quit
		set TYP=rs.getCol(3)
		set TAG=rs.getCol(2)
		do CONV
		}
	quit


LNFEE	// Add fee tran codes to fee plans

	type String FEE
	
	type ResultSet rs=Db.select("FEETYP","LNFEEP")
	
	while rs.next() do {
		
		set FEE=rs.getCol("FEETYP")
		
		type RecordLNFEEP lnfeep=Db.getRecord("LNFEEP","FEETYP=:FEE", 1)
		
		if lnfeep.comfct.isNull() set lnfeep.comfct="CMMR"
		if lnfeep.mtgfct.isNull() set lnfeep.mtgfct="MMR"
		if lnfeep.lnfct.isNull() set lnfeep.lnfct="LMR"
		if lnfeep.cblfct.isNull() set lnfeep.cblfct="CBMR"
		if lnfeep.rcfct.isNull() set lnfeep.rcfct="RMR"
		if lnfeep.dmfct.isNull() set lnfeep.dmfct="DLMR"
		if lnfeep.comfiat.isNull() set lnfeep.comfiat="CMMI"
		if lnfeep.mtgfiat.isNull() set lnfeep.mtgfiat="MMI"		
		if lnfeep.lnfiat.isNull() set lnfeep.lnfiat="LMI"
		if lnfeep.cblfiat.isNull() set lnfeep.cblfiat="CBMI"		
		if lnfeep.rcfiat.isNull() set lnfeep.rcfiat="RMI"
		if lnfeep.dmfiat.isNull() set lnfeep.dmfiat="DLMI"
		
		do lnfeep.bypassSave()
                }
	quit

CONV	//

	do @TAG
	quit

ESC	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
	set prodctl.dradpr="EOW"
	set prodctl.dradie="EOW"
	set prodctl.dradna="ECWI"
	set prodctl.dradres="ER"
	set prodctl.cradpr="ED"
	set prodctl.cradpe="EIP"
	set prodctl.cradie="EOP"
	set prodctl.drtros="DIAE"
	set prodctl.drtrts="DIPE"
	set prodctl.crtrts="IIPE"
	do prodctl.save()
	
	quit

SAV	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="SW"
        set prodctl.dradpe="DIPS"
        set prodctl.dradna="SCWI"
        set prodctl.cradpr="SD"
        set prodctl.cradpe="IIPS"
        set prodctl.drtrgp="SW"
        set prodctl.drtros="DIAS"
        set prodctl.drtrts="DIPS"
        set prodctl.drtrci="INAS"
        set prodctl.drtrrl="INIS"
	set prodctl.crtrgp="SD"
	set prodctl.crtrts="IIPS"
	set prodctl.crtrci="DNAS"
	set prodctl.crtrrl="DNIS"
        do prodctl.save()

	quit

DDA	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="DW"
        set prodctl.dradin="DW"
        set prodctl.dradpe="DIPD"
        set prodctl.dradna="DC"
        set prodctl.cradpr="DD"
        set prodctl.cradpe="IIPD"
        set prodctl.cradna="DCDB"
        set prodctl.drtrgp="DW"
        set prodctl.drtros="DIAD"
        set prodctl.drtrts="DIPD"
        set prodctl.drtrci="INAA"
        set prodctl.drtrrl="INIA"
        set prodctl.drtrfr="IRID"
        set prodctl.crtrgp="DD"
	set prodctl.crtrts="IIPD"
	set prodctl.crtrci="DNAA"
	set prodctl.crtrrl="DNIA"
	set prodctl.crtrfr="DRID"
        do prodctl.save()

        quit

CD	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="CW"
        set prodctl.dradpe="DIPC"
        set prodctl.dradna="CCWI"
        set prodctl.cradpr="CD"
        set prodctl.cradpe="IIPC"
        set prodctl.drtrgp="CW"
        set prodctl.drtros="DIAC"
        set prodctl.drtrts="DIPC"
        set prodctl.drtrci="INAC"
        set prodctl.drtrrl="INIC"
        set prodctl.crtrgp="CD"
        set prodctl.crtrin="DPC"
        set prodctl.crtrts="IIPC"
        set prodctl.crtrci="DNAC"
        set prodctl.crtrrl="DNIC"
	do prodctl.save()

	quit

WASH	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="WW"
        set prodctl.dradna="WCDW"
        set prodctl.cradpr="WD"
        set prodctl.drtrci="INAW"
        set prodctl.crtrci="DNAW"
	do prodctl.save()

	quit

DBD	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="DBDW"
        set prodctl.dradpe="DIPDBD"
        set prodctl.dradna="DBDC"
        set prodctl.cradpr="DBDD"
        set prodctl.cradpe="IIPDBD"
        set prodctl.cradna="DBDCWI"
        set prodctl.drtrgp="DBDW"
        set prodctl.drtros="DIADBD"
        set prodctl.drtrci="DNADBD"
        set prodctl.crtrgp="DBDD"
	set prodctl.crtrci="INADBD"
        do prodctl.save()

	quit

CBL	//
	
	 
        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="CBD"
        set prodctl.dradin="CBDEB"
        set prodctl.dradpe="CBRIP"
        set prodctl.draddc="CBLC"
        set prodctl.dradts="CBMC"
        set prodctl.dradii="CBEW"
        set prodctl.cradpr="CBP"
        set prodctl.cradin="CBPPO"
        set prodctl.cradpe="CBPIO"
        set prodctl.craddc="CBPLO"
        set prodctl.cradts="CBPMO"
        set prodctl.cradii="CBEO"
        set prodctl.drtrpr="IIACB"
        set prodctl.crtrpr="DIACB"
        do prodctl.save()

	quit

RC	//
	 
        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="RA"
        set prodctl.dradin="RDEB"
        set prodctl.dradpe="RRIP"
        set prodctl.draddc="RLC"
        set prodctl.dradts="RMC"
        set prodctl.dradii="REW"
        set prodctl.cradpr="RP"
        set prodctl.cradin="RPPO"
        set prodctl.cradpe="RPIO"
        set prodctl.craddc="RPLO"
        set prodctl.cradts="RPMO"
        set prodctl.cradii="REO"
        set prodctl.drtrpr="IIAR"
        set prodctl.crtrpr="DIAR"
        do prodctl.save()

        quit

COM	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="CMD"
        set prodctl.dradin="CMDEB"
        set prodctl.dradpe="CMRIP"
        set prodctl.draddc="CMLC"
        set prodctl.dradts="CMMC"
        set prodctl.dradii="CMEW"
        set prodctl.cradpr="CMP"
        set prodctl.cradin="CMPPO"
        set prodctl.cradpe="CMPIO"
        set prodctl.craddc="CMPLO"
        set prodctl.cradts="CMPMO"
        set prodctl.cradii="CMEO"
        set prodctl.drtrpr="IIACM"
        set prodctl.crtrpr="DIACM"
        do prodctl.save()

        quit

LN	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="LD"
        set prodctl.dradin="LDEB"
        set prodctl.dradpe="LRIP"
        set prodctl.draddc="LLC"
        set prodctl.dradts="LMC"
        set prodctl.dradii="LEW"
        set prodctl.cradpr="LP"
        set prodctl.cradin="LPPO"
        set prodctl.cradpe="LPIO"
        set prodctl.craddc="LPLO"
        set prodctl.cradts="LPMO"
        set prodctl.cradii="LEO"
        set prodctl.drtrpr="IIAI"
        set prodctl.crtrpr="DIAI"
        do prodctl.save()

        quit

MTG	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="MD"
        set prodctl.dradin="MDEB"
        set prodctl.dradpe="MRIP"
        set prodctl.draddc="MLC"
        set prodctl.dradts="MMC"
        set prodctl.dradii="MEW"
        set prodctl.cradpr="MP"
        set prodctl.cradin="MPPO"
        set prodctl.cradpe="MPIO"
        set prodctl.craddc="MPLO"
        set prodctl.cradts="MPMO"
        set prodctl.cradii="MEO"
        set prodctl.drtrpr="IIAM"
        set prodctl.crtrpr="DIAM"
        do prodctl.save()

        quit


DM	//

        type RecordPRODCTL prodctl=Db.getRecord("PRODCTL","TYPE=:TYP")
        set prodctl.dradpr="DLD"
        set prodctl.dradin="DLDEB"
        set prodctl.dradpe="DRIP"
        set prodctl.draddc="DLC"
        set prodctl.dradts="DLMC"
        set prodctl.dradii="DLEW"
        set prodctl.cradpr="DLP"
        set prodctl.cradin="DLPO"
        set prodctl.cradpe="DLPIO"
        set prodctl.craddc="DLPLO"
        set prodctl.cradts="DLPMO"
        set prodctl.cradii="DLEO"
        set prodctl.drtrpr="IIADL"
        set prodctl.crtrpr="DIADL"
        do prodctl.save()

        quit

vSIG()	quit "60326^48112^Eugene Titov^8882"	// Signature - LTD^TIME^USER^SIZE
