LNES3	//Loan Escrow Account History ; Procedure LNES3 - Loan Escrow Account History
 ;;Copyright(c)2005 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/09/05 10:33 - spatola
 ;
 ; **** This is a DATA-QWIK generated routine (level 25) ****
 ;
	/*

	  ---- Revision History ------------------------------------------------

	05/16/02 - VETSENM - 49794
                   Converted to PSL.            	
	
	*/

VPG0	//
	kill OLNTB
	set %PG=0

	set %TAB("CID")=".CID3/XPP=set %EXT=1 do ^UACN/XPR=set (CLS,ZCLS)=""L"""
	set %TAB("TRTYPE")=".ESC/TBL=PR(/XPR=do TT^LNES2"

	set %READ="@@%FN,,,CID/REQ,TRTYPE/REQ"
	do ^UTLREAD if VFMQ="Q" quit
	
	set CID=$$ECID^LNU(CID,TRTYPE)
	do PROT^UHIS

	// ~p1 account does not have any activity
	if ER do { quit
		if RM[($P(PR(TRTYPE),"|",2)) set RM=$$^MSG(3011,TRTYPE) 
		set TRTYPE="" 
		do VPG0
		}
	
	set %PG=1 do EXT^UHIS
	quit

vSIG()	quit "59886^43534^Sanchez SCM Administrator^592"	// Signature - LTD^TIME^USER^SIZE
