LNFIL1 // LN DATA-QWIK filer, part (3)
 // Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:25 - shetyes

	quit		// Not called from top


vddver // Validate data dictionary attributes

	type public Number %O
	type public String vpar,vx()

	type String vRM,X
	type public RecordLN ln

	if (%O = 2) do vload^LNFILE

	if vobj(ln,1).exists() do {

		if ln.acctname.length()>25 set vRM = $$^MSG(1076,25) do vdderr("ACCTNAME", vRM) quit
		if ln.title1.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE1", vRM) quit
		if ln.title2.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE2", vRM) quit
		if ln.title3.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE3", vRM) quit
		if ln.title4.length()>40 set vRM = $$^MSG(1076,40) do vdderr("TITLE4", vRM) quit
	}

	if vobj(ln,49).exists() do {

		set X = ln.anpp if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ANPP", vRM) quit
		if '("01"[ln.ARUF) set vRM=$$^MSG(742,"L") do vdderr("ARUF", vRM) quit
		if '("01"[ln.CPF) set vRM=$$^MSG(742,"L") do vdderr("CPF", vRM) quit
		if ln.custnot.length()>10 set vRM = $$^MSG(1076,10) do vdderr("CUSTNOT", vRM) quit
		set X = ln.ddra if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("DDRA", vRM) quit
		set X = ln.ddrd if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DDRD", vRM) quit
		if ln.iacm.length()>2 set vRM = $$^MSG(1076,2) do vdderr("IACM", vRM) quit
		set X = ln.iam if 'X.isNull(),'Db.isDefined("STBLIAM","X") set vRM = $$^MSG(1485,X) do vdderr("IAM", vRM) quit
		set X = ln.icm if 'X.isNull(),'Db.isDefined("STBLICM","X") set vRM = $$^MSG(1485,X) do vdderr("ICM", vRM) quit
		set X = ln.idp if 'X.isNull(),'Db.isDefined("STBLIDP","X") set vRM = $$^MSG(1485,X) do vdderr("IDP", vRM) quit
		set X = ln.incdr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INCDR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.irb if 'X.isNull(),'Db.isDefined("STBLGRPI","X") set vRM = $$^MSG(1485,X) do vdderr("IRB", vRM) quit
		if '("01"[ln.IRCB) set vRM=$$^MSG(742,"L") do vdderr("IRCB", vRM) quit
		set X = ln.maxdrct if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("MAXDRCT", vRM) quit
		set X = ln.minacr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MINACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mindr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MINDR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.minopt if 'X.isNull(),'Db.isDefined("STBLMINOPT","X") set vRM = $$^MSG(1485,X) do vdderr("MINOPT", vRM) quit
		if '("01"[ln.NEGACRPO) set vRM=$$^MSG(742,"L") do vdderr("NEGACRPO", vRM) quit
		set X = ln.negipo if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("NEGIPO", vRM) quit
		set X = ln.odio if 'X.isNull(),'Db.isDefined("STBLODIO","X") set vRM = $$^MSG(1485,X) do vdderr("ODIO", vRM) quit
		set X = ln.odo if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("ODO", vRM) quit
		if ln.pap.length()>12 set vRM = $$^MSG(1076,12) do vdderr("PAP", vRM) quit
		set X = ln.pas if 'X.isNull(),'Db.isDefined("LNPAS2","X") set vRM = $$^MSG(1485,X) do vdderr("PAS", vRM) quit
		if ln.pcm.length()>3 set vRM = $$^MSG(1076,3) do vdderr("PCM", vRM) quit
		if ln.pdag.length()>12 set vRM = $$^MSG(1076,12) do vdderr("PDAG", vRM) quit
		set X = ln.pmtdelqr if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PMTDELQR", vRM) quit
		if ln.pmtgrc.length()>6 set vRM = $$^MSG(1076,6) do vdderr("PMTGRC", vRM) quit
		set X = ln.pmtmin if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMTMIN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.popt.length()>6 set vRM = $$^MSG(1076,6) do vdderr("POPT", vRM) quit
		set X = ln.ppf if 'X.isNull(),'Db.isDefined("STBLPPF","X") set vRM = $$^MSG(1485,X) do vdderr("PPF", vRM) quit
		set X = ln.pvo if 'X.isNull(),'Db.isDefined("STBLPVO","X") set vRM = $$^MSG(1485,X) do vdderr("PVO", vRM) quit
		set X = ln.sbwamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.SBWAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.scc.length()>3 set vRM = $$^MSG(1076,3) do vdderr("SCC", vRM) quit
		if '("01"[ln.SIBF) set vRM=$$^MSG(742,"L") do vdderr("SIBF", vRM) quit
		set X = ln.trb if 'X.isNull(),'Db.isDefined("STBLDC","X") set vRM = $$^MSG(1485,X) do vdderr("TRB", vRM) quit
	}

	if vobj(ln,50).exists() do {

		set X = ln.acngrp if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("ACNGRP", vRM) quit
		if '("01"[ln.ANLSYS) set vRM=$$^MSG(742,"L") do vdderr("ANLSYS", vRM) quit
		set X = ln.aomcode if 'X.isNull(),'Db.isDefined("STBLCINTMET","X") set vRM = $$^MSG(1485,X) do vdderr("AOMCODE", vRM) quit
		if ln.atn.length()>50 set vRM = $$^MSG(1076,50) do vdderr("ATN", vRM) quit
		set X = ln.cc if 'X.isNull(),'Db.isDefined("UTBLCCNTR","X") set vRM = $$^MSG(1485,X) do vdderr("CC", vRM) quit
		set X = ln.ccode if 'X.isNull(),'Db.isDefined("UTBLCC","X") set vRM = $$^MSG(1485,X) do vdderr("CCODE", vRM) quit
		set X = ln.cls if 'X.isNull(),'Db.isDefined("STBLCLS","X") set vRM = $$^MSG(1485,X) do vdderr("CLS", vRM) quit
		if '("01"[ln.COMM) set vRM=$$^MSG(742,"L") do vdderr("COMM", vRM) quit
		if ln.crcd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("CRCD", vRM) quit
		if '("01"[ln.CUSTOM1) set vRM=$$^MSG(742,"L") do vdderr("CUSTOM1", vRM) quit
		if '("01"[ln.CUSTOM2) set vRM=$$^MSG(742,"L") do vdderr("CUSTOM2", vRM) quit
		if '("01"[ln.CUSTOM3) set vRM=$$^MSG(742,"L") do vdderr("CUSTOM3", vRM) quit
		if '("01"[ln.EMPLBEN) set vRM=$$^MSG(742,"L") do vdderr("EMPLBEN", vRM) quit
		set X = ln.emplno if 'X.isNull(),'Db.isDefined("UTBLEMPLOYER","X") set vRM = $$^MSG(1485,X) do vdderr("EMPLNO", vRM) quit
		if ln.feepln.length()>5 set vRM = $$^MSG(1076,5) do vdderr("FEEPLN", vRM) quit
		set X = ln.fldstaff if 'X.isNull(),'Db.isDefined("UTBLFLDSTAFF","X") set vRM = $$^MSG(1485,X) do vdderr("FLDSTAFF", vRM) quit
		set X = ln.glsc if 'X.isNull(),'Db.isDefined("UTBLGLSC","X") set vRM = $$^MSG(1485,X) do vdderr("GLSC", vRM) quit
		set X = ln.grp if 'X.isNull(),'Db.isDefined("STBLGRP","CLS=""L"",GRP=:X") set vRM = $$^MSG(1485,X) do vdderr("GRP", vRM) quit
		if '("01"[ln.HIGHVOL) set vRM=$$^MSG(742,"L") do vdderr("HIGHVOL", vRM) quit
		set X = ln.lfpc if 'X.isNull(),'Db.isDefined("STBLLFSC1","X") set vRM = $$^MSG(1485,X) do vdderr("LFPC", vRM) quit
		if ln.lfsc.length()>6 set vRM = $$^MSG(1076,6) do vdderr("LFSC", vRM) quit
		if ln.lnm.length()>20 set vRM = $$^MSG(1076,20) do vdderr("LNM", vRM) quit
		set X = ln.mf if 'X.isNull(),'Db.isDefined("UTBLMF","X") set vRM = $$^MSG(1485,X) do vdderr("MF", vRM) quit
		set X = ln.pers if 'X.isNull(),'Db.isDefined("STBLPERS","X") set vRM = $$^MSG(1485,X) do vdderr("PERS", vRM) quit
		if '("01"[ln.REGCC) set vRM=$$^MSG(742,"L") do vdderr("REGCC", vRM) quit
		set X = ln.regccexc if 'X.isNull(),'Db.isDefined("STBLREGCCX","X") set vRM = $$^MSG(1485,X) do vdderr("REGCCEXC", vRM) quit
		set X = ln.regccexp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("REGCCEXP", vRM) quit
		set X = ln.regd if 'X.isNull(),'Db.isDefined("STBLREGD1","X") set vRM = $$^MSG(1485,X) do vdderr("REGD", vRM) quit
		set X = ln.secgrp if 'X.isNull(),'Db.isDefined("UTBLSECGRP","X") set vRM = $$^MSG(1485,X) do vdderr("SECGRP", vRM) quit
		set X = ln.subcd if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("SUBCD", vRM) quit
		set X = ln.type if 'X.isNull(),'Db.isDefined("PRODDFTL","X") set vRM = $$^MSG(1485,X) do vdderr("TYPE", vRM) quit
	}

	if vobj(ln,51).exists() do {

		if '("01"[ln.ADF) set vRM=$$^MSG(742,"L") do vdderr("ADF", vRM) quit
		set X = ln.bal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.BAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.balcol if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.BALCOL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.balint if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.BALINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ccl if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("CCL", vRM) quit
		set X = ln.ccld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CCLD", vRM) quit
		set X = ln.chkhld if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CHKHLD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cntcr if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("CNTCR", vRM) quit
		set X = ln.cntdr if 'X.isNull(),X'?1.10N,X'?1"-"1.9N set vRM=$$^MSG(742,"N") do vdderr("CNTDR", vRM) quit
		set X = ln.coa if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.donrsk if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DONRSK"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.ENTF) set vRM=$$^MSG(742,"L") do vdderr("ENTF", vRM) quit
		set X = ln.flttbl if 'X.isNull(),'Db.isDefined("UTBLRTTBL","X") set vRM = $$^MSG(1485,X) do vdderr("FLTTBL", vRM) quit
		set X = ln.fmld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("FMLD", vRM) quit
		set X = ln.habl1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.HABL1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.habl2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.HABL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.hldtbl if 'X.isNull(),'Db.isDefined("UTBLRTTBL","X") set vRM = $$^MSG(1485,X) do vdderr("HLDTBL", vRM) quit
		set X = ln.icpa if 'X.isNull(),'Db.isDefined("UTBLICPA","X") set vRM = $$^MSG(1485,X) do vdderr("ICPA", vRM) quit
		set X = ln.lnsa if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("LNSA", vRM) quit
		set X = ln.lpdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LPDT", vRM) quit
		set X = ln.odd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ODD", vRM) quit
		if '("01"[ln.PBI) set vRM=$$^MSG(742,"L") do vdderr("PBI", vRM) quit
		if '("01"[ln.PHLD) set vRM=$$^MSG(742,"L") do vdderr("PHLD", vRM) quit
		set X = ln.rec if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.REC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.REVF) set vRM=$$^MSG(742,"L") do vdderr("REVF", vRM) quit
		if '("01"[ln.RFLG) set vRM=$$^MSG(742,"L") do vdderr("RFLG", vRM) quit
		set X = ln.rskopt if 'X.isNull(),'Db.isDefined("STBLRSKOPT","X") set vRM = $$^MSG(1485,X) do vdderr("RSKOPT", vRM) quit
		set X = ln.stat if 'X.isNull(),'Db.isDefined("STBLSTATL","X") set vRM = $$^MSG(1485,X) do vdderr("STAT", vRM) quit
		set X = ln.stfnet if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.STFNET"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.stp.length()>20 set vRM = $$^MSG(1076,20) do vdderr("STP", vRM) quit
		set X = ln.stp2 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP2", vRM) quit
		set X = ln.stp3 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP3", vRM) quit
		set X = ln.stp4 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP4", vRM) quit
		set X = ln.stp5 if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("STP5", vRM) quit
		set X = ln.teb if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TEB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.tld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("TLD", vRM) quit
		set X = ln.udbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.UDBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,52).exists() do {

		set X = ln.amodt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("AMODT", vRM) quit
		set X = ln.boo if 'X.isNull(),'Db.isDefined("UTBLBRCD","X") set vRM = $$^MSG(1485,X) do vdderr("BOO", vRM) quit
		if ln.convacn.length()>40 set vRM = $$^MSG(1076,40) do vdderr("CONVACN", vRM) quit
		set X = ln.convdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CONVDT", vRM) quit
		set X = ln.dfp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DFP", vRM) quit
		set X = ln.dtc if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DTC", vRM) quit
		set X = ln.dtnt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DTNT", vRM) quit
		set X = ln.fma if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("FMA", vRM) quit
		set X = ln.fmo if 'X.isNull(),'Db.isDefined("STBLFMO","X") set vRM = $$^MSG(1485,X) do vdderr("FMO", vRM) quit
		set X = ln.hisctf if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("HISCTF", vRM) quit
		set X = ln.iro if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IRO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.maxbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MAXBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.maxfta if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MAXFTA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.maxftd if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("MAXFTD", vRM) quit
		set X = ln.mincl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MINCL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.odt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ODT", vRM) quit
		set X = ln.off if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("OFF", vRM) quit
		set X = ln.off2 if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("OFF2", vRM) quit
		set X = ln.off3 if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("OFF3", vRM) quit
		set X = ln.off4 if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("OFF4", vRM) quit
		set X = ln.off5 if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("OFF5", vRM) quit
		set X = ln.onp if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ONP", vRM) quit
		set X = ln.pmtorg if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMTORG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.refnum.length()>12 set vRM = $$^MSG(1076,12) do vdderr("REFNUM", vRM) quit
		set X = ln.rescd if 'X.isNull(),'Db.isDefined("UTBLRESCD","X") set vRM = $$^MSG(1485,X) do vdderr("RESCD", vRM) quit
		if '("01"[ln.TRUNC) set vRM=$$^MSG(742,"L") do vdderr("TRUNC", vRM) quit
	}

	if vobj(ln,53).exists() do {

		if '("01"[ln.AIPR) set vRM=$$^MSG(742,"L") do vdderr("AIPR", vRM) quit
		set X = ln.ambas if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("AMBAS", vRM) quit
		set X = ln.amtreq if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,1,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.AMTREQ"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.busopt if 'X.isNull(),'Db.isDefined("STBLBUSOPT","X") set vRM = $$^MSG(1485,X) do vdderr("BUSOPT", vRM) quit
		set X = ln.clmd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CLMD", vRM) quit
		set X = ln.clps if 'X.isNull(),'Db.isDefined("STBLCLPS","X") set vRM = $$^MSG(1485,X) do vdderr("CLPS", vRM) quit
		set X = ln.cnvprd if 'X.isNull(),'Db.isDefined("PRODDFTL","X") set vRM = $$^MSG(1485,X) do vdderr("CNVPRD", vRM) quit
		set X = ln.crlmt if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CRLMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ero if 'X.isNull(),'Db.isDefined("STBLERO","X") set vRM = $$^MSG(1485,X) do vdderr("ERO", vRM) quit
		if '("01"[ln.IPD) set vRM=$$^MSG(742,"L") do vdderr("IPD", vRM) quit
		set X = ln.lrd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LRD", vRM) quit
		set X = ln.lriab if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LRIAB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lripb if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LRIPB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lrpb if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LRPB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("MDT", vRM) quit
		set X = ln.nbdc if 'X.isNull(),'Db.isDefined("UTBLNBD","X") set vRM = $$^MSG(1485,X) do vdderr("NBDC", vRM) quit
		set X = ln.nbf if 'X.isNull(),'Db.isDefined("STBLLBF","X") set vRM = $$^MSG(1485,X) do vdderr("NBF", vRM) quit
		set X = ln.nobf if 'X.isNull(),'Db.isDefined("STBLLBF","X") set vRM = $$^MSG(1485,X) do vdderr("NOBF", vRM) quit
		set X = ln.oltp if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.OLTP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.org if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ORG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.ptrm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("PTRM", vRM) quit
		if ln.rencd.length()>8 set vRM = $$^MSG(1076,8) do vdderr("RENCD", vRM) quit
		set X = ln.rro if 'X.isNull(),'Db.isDefined("STBLRRO","X") set vRM = $$^MSG(1485,X) do vdderr("RRO", vRM) quit
		if '("01"[ln.SWPEL) set vRM=$$^MSG(742,"L") do vdderr("SWPEL", vRM) quit
		set X = ln.tdr if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TDR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.tracn if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("TRACN", vRM) quit
		if ln.trm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("TRM", vRM) quit
	}

	if vobj(ln,54).exists() do {

		set X = ln.acr if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acs if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ACS", vRM) quit
		set X = ln.copy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.coytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.daa if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DAA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intdef if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTDEF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ipl if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.IPLCF) set vRM=$$^MSG(742,"L") do vdderr("IPLCF", vRM) quit
		set X = ln.ipnd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IPND"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ipy if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.iun if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IUN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.iytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.NAI) set vRM=$$^MSG(742,"L") do vdderr("NAI", vRM) quit
		set X = ln.negacr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NEGACR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.negacrun if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NEGACRUN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.negipl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NEGIPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.negipy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NEGIPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.negiytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NEGIYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.prefint if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PREFINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.probal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PROBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.proind if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("PROIND", vRM) quit
		set X = ln.recpy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RECPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.recytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RECYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.refint if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.REFINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.trate if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TRATE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.trexd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("TREXD", vRM) quit
	}

	if vobj(ln,55).exists() do {

		set X = ln.cbfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]CBFRE",0) if 'vRM.get().isNull() do vdderr("CBFRE", vRM) quit
		set X = ln.cbmet if 'X.isNull(),'Db.isDefined("STBLCBMET","X") set vRM = $$^MSG(1485,X) do vdderr("CBMET", vRM) quit
		set X = ln.cboff if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("CBOFF", vRM) quit
		set X = ln.cbond if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CBOND", vRM) quit
		set X = ln.cbpld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CBPLD", vRM) quit
		set X = ln.cbpnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CBPND", vRM) quit
		set X = ln.dafpy if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DAFPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dafyd if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DAFYD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.darcexpd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DARCEXPD", vRM) quit
		set X = ln.darcls if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DARCLS", vRM) quit
		set X = ln.darcovr if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DARCOVR", vRM) quit
		if '("01"[ln.DLCAF) set vRM=$$^MSG(742,"L") do vdderr("DLCAF", vRM) quit
		set X = ln.drbl if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DRBL", vRM) quit
		set X = ln.extamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.EXTAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.extldt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EXTLDT", vRM) quit
		set X = ln.exttot if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("EXTTOT", vRM) quit
		set X = ln.fisbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.FISBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.fisint if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.FISINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.flca if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.FLCA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lchg if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LCHG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lcla if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LCLA", vRM) quit
		set X = ln.ndafpy if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NDAFPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ndafyd if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NDAFYD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ppl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.suspect if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("SUSPECT", vRM) quit
		set X = ln.unapf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.UNAPF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.WOFF) set vRM=$$^MSG(742,"L") do vdderr("WOFF", vRM) quit
	}

	if vobj(ln,56).exists() do {

		set X = ln.adtar if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("ADTAR", vRM) quit
		set X = ln.alpdue if 'X.isNull(),'Db.isDefined("STBLALPDUE","X") set vRM = $$^MSG(1485,X) do vdderr("ALPDUE", vRM) quit
		set X = ln.alpmin if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ALPMIN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.ALPRTY) set vRM=$$^MSG(742,"L") do vdderr("ALPRTY", vRM) quit
		set X = ln.auptcid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("AUPTCID", vRM) quit
		if '("01"[ln.CCBIND) set vRM=$$^MSG(742,"L") do vdderr("CCBIND", vRM) quit
		set X = ln.cfreq if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]CFREQ",0) if 'vRM.get().isNull() do vdderr("CFREQ", vRM) quit
		set X = ln.cmrate if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CMRATE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cmrindx if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("CMRINDX", vRM) quit
		set X = ln.cncal if 'X.isNull(),'Db.isDefined("UTBLNBD","X") set vRM = $$^MSG(1485,X) do vdderr("CNCAL", vRM) quit
		set X = ln.cnoff if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CNOFF", vRM) quit
		set X = ln.cnvdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CNVDT", vRM) quit
		if '("01"[ln.FPIND) set vRM=$$^MSG(742,"L") do vdderr("FPIND", vRM) quit
		set X = ln.pamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ppacp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PPACP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ppal if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PPAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ppdpl if 'X.isNull(),'Db.isDefined("UTBLPPDPL","X") set vRM = $$^MSG(1485,X) do vdderr("PPDPL", vRM) quit
		set X = ln.ppfreq if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]PPFREQ",0) if 'vRM.get().isNull() do vdderr("PPFREQ", vRM) quit
		set X = ln.ppld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PPLD", vRM) quit
		set X = ln.ppnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PPND", vRM) quit
		set X = ln.ppnopl if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("PPNOPL", vRM) quit
		set X = ln.ppnopp if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("PPNOPP", vRM) quit
		if '("01"[ln.RCBIND) set vRM=$$^MSG(742,"L") do vdderr("RCBIND", vRM) quit
		set X = ln.rdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("RDT", vRM) quit
		if '("01"[ln.RFMO) set vRM=$$^MSG(742,"L") do vdderr("RFMO", vRM) quit
		set X = ln.rfreq if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]RFREQ",0) if 'vRM.get().isNull() do vdderr("RFREQ", vRM) quit
		set X = ln.rncal if 'X.isNull(),'Db.isDefined("UTBLNBD","X") set vRM = $$^MSG(1485,X) do vdderr("RNCAL", vRM) quit
		if '("01"[ln.RNFLG) set vRM=$$^MSG(742,"L") do vdderr("RNFLG", vRM) quit
		set X = ln.rnoff if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RNOFF", vRM) quit
		if '("01"[ln.RPMO) set vRM=$$^MSG(742,"L") do vdderr("RPMO", vRM) quit
		set X = ln.rrmo if 'X.isNull(),'Db.isDefined("UTBLRRMO","X") set vRM = $$^MSG(1485,X) do vdderr("RRMO", vRM) quit
		if '("01"[ln.SRCBIND) set vRM=$$^MSG(742,"L") do vdderr("SRCBIND", vRM) quit
		set X = ln.srcdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SRCDT", vRM) quit
		set X = ln.strate if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.STRATE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.strcal if 'X.isNull(),'Db.isDefined("UTBLNBD","X") set vRM = $$^MSG(1485,X) do vdderr("STRCAL", vRM) quit
		set X = ln.strindx if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("STRINDX", vRM) quit
		set X = ln.stroff if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("STROFF", vRM) quit
		set X = ln.uppen if 'X.isNull(),'Db.isDefined("UTBLLNPPN","X") set vRM = $$^MSG(1485,X) do vdderr("UPPEN", vRM) quit
	}

	if vobj(ln,57).exists() do {

		if '("01"[ln.AIR) set vRM=$$^MSG(742,"L") do vdderr("AIR", vRM) quit
		set X = ln.aniriv if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ANIRIV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.anirld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANIRLD", vRM) quit
		set X = ln.anirnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANIRND", vRM) quit
		set X = ln.aniro if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ANIRO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.diaa if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DIAA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.diald if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIALD", vRM) quit
		set X = ln.diand if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIAND", vRM) quit
		set X = ln.dic if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dimxb if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DIMXB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dimxl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DIMXL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dimxy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DIMXY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dirfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]DIRFRE",0) if 'vRM.get().isNull() do vdderr("DIRFRE", vRM) quit
		set X = ln.dirld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIRLD", vRM) quit
		set X = ln.dirnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIRND", vRM) quit
		set X = ln.ditgacn if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("DITGACN", vRM) quit
		set X = ln.diu if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DIU"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.eirn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.EIRN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.eod if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EOD", vRM) quit
		if '("01"[ln.FLAT) set vRM=$$^MSG(742,"L") do vdderr("FLAT", vRM) quit
		set X = ln.iacf if 'X.isNull(),'Db.isDefined("STBLIACF","X") set vRM = $$^MSG(1485,X) do vdderr("IACF", vRM) quit
		set X = ln.ichld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ICHLD", vRM) quit
		set X = ln.ichnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ICHND", vRM) quit
		set X = ln.icpf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]ICPF",0) if 'vRM.get().isNull() do vdderr("ICPF", vRM) quit
		set X = ln.idefly if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IDEFLY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.idf if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,8) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IDF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intdefpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTDEFPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intdeftytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTDEFTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intmn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intmno if 'X.isNull(),'Db.isDefined("STBLINTMNO","X") set vRM = $$^MSG(1485,X) do vdderr("INTMNO", vRM) quit
		set X = ln.intmx if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMX"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intramt1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTRAMT1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intramt2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTRAMT2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intramt3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTRAMT3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intrexp1 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTREXP1", vRM) quit
		set X = ln.intrexp2 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTREXP2", vRM) quit
		set X = ln.intrexp3 if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTREXP3", vRM) quit
		set X = ln.intrrat1 if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTRRAT1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intrrat2 if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTRRAT2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intrrat3 if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTRRAT3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.invl if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INVL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.irf if 'X.isNull(),'Db.isDefined("STBLIRF","X") set vRM = $$^MSG(1485,X) do vdderr("IRF", vRM) quit
		set X = ln.irn if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IRN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.irsexm if 'X.isNull(),'Db.isDefined("STBLIRSEXM","X") set vRM = $$^MSG(1485,X) do vdderr("IRSEXM", vRM) quit
		set X = ln.nalpb if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NALPB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.namxb if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NAMXB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.narl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NARL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.RPIDC) set vRM=$$^MSG(742,"L") do vdderr("RPIDC", vRM) quit
		set X = ln.sch if 'X.isNull(),'Db.isDefined("UTBLRATE","X") set vRM = $$^MSG(1485,X) do vdderr("SCH", vRM) quit
	}

	if vobj(ln,58).exists() do {

		set X = ln.anld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANLD", vRM) quit
		set X = ln.anoff if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ANOFF", vRM) quit
		set X = ln.anoffdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANOFFDT", vRM) quit
		set X = ln.apcnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("APCND", vRM) quit
		if '("01"[ln.AUO) set vRM=$$^MSG(742,"L") do vdderr("AUO", vRM) quit
		set X = ln.aytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.AYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cues if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CUES"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cuin if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CUIN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cupr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CUPR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dico if 'X.isNull(),'Db.isDefined("STBLDICO","X") set vRM = $$^MSG(1485,X) do vdderr("DICO", vRM) quit
		set X = ln.dicytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DICYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.DRF) set vRM=$$^MSG(742,"L") do vdderr("DRF", vRM) quit
		if '("01"[ln.EACIP) set vRM=$$^MSG(742,"L") do vdderr("EACIP", vRM) quit
		if '("01"[ln.FPAF) set vRM=$$^MSG(742,"L") do vdderr("FPAF", vRM) quit
		set X = ln.fpc01 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC01", vRM) quit
		set X = ln.fpc02 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC02", vRM) quit
		set X = ln.fpc03 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC03", vRM) quit
		set X = ln.fpc04 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC04", vRM) quit
		set X = ln.fpc05 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC05", vRM) quit
		set X = ln.fpc06 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC06", vRM) quit
		set X = ln.fpc07 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC07", vRM) quit
		set X = ln.fpc08 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC08", vRM) quit
		set X = ln.fpc09 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC09", vRM) quit
		set X = ln.fpc10 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC10", vRM) quit
		set X = ln.fpc11 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC11", vRM) quit
		set X = ln.fpc12 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPC12", vRM) quit
		if '("01"[ln.INTCAP) set vRM=$$^MSG(742,"L") do vdderr("INTCAP", vRM) quit
		set X = ln.ispytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ISPYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.PFLG) set vRM=$$^MSG(742,"L") do vdderr("PFLG", vRM) quit
		set X = ln.pmt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmtpi if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMTPI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmttrs if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMTTRS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.poamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.POAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ppa if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PPA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.PPFLG) set vRM=$$^MSG(742,"L") do vdderr("PPFLG", vRM) quit
		set X = ln.pvar if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PVAR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.rnd.length()>6 set vRM = $$^MSG(1076,6) do vdderr("RND", vRM) quit
		set X = ln.ropt if 'X.isNull(),'Db.isDefined("STBLROPT","X") set vRM = $$^MSG(1485,X) do vdderr("ROPT", vRM) quit
		set X = ln.schbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.SCHBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.schld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SCHLD", vRM) quit
		set X = ln.schnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SCHND", vRM) quit
		set X = ln.schnum if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("SCHNUM", vRM) quit
		set X = ln.schseq if 'X.isNull() set vRM = $$VAL^DBSVER("N",13,0,,,,,8) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.SCHSEQ"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.tdue if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TDUE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.tflg if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("TFLG", vRM) quit
		set X = ln.unes if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.UNES"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.unin if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.UNIN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.unpr if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.UNPR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,60).exists() do {

		set X = ln.anptld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANPTLD", vRM) quit
		set X = ln.anptnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("ANPTND", vRM) quit
		set X = ln.anpto if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ANPTO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.caf if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CAF", vRM) quit
		set X = ln.cntc if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CNTC", vRM) quit
		if ln.compirn.length()>10 set vRM = $$^MSG(1076,10) do vdderr("COMPIRN", vRM) quit
		set X = ln.ichm if 'X.isNull(),'Db.isDefined("STBLICHM","X") set vRM = $$^MSG(1485,X) do vdderr("ICHM", vRM) quit
		set X = ln.index if 'X.isNull(),'Db.isDefined("INDEX","X") set vRM = $$^MSG(1485,X) do vdderr("INDEX", vRM) quit
		if ln.index1.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX1", vRM) quit
		if ln.index10.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX10", vRM) quit
		if ln.index2.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX2", vRM) quit
		if ln.index3.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX3", vRM) quit
		if ln.index4.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX4", vRM) quit
		if ln.index5.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX5", vRM) quit
		if ln.index6.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX6", vRM) quit
		if ln.index7.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX7", vRM) quit
		if ln.index8.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX8", vRM) quit
		if ln.index9.length()>20 set vRM = $$^MSG(1076,20) do vdderr("INDEX9", vRM) quit
		set X = ln.indo if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INDO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]INTFRE",0) if 'vRM.get().isNull() do vdderr("INTFRE", vRM) quit
		set X = ln.intmat if 'X.isNull(),'Db.isDefined("UTBLMATATT","X") set vRM = $$^MSG(1485,X) do vdderr("INTMAT", vRM) quit
		set X = ln.intmndc if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMNDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intmnic if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMNIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intmxdc if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMXDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intmxdy if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMXDY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intmxic if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMXIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intmxiy if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTMXIY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.intoff if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("INTOFF", vRM) quit
		set X = ln.intoffcl if 'X.isNull(),'Db.isDefined("UTBLNBD","X") set vRM = $$^MSG(1485,X) do vdderr("INTOFFCL", vRM) quit
		set X = ln.intoffdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("INTOFFDT", vRM) quit
		if ln.intspr.length()>9 set vRM = $$^MSG(1076,9) do vdderr("INTSPR", vRM) quit
		set X = ln.ipf if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]IPF",0) if 'vRM.get().isNull() do vdderr("IPF", vRM) quit
		set X = ln.numch if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("NUMCH", vRM) quit
		set X = ln.pcfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]PCFRE",0) if 'vRM.get().isNull() do vdderr("PCFRE", vRM) quit
		set X = ln.pchld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PCHLD", vRM) quit
		set X = ln.pchm if 'X.isNull(),'Db.isDefined("STBLPCHM","X") set vRM = $$^MSG(1485,X) do vdderr("PCHM", vRM) quit
		set X = ln.pchnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PCHND", vRM) quit
		set X = ln.pcoff if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PCOFF", vRM) quit
		set X = ln.pcoffdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PCOFFDT", vRM) quit
		if '("01"[ln.PIACM) set vRM=$$^MSG(742,"L") do vdderr("PIACM", vRM) quit
		set X = ln.pmnddc if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMNDDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmndic if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMNDIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxddc if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXDDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxddl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXDDL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxddy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXDDY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxdic if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXDIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxdil if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXDIL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxdiy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXDIY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxpdc if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXPDC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxpdl if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXPDL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxpdy if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXPDY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxpic if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXPIC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxpil if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXPIL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmxpiy if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PMXPIY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ppinc if 'X.isNull() set vRM = $$VAL^DBSVER("$",8,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PPINC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.prcb if 'X.isNull(),'Db.isDefined("STBLPRCB","X") set vRM = $$^MSG(1485,X) do vdderr("PRCB", vRM) quit
		set X = ln.rafre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]RAFRE",0) if 'vRM.get().isNull() do vdderr("RAFRE", vRM) quit
		set X = ln.rald if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("RALD", vRM) quit
		set X = ln.rand if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("RAND", vRM) quit
		set X = ln.randoff if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("RANDOFF", vRM) quit
		if ln.rndmtd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("RNDMTD", vRM) quit
		if ln.trmmx.length()>8 set vRM = $$^MSG(1076,8) do vdderr("TRMMX", vRM) quit
	}

	if vobj(ln,61).exists() do {

		set X = ln.chkcnt if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CHKCNT", vRM) quit
		if '("01"[ln.CHKEURO) set vRM=$$^MSG(742,"L") do vdderr("CHKEURO", vRM) quit
		if '("01"[ln.CHKISS) set vRM=$$^MSG(742,"L") do vdderr("CHKISS", vRM) quit
		set X = ln.chkout if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("CHKOUT", vRM) quit
		set X = ln.chks if 'X.isNull(),'Db.isDefined("UTBLCHKS","X") set vRM = $$^MSG(1485,X) do vdderr("CHKS", vRM) quit
		set X = ln.fltd1 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD1", vRM) quit
		set X = ln.fltd2 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD2", vRM) quit
		set X = ln.fltd3 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD3", vRM) quit
		set X = ln.fltd4 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD4", vRM) quit
		set X = ln.fltd5 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FLTD5", vRM) quit
		set X = ln.fltp1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP1", vRM) quit
		set X = ln.fltp2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP2", vRM) quit
		set X = ln.fltp3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP3", vRM) quit
		set X = ln.fltp4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP4", vRM) quit
		set X = ln.fltp5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("FLTP5", vRM) quit
		set X = ln.hldd1 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD1", vRM) quit
		set X = ln.hldd2 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD2", vRM) quit
		set X = ln.hldd3 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD3", vRM) quit
		set X = ln.hldd4 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD4", vRM) quit
		set X = ln.hldd5 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("HLDD5", vRM) quit
		set X = ln.hldp1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP1", vRM) quit
		set X = ln.hldp2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP2", vRM) quit
		set X = ln.hldp3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP3", vRM) quit
		set X = ln.hldp4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP4", vRM) quit
		set X = ln.hldp5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("HLDP5", vRM) quit
	}

	if vobj(ln,62).exists() do {

		if '("01"[ln.ACTIBPAY) set vRM=$$^MSG(742,"L") do vdderr("ACTIBPAY", vRM) quit
		if '("01"[ln.DSCHPR) set vRM=$$^MSG(742,"L") do vdderr("DSCHPR", vRM) quit
		if '("01"[ln.EFTDD) set vRM=$$^MSG(742,"L") do vdderr("EFTDD", vRM) quit
		if '("01"[ln.EFTDEB) set vRM=$$^MSG(742,"L") do vdderr("EFTDEB", vRM) quit
		if '("01"[ln.EFTREQ) set vRM=$$^MSG(742,"L") do vdderr("EFTREQ", vRM) quit
		set X = ln.lcadl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LCADL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lcan if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("LCAN", vRM) quit
		set X = ln.lcanl if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("LCANL", vRM) quit
		set X = ln.lcanlf if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("LCANLF", vRM) quit
		set X = ln.lcldl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LCLDL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lclnl if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("LCLNL", vRM) quit
		set X = ln.papl if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PAPL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.papy if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PAPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.paytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PAYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.sdta if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("SDTA", vRM) quit
		if '("01"[ln.SMET) set vRM=$$^MSG(742,"L") do vdderr("SMET", vRM) quit
		if ln.stmdscd.length()>30 set vRM = $$^MSG(1076,30) do vdderr("STMDSCD", vRM) quit
	}

	if vobj(ln,64).exists() do {

		set X = ln.baola if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.BAOLA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dist1af if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DIST1AF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dist1fre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]DIST1FRE",0) if 'vRM.get().isNull() do vdderr("DIST1FRE", vRM) quit
		set X = ln.dist1ld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST1LD", vRM) quit
		set X = ln.dist1nd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST1ND", vRM) quit
		set X = ln.dist2fre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]DIST2FRE",0) if 'vRM.get().isNull() do vdderr("DIST2FRE", vRM) quit
		set X = ln.dist2ld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST2LD", vRM) quit
		set X = ln.dist2nd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST2ND", vRM) quit
		set X = ln.dist3fre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]DIST3FRE",0) if 'vRM.get().isNull() do vdderr("DIST3FRE", vRM) quit
		set X = ln.dist3ld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST3LD", vRM) quit
		set X = ln.dist3nd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST3ND", vRM) quit
		set X = ln.dist4fre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]DIST4FRE",0) if 'vRM.get().isNull() do vdderr("DIST4FRE", vRM) quit
		set X = ln.dist4ld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST4LD", vRM) quit
		set X = ln.dist4nd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DIST4ND", vRM) quit
		set X = ln.dpmt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DPMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dseq if 'X.isNull() set vRM = $$VAL^DBSVER("N",13,0,,,,,8) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DSEQ"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.EPA) set vRM=$$^MSG(742,"L") do vdderr("EPA", vRM) quit
		set X = ln.inta if 'X.isNull() set vRM = $$VAL^DBSVER("N",15,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ladt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LADT", vRM) quit
		set X = ln.lcad if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LCAD", vRM) quit
		set X = ln.lcbo if 'X.isNull(),'Db.isDefined("STBLLCBO","X") set vRM = $$^MSG(1485,X) do vdderr("LCBO", vRM) quit
		set X = ln.lcefd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LCEFD", vRM) quit
		if '("01"[ln.LCHGNOTO) set vRM=$$^MSG(742,"L") do vdderr("LCHGNOTO", vRM) quit
		set X = ln.limit if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("LIMIT", vRM) quit
		if '("01"[ln.MDF) set vRM=$$^MSG(742,"L") do vdderr("MDF", vRM) quit
		set X = ln.olimit if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("OLIMIT", vRM) quit
		set X = ln.oseq if 'X.isNull() set vRM = $$VAL^DBSVER("N",13,0,,,,,8) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.OSEQ"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.PAF) set vRM=$$^MSG(742,"L") do vdderr("PAF", vRM) quit
		if ln.pmtdist.length()>120 set vRM = $$^MSG(1076,120) do vdderr("PMTDIST", vRM) quit
		if ln.pmtdistf.length()>40 set vRM = $$^MSG(1076,40) do vdderr("PMTDISTF", vRM) quit
		set X = ln.tba if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TBA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,65).exists() do {

		if ln.ckc.length()>12 set vRM = $$^MSG(1076,12) do vdderr("CKC", vRM) quit
		set X = ln.cktyp if 'X.isNull(),'Db.isDefined("UTBLCHKS","X") set vRM = $$^MSG(1485,X) do vdderr("CKTYP", vRM) quit
		set X = ln.cod if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("COD", vRM) quit
		set X = ln.nock if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("NOCK", vRM) quit
		set X = ln.npc if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("NPC", vRM) quit
		if ln.ppdcat1.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT1", vRM) quit
		if ln.ppdcat10.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT10", vRM) quit
		if ln.ppdcat2.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT2", vRM) quit
		if ln.ppdcat3.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT3", vRM) quit
		if ln.ppdcat4.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT4", vRM) quit
		if ln.ppdcat5.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT5", vRM) quit
		if ln.ppdcat6.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT6", vRM) quit
		if ln.ppdcat7.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT7", vRM) quit
		if ln.ppdcat8.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT8", vRM) quit
		if ln.ppdcat9.length()>80 set vRM = $$^MSG(1076,80) do vdderr("PPDCAT9", vRM) quit
		if ln.scn.length()>12 set vRM = $$^MSG(1076,12) do vdderr("SCN", vRM) quit
	}

	if vobj(ln,66).exists() do {

		set X = ln.aoamtorg if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.AOAMTORG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.aprapp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.APRAPP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.aprapp1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.APRAPP1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.aprmthd if 'X.isNull(),'Db.isDefined("STBLAPRMTHD","X") set vRM = $$^MSG(1485,X) do vdderr("APRMTHD", vRM) quit
		set X = ln.comfa if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COMFA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.comfp if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COMFP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.disamf if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISAMF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.disapr if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISAPR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dismip if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISMIP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dispmp if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISPMP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.disppi if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISPPI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.disppid if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DISPPID", vRM) quit
		set X = ln.distint if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISTINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.distip if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISTIP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.distpmt if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DISTPMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lvr if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("LVR", vRM) quit
		set X = ln.lvv if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("LVV", vRM) quit
		set X = ln.nfamtorg if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NFAMTORG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.nfplnorg.length()>6 set vRM = $$^MSG(1076,6) do vdderr("NFPLNORG", vRM) quit
		set X = ln.orgfa if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ORGFA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.orgfp if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ORGFP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa10a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA10A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa10f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA10F", vRM) quit
		set X = ln.pa10t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA10T", vRM) quit
		set X = ln.pa11a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA11A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa11f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA11F", vRM) quit
		set X = ln.pa11t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA11T", vRM) quit
		set X = ln.pa12a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA12A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa12f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA12F", vRM) quit
		set X = ln.pa12t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA12T", vRM) quit
		set X = ln.pa13a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA13A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa13f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA13F", vRM) quit
		set X = ln.pa13t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA13T", vRM) quit
		set X = ln.pa14a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA14A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa14f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA14F", vRM) quit
		set X = ln.pa14t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA14T", vRM) quit
		set X = ln.pa15a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA15A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa15f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA15F", vRM) quit
		set X = ln.pa15t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA15T", vRM) quit
		set X = ln.pa1a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA1A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa1f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA1F", vRM) quit
		set X = ln.pa1t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA1T", vRM) quit
		set X = ln.pa2a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA2A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa2f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA2F", vRM) quit
		set X = ln.pa2t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA2T", vRM) quit
		set X = ln.pa3a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA3A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa3f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA3F", vRM) quit
		set X = ln.pa3t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA3T", vRM) quit
		set X = ln.pa4a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA4A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa4f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA4F", vRM) quit
		set X = ln.pa4t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA4T", vRM) quit
		set X = ln.pa5a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA5A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa5f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA5F", vRM) quit
		set X = ln.pa5t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA5T", vRM) quit
		set X = ln.pa6a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA6A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa6f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA6F", vRM) quit
		set X = ln.pa6t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA6T", vRM) quit
		set X = ln.pa7a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA7A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa7f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA7F", vRM) quit
		set X = ln.pa7t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA7T", vRM) quit
		set X = ln.pa8a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA8A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa8f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA8F", vRM) quit
		set X = ln.pa8t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA8T", vRM) quit
		set X = ln.pa9a if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PA9A"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pa9f if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA9F", vRM) quit
		set X = ln.pa9t if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PA9T", vRM) quit
		set X = ln.rlvp if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("RLVP", vRM) quit
	}

	if vobj(ln,67).exists() do {

		set X = ln.ddbal1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal10 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL10"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal11 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL11"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal12 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL12"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal6 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL6"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal7 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL7"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal8 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL8"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbal9 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBAL9"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ddbalcur if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DDBALCUR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,68).exists() do {

		set X = ln.mebal1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal10 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL10"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal11 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL11"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal12 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL12"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal6 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL6"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal7 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL7"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal8 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL8"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mebal9 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MEBAL9"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef10 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF10"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef6 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF6"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef7 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF7"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef8 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF8"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.usrdef9 if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.USRDEF9"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,70).exists() do {

		if '("01"[ln.CMSFLG) set vRM=$$^MSG(742,"L") do vdderr("CMSFLG", vRM) quit
		if '("01"[ln.DIP) set vRM=$$^MSG(742,"L") do vdderr("DIP", vRM) quit
		if '("01"[ln.DLRP) set vRM=$$^MSG(742,"L") do vdderr("DLRP", vRM) quit
		if '("01"[ln.HIP) set vRM=$$^MSG(742,"L") do vdderr("HIP", vRM) quit
		if '("01"[ln.LIP) set vRM=$$^MSG(742,"L") do vdderr("LIP", vRM) quit
		if '("01"[ln.MSCP) set vRM=$$^MSG(742,"L") do vdderr("MSCP", vRM) quit
		if '("01"[ln.PTSP) set vRM=$$^MSG(742,"L") do vdderr("PTSP", vRM) quit
	}

	if vobj(ln,71).exists() do {

		set X = ln.eppendat if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EPPENDAT", vRM) quit
		set X = ln.eppenmet if 'X.isNull(),'Db.isDefined("UTBLLNPPN","X") set vRM = $$^MSG(1485,X) do vdderr("EPPENMET", vRM) quit
		set X = ln.opchg if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.OPCHG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.payacm if 'X.isNull(),'Db.isDefined("STBLAACM","X") set vRM = $$^MSG(1485,X) do vdderr("PAYACM", vRM) quit
		set X = ln.paylkamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PAYLKAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.paylkfrm if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PAYLKFRM", vRM) quit
		set X = ln.paylkto if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PAYLKTO", vRM) quit
		if '("01"[ln.PLDF) set vRM=$$^MSG(742,"L") do vdderr("PLDF", vRM) quit
		set X = ln.ppo if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("PPO", vRM) quit
	}

	if vobj(ln,75).exists() do {

		set X = ln.feegrpo if 'X.isNull(),'Db.isDefined("UTBLLNFEEGRP","X") set vRM = $$^MSG(1485,X) do vdderr("FEEGRPO", vRM) quit
		set X = ln.lnfeegl if 'X.isNull(),'Db.isDefined("GLAD","X") set vRM = $$^MSG(1485,X) do vdderr("LNFEEGL", vRM) quit
		set X = ln.lnfeeta if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("LNFEETA", vRM) quit
	}

	if vobj(ln,80).exists() do {

		if '("01"[ln.ADJCRLMT) set vRM=$$^MSG(742,"L") do vdderr("ADJCRLMT", vRM) quit
		if ln.colcd.length()>6 set vRM = $$^MSG(1076,6) do vdderr("COLCD", vRM) quit
		set X = ln.coll if 'X.isNull(),X'?1.9N,X'?1"-"1.8N set vRM=$$^MSG(742,"N") do vdderr("COLL", vRM) quit
		set X = ln.fclf if 'X.isNull(),'Db.isDefined("STBLFCLF","X") set vRM = $$^MSG(1485,X) do vdderr("FCLF", vRM) quit
		set X = ln.fclp if 'X.isNull(),'Db.isDefined("STBLFCLP","X") set vRM = $$^MSG(1485,X) do vdderr("FCLP", vRM) quit
		set X = ln.fcpt if 'X.isNull(),'Db.isDefined("STBLFCPT","X") set vRM = $$^MSG(1485,X) do vdderr("FCPT", vRM) quit
		set X = ln.minrate if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MINRATE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,85).exists() do {

		if '("01"[ln.AFLG) set vRM=$$^MSG(742,"L") do vdderr("AFLG", vRM) quit
		set X = ln.anfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]ANFRE",0) if 'vRM.get().isNull() do vdderr("ANFRE", vRM) quit
		set X = ln.apcld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("APCLD", vRM) quit
		if '("01"[ln.CONCAL) set vRM=$$^MSG(742,"L") do vdderr("CONCAL", vRM) quit
		set X = ln.ocadt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("OCADT", vRM) quit
		if '("01"[ln.OCAF) set vRM=$$^MSG(742,"L") do vdderr("OCAF", vRM) quit
	}

	if vobj(ln,98).exists() do {

		if ln.corre.length()>12 set vRM = $$^MSG(1076,12) do vdderr("CORRE", vRM) quit
		if ln.correacn.length()>35 set vRM = $$^MSG(1076,35) do vdderr("CORREACN", vRM) quit
	}

	if vobj(ln,99).exists() do {

		set X = ln.acn if 'X.isNull(),'Db.isDefined("CIF","X") set vRM = $$^MSG(1485,X) do vdderr("ACN", vRM) quit
		if ln.acnrelc.length()>2 set vRM = $$^MSG(1076,2) do vdderr("ACNRELC", vRM) quit
		if ln.aplid.length()>25 set vRM = $$^MSG(1076,25) do vdderr("APLID", vRM) quit
	}

	if vobj(ln,101).exists() do {

		set X = ln.bldt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BLDT", vRM) quit
		if ln.bloff.length()>3 set vRM = $$^MSG(1076,3) do vdderr("BLOFF", vRM) quit
		if '("01"[ln.BMET) set vRM=$$^MSG(742,"L") do vdderr("BMET", vRM) quit
		set X = ln.bndt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BNDT", vRM) quit
		if '("01"[ln.BPOCL) set vRM=$$^MSG(742,"L") do vdderr("BPOCL", vRM) quit
		set X = ln.bseq if 'X.isNull() set vRM = $$VAL^DBSVER("N",13,0,,,,,8) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.BSEQ"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cdepamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CDEPAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dpdo if 'X.isNull(),'Db.isDefined("STBLDPPO","X") set vRM = $$^MSG(1485,X) do vdderr("DPDO", vRM) quit
		set X = ln.dppo if 'X.isNull(),'Db.isDefined("STBLDPPO","X") set vRM = $$^MSG(1485,X) do vdderr("DPPO", vRM) quit
		if '("01"[ln.DXSI) set vRM=$$^MSG(742,"L") do vdderr("DXSI", vRM) quit
		set X = ln.fia if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.FIA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.fpa if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.FPA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lairdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LAIRDT", vRM) quit
		set X = ln.lbdd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LBDD", vRM) quit
		set X = ln.mfcb if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MFCB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mpo if 'X.isNull(),'Db.isDefined("STBLLMPO","X") set vRM = $$^MSG(1485,X) do vdderr("MPO", vRM) quit
		set X = ln.mppf if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MPPF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pbpor if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PBPOR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.PEBA) set vRM=$$^MSG(742,"L") do vdderr("PEBA", vRM) quit
		set X = ln.ppb if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PPB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ptbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PTBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.PTF) set vRM=$$^MSG(742,"L") do vdderr("PTF", vRM) quit
		set X = ln.rpp if 'X.isNull(),'Db.isDefined("UTBLRPP","X") set vRM = $$^MSG(1485,X) do vdderr("RPP", vRM) quit
		set X = ln.subamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.SUBAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.subld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SUBLD", vRM) quit
		set X = ln.subnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SUBND", vRM) quit
		set X = ln.subpln if 'X.isNull(),'Db.isDefined("UTBLLNSUB","X") set vRM = $$^MSG(1485,X) do vdderr("SUBPLN", vRM) quit
		set X = ln.subrat if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.SUBRAT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,102).exists() do {

		set X = ln.apld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("APLD", vRM) quit
		set X = ln.apn if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("APN", vRM) quit
		set X = ln.aptamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.APTAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.cnvstat.length()>1 set vRM = $$^MSG(1076,1) do vdderr("CNVSTAT", vRM) quit
		if '("01"[ln.DIRDEF) set vRM=$$^MSG(742,"L") do vdderr("DIRDEF", vRM) quit
		set X = ln.idpf if 'X.isNull(),'Db.isDefined("STBLIDPF","X") set vRM = $$^MSG(1485,X) do vdderr("IDPF", vRM) quit
		if ln.igrc.length()>8 set vRM = $$^MSG(1076,8) do vdderr("IGRC", vRM) quit
		if ln.purcd.length()>6 set vRM = $$^MSG(1076,6) do vdderr("PURCD", vRM) quit
		set X = ln.relcid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("RELCID", vRM) quit
		set X = ln.slbl if 'X.isNull(),'Db.isDefined("STBLSLBL","X") set vRM = $$^MSG(1485,X) do vdderr("SLBL", vRM) quit
		set X = ln.sldfd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SLDFD", vRM) quit
		set X = ln.sldnum if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("SLDNUM", vRM) quit
		set X = ln.sldrsn if 'X.isNull(),'Db.isDefined("UTBLSLDRSN","X") set vRM = $$^MSG(1485,X) do vdderr("SLDRSN", vRM) quit
		set X = ln.sldtd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SLDTD", vRM) quit
		if ln.sldtrm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("SLDTRM", vRM) quit
		if ln.subt.length()>5 set vRM = $$^MSG(1076,5) do vdderr("SUBT", vRM) quit
	}

	if vobj(ln,107).exists() do {

		set X = ln.colcdte if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("COLCDTE", vRM) quit
		set X = ln.pcollst if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("PCOLLST", vRM) quit
		set X = ln.promamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PROMAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.prombrd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROMBRD", vRM) quit
		set X = ln.prommd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROMMD", vRM) quit
		set X = ln.promsd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROMSD", vRM) quit
	}

	if vobj(ln,111).exists() do {

		set X = ln.abdm if 'X.isNull(),'Db.isDefined("UTBLABDM","X") set vRM = $$^MSG(1485,X) do vdderr("ABDM", vRM) quit
		set X = ln.acfx1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACFX1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acfx2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACFX2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acfx3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACFX3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acfx4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACFX4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acfx5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACFX5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acpc1 if 'X.isNull() set vRM = $$VAL^DBSVER("$",6,0,,,0,100,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACPC1"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acpc2 if 'X.isNull() set vRM = $$VAL^DBSVER("$",6,0,,,0,100,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACPC2"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acpc3 if 'X.isNull() set vRM = $$VAL^DBSVER("$",6,0,,,0,100,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACPC3"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acpc4 if 'X.isNull() set vRM = $$VAL^DBSVER("$",6,0,,,0,100,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACPC4"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acpc5 if 'X.isNull() set vRM = $$VAL^DBSVER("$",6,0,,,0,100,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACPC5"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.ASSUMF) set vRM=$$^MSG(742,"L") do vdderr("ASSUMF", vRM) quit
		set X = ln.calacls if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CALACLS", vRM) quit
		if ln.case.length()>13 set vRM = $$^MSG(1076,13) do vdderr("CASE", vRM) quit
		if ln.cbc.length()>2 set vRM = $$^MSG(1076,2) do vdderr("CBC", vRM) quit
		set X = ln.cbdoo if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("CBDOO", vRM) quit
		set X = ln.cbst if 'X.isNull(),'Db.isDefined("UTBLCBST","X") set vRM = $$^MSG(1485,X) do vdderr("CBST", vRM) quit
		set X = ln.crepscc if 'X.isNull(),'Db.isDefined("UTBLCREPSCC","X") set vRM = $$^MSG(1485,X) do vdderr("CREPSCC", vRM) quit
		set X = ln.dlr if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DLR", vRM) quit
		set X = ln.ecoa if 'X.isNull(),'Db.isDefined("UTBLECOA","X") set vRM = $$^MSG(1485,X) do vdderr("ECOA", vRM) quit
		set X = ln.fppa if 'X.isNull(),X'?1.17N,X'?1"-"1.16N set vRM=$$^MSG(742,"N") do vdderr("FPPA", vRM) quit
		set X = ln.fppi if 'X.isNull(),'Db.isDefined("UTBLFPI","X") set vRM = $$^MSG(1485,X) do vdderr("FPPI", vRM) quit
		set X = ln.modcd if 'X.isNull(),'Db.isDefined("UTBLLNMC","X") set vRM = $$^MSG(1485,X) do vdderr("MODCD", vRM) quit
		set X = ln.moddt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("MODDT", vRM) quit
		set X = ln.plf if 'X.isNull(),'Db.isDefined("STBLLNTDR","X") set vRM = $$^MSG(1485,X) do vdderr("PLF", vRM) quit
		set X = ln.pntspd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PNTSPD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pntspds if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PNTSPDS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.provbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",15,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PROVBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.provcat if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PROVCAT", vRM) quit
		set X = ln.provexpd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PROVEXPD", vRM) quit
		set X = ln.provoamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PROVOAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.provopct if 'X.isNull() set vRM = $$VAL^DBSVER("N",9,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PROVOPCT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.rac if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("RAC", vRM) quit
		set X = ln.racna if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("RACNA", vRM) quit
		set X = ln.racovr if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("RACOVR", vRM) quit
		if '("01"[ln.RECCD) set vRM=$$^MSG(742,"L") do vdderr("RECCD", vRM) quit
	}

	if vobj(ln,112).exists() do {

		set X = ln.coloff if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("COLOFF", vRM) quit
		if ln.crsc.length()>3 set vRM = $$^MSG(1076,3) do vdderr("CRSC", vRM) quit
		set X = ln.dlfp if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DLFP", vRM) quit
		set X = ln.dp1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DP1", vRM) quit
		set X = ln.dp2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DP2", vRM) quit
		set X = ln.dp3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DP3", vRM) quit
		set X = ln.dp4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DP4", vRM) quit
		set X = ln.dp5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DP5", vRM) quit
		set X = ln.dp6 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DP6", vRM) quit
		set X = ln.dp7 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DP7", vRM) quit
		set X = ln.fcld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("FCLD", vRM) quit
		set X = ln.fpp01 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP01", vRM) quit
		set X = ln.fpp02 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP02", vRM) quit
		set X = ln.fpp03 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP03", vRM) quit
		set X = ln.fpp04 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP04", vRM) quit
		set X = ln.fpp05 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP05", vRM) quit
		set X = ln.fpp06 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP06", vRM) quit
		set X = ln.fpp07 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP07", vRM) quit
		set X = ln.fpp08 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP08", vRM) quit
		set X = ln.fpp09 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP09", vRM) quit
		set X = ln.fpp10 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP10", vRM) quit
		set X = ln.fpp11 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP11", vRM) quit
		set X = ln.fpp12 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("FPP12", vRM) quit
		set X = ln.not1dt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NOT1DT", vRM) quit
		set X = ln.not2dt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NOT2DT", vRM) quit
		set X = ln.not3dt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NOT3DT", vRM) quit
		set X = ln.not4dt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NOT4DT", vRM) quit
		set X = ln.not5dt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NOT5DT", vRM) quit
		set X = ln.old if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("OLD", vRM) quit
	}

	if vobj(ln,113).exists() do {

		set X = ln.aupbr if 'X.isNull() set vRM = $$VAL^DBSVER("$",6,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.AUPBR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dy1 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DY1", vRM) quit
		set X = ln.dy2 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DY2", vRM) quit
		set X = ln.dy3 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DY3", vRM) quit
		set X = ln.dy4 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DY4", vRM) quit
		set X = ln.dy5 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DY5", vRM) quit
		set X = ln.dy6 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DY6", vRM) quit
		set X = ln.dy7 if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("DY7", vRM) quit
	}

	if vobj(ln,114).exists() do {

		set X = ln.cusha if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CUSHA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cushf if 'X.isNull() set vRM = $$VAL^DBSVER("N",12,0,,,,,9) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CUSHF"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cusho if 'X.isNull(),'Db.isDefined("STBLCUSHO","X") set vRM = $$^MSG(1485,X) do vdderr("CUSHO", vRM) quit
		set X = ln.ddmg if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("DDMG", vRM) quit
		set X = ln.ddml if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("DDML", vRM) quit
		set X = ln.dfda if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DFDA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ieasgf if 'X.isNull(),'Db.isDefined("STBLSTMT","X") set vRM = $$^MSG(1485,X) do vdderr("IEASGF", vRM) quit
		set X = ln.oda if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ODA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.odmg if 'X.isNull(),'Db.isDefined("STBLODM","X") set vRM = $$^MSG(1485,X) do vdderr("ODMG", vRM) quit
		set X = ln.odml if 'X.isNull(),'Db.isDefined("STBLODM","X") set vRM = $$^MSG(1485,X) do vdderr("ODML", vRM) quit
		set X = ln.sda if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.SDA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.sdmg if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("SDMG", vRM) quit
		set X = ln.sdml if 'X.isNull(),'Db.isDefined("STBLTRDD","X") set vRM = $$^MSG(1485,X) do vdderr("SDML", vRM) quit
		set X = ln.sdo if 'X.isNull(),'Db.isDefined("STBLSDO","X") set vRM = $$^MSG(1485,X) do vdderr("SDO", vRM) quit
	}

	if vobj(ln,115).exists() do {

		set X = ln.dl1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DL1", vRM) quit
		set X = ln.dl2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DL2", vRM) quit
		set X = ln.dl3 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DL3", vRM) quit
		set X = ln.dl4 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DL4", vRM) quit
		set X = ln.dl5 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DL5", vRM) quit
		set X = ln.dl6 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DL6", vRM) quit
		set X = ln.dl7 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DL7", vRM) quit
	}

	if vobj(ln,300).exists() do {

		set X = ln.pbkbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PBKBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pbkld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PBKLD", vRM) quit
		set X = ln.pbklin if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("PBKLIN", vRM) quit
		set X = ln.pbkseq if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("PBKSEQ", vRM) quit
		set X = ln.pbksn if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("PBKSN", vRM) quit
	}

	if vobj(ln,426).exists() do {

		set X = ln.retfcpy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RETFCPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.retfcytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RETFCYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.retfwpy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RETFWPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.retfwytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RETFWYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.retmxfee if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RETMXFEE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,429).exists() do {

		set X = ln.lmtatm if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LMTATM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lmtcjd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LMTCJD", vRM) quit
		set X = ln.lmtpos if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LMTPOS"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,430).exists() do {

		set X = ln.eurbatch if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("EURBATCH", vRM) quit
		set X = ln.eurcnvd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EURCNVD", vRM) quit
		set X = ln.eurcvinbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.EURCVINBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.eurefd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EUREFD", vRM) quit
		set X = ln.eureqdat if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EUREQDAT", vRM) quit
		set X = ln.eurevdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EUREVDT", vRM) quit
		set X = ln.eurstat if 'X.isNull(),'Db.isDefined("STBLEURSTAT","X") set vRM = $$^MSG(1485,X) do vdderr("EURSTAT", vRM) quit
		set X = ln.eurudrq if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("EURUDRQ", vRM) quit
		if ln.orgcrcd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("ORGCRCD", vRM) quit
		if ln.orgindex.length()>20 set vRM = $$^MSG(1076,20) do vdderr("ORGINDEX", vRM) quit
		set X = ln.orgsch if 'X.isNull(),'Db.isDefined("UTBLRATE","X") set vRM = $$^MSG(1485,X) do vdderr("ORGSCH", vRM) quit
	}

	if vobj(ln,431).exists() do {

		set X = ln.ballamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.BALLAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cbt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CBT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.costyp if 'X.isNull(),'Db.isDefined("UTBLECOSTOP","X") set vRM = $$^MSG(1485,X) do vdderr("COSTYP", vRM) quit
		set X = ln.dbt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DBT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mbldelq if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MBLDELQ"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.nbtck if 'X.isNull(),'Db.isDefined("UTBLCHKS","X") set vRM = $$^MSG(1485,X) do vdderr("NBTCK", vRM) quit
		set X = ln.nbtr if 'X.isNull(),'Db.isDefined("STBLNEGBTR","X") set vRM = $$^MSG(1485,X) do vdderr("NBTR", vRM) quit
		set X = ln.ntropt if 'X.isNull(),'Db.isDefined("STBLNEGBOPT","X") set vRM = $$^MSG(1485,X) do vdderr("NTROPT", vRM) quit
		if '("01"[ln.PAYEFT) set vRM=$$^MSG(742,"L") do vdderr("PAYEFT", vRM) quit
		set X = ln.rfp if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("RFP", vRM) quit
		set X = ln.sfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]SFRE",0) if 'vRM.get().isNull() do vdderr("SFRE", vRM) quit
		set X = ln.trcid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("TRCID", vRM) quit
		set X = ln.troffd if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("TROFFD", vRM) quit
	}

	if vobj(ln,432).exists() do {

		set X = ln.cnvtyp if 'X.isNull(),'Db.isDefined("STBLCNVTYP","X") set vRM = $$^MSG(1485,X) do vdderr("CNVTYP", vRM) quit
		if '("01"[ln.COLLQUE) set vRM=$$^MSG(742,"L") do vdderr("COLLQUE", vRM) quit
		set X = ln.collst if 'X.isNull(),'Db.isDefined("UTBLCOLLST","X") set vRM = $$^MSG(1485,X) do vdderr("COLLST", vRM) quit
		set X = ln.comppy if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COMPPY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.compytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COMPYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ipty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.itytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ITYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.penpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PENPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pentytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PENTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.restyp if 'X.isNull(),'Db.isDefined("STBLRESTYP","X") set vRM = $$^MSG(1485,X) do vdderr("RESTYP", vRM) quit
		set X = ln.wrkdte if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("WRKDTE", vRM) quit
	}

	if vobj(ln,433).exists() do {

		set X = ln.alprtyd if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ALPRTYD", vRM) quit
		if '("01"[ln.AVCRLMT) set vRM=$$^MSG(742,"L") do vdderr("AVCRLMT", vRM) quit
		if '("01"[ln.CINTBNP) set vRM=$$^MSG(742,"L") do vdderr("CINTBNP", vRM) quit
		set X = ln.dpa if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("DPA", vRM) quit
		if '("01"[ln.ICAP) set vRM=$$^MSG(742,"L") do vdderr("ICAP", vRM) quit
		set X = ln.iropt if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("IROPT", vRM) quit
		if ln.lpspdag.length()>8 set vRM = $$^MSG(1076,8) do vdderr("LPSPDAG", vRM) quit
		set X = ln.paytol if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PAYTOL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.paytolp if 'X.isNull() set vRM = $$VAL^DBSVER("N",6,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PAYTOLP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pmtrdfac if 'X.isNull(),X'?1.5N,X'?1"-"1.4N set vRM=$$^MSG(742,"N") do vdderr("PMTRDFAC", vRM) quit
		set X = ln.reldepacct if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("RELDEPACCT", vRM) quit
		set X = ln.toldue if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TOLDUE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.wdamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.WDAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.wdfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]WDFRE",0) if 'vRM.get().isNull() do vdderr("WDFRE", vRM) quit
		set X = ln.wdld if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("WDLD", vRM) quit
		set X = ln.wdlmt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.WDLMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.WDLMTP) set vRM=$$^MSG(742,"L") do vdderr("WDLMTP", vRM) quit
		set X = ln.wdnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("WDND", vRM) quit
	}

	if vobj(ln,435).exists() do {

		if '("01"[ln.ADDLCHG) set vRM=$$^MSG(742,"L") do vdderr("ADDLCHG", vRM) quit
		set X = ln.aldchk if 'X.isNull(),'Db.isDefined("UTBLCHKS","X") set vRM = $$^MSG(1485,X) do vdderr("ALDCHK", vRM) quit
		set X = ln.aldext if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("ALDEXT", vRM) quit
		set X = ln.aldm if 'X.isNull(),'Db.isDefined("STBLALDM","X") set vRM = $$^MSG(1485,X) do vdderr("ALDM", vRM) quit
		if ln.aldp.length()>20 set vRM = $$^MSG(1076,20) do vdderr("ALDP", vRM) quit
		set X = ln.amtworpi if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.AMTWORPI"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.appnum if 'X.isNull(),X'?1.18N,X'?1"-"1.17N set vRM=$$^MSG(742,"N") do vdderr("APPNUM", vRM) quit
		set X = ln.blkprinnd if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("BLKPRINND", vRM) quit
		set X = ln.blkprinpan if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.BLKPRINPAN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.disbchk if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("DISBCHK", vRM) quit
		if '("01"[ln.ELLPLS) set vRM=$$^MSG(742,"L") do vdderr("ELLPLS", vRM) quit
		if '("01"[ln.GENPRN) set vRM=$$^MSG(742,"L") do vdderr("GENPRN", vRM) quit
		set X = ln.idgp if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("IDGP", vRM) quit
		set X = ln.inspr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INSPR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.perno if 'X.isNull(),X'?1.18N,X'?1"-"1.17N set vRM=$$^MSG(742,"N") do vdderr("PERNO", vRM) quit
		set X = ln.refpr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.REFPR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.rpiprem if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RPIPREM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.rpirate if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RPIRATE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.rpireb if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.RPIREB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,438).exists() do {

		if '("01"[ln.MT900) set vRM=$$^MSG(742,"L") do vdderr("MT900", vRM) quit
		set X = ln.mt900a if 'X.isNull(),'Db.isDefined("UTBLCORRE","X") set vRM = $$^MSG(1485,X) do vdderr("MT900A", vRM) quit
		set X = ln.mt900thr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MT900THR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.MT910) set vRM=$$^MSG(742,"L") do vdderr("MT910", vRM) quit
		set X = ln.mt910a if 'X.isNull(),'Db.isDefined("UTBLCORRE","X") set vRM = $$^MSG(1485,X) do vdderr("MT910A", vRM) quit
		set X = ln.mt910thr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MT910THR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,440).exists() do {

		set X = ln.acoint if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACOINT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acolchg if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACOLCHG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acomfee if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACOMFEE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.acoprin if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ACOPRIN"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.COF) set vRM=$$^MSG(742,"L") do vdderr("COF", vRM) quit
		if ln.cogs.length()>4 set vRM = $$^MSG(1076,4) do vdderr("COGS", vRM) quit
		set X = ln.com if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("COM", vRM) quit
		set X = ln.cot if 'X.isNull(),X'?1N set vRM=$$^MSG(742,"N") do vdderr("COT", vRM) quit
		set X = ln.dtco if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("DTCO", vRM) quit
		set X = ln.intrec if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.INTREC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.lchgrec if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.LCHGREC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mfeerec if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MFEEREC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.prinrec if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PRINREC"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,443).exists() do {

		set X = ln.dafpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DAFPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.daftytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DAFTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.efrpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.EFRPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.efrtytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.EFRTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.feepty if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.FEEPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.feetytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",12,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.FEETYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ndafpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NDAFPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ndaftytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NDAFTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pntspdsty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PNTSPDSTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pntstytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PNTSTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.refintpty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.REFINTPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.refinttytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.REFINTTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,445).exists() do {

		if '("01"[ln.REFFLG) set vRM=$$^MSG(742,"L") do vdderr("REFFLG", vRM) quit
		set X = ln.tcrl if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TCRL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.tcrp if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TCRP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.tcsa if 'X.isNull() set vRM = $$VAL^DBSVER("N",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TCSA"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.tcsl if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.TCSL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.wspouscif if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("WSPOUSCIF", vRM) quit
		set X = ln.wspousdob if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("WSPOUSDOB", vRM) quit
		if '("01"[ln.WSPOUSFL) set vRM=$$^MSG(742,"L") do vdderr("WSPOUSFL", vRM) quit
		if ln.wspousnm.length()>40 set vRM = $$^MSG(1076,40) do vdderr("WSPOUSNM", vRM) quit
	}

	if vobj(ln,447).exists() do {

		set X = ln.copty if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COPTY"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cotytd if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COTYTD"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cvcid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("CVCID", vRM) quit
		set X = ln.efdsub if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("EFDSUB", vRM) quit
		if '("01"[ln.PAOI) set vRM=$$^MSG(742,"L") do vdderr("PAOI", vRM) quit
		set X = ln.pcidstat if 'X.isNull(),'Db.isDefined("STBLPCIDSTAT","X") set vRM = $$^MSG(1485,X) do vdderr("PCIDSTAT", vRM) quit
	}

	if vobj(ln,448).exists() do {

		set X = ln.npiaab if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.NPIAAB"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.OSGNCRDC) set vRM=$$^MSG(742,"L") do vdderr("OSGNCRDC", vRM) quit
		set X = ln.psgncrdr if 'X.isNull(),'Db.isDefined("STBLPSGNCRDR","X") set vRM = $$^MSG(1485,X) do vdderr("PSGNCRDR", vRM) quit
		set X = ln.sgncrd if 'X.isNull(),'Db.isDefined("STBLSGNCRD","X") set vRM = $$^MSG(1485,X) do vdderr("SGNCRD", vRM) quit
		set X = ln.sgncrdchgdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SGNCRDCHGDT", vRM) quit
	}

	if vobj(ln,449).exists() do {

		if '("01"[ln.CBF) set vRM=$$^MSG(742,"L") do vdderr("CBF", vRM) quit
		if '("01"[ln.CDF) set vRM=$$^MSG(742,"L") do vdderr("CDF", vRM) quit
		set X = ln.iramto if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.IRAMTO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ircid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("IRCID", vRM) quit
		if '("01"[ln.IRP) set vRM=$$^MSG(742,"L") do vdderr("IRP", vRM) quit
		set X = ln.maxaggr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MAXAGGR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if ln.paytrnst.length()>12 set vRM = $$^MSG(1076,12) do vdderr("PAYTRNST", vRM) quit
		set X = ln.pramt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PRAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pramtcid if 'X.isNull(),X'?1.18N,X'?1"-"1.17N set vRM=$$^MSG(742,"N") do vdderr("PRAMTCID", vRM) quit
		set X = ln.prcntap if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PRCNTAP"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.prcntcid if 'X.isNull(),X'?1.18N,X'?1"-"1.17N set vRM=$$^MSG(742,"N") do vdderr("PRCNTCID", vRM) quit
	}

	if vobj(ln,451).exists() do {

		set X = ln.rcalcm if 'X.isNull(),'Db.isDefined("STBLAOAMO","X") set vRM = $$^MSG(1485,X) do vdderr("RCALCM", vRM) quit
	}

	if vobj(ln,452).exists() do {

		if ln.rsintspr.length()>9 set vRM = $$^MSG(1076,9) do vdderr("RSINTSPR", vRM) quit
		if ln.rsrndmtd.length()>3 set vRM = $$^MSG(1076,3) do vdderr("RSRNDMTD", vRM) quit
	}

	if vobj(ln,453).exists() do {

		if '("01"[ln.AFFLN) set vRM=$$^MSG(742,"L") do vdderr("AFFLN", vRM) quit
		set X = ln.ansale if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.ANSALE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.BCAPINT) set vRM=$$^MSG(742,"L") do vdderr("BCAPINT", vRM) quit
		if ln.cen.length()>7 set vRM = $$^MSG(1076,7) do vdderr("CEN", vRM) quit
		set X = ln.cracntcd if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CRACNTCD", vRM) quit
		set X = ln.crastcd if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("CRASTCD", vRM) quit
		set X = ln.msacd if 'X.isNull(),'Db.isDefined("UTBLMSA","X") set vRM = $$^MSG(1485,X) do vdderr("MSACD", vRM) quit
		set X = ln.rescls if 'X.isNull(),'Db.isDefined("STBLRESCLS","X") set vRM = $$^MSG(1485,X) do vdderr("RESCLS", vRM) quit
	}

	if vobj(ln,454).exists() do {

		set X = ln.precard if 'X.isNull(),X'?1.20N,X'?1"-"1.19N set vRM=$$^MSG(742,"N") do vdderr("PRECARD", vRM) quit
		if ln.prepin.length()>20 set vRM = $$^MSG(1076,20) do vdderr("PREPIN", vRM) quit
	}

	if vobj(ln,455).exists() do {

		set X = ln.co if 'X.isNull(),'Db.isDefined("UTBLCO","X") set vRM = $$^MSG(1485,X) do vdderr("CO", vRM) quit
		set X = ln.delqrsn if 'X.isNull(),'Db.isDefined("UTBLRFD","X") set vRM = $$^MSG(1485,X) do vdderr("DELQRSN", vRM) quit
	}

	if vobj(ln,456).exists() do {

		set X = ln.colexthrsh if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COLEXTHRSH"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.colextrdys if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("COLEXTRDYS", vRM) quit
		set X = ln.regeamt if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.REGEAMT"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.stmtsrt if 'X.isNull(),'Db.isDefined("STBLSTMTSRT","X") set vRM = $$^MSG(1485,X) do vdderr("STMTSRT", vRM) quit
	}

	if vobj(ln,457).exists() do {

		set X = ln.anmth if 'X.isNull(),'Db.isDefined("UTBLANMTH","X") set vRM = $$^MSG(1485,X) do vdderr("ANMTH", vRM) quit
		if ln.currisk.length()>3 set vRM = $$^MSG(1076,3) do vdderr("CURRISK", vRM) quit
		set X = ln.curscor1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CURSCOR1", vRM) quit
		set X = ln.curscor2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("CURSCOR2", vRM) quit
		if ln.pririsk.length()>3 set vRM = $$^MSG(1076,3) do vdderr("PRIRISK", vRM) quit
		set X = ln.priscor1 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PRISCOR1", vRM) quit
		set X = ln.priscor2 if 'X.isNull(),X'?1.3N,X'?1"-"1.2N set vRM=$$^MSG(742,"N") do vdderr("PRISCOR2", vRM) quit
	}

	if vobj(ln,458).exists() do {

		set X = ln.clr if 'X.isNull(),X'?1.2N,X'?1"-"1.1N set vRM=$$^MSG(742,"N") do vdderr("CLR", vRM) quit
		set X = ln.slc if 'X.isNull(),'Db.isDefined("STBLSBSLC","X") set vRM = $$^MSG(1485,X) do vdderr("SLC", vRM) quit
	}

	if vobj(ln,459).exists() do {

		set X = ln.cipy98e if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CIPY98E"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.sdate98e if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("SDATE98E", vRM) quit
	}

	if vobj(ln,461).exists() do {

		if '("01"[ln.GENPRJREP) set vRM=$$^MSG(742,"L") do vdderr("GENPRJREP", vRM) quit
		if ln.maxptrm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("MAXPTRM", vRM) quit
		if ln.minptrm.length()>8 set vRM = $$^MSG(1076,8) do vdderr("MINPTRM", vRM) quit
		set X = ln.numdtp if 'X.isNull(),X'?1.6N,X'?1"-"1.5N set vRM=$$^MSG(742,"N") do vdderr("NUMDTP", vRM) quit
		set X = ln.pmro if 'X.isNull(),'Db.isDefined("STBLPMRO","X") set vRM = $$^MSG(1485,X) do vdderr("PMRO", vRM) quit
	}

	if vobj(ln,463).exists() do {

		set X = ln.maxo if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MAXO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.mino if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.MINO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.pcto if 'X.isNull() set vRM = $$VAL^DBSVER("N",8,0,,,,,5) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PCTO"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,465).exists() do {

		if '("01"[ln.ADJCOL) set vRM=$$^MSG(742,"L") do vdderr("ADJCOL", vRM) quit
		set X = ln.collim if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.COLLIM"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		if '("01"[ln.COLLIMPR) set vRM=$$^MSG(742,"L") do vdderr("COLLIMPR", vRM) quit
		if '("01"[ln.FSOVRDUE) set vRM=$$^MSG(742,"L") do vdderr("FSOVRDUE", vRM) quit
		if '("01"[ln.OOC) set vRM=$$^MSG(742,"L") do vdderr("OOC", vRM) quit
		set X = ln.pbfre if 'X.isNull() set vRM = "" do DBSEDT^UFRE("[LN]PBFRE",0) if 'vRM.get().isNull() do vdderr("PBFRE", vRM) quit
		set X = ln.pblstdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PBLSTDT", vRM) quit
		set X = ln.pbnxtdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("PBNXTDT", vRM) quit
		if '("01"[ln.RACLC) set vRM=$$^MSG(742,"L") do vdderr("RACLC", vRM) quit
		if '("01"[ln.RACLF) set vRM=$$^MSG(742,"L") do vdderr("RACLF", vRM) quit
		if '("01"[ln.SECMTG) set vRM=$$^MSG(742,"L") do vdderr("SECMTG", vRM) quit
	}

	if vobj(ln,467).exists() do {

		set X = ln.psrlnbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.PSRLNBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.ssrlnbal if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.SSRLNBAL"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
	}

	if vobj(ln,469).exists() do {

		set X = ln.altoff if 'X.isNull(),'Db.isDefined("UTBLOFF","X") set vRM = $$^MSG(1485,X) do vdderr("ALTOFF", vRM) quit
		set X = ln.defltdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DEFLTDT", vRM) quit
		if '("01"[ln.DMNDLN) set vRM=$$^MSG(742,"L") do vdderr("DMNDLN", vRM) quit
		set X = ln.dtpmstch if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DTPMSTCH", vRM) quit
		set X = ln.jcode if 'X.isNull(),'Db.isDefined("UTBLJUD","X") set vRM = $$^MSG(1485,X) do vdderr("JCODE", vRM) quit
		set X = ln.jdgmfldt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("JDGMFLDT", vRM) quit
		set X = ln.lienfldt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("LIENFLDT", vRM) quit
		set X = ln.naics if 'X.isNull(),'Db.isDefined("UTBLNAICS","X") set vRM = $$^MSG(1485,X) do vdderr("NAICS", vRM) quit
		set X = ln.naplmtdt if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("NAPLMTDT", vRM) quit
		set X = ln.nucollyr if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("NUCOLLYR", vRM) quit
		set X = ln.nucolytd if 'X.isNull(),X'?1.4N,X'?1"-"1.3N set vRM=$$^MSG(742,"N") do vdderr("NUCOLYTD", vRM) quit
		if ln.trstrcno.length()>20 set vRM = $$^MSG(1076,20) do vdderr("TRSTRCNO", vRM) quit
	}

	if vobj(ln,500).exists() do {

		if ln.acycode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("ACYCODE", vRM) quit
		if ln.agcode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("AGCODE", vRM) quit
		if ln.agtypec.length()>15 set vRM = $$^MSG(1076,15) do vdderr("AGTYPEC", vRM) quit
		if ln.busadv.length()>15 set vRM = $$^MSG(1076,15) do vdderr("BUSADV", vRM) quit
		set X = ln.cptag if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CPTAG"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cptbadv if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CPTBADV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cptiae if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CPTIAE"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.cptrefr if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.CPTREFR"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dcptag if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DCPTAG", vRM) quit
		set X = ln.dcptbadv if 'X.isNull() set vRM = $$VAL^DBSVER("$",18,0,,,,,2) if 'vRM.isNull() set vRM = $$^MSG(979,"LN.DCPTBADV"_" "_vRM) throw Class.new("Error","%PSL-E-DBFILER,"_vRM.replace(",","~"))
		set X = ln.dcptiae if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DCPTIAE", vRM) quit
		set X = ln.dcptrefr if 'X.isNull(),X'?1.5N set vRM=$$^MSG(742,"D") do vdderr("DCPTREFR", vRM) quit
		if ln.ilcode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("ILCODE", vRM) quit
		if ln.refrep.length()>15 set vRM = $$^MSG(1076,15) do vdderr("REFREP", vRM) quit
		if ln.sofcode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("SOFCODE", vRM) quit
		if ln.subscode.length()>15 set vRM = $$^MSG(1076,15) do vdderr("SUBSCODE", vRM) quit
	}
	set X = ln.cid if 'X.isNull(),X'?1.12N,X'?1"-"1.11N set vRM=$$^MSG(742,"N") do vdderr("CID", vRM) quit
	quit

vdderr(di, vRM) // Column attribute error

	type public Boolean ER = 0
	type public String RM
	do SETERR^DBSEXECU("LN","MSG",979,"LN."_di_" "_vRM)
	if ER throw Class.new("Error","%PSL-E-DBFILER,"_RM.get().replace(",","~"))
	quit
