LNNTMES	//MAINTENANCE FOR LATE NOTICES DESCRIPTION
	/*
	       ORIG:  Kathie Jalbuena (7070) - 10/16/87

	  ---- Revision History ------------------------------------------------

	   05/12/05 - HILANBRAND - 13281
	              Modified FILE subsection to only delete if %ProcessMode
	              is equal to 3.
           
           07/26/02 - SRIVASTAVAN - 49451
                      Converted to PSL
          --------------------------------------------------------------------
	*/

NEW	//  

	do INIT(0)

     	quit


UPD	//  

	do INIT(1)

   	quit


INQ	//  

	do INIT(2)

    	quit
 

DEL	//  

	do INIT(3)

     	quit


INIT(%ProcessMode)	//	

	new VFMQ
	set %PG=0 
        set %PAGE=1

	type RecordUTBLLNOT LNOT
	do VPG(.LNOT)

	quit


VPG(RecordUTBLLNOT LNOT)	// Page control

	new FINISH
	set FINISH=0        
	for  do { quit:FINISH
		if %PG=0 do VPG00 if ("Q"[VFMQ)!ER set FINISH=1 quit
                
	       	if %PG>0 do VPG01(.LNOT) if ("Q"[VFMQ)!ER set FINISH=1 quit

		if "DFQ"[VFMQ do VER(.LNOT) set FINISH=1 quit

        	set %PG=%PG+1
		}
	quit


VPG00	// Set up

	set %TAB("KEY")=".KEY1/TBL=[UTBLLNOT]KEY,DES/XPP=D POST^LNNTMES"

	set %READ="@@%FN,,,KEY/REQ"

	do ^UTLREAD

	if VFMQ="Q" set ER=1 quit
	set %TAB("DES")=".DESC2"
	set OLNTB=4000
	set %READ="DES/REQ"

	do ^UTLREAD

	quit


VPG01(RecordUTBLLNOT LNOT)	// Screen

	set LNOT=Db.getRecord("UTBLLNOT","KEY=:KEY",1)
	
	do DRV^USID(%ProcessMode,"UTBLLNOT",.LNOT)

	quit


ERR	//

	set ER=1 
	
	do ^UTLERR
	
	set VFMQ="Q"

	quit


VER(RecordUTBLLNOT LNOT)	//     

	if %ProcessMode=2!(%ProcessMode=4)!(VFMQ="Q") do END quit

	set LNOT.des=DES

        do FILE(.LNOT)

	do END
	
	quit


FILE(RecordUTBLLNOT LNOT)	// File data
	
	if %ProcessMode=3 do Db.delete("UTBLLNOT","KEY=:KEY") quit
	
	do LNOT.save()          

	quit


END	//

	kill %TAB lock 

	if ER!(%ProcessMode=2)!(%ProcessMode=4) quit

	set KEY=$G(KEY)

        if VFMQ="Q" do {
		
		// Message for ~p1 not created
		if %ProcessMode=0 set RM=$$^MSG(1717,KEY) quit

	        // Message for ~p1 not modified
		if %ProcessMode=1 set RM=$$^MSG(1719,KEY) quit

	 	// Message for ~p1 not deleted
		set RM=$$^MSG(1718,KEY)
		}
	else  do {

		// Message for ~p1 created
		if %ProcessMode=0 set RM=$$^MSG(1714,KEY) quit

		// Message for ~p1 modified
		if %ProcessMode=1 set RM=$$^MSG(1716,KEY) quit

		// Message for ~p1 deleted
  		set RM=$$^MSG(1715,KEY)
		}
	set ER="W"
	quit


POST	// Post processor for key
	
        type RecordUTBLLNOT utblnot=Db.getRecord("UTBLLNOT","KEY=:X",1)
        if '%OSAVE,utblnot.getMode() do { quit
        	set ET="LNONFIL"
        	do ERR^LNNTMES
        	}
	if %OSAVE,utblnot.getMode() set DES=utblnot.des

	quit

	

vSIG()	quit "60032^62267^Laura Hillanbrand^2464"	// Signature - LTD^TIME^USER^SIZE
