LNPPEC1	//PBS - LN, Escrow pre/post processors - create account (1)
	/*
	 The function is used to compute [TRTYPE]XDEP06 field
 
        ARGUMENTS:
                . CID  Account Number        /TYP=N/REQ/
		. TYP  Escrow Transfer Type  /TYP=T/REQ/
        RETURNS:
		. Remittance Information     /TYP=T
 
        EXAMPLE:
                W $$REMACT^LNPPEC1(CID,TYP)

	----Revision History--------------------------------------------------
	
	04/05/02 - VETSENM - 49794
		   Converted to PSL.	            	


	*/

	quit

REMACT(CID,TYP)	// calcuate escrow next remittance values
	
	new REMACT,REMEAI,REMDT

        type RecordTRTYPE trtype=Db.getRecord("TRTYPE","CID=:CID,TYP=:TYP")

        set REMDT=trtype.remnd
        
        if trtype.roea set REMDT=Db.prevVal("RAMT","CID=:CID,TYP=:TYP,REMDT=:REMDT+1")
	
        type RecordRAMT ramt=Db.getRecord("RAMT","CID=:CID,TYP=:TYP,REMDT=:REMDT",1)	

	set REMACT=ramt.remamt
	set REMEAI=ramt.estflg 

	set XDEP06=REMACT_"|"_REMEAI_"|"_REMDT
	
	quit XDEP06	

vSIG()	quit "59886^43540^Sanchez SCM Administrator^897"	// Signature - LTD^TIME^USER^SIZE
