MRPC084(return,versn,crdtyp,acn)
        /*
        Procedure ID: MRPC084
        DESC: Card Number Generation
        KEYWORDS: RPC,Card
 
        ARGUMENTS:
                . return  Card Number       		/TYP=N/REQ/MECH=REFNAM
 
                . versn   ^MRPC084 version number       /TYP=N/REQ/MECH=VAL
                          current version=1
 
                . crdtyp  Card Type                	/TYP=T/REQ/MECH=VAL
  
        RETURNS:
                . $$      Error Message                 /TYP=T
                          Null= No Error
 
        RELATED:
                . $$^PBSMRPC - MRPC Service Class Driver
 
        EXAMPLE:
                S RM=$$^MRPC084(.VAL,1,'CARDTYP')
 
        ---- Revision History ------------------------------------------------
	6/29/1999   - Anna Maltepes   32386
		      Added one more parameter acn for the new card creation. 
        ---------------------------------------------------------------------- 
        */
        //----------------------------------------------------------------------
	// Version number of client message is not compatible with server
	if $G(versn)'=1 quit $$ERRMSG^PBSUTL($$^MSG(2951))

	new str

	if $G(crdtyp)="" set return=""
	else  set str=$$START^CRDNUMGN(crdtyp,$g(acn))
	
	quit:$G(RM)!$G(ER) $$ERRMSG^PBSUTL($G(RM))

	set return=$$V2LV^MSG(str)
	quit ""
        //-----------------------------------------------------------------

vSIG()	quit "59886^43588^Sanchez SCM Administrator^1343"	// Signature - LTD^TIME^USER^SIZE
