MRPC011(String return,Number versn,String bse,String sec,Number amt,Boolean bseamt,Number trntyp,Number cash,Number custcd,Date efd,Number r8typ)	//Public;Currency Exchange
	/*
	   ORIG: MATTSON - 09/17/93

	   This extrinsic function returns the exchange amount between
	   two currencies.

	    [SCATBL5]RPCID=11

	   KEYWORDS: Client/Server, Currency

	   ARGUMENTS:
	       	. return 	Value of fields requested 	/TYP=T/REQ
	        						/MECH=REFNAM:W

	       	. versn 	^MRPC011 version number  	/TYP=N/REQ
	    			Current version = 1  		/MECH=VAL

	       The following arguments are also arguments to the call to the
	       standard currency exchange utility $$EXC^CRCDUTL.  Refer to
	       the documentation in $$EXC^CRCDUTL for further information.

	       . bse 	Base currency code  		/TYP=T/REQ/MECH=VAL
	       . sec 	Secondary currency code  	/TYP=T/REQ/MECH=VAL
	       . amt 	Amount of exchange (bse or sec) /TYP=$/REQ/MECH=VAL
	       . bseamt Is 'amt' in base currency 	/TYP=L/REQ/MECH=VAL
	       . trntyp Transaction type  		/TYP=N/REQ/MECH=VAL
	       . cash   Cash transaction flag  		/TYP=N/REQ/MECH=VAL
	       . custcd Customer code   		/TYP=N/NOREQ/MECH=VAL
	       . efd 	Effective date   		/TYP=D/NOREQ/MECH=VAL
	       . r8typ  Rate type   			/TYP=N/NOREQ/MECH=VAL

	   RETURNS:
	       . $$ 	Error message   		/TYP=T
	    	 	Null = No error

	   RELATED:
	       . $$^PBSMRPC - MRPC Service Class Driver

	   EXAMPLES:

	       S RM=$$^MRPC011(.val,1,"DEM","GBP",250,0,11)

	---- Revision History ------------------------------------------------

        07/26/05 - SkariahV- CR16679
	           Removed #WARN directive.
	              	
	01/08/03 - GRAY - 51351
		   Converted to PSL.


	*/


	// Version number of client message is not compatible with server
	if versn.get()'=1 quit $$ERRMSG^PBSUTL($$^MSG(2951))

	type String array,x
	type Number EXCAMT,MAXRATE,MINRATE,MULTIPLY,RATE,VARIANCE
	type Boolean TRESREF
	type Public Number ER
	type Public String ET,RM

	set custcd=custcd.get() 
	set efd=efd.get() 
	set r8typ=r8typ.get()

	do EXC^CRCDUTL(bse,sec,amt,bseamt,trntyp,cash,custcd,efd,r8typ)

	if ER.get() quit $$ERRMSG^PBSUTL(RM.get(),ET.get())

	set x=EXCAMT.get()_"|"_RATE.get()_"|"_MINRATE.get()_"|"_MAXRATE.get()
	set x=x_"|"_MULTIPLY.get()_"|"_TRESREF.get()_"|"_VARIANCE.get()

	set x=$$COLUMN^MSG(x,124,.array)

	set return=$$V2LV^MSG(.array)

	quit ""

vSIG()	quit "60107^17672^Viji Skariah^2152"	// Signature - LTD^TIME^USER^SIZE
