MRPC033(String RETURN,Number VERSN,Number CID,Number RPADIS,Number TAMT)	//Public;MRPC call for Distribution w/h amount calculating
	/*

	   DESC: Interest Change Summary Report.
	   KEYWORDS: RPC

	   ARGUMENTS:
		. RETURN	Date, interest rate & balance details 
							/TYP=T/REQ/MECH=REFNAM:W

		. VERSN         ^MRPC033 version number /TYP=N/REQ/MECH=VAL
	                         current version=1

		. CID           Account Number          /TYP=N/REQ/MECH=VAL

		. RPADIS        Dist. reason code     	/TYP=N/REQ/MECH=VAL

		. TAMT          Gross withdrawl amt     /TYP=N/REQ/MECH=VAL

	   RETURNS:
		. $$    	Error Message       	/TYP=T
	          		Null= No Error

	   RELATED:
	         . $$^PBSMRPC - MRPC Service Class Driver

	   EXAMPLE:
	         S RM=$$^MRPC033(.VAL,1,CID,RPADIS,TAMT)

	------------------ Revision History ----------------------------------

        07/25/05 - SkariahV- CR16679
	           Removed #WARN directive.
	              
	01/10/03 - GRAY - 51351
		   Converted to PSL.

	02/26/02 - ANTONOVS - 46454
		   Modified to add State Withholding amount to return value.

	*/

	type Public Number ER
	type Public String ET,RM

	// Version number of client message is not compatible with server
	if VERSN.get()'=1 quit $$ERRMSG^PBSUTL($$^MSG(2951))

	// Reason code required for this transaction
	if RPADIS.get()="" quit $$ERRMSG^PBSUTL($$^MSG(1078))

	// Withdrawl amount required for this transaction
	if TAMT.get()="" quit $$ERRMSG^PBSUTL($$^MSG(1079))

	type RecordDEP dep=Db.getRecord("DEP","CID=:CID",1)

	// Invalid account ~p1
	if dep.getMode()=0 quit $$ERRMSG^PBSUTL($$^MSG(1259,CID))

	// Not a retirement plan account
	if 'dep.ira quit $$ERRMSG^PBSUTL($$^MSG(2030))

	// Return distribution w/h amount
	// 46454 - AS add State withholding amount to distribution w/h amount
	set RETURN=$$V2LV^MSG($$RPACRT^IRAWH(.dep,RPADIS,TAMT)+$$RPACRTS^IRAWH(.dep,RPADIS,TAMT))

	if ER.get() set RETURN="" quit $$ERRMSG^PBSUTL(RM.get())

	quit ""

vSIG()	quit "60107^17668^Viji Skariah^1777"	// Signature - LTD^TIME^USER^SIZE
