PNLTYBAL(CID,LSTDT,PBAL)
  /*
ORIG: KELLYP - 11/29/2000
DESC: Custom Penalty Balance Calculation Proc.

---- Comments --------------------------------------------------------

 This procedure calculates the total Penalty Balance for an ODCC account
 by summing the value of PNLTYEVENT.PENBAL using all PNLTYEVENT entries
 dated from LSTDT (LN.PBLSTDT) through TJD (inclusive). The calculated 
 total Penalty Balance is returned via the PBAL parameter (which should
 in passed in by reference).
 
	ARGUMENTS:
        	. XCID         Account Number                   /TYP=N/REQ
        	. XLSTDT       Penalty Balance Last Cutoff Date /TYP=D/REQ
        
        RETURNS:
               	Total Penalty Balance from LSTDT through TJD (inclusive)
        
        EXAMPLE:
    		D ^PNLTYBAL(CID,58800,.PBAL)

---- Revision History ------------------------------------------------

	02/02/05 - ARPAVC 14330
		   Fixed compile errors by removing unreferenced variable 
		   TOTPBAL.
		   
 */
 
 type Date BEGDT,ENDDT
 
 if $G(PBAL)'=0 set PBAL=0
 if ($G(CID)="")!($G(LSTDT)="") quit

 /*
  Total penalty balance should include PNLTYEVENT.PENBAL entries from
  LSTDT through TJD (inclusive).
 */

 set ENDDT=(%SystemDate+1)	// TJD + 1 for SQL WHERE statement
 set BEGDT=LSTDT-1		// Last Date - 1 for SQL WHERE statement

 type ResultSet rs=Db.select("PENBAL","PNLTYEVENT","CID=:CID AND PDT>:BEGDT AND PDT<:ENDDT")

 if rs.isEmpty() quit

 while rs.next() set PBAL=PBAL+rs.getCol(1)

 quit

vSIG()	quit "59987^61851^Vincent Arpa^1408"	// Signature - LTD^TIME^USER^SIZE
