QRYGRP(CLS,GRPLIST)
	/*
	ORIG:  Allan R. Mattson (6915) - 09/11/86
	PROCEDURE ID: QRYGRP
	DESC: Account Group Query
	
	---- Comments --------------------------------------------------------

	Allow screen selection of a list of groups for the specified class.

	ARGUMENTS:
		. CLS		Class		/TYP=T/REQ/NONULL/MECH=VAL

		. TYPELIST	List of selected type	/REQ/MECH=REFARR:W

	RETURNS:
		. ER		Error flag	/TYP=L
		
		. RM		Error message	/TYP=T	

	------ Revision History ------------------------------------------------
	
	11/02/04 - RussellDS - CR13011
		   Corrected undefined.  Cleaned up scope and precedence warnings.
	
	07/10/02 - YENDAPALLIS - 43583
		   PSL conversion clean up.

	08/12/02 - Dan Russell - 49794
		   Restructured to simplify.  Added parameters to eliminate Q
		   array and to allow list of returned values.

	04/05/02 - YENDAPALLIS - 43583
		   Converted to PSL 
	----------------------------------------------------------------------------
	*/

	type Public Number ER
	type Public String RM, VFMQ

	type Number N,%PAGE,%PG,%REPEAT
	type String PGM,R(),SID,STR

	kill GRPLIST
	set %ProcessMode=0
	set %PG=1
	do DFT

	set SID="QRYGRP" 
	do DRV^USID(%ProcessMode,SID) 
	if ER do { quit
		set ER=1
		do DSPBP^UTLERR
		}

	if VFMQ="Q" quit

	set N="" 
	set STR="|" 
	
	for  set N=$O(R(N)) quit:N=""  do {
		
		type Number I
		
		for I=2,4,6  do {
			if $P(R(N),"|",I) do {
				type String GRP
				set GRP=$P(R(N),"|",I-1) 
				set GRPLIST(GRP)=""
			}
		}
	}

	// No groups selected
	if '$D(GRPLIST) set ER=1 set RM=$$^MSG("1946")

	quit


DFT	// Create screen default info

	type Public Number %REPEAT
	type Public String R()

	set R=0
	
	type ResultSet rs=Db.select("distinct GRP","ACN","CLS=:CLS")
	while rs.next() do {
		new GRP
		set GRP=rs.getCol(1)
		set R=R+1
		set $P(R(((R-1)\3)+1),"|",(((R-1)#3)*2)+1)=GRP_"|"_1
	}

	set %REPEAT=$O(R(""),-1)
	
	quit

vSIG()	quit "59886^43598^Sanchez SCM Administrator^1763"	// Signature - LTD^TIME^USER^SIZE
