R01S289	// SCA284 - Monthly Customer Officer Account Report
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:47 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN1="ALL"

	set RID="SCA284"
	set RN="Monthly Customer Officer Account Report"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN1")="|255||[CIF]CIFOFF|[UTBLOFF]:NOVAL||D EXT^DBSQRY||T|Officer Code|||||"

	set %READ="IO/REQ,VIN1#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String VIN1
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,ACC,ACCT,CONAM,RID,RN,SYSEQUIV,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA284",RN="Monthly Customer Officer Account Report"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA284","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[ACN]CID#16#12,[ACN]GRP#32#4,[ACN]TYPE#40#4,[ACN]TITLE1#48#40,[ACN]BAL#89#14,[ACN]CRCD#104#3"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		if VIN1.get()="" set VIN1="ALL"
		if VIN1'="ALL" set DQQRY(SEQ)="[CIF]CIFOFF "_VIN1,SEQ=SEQ+1
		set DQQRY(SEQ)="[ACN]STAT'=4",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("ACN,CIF") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",1)="WC2|"_"Officer Code"_"|VIN1|"_VIN1.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Monthly Customer Officer Account Report"
		set VBNRINFO("PGM")="R01S289"
		set VBNRINFO("RID")="SCA284"
		set VBNRINFO("TABLES")="ACN,CIF"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,CIF]CIFOFF"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,CIF]ACN"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,ACN]CLS"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,ACN]TYPE"
		set VBNRINFO("ORDERBY",5)="[SYSDEV,ACN]CID"


		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:5 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:2 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"CIF.CIFOFF,CIF.ACN,ACN.CLS,ACN.TYPE,ACN.CID,ACN.GR"
	set VSELECT=VSELECT_"P,ACN.TITLE1,ACN.BAL,ACN.CRCD,CIF.NAM"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"ACN,CIF",VWHERE,"CIF.CIFOFF,CIF.ACN,ACN.CLS,ACN.TYPE,ACN.CID","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2,vovc3,vovc4,vovc5
	set vovc1="",vovc2="",vovc3="",vovc4="",vovc5=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2,vovc3,vc3,vovc4,vc4,vovc5,vc5
	set vovc1=vc1,vovc2=vc2,vovc3=vc3,vovc4=vc4,vovc5=vc5
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10
	set vc1=V.piece($C(9),1)			// CIF.CIFOFF
	set vc2=V.piece($C(9),2)			// CIF.ACN
	set vc3=V.piece($C(9),3)			// ACN.CLS
	set vc4=V.piece($C(9),4)			// ACN.TYPE
	set vc5=V.piece($C(9),5)			// ACN.CID
	set vc6=V.piece($C(9),6)			// ACN.GRP
	set vc7=V.piece($C(9),7)			// ACN.TITLE1
	set vc8=V.piece($C(9),8)			// ACN.BAL
	set vc9=V.piece($C(9),9)			// ACN.CRCD
	set vc10=V.piece($C(9),10)			// CIF.NAM
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0,vs(5)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1,vskp(4)=1,vskp(5)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(1).get() do VDTL1 quit:VFMQ
	do VHDG3 quit:VFMQ
	if 'vskp(3).get() do VDTL3 quit:VFMQ
	if 'vskp(5).get() do VDTL5 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(5)
	type Public String vc1,vovc1,vc2,vovc2,vc3,vovc3,vc4,vovc4,vc5,vovc5
	type Number vb1,vb2,vb3,vb4,vb5
	set (vb1,vb2,vb3,vb4,vb5)=0
	if vb1!(vovc1'=vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1,vb5=1,VH0=1
	if vb2!(+vovc2'=+vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1,vb5=1
	if vb3!(vovc3'=vc3) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1,vb5=1
	if vb4!(+vovc4'=+vc4) set vs(5)=0,vh(5)=0,VD(4)=0,vb5=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(5) set vs(5)=1 do stat^DBSRWUTL(5)
	if 'vs(4) set vs(4)=1 do VSUM4 quit:VFMQ  do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do VSUM2 quit:VFMQ  do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT(),SYSEQUIV,vc8
	type Public String VSTATS

	set VT(5)=VT(5)+1
	set VT(5,1,1)=VT(5,1,1)+SYSEQUIV		// @TOT(<<SYSEQUIV>>)
	set VT(5,2,1)=VT(5,2,1)+vc8			// @TOT([ACN]BAL)
	quit

VDTL1	// Detail
	type public String %TIM,ACC,ACCT,IOSL,SYSEQUIV,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx

	quit:VD(1)  set VD(1)=1				// Print flag
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="Account Officer "
	do VP1 quit:VFMQ!verror.get()  set V=$E(xxx,1,40)
	set VL=VL_$J("",16-VL.length())_V
	do VOM
	set VL="===================================================================================================================================="
	do VOM
	quit

VSUM2	// Summary
	type public String %TIM,ACC,ACCT,I,IOSL,SYSEQUIV,V,VFMQ,VL,VLC,VO,VOFFLG,VPN,VT(),VX(),vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx

	if 'VT(2) quit
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	set VL="System Equivalent Totals for CIF:"
	set V=VT(2,2,1)					// @TOT([ACN]BAL,)
	set VL=VL_$J("",88-VL.length())_$J($FN(V,",",2),14)
	set V=VT(2,1,1)					// @TOT(<<SYSEQUIV>>,)
	set VL=VL_$J("",110-VL.length())_$J($FN(V,",",2),14)
	do VOM
	set VL="" do VOM
	quit

VHDG3	// Group Header
	type public String %MSKD,%TIM,ACC,ACCT,CONAM,ER,IOSL,RID,RN,SYSEQUIV,V,VFMQ,VL,VLC,VNEWHDR,VO,VOFFLG,VPN,VRG,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vcrt,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx

	quit:vh(3)  set vh(3)=1				// Print flag
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	set VL="Customer #: "
	set VL=VL_$J("",13-VL.length())_vc2_$J("",12-$L(vc2))
	set VL=VL_$J("",32-VL.length())_"Customer Name: "
	set VL=VL_$J("",48-VL.length())_$E(vc10,1,40)
	do VOM
	quit

VDTL3	// Detail
	type public String %TIM,ACC,ACCT,IOSL,SYSEQUIV,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx

	quit:VD(3)  set VD(3)=1				// Print flag
	if VLC+3>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	do VP2 quit:VFMQ!verror.get()  set V=$E(ACC,1,16) set VL="           "_V
	set VL=VL_$J("",31-VL.length())_"Group"
	set VL=VL_$J("",39-VL.length())_"Type"
	set VL=VL_$J("",47-VL.length())_"Account Title"
	set VL=VL_$J("",95-VL.length())_"Balance"
	set VL=VL_$J("",109-VL.length())_"System Equivalent"
	do VOM
	set VL="           "_"-"
	set VL=VL_$J("",12-VL.length())_"-------------------------------------------------------------------------------------------------------------------"
	do VOM
	quit

VSUM4	// Summary
	type public String %TIM,ACC,ACCT,I,IOSL,SYSEQUIV,V,VFMQ,VL,VLC,VO,VOFFLG,VPN,VT(),VX(),vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx

	if 'VT(4) quit
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	do VP3 quit:VFMQ!verror.get()  set V=$E(ACCT,1,40) set VL="              "_V
	set V=VT(4,2,1)					// @TOT([ACN]BAL,)
	set VL=VL_$J("",88-VL.length())_$J($FN(V,",",2),14)
	set V=VT(4,1,1)					// @TOT(<<SYSEQUIV>>,)
	set VL=VL_$J("",110-VL.length())_$J($FN(V,",",2),14)
	do VOM
	set VL="" do VOM
	quit

VDTL5	// Detail
	type public String %TIM,ACC,ACCT,IOSL,SYSEQUIV,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx

	if VLC+1>IOSL do VHDG0 quit:VFMQ

	set VL="               "_$J(vc5,12)
	set VL=VL_$J("",31-VL.length())_$E(vc6,1,4)
	set VL=VL_$J("",36-VL.length())_$J(vc4,7)
	set VL=VL_$J("",47-VL.length())_$E(vc7,1,40)
	set VL=VL_$J("",88-VL.length())_$J($FN(vc8,",",2),14)
	set VL=VL_$J("",103-VL.length())_$E(vc9,1,3)
	do VP4 quit:VFMQ!verror.get()  set V=$J($FN(SYSEQUIV,",",2),14)
	set VL=VL_$J("",110-VL.length())_V
	do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,ACC,ACCT,CONAM,RID,RN,SYSEQUIV,VL,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate,xxx
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+3,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E(CONAM,1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  ("_RID_")"
	set VL=VL_$J("",102-VL.length())_"System:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$J(VPN,3)
	do VOM
	set VL="" do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - Variable: xxx

	type public String vc1
	type Public String CIFOFF,ZDATA,xxx

	set CIFOFF=vc1
	if CIFOFF="" set xxx="NONE" quit 
	
	do { 
		new rs 
		type ResultSet rs=Db.select("DESC,SNME","UTBLOFF","OFF=:CIFOFF") 
		set ZDATA="" if 'rs.next()  quit
		set ZDATA=rs.getRow()
		} 
	
	
	set ZDATA=$TR(ZDATA,$C(9),"|")
	set xxx=CIFOFF_" - "_ZDATA
	quit

VP2	// Column pre-processor - Variable: ACC

	type public String vc3
	type Public String ACC,CLS
	
	set CLS=vc3

	set ACC=$S(CLS="D":$$^MSG(5166),1:$$^MSG(8455))      
	// I18N=OFF
	set ACC=ACC_" Account"
	// I18N=ON
	quit

VP3	// Column pre-processor - Variable: ACCT

	type public String vc2
	type Public String ACC,ACCT,ACN

	set ACN=vc2
	
	set ACCT=$$^MSG(6451,ACC,ACN)          //~p1 Totals,Customer # ~p2
	quit

VP4	// Column pre-processor - Variable: SYSEQUIV

	type public String vc8,vc5,vc9
	type Public Number SYSEQUIV
        type Number BAL,CID
	type String CRCD

        set BAL=vc8
	set CID=vc5
	set CRCD=vc9
 
	set SYSEQUIV=$$SYSEQV^DEPCDI(CID,CRCD,BAL)
	quit
