R01S614	// SCA715 - OTS Schedule PD
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:53 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type public String SCDATE
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN1=$$KEY^DBSREP("LNOTSSC","",1,"D")

	set RID="SCA715"
	set RN="OTS Schedule PD"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	do VPREBQ quit:VFMQ.get()			// Pre-processor (before query)

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN1")="|255||[LNOTSSC]SCDT|[LNOTSSC]SCDT:DISTINCT:NOVAL||D EXT^DBSQRY||T|System Processing Date|||||"

	set %READ="IO/REQ,VIN1#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String SCDATE
	type public String VIN1
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,CONAM,PD(),RID,RN,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc2,vovc1,vovc2,vrundate,vsysdate

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA715",RN="OTS Schedule PD"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA715","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()


	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		if VIN1.get()="" set VIN1="ALL"
		if VIN1'="ALL" set DQQRY(SEQ)="[LNOTSSC]SCDT "_VIN1,SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("LNOTSSC") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Initialize variables
	set (vc1,vc2)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:2 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:0 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	if VDISTKEY.get()="" do { quit:VFMQ		// Report Pre-processor (after query)
		do VPREAQ
		if VFMQ set vh(0)=1 do VEXIT(0)
		}

	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT="LNOTSSC.SCDT,LNOTSSC.SCLN"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"LNOTSSC",VWHERE,"LNOTSSC.SCDT,LNOTSSC.SCLN","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2
	set vovc1="",vovc2=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2
	set vovc1=vc1,vovc2=vc2
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2
	set vc1=V.piece($C(9),1)			// LNOTSSC.SCDT
	set vc2=V.piece($C(9),2)			// LNOTSSC.SCLN
	quit

	// User-defined pre/post-processor code

VPREAQ	// Pre-processor (after query)

 type Public Date SCDATE
 type Public Number PD()

 type Number I
 type String PDLN

 type RecordLNOTSSC lnotssc

 for I=10,115,121,123,124,125,135,138,140,161,163,165,167,169,180,20,215,221,223,224,225,235,238,240,261,263,265,267,269,280 do {
 	set PDLN="PD"_I
	set PD(I)=""
 	set lnotssc=Db.getRecord("LNOTSSC","SCDT=:SCDATE,SCLN=:PDLN",1)
	if lnotssc.getMode() set PD(I)=lnotssc.tot
 }

 for I=30,315,321,323,324,325,335,338,340,361,363,365,367,369,380 do {
 	set PDLN="PD"_I
	set PD(I)=""
	set lnotssc=Db.getRecord("LNOTSSC","SCDT=:SCDATE,SCLN=:PDLN",1)
	if lnotssc.getMode() set PD(I)=lnotssc.tot
 }
	quit

VPREBQ	// Pre-processor (before query)

 //Incoming=SCDATE
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0
	if 'VFMQ do VSUM
	if 'VFMQ do VRSUM
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(2)
	type Public String vc1,vovc1,vc2,vovc2
	type Number vb1,vb2
	set (vb1,vb2)=0
	if vb1!(vovc1'=vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,VH0=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT()
	type Public String VSTATS

	set VT(2)=VT(2)+1
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,CONAM,PD(),RID,RN,SCDATE,VL,vc1,vc2,vovc1,vovc2,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+26,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E($G(CONAM),1,40)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",122-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  ("_RID_")"
	set VL=VL_$J("",102-VL.length())_"System:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",121-VL.length())_"Page:"
	set VL=VL_$J("",127-VL.length())_$J(VPN,3)
	do VOM
	set VL="" do VOM
	set VL="                                                               "_"Past Due and Still Accruing                        Nonaccrual"
	do VOM
	set VL="                                                          "_"30-89 Days               90 Days or More"
	do VOM
	set VL="Mortgage Loans:"
	do VOM
	set VL="Construction                              PD 115"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(115),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 215  "
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(215),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 315"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(315),",",0),18)
	do VOM
	set VL="Permanent, Secured By:"
	do VOM
	set VL="1-4 Dwelling Units:                         "
	do VOM
	set VL="Revolving, Open-End Loans                 PD 121"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(121),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 221"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(221),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 321"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(321),",",0),18)
	do VOM
	set VL="All Other:"
	do VOM
	set VL="Secured by First Liens                    PD 123  "
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(123),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 223  "
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(223),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 323  "
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(323),",",0),18)
	do VOM
	set VL="Secured by Junior Liens                   PD 124 "
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(124),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 224"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(224),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 324  "
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(324),",",0),18)
	do VOM
	set VL="Multifamily (5 or More Dwelling Units)    PD 125"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(125),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 225"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(225),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 325"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(325),",",0),18)
	do VOM
	set VL="Nonresidential Property (Except Land)     PD 135  "
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(135),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 235"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(235),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 335"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(335),",",0),18)
	do VOM
	set VL="Land                                      PD 138"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(138),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 238"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(238),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 338"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(338),",",0),18)
	do VOM
	set VL="Nonmortgage Loans:                        PD 180  "
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(180),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 280  "
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(280),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 380  "
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(380),",",0),18)
	do VOM
	set VL="Commercial Loans:                         PD 140"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(140),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 240"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(240),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 340"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(340),",",0),18)
	do VOM
	set VL="Consumer Loans:"
	do VOM
	set VL="Loans on Deposit                          PD 161"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(161),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 261"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(261),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 361"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(361),",",0),18)
	do VOM
	set VL="Home Improvement Loans                    PD 163 "
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(163),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 263"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(263),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 363"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(363),",",0),18)
	do VOM
	set VL="Education Loans                           PD 165"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(165),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 265"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(265),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 365"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(365),",",0),18)
	do VOM
	set VL="Auto Loans                                PD 167"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(167),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 267"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(267),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 367"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(367),",",0),18)
	do VOM
	set VL="Mobile Home Loans                         PD 169"
	set VL=VL_$J("",50-VL.length())_$J($FN(PD(169),",",0),18)
	set VL=VL_$J("",73-VL.length())_"PD 269"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(269),",",0),18)
	set VL=VL_$J("",104-VL.length())_"PD 369"
	set VL=VL_$J("",112-VL.length())_$J($FN(PD(369),",",0),18)
	do VOM
	set VL="" do VOM
	set VL="Total                                     PD 10"
	set VL=VL_$J("",49-VL.length())_$J($FN(PD(10),",",0),19)
	set VL=VL_$J("",73-VL.length())_"PD 20"
	set VL=VL_$J("",81-VL.length())_$J($FN(PD(20),",",0),19)
	set VL=VL_$J("",104-VL.length())_"PD 30"
	set VL=VL_$J("",111-VL.length())_$J($FN(PD(30),",",0),19)
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VRSUM	// Report Summary
	type Public Number IOSL,verror,VFMQ,vh,VLC,VT(),VX()
	type Public String %TIM,PD(),SCDATE,VPN,vovc1,vovc2,vrundate,vsysdate
	type Number I
	type String V,VL

	set VL=""
	if 'vh(0) do VHDG0 quit:VFMQ
	if VLC+55>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="                          "
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="                                     "
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="                                                         "
	do VOM
	set VL="                                     "_"                 "
	do VOM
	set VL="                                                   "
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="                                           "
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="                                   "
	do VOM
	set VL="                                "
	do VOM
	set VL="                                        "
	do VOM
	set VL="                                     "
	do VOM
	set VL="                                     "
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="                                                    "
	do VOM
	quit

VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors
