R01S214	// SCA160 - Tax Year-End Loan Summary
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:45 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN2="ALL"
	type String VIN3="ALL"
	type String VIN4="ALL"
	type String VIN5=">0"

	set RID="SCA160"
	set RN="Tax Year-End Loan Summary"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN2")="|255||[LN]GRP|[STBLGRP]:QU ""[STBLGRP]CLS=""""L"""""":NOVAL||D EXT^DBSQRY||T|Loan Group|||||"
	set %TAB("VIN3")="|255||[LN]TYPE|[PRODDFTL]:NOVAL||D EXT^DBSQRY||T|Product|||||"
	set %TAB("VIN4")="|255||[LN]BALPTYE|||D EXT^DBSQRY||T|Tax Year End Balance|||||"
	set %TAB("VIN5")="|255||[LN]IPTY|||D EXT^DBSQRY||T|Prior Tax Year Int Collected|||||"

	set %READ="IO/REQ,VIN2#0,VIN3#0,VIN4#0,VIN5#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=31
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type Boolean VHIT
	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String VIN2,VIN3,VIN4,VIN5
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,CONAM,RID,RN,STGRP,STTYPE,TAX,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA160",RN="Tax Year-End Loan Summary"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA160","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[LN]CID#1#12,[CIF]NAM#17#30,[LN]IPTY#51#12,[LN]ADBPTY#86#12,[LN]BALPTYE#102#12,[LN]PENPTY#118#12"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[LN]CLS=""L""",SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[LN]GRP "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[LN]TYPE "_VIN3,SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[LN]BALPTYE "_VIN4,SEQ=SEQ+1
		if VIN5.get()="" set VIN5="ALL"
		if VIN5'="ALL" set DQQRY(SEQ)="[LN]IPTY "_VIN5,SEQ=SEQ+1
		set DQQRY(SEQ)="([LN]PCIDSTAT=0)!([LN]PCIDSTAT="""")",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("LN,CIF") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",2)="WC2|"_"Loan Group"_"|VIN2|"_VIN2.get()
		set VBNRINFO("PROMPTS",3)="WC2|"_"Product"_"|VIN3|"_VIN3.get()
		set VBNRINFO("PROMPTS",4)="WC2|"_"Tax Year End Balance"_"|VIN4|"_VIN4.get()
		set VBNRINFO("PROMPTS",5)="WC2|"_"Prior Tax Year Int Collected"_"|VIN5|"_VIN5.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Tax Year-End Loan Summary"
		set VBNRINFO("PGM")="R01S214"
		set VBNRINFO("RID")="SCA160"
		set VBNRINFO("TABLES")="LN,CIF"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,LN]CLS"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,LN]GRP"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,LN]TYPE"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,LN]CID"

		set VBNRINFO("DOC",1)="/*"
		set VBNRINFO("DOC",2)="  ---------- Revision History --------------------------------------------"
		set VBNRINFO("DOC",3)="    12/28/05 - SWARNALP - 17293"
		set VBNRINFO("DOC",4)="              Converted to PSL  "
		set VBNRINFO("DOC",5)="  ------------------------------------------------------------------------"
		set VBNRINFO("DOC",6)="*/"

		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VHIT = 0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:4 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:5 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"LN.CID,LN.CLS,LN.GRP,LN.TYPE,LN.IPTY,LN.ADBPTY,LN."
	set VSELECT=VSELECT_"BALPTYE,LN.PENPTY,CIF.NAM"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"LN,CIF",VWHERE,"LN.CLS,LN.GRP,LN.TYPE,LN.CID","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
	type Boolean VSKIPREC = 0
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VFPOST quit:(VFMQ ! VSKIPREC)  set VHIT = 1
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT('VHIT)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc2,vovc3,vovc4,vovc1
	set vovc2="",vovc3="",vovc4="",vovc1=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc2,vc2,vovc3,vc3,vovc4,vc4,vovc1,vc1
	set vovc2=vc2,vovc3=vc3,vovc4=vc4,vovc1=vc1
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9
	set vc1=V.piece($C(9),1)			// LN.CID
	set vc2=V.piece($C(9),2)			// LN.CLS
	set vc3=V.piece($C(9),3)			// LN.GRP
	set vc4=V.piece($C(9),4)			// LN.TYPE
	set vc5=V.piece($C(9),5)			// LN.IPTY
	set vc6=V.piece($C(9),6)			// LN.ADBPTY
	set vc7=V.piece($C(9),7)			// LN.BALPTYE
	set vc8=V.piece($C(9),8)			// LN.PENPTY
	set vc9=V.piece($C(9),9)			// CIF.NAM
	quit

	// User-defined pre/post-processor code

VFPOST	// FETCH post-processor

	type public String vc1
 type public Number TAX

 type Number CID,CTR,DA
 type String BIL,COLS,TRTYPE
 
 set CID=vc1
 
 set TAX=0
 
 type ResultSet rs1 = Db.select("PE01,PE02,PE03,PE04,PE05,PE06,PE07,PE08,PE09,PE10,PE11,PE12,PE13,PE14,PE15,PE16,PE17,PE18,PE19,PE20","LNBIL0","CID=:CID")
 if rs1.next() set COLS=rs1.getRow("|")
 
 for CTR=1:1 set BIL=COLS.piece("|",CTR) quit:BIL=""  do {
 	if BIL.extract()="T" do {
 		set DA=BIL.piece("#",2)
 		type ResultSet rs2 = Db.select("TRTYPE,REMPY","TRTYPE","CID=:DA")
 		while rs2.next() do {
 			set TRTYPE=rs2.getCol("TRTYPE")
 			type RecordLNTRS lntrs=Db.getRecord("LNTRS","TRTYPE=:TRTYPE",1)
 			if lntrs.getMode() do {
 				if lntrs.etyp=1 set TAX=TAX+rs2.getCol("REMPY")
 				}
 			}
 		}
 	}
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0
	if 'VFMQ do VSUM
	if 'VFMQ do VRSUM
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(3)=1,vskp(4)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(4).get() do VDTL4 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(4)
	type Public String vc2,vovc2,vc3,vovc3,vc4,vovc4,vc1,vovc1
	type Number vb1,vb2,vb3,vb4
	set (vb1,vb2,vb3,vb4)=0
	if vb1!(vovc2'=vc2) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1,VH0=1
	if vb2!(vovc3'=vc3) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1,VH0=1
	if vb3!(+vovc4'=+vc4) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1,VH0=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(4) set vs(4)=1 do VSUM4 quit:VFMQ  do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do VSUM3 quit:VFMQ  do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT(),TAX,vc6,vc7,vc5,vc8
	type Public String VSTATS

	set VT(4)=VT(4)+1
	set VT(4,1,1)=VT(4,1,1)+TAX			// @TOT(<<TAX>>)
	set VT(4,2,1)=VT(4,2,1)+vc6			// @TOT([LN]ADBPTY)
	set VT(4,3,1)=VT(4,3,1)+vc7			// @TOT([LN]BALPTYE)
	set VT(4,4,1)=VT(4,4,1)+vc5			// @TOT([LN]IPTY)
	set VT(4,5,1)=VT(4,5,1)+vc8			// @TOT([LN]PENPTY)
	quit

VSUM3	// Summary
	type public String %TIM,I,IOSL,STGRP,STTYPE,TAX,V,VFMQ,VL,VLC,VO,VOFFLG,VT(),VX(),vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	if 'VT(3) quit
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="                                                  "_"------------    ------------       ------------"
	set VL=VL_$J("",101-VL.length())_"------------    ------------"
	do VOM
	set VL="GROUP "
	set VL=VL_$J("",6-VL.length())_$E(STGRP,1,4)
	set VL=VL_$J("",11-VL.length())_"TOTALS:"
	set V=VT(3,4,1)					// @TOT([LN]IPTY,)
	set VL=VL_$J("",50-VL.length())_$J(V,12,2)
	set V=VT(3,1,1)					// @TOT(<<TAX>>,)
	set VL=VL_$J("",66-VL.length())_$J(V,12,2)
	set V=VT(3,2,1)					// @TOT([LN]ADBPTY,)
	set VL=VL_$J("",85-VL.length())_$J(V,12,2)
	set V=VT(3,3,1)					// @TOT([LN]BALPTYE,)
	set VL=VL_$J("",101-VL.length())_$J(V,12,2)
	set V=VT(3,5,1)					// @TOT([LN]PENPTY,)
	set VL=VL_$J("",117-VL.length())_$J(V,12,2)
	do VOM
	set VL="" do VOM
	quit

VDTL4	// Detail
	type public String %TIM,IOSL,STGRP,STTYPE,TAX,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VRG,VT(),vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	if VLC+1>IOSL do VHDG0 quit:VFMQ

	set VL=$J(vc1,12)
	set VL=VL_$J("",16-VL.length())_$E(vc9,1,30)
	set VL=VL_$J("",47-VL.length())_$J(vc5,15,2)
	set VL=VL_$J("",66-VL.length())_$J(TAX,12,2)
	set VL=VL_$J("",79-VL.length())_$J(vc6,18,2)
	set VL=VL_$J("",98-VL.length())_$J(vc7,15,2)
	set VL=VL_$J("",114-VL.length())_$J(vc8,15,2)
	do VOM
	quit

VSUM4	// Summary
	type public String %TIM,I,IOSL,STGRP,STTYPE,TAX,V,VFMQ,VL,VLC,VO,VOFFLG,VT(),VX(),vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	if 'VT(4) quit
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="                                                  "_"------------    ------------       ------------"
	set VL=VL_$J("",101-VL.length())_"------------    ------------"
	do VOM
	set VL="TYPE "
	set VL=VL_$J("",5-VL.length())_$J(STTYPE,4)
	set VL=VL_$J("",10-VL.length())_"TOTALS:"
	set V=VT(4,4,1)					// @TOT([LN]IPTY,)
	set VL=VL_$J("",50-VL.length())_$J(V,12,2)
	set V=VT(4,1,1)					// @TOT(<<TAX>>,)
	set VL=VL_$J("",66-VL.length())_$J(V,12,2)
	set V=VT(4,2,1)					// @TOT([LN]ADBPTY,)
	set VL=VL_$J("",85-VL.length())_$J(V,12,2)
	set V=VT(4,3,1)					// @TOT([LN]BALPTYE,)
	set VL=VL_$J("",101-VL.length())_$J(V,12,2)
	set V=VT(4,5,1)					// @TOT([LN]PENPTY,)
	set VL=VL_$J("",117-VL.length())_$J(V,12,2)
	do VOM
	set VL="" do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,CONAM,RID,RN,STGRP,STTYPE,TAX,VL,vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+8,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E(CONAM,1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  (SCA160)"
	set VL=VL_$J("",102-VL.length())_"System:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$E($J(VPN,3),1,3)
	do VOM
	set VL="" do VOM
	set VL="GROUP "
	set V=vc3,VO=V set V=$E(V,1,4) do VP1 quit:VFMQ!verror.get()
	set VL=VL_$J("",6-VL.length())_V		// [SYSDEV,LN]GRP
	set VL=VL_$J("",12-VL.length())_"TYPE "
	set V=vc4,VO=V set V=$J(V,3) do VP2 quit:VFMQ!verror.get()
	set VL=VL_$J("",18-VL.length())_V		// [SYSDEV,LN]TYPE
	do VOM
	set VL="" do VOM
	set VL="     "_"ACCOUNT    BORROWER                              INTEREST    TAX REMITTED    AVERAGE BALANCE     Y/E BALANCE         PENALTY"
	do VOM
	set VL="===================================================================================================================================="
	do VOM
	set VL="" do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VRSUM	// Report Summary
	type Public Number IOSL,verror,VFMQ,vh,VLC,VT(),VX()
	type Public String %TIM,STGRP,STTYPE,TAX,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate
	type Number I
	type String V,VL

	set VL=""
	if 'vh(0) do VHDG0 quit:VFMQ
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="                                                  "_"------------    ------------       ------------    ------------    ------------"
	do VOM
	set VL="REPORT TOTALS:"
	set V=0						// @TOT([LN]IPTY,0)
	for I=0:1:4 set V=V+VT(I,4,1)
	set VL=VL_$J("",50-VL.length())_$J(V,12,2)
	set V=0						// @TOT(<<TAX>>,0)
	for I=0:1:4 set V=V+VT(I,1,1)
	set VL=VL_$J("",66-VL.length())_$J(V,12,2)
	set V=0						// @TOT([LN]ADBPTY,0)
	for I=0:1:4 set V=V+VT(I,2,1)
	set VL=VL_$J("",85-VL.length())_$J(V,12,2)
	set V=0						// @TOT([LN]BALPTYE,0)
	for I=0:1:4 set V=V+VT(I,3,1)
	set VL=VL_$J("",101-VL.length())_$J(V,12,2)
	set V=0						// @TOT([LN]PENPTY,0)
	for I=0:1:4 set V=V+VT(I,5,1)
	set VL=VL_$J("",117-VL.length())_$J(V,12,2)
	do VOM
	quit

VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column post-processor - [SYSDEV,LN]GRP

	type public String vc3
 type public String STGRP

 set STGRP = vc3
	quit

VP2	// Column post-processor - [SYSDEV,LN]TYPE

	type public String vc4
 type public Number STTYPE

 set STTYPE = vc4
	quit
