R01S442	// SCA485 - Outgoing Foreign Payment Report
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:50 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN2="ALL"
	type String VIN3="ALL"
	type String VIN4="ALL"
	type String VIN5="ALL"
	type String VIN6="ALL"

	set RID="SCA485"
	set RN="Outgoing Foreign Payment Report"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN2")="|255||[EFTPAY]CID|[EFTPAY]CID:DISTINCT:NOVAL||D EXT^DBSQRY||T|Account Number|||||"
	set %TAB("VIN3")="|255||[EFTPAY]CRCDCID|[CRCD]:QU ""[CRCD]CO=<<%CO>>"":NOVAL||D EXT^DBSQRY||T|Client Account Currency|||||"
	set %TAB("VIN4")="|255||[EFTPAY]CRCD|[CRCD]:QU ""[CRCD]CO=<<%CO>>"":NOVAL||D EXT^DBSQRY||T|Payment Currency|||||"
	set %TAB("VIN5")="|255||[EFTPAY]CCODE|[UTBLCC]:NOVAL||D EXT^DBSQRY||T|Margin-Rate Code|||||"
	set %TAB("VIN6")="|255||[EFTPAY]STATUS|[STBLESTAT]:NOVAL||D EXT^DBSQRY||T|Status|||||"

	set %READ="IO/REQ,VIN2#0,VIN3#0,VIN4#0,VIN5#0,VIN6#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String VIN2,VIN3,VIN4,VIN5,VIN6
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,CONAM,ERI,RID,RN,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vovc5,vovc6,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA485",RN="Outgoing Foreign Payment Report"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA485","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[EFTPAY]REFNO#1#34\[EFTPAY]CID#2#12,[EFTPAY]SEQ#17#8,[EFTPAY]CCODE#28#8,[EFTPAY]STATUS#37#2,[EFTPAY]ANTRATE#41#12,[EFTPAY]ANTAMT#55#12,[EFTPAY]RATE#69#12,[EFTPAY]ACTAMT#83#12,[EFTPAY]AMOUNT#97#12"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[EFTPAY]EFTTYPE=""NDPO""",SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[EFTPAY]CID "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[EFTPAY]CRCDCID "_VIN3,SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[EFTPAY]CRCD "_VIN4,SEQ=SEQ+1
		if VIN5.get()="" set VIN5="ALL"
		if VIN5'="ALL" set DQQRY(SEQ)="[EFTPAY]CCODE "_VIN5,SEQ=SEQ+1
		if VIN6.get()="" set VIN6="ALL"
		if VIN6'="ALL" set DQQRY(SEQ)="[EFTPAY]STATUS "_VIN6,SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("EFTPAY,ACN") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",2)="WC2|"_"Account Number"_"|VIN2|"_VIN2.get()
		set VBNRINFO("PROMPTS",3)="WC2|"_"Client Account Currency"_"|VIN3|"_VIN3.get()
		set VBNRINFO("PROMPTS",4)="WC2|"_"Payment Currency"_"|VIN4|"_VIN4.get()
		set VBNRINFO("PROMPTS",5)="WC2|"_"Margin-Rate Code"_"|VIN5|"_VIN5.get()
		set VBNRINFO("PROMPTS",6)="WC2|"_"Status"_"|VIN6|"_VIN6.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Outgoing Foreign Payment Report"
		set VBNRINFO("PGM")="R01S442"
		set VBNRINFO("RID")="SCA485"
		set VBNRINFO("TABLES")="EFTPAY,ACN"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,EFTPAY]EFTTYPE"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,EFTPAY]CRCDCID"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,EFTPAY]CRCD"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,EFTPAY]SETCRCD"
		set VBNRINFO("ORDERBY",5)="[SYSDEV,EFTPAY]CID"
		set VBNRINFO("ORDERBY",6)="[SYSDEV,EFTPAY]SEQ"


		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:6 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:3 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"EFTPAY.EFTTYPE,EFTPAY.CRCDCID,EFTPAY.CRCD,EFTPAY.S"
	set VSELECT=VSELECT_"ETCRCD,EFTPAY.CID,EFTPAY.SEQ,EFTPAY.ANTAMT,EFTPAY."
	set VSELECT=VSELECT_"ACTAMT,EFTPAY.REFNO,EFTPAY.CCODE,EFTPAY.STATUS,EFT"
	set VSELECT=VSELECT_"PAY.ANTRATE,EFTPAY.RATE,EFTPAY.AMOUNT,EFTPAY.MSGFP"
	set VSELECT=VSELECT_"1"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"EFTPAY,ACN",VWHERE,"EFTPAY.EFTTYPE,EFTPAY.CRCDCID,EFTPAY.CRCD,EFTPAY.SETCRCD,EFTPAY.CID,EFTPAY.SEQ","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2,vovc3,vovc4,vovc5,vovc6
	set vovc1="",vovc2="",vovc3="",vovc4="",vovc5="",vovc6=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2,vovc3,vc3,vovc4,vc4,vovc5,vc5,vovc6,vc6
	set vovc1=vc1,vovc2=vc2,vovc3=vc3,vovc4=vc4,vovc5=vc5,vovc6=vc6
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15
	set vc1=V.piece($C(9),1)			// EFTPAY.EFTTYPE
	set vc2=V.piece($C(9),2)			// EFTPAY.CRCDCID
	set vc3=V.piece($C(9),3)			// EFTPAY.CRCD
	set vc4=V.piece($C(9),4)			// EFTPAY.SETCRCD
	set vc5=V.piece($C(9),5)			// EFTPAY.CID
	set vc6=V.piece($C(9),6)			// EFTPAY.SEQ
	set vc7=V.piece($C(9),7)			// EFTPAY.ANTAMT
	set vc8=V.piece($C(9),8)			// EFTPAY.ACTAMT
	set vc9=V.piece($C(9),9)			// EFTPAY.REFNO
	set vc10=V.piece($C(9),10)			// EFTPAY.CCODE
	set vc11=V.piece($C(9),11)			// EFTPAY.STATUS
	set vc12=V.piece($C(9),12)			// EFTPAY.ANTRATE
	set vc13=V.piece($C(9),13)			// EFTPAY.RATE
	set vc14=V.piece($C(9),14)			// EFTPAY.AMOUNT
	set vc15=V.piece($C(9),15)			// EFTPAY.MSGFP1
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0,vs(5)=0,vs(6)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(3)=1,vskp(4)=1,vskp(5)=1,vskp(6)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(6).get() do VDTL6 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(6)
	type Public String vc1,vovc1,vc2,vovc2,vc3,vovc3,vc4,vovc4,vc5,vovc5,vc6,vovc6
	type Number vb1,vb2,vb3,vb4,vb5,vb6
	set (vb1,vb2,vb3,vb4,vb5,vb6)=0
	if vb1!(vovc1'=vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1,vb5=1,vb6=1,VH0=1
	if vb2!(vovc2'=vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1,vb5=1,vb6=1,VH0=1
	if vb3!(vovc3'=vc3) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1,vb5=1,vb6=1,VH0=1
	if vb4!(vovc4'=vc4) set vs(5)=0,vh(5)=0,VD(4)=0,vb5=1,vb6=1,VH0=1
	if vb5!(+vovc5'=+vc5) set vs(6)=0,vh(6)=0,VD(5)=0,vb6=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(6) set vs(6)=1 do stat^DBSRWUTL(6)
	if 'vs(5) set vs(5)=1 do stat^DBSRWUTL(5)
	if 'vs(4) set vs(4)=1 do VSUM4 quit:VFMQ  do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do VSUM3 quit:VFMQ  do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT(),vc8,vc14,vc7
	type Public String VSTATS

	set VT(6)=VT(6)+1
	set VT(6,1,1)=VT(6,1,1)+vc8			// @TOT([EFTPAY]ACTAMT)
	set VT(6,2,1)=VT(6,2,1)+vc14			// @TOT([EFTPAY]AMOUNT)
	set VT(6,3,1)=VT(6,3,1)+vc7			// @TOT([EFTPAY]ANTAMT)
	quit

VSUM3	// Summary
	type public String %TIM,ERI,I,IOSL,V,VFMQ,VL,VLC,VO,VOFFLG,VPN,VT(),VX(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vovc6,vrundate,vsysdate

	if 'VT(3) quit
	if VLC+1>IOSL do VHDG0 quit:VFMQ

	set VL="                                                      "_"-------------"
	set VL=VL_$J("",82-VL.length())_"------------"
	do VOM
	set VL="                                     "_"Currency Total:"
	set V=VT(3,3,1)					// @TOT([EFTPAY]ANTAMT,)
	set VL=VL_$J("",54-VL.length())_$J($FN(V,",",2),12)
	set V=VT(3,1,1)					// @TOT([EFTPAY]ACTAMT,)
	set VL=VL_$J("",82-VL.length())_$J($FN(V,",",2),12)
	do VOM
	quit

VSUM4	// Summary
	type public String %TIM,ERI,I,IOSL,V,VFMQ,VL,VLC,VO,VOFFLG,VPN,VT(),VX(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vovc6,vrundate,vsysdate

	if 'VT(4) quit
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="                                                      "_"------------"
	set VL=VL_$J("",82-VL.length())_"------------"
	set VL=VL_$J("",96-VL.length())_"------------"
	do VOM
	set VL="                                  "_"Currency Subtotal:"
	set V=VT(4,3,1)					// @TOT([EFTPAY]ANTAMT,)
	set VL=VL_$J("",54-VL.length())_$J($FN(V,",",2),12)
	set V=VT(4,1,1)					// @TOT([EFTPAY]ACTAMT,)
	set VL=VL_$J("",82-VL.length())_$J($FN(V,",",2),12)
	set V=VT(4,2,1)					// @TOT([EFTPAY]AMOUNT,)
	set VL=VL_$J("",96-VL.length())_$J($FN(V,",",2),12)
	do VOM
	set VL="" do VOM
	quit

VDTL6	// Detail
	type public String %TIM,ERI,IOSL,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vovc6,vrundate,vsysdate

	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL=$E(vc9,1,34)
	do VOM
	set VL=" "_$J(vc5,12)
	set VL=VL_$J("",14-VL.length())_$J(vc6,10)
	set VL=VL_$J("",27-VL.length())_$E(vc10,1,8)
	set VL=VL_$J("",36-VL.length())_$E(vc11,1,2)
	set VL=VL_$J("",40-VL.length())_$J(vc12,12,6)
	set VL=VL_$J("",53-VL.length())_$J($FN(vc7,",",2),13)
	set VL=VL_$J("",68-VL.length())_$J(vc13,12,6)
	set VL=VL_$J("",81-VL.length())_$J($FN(vc8,",",2),13)
	set VL=VL_$J("",95-VL.length())_$J($FN(vc14,",",2),13)
	do VP1 quit:VFMQ!verror.get()  set V=$E(ERI,1,18)
	set VL=VL_$J("",110-VL.length())_V
	do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,CONAM,ERI,RID,RN,VL,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vovc5,vovc6,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+9,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL="  "_$E(CONAM,1,20)
	set VL=VL_$J("",97-VL.length())_"Run Date:"
	set VL=VL_$J("",107-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",121-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL="  "_$E(RN,1,30)
	set VL=VL_$J("",34-VL.length())_$E(RID,1,12)
	set VL=VL_$J("",94-VL.length())_"System Date:"
	set VL=VL_$J("",107-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",121-VL.length())_"Page:"
	set VL=VL_$J("",127-VL.length())_$J(VPN,3)
	do VOM
	set VL="" do VOM
	set VL="  "_"Payment Type:"
	set VL=VL_$J("",16-VL.length())_$E(vc1,1,12)
	set VL=VL_$J("",38-VL.length())_"Account's Currency:"
	set VL=VL_$J("",58-VL.length())_$E(vc2,1,3)
	set VL=VL_$J("",73-VL.length())_"Payment Currency:"
	set VL=VL_$J("",91-VL.length())_$E(vc3,1,3)
	do VOM
	set VL="" do VOM
	set VL="Transaction Reference"
	do VOM
	set VL="      "_"Account              Margin        Anticipated   Anticipated        Actual        Actual       Payment        Euro-Related"
	do VOM
	set VL="       "_"Number   Sequence   Code     St      Rate       Amount               Rate        Amount       Amount          Information"
	do VOM
	set VL="=================================================================================================================================="
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - Variable: ERI

	type public String vc15
	// Converted to PSL by CNV70RW
	type Public String EFTPAY,ERI,MSGFP1

	set ERI=vc15
	if '(ERI["/OCMT/") set ERI=""
	quit
