R01S223	// SCA170 - Loan Year-End Notices
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:45 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type public String TJD
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN2="ALL"
	type String VIN3="ALL"
	type String VIN4="ALL"
	type String VIN5=">0"

	set RID="SCA170"
	set RN="Loan Year-End Notices"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	do VPREBQ quit:VFMQ.get()			// Pre-processor (before query)

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN2")="|255||[LN]GRP|[STBLGRP]:QU ""[STBLGRP]CLS=""""L"""""":NOVAL||D EXT^DBSQRY||T|Loan Group|||||"
	set %TAB("VIN3")="|255||[LN]TYPE|[PRODDFTL]:NOVAL||D EXT^DBSQRY||T|Product|||||"
	set %TAB("VIN4")="|255||[LN]BALPTYE|||D EXT^DBSQRY||T|Y/E Principal Balance|||||"
	set %TAB("VIN5")="|255||[LN]IPTY|||D EXT^DBSQRY||T|Tax Year Int Collected|||||"

	set %READ="IO/REQ,VIN2#0,VIN3#0,VIN4#0,VIN5#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String TJD
	type public String VIN2,VIN3,VIN4,VIN5
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,ACN,CAD(),CONAM,FRM,RID,RN,VD(),VH(),VL,VLOF,VRF(),VSTATS(),YEAR,YN,vCOL,vHDG,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA170",RN="Loan Year-End Notices"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA170","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=99999999			// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=81")
		write $$CLEARXY^%TRMVT
		}

	do INIT^%ZM()


	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[LN]CLS=""L""",SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[LN]GRP "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[LN]TYPE "_VIN3,SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[LN]BALPTYE "_VIN4,SEQ=SEQ+1
		if VIN5.get()="" set VIN5="ALL"
		if VIN5'="ALL" set DQQRY(SEQ)="[LN]IPTY "_VIN5,SEQ=SEQ+1
		set DQQRY(SEQ)="(([CIF]MF=1)!([CIF]MF=""""))&(([LN]MF=1)!([LN]MF=""""))",SEQ=SEQ+1
		set DQQRY(SEQ)="([LN]PCIDSTAT=0)!([LN]PCIDSTAT="""")",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("LN,COL,CIF") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}


	// Alignment pattern
	if cuvar.alcount,IOTYP'="TRM",'VRWOPT("NOALIGN").get() do ^DBSRWALN(RID,IO,cuvar.alcount)

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:4 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:0 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	if VDISTKEY.get()="" do { quit:VFMQ		// Report Pre-processor (after query)
		do VPREAQ
		if VFMQ set vh(0)=1 do VEXIT(0)
		}

	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"LN.CLS,LN.GRP,LN.TYPE,LN.CID,LN.BALPTYE,LN.IPTY,LN"
	set VSELECT=VSELECT_".PENPTY,LN.RPYTX,LN.TITLE1,CIF.ACN"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"LN,COL,CIF",VWHERE,"LN.CLS,LN.GRP,LN.TYPE,LN.CID","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2,vovc3,vovc4
	set vovc1="",vovc2="",vovc3="",vovc4=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2,vovc3,vc3,vovc4,vc4
	set vovc1=vc1,vovc2=vc2,vovc3=vc3,vovc4=vc4
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10
	set vc1=V.piece($C(9),1)			// LN.CLS
	set vc2=V.piece($C(9),2)			// LN.GRP
	set vc3=V.piece($C(9),3)			// LN.TYPE
	set vc4=V.piece($C(9),4)			// LN.CID
	set vc5=V.piece($C(9),5)			// LN.BALPTYE
	set vc6=V.piece($C(9),6)			// LN.IPTY
	set vc7=V.piece($C(9),7)			// LN.PENPTY
	set vc8=V.piece($C(9),8)			// LN.RPYTX
	set vc9=V.piece($C(9),9)			// LN.TITLE1
	set vc10=V.piece($C(9),10)			// CIF.ACN
	quit

	// User-defined pre/post-processor code

VPREAQ	// Pre-processor (after query)

 type public Date TJD
 type public Number FRM,VD(),VH(),YEAR,YN

 set TJD=%SystemDate
 set YEAR=%SystemDate.toString("YEAR")-1
 set (FRM,VH(0))=1
 
 if FRM use 0 set YN=$$YN^DBSMBAR("",$$^MSG(6409),1) if 'YN set VD(4)=0 quit
 if FRM set FRM=0 quit
	quit

VPREBQ	// Pre-processor (before query)

 //Incoming=TJD

	quit

	// Pre/post-processor library code

VLIB1	// User library - CUSAD
	type public String vc10
	/*
	---- Revision History -----------------------------------------------
	
	08/22/05 - SWARNALATHAP - CR 16781
	Converted to PSL
	
	---------------------------------------------------------------------
	*/
	// Format mailing address
	type Public String CAD()
	type Public Number ACN
	type Number I,N
	type String CNTRY
	type RecordCIF cif = Db.getRecord("CIF","ACN=:ACN")
	type RecordCUVAR cuvar = Db.getRecord("CUVAR")
	
	if cuvar.catsup,cif.mcntry = cuvar.cntry set CNTRY = ""
	else  set CNTRY = "  "_cif.mcntry
	set N = 0
	if cif.mad1 set N = N + 1,CAD(N) = cif.mad1.extract(1,30)
	if cif.mad2 set N = N + 1,CAD(N) = cif.mad2.extract(1,30)
	if cif.mad3 set N = N + 1,CAD(N) = cif.mad3.extract(1,30)
	if cif.mad4 set N = N + 1,CAD(N) = cif.mad4.extract(1,30)
	set N = N + 1
	set CAD(N) = cif.mcity.extract(1,15)_", "_cif.mstate_CNTRY_"  "_cif.mzip
	
	for I = N+1:1:5 set CAD(I) = ""
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(4)=1		// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(4).get() do VDTL4 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(4)
	type Public String vc1,vovc1,vc2,vovc2,vc3,vovc3,vc4,vovc4
	type Number vb1,vb2,vb3,vb4
	set (vb1,vb2,vb3,vb4)=0
	if vb1!(vovc1'=vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1
	if vb2!(vovc2'=vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1
	if vb3!(+vovc3'=+vc3) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(4) set vs(4)=1 do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT()
	type Public String VSTATS

	set VT(4)=VT(4)+1
	quit

VDTL4	// Detail
	type public String ACN,CAD(),FRM,IOSL,TJD,V,VD(),VFMQ,VH(),VL,VLC,VO,VOFFLG,VRG,VT(),YEAR,YN,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4

	if VLC+22>IOSL do VHDG0 quit:VFMQ

	set VL="                         "_"YEAR-END STATEMENT "_YEAR
	do VOM
	set VL="" do VOM
	set VL="                         "_"ACCOUNT NUMBER:"
	set V=vc4,VO=V do VP1 quit:VFMQ!verror.get()  set V=$J(V,12)
	set VL=VL_$J("",41-VL.length())_V		// [SYSDEV,LN]CID
	do VOM
	set VL="" do VOM
	set VL="    "_"PRINCIPAL"
	set VL=VL_$J("",23-VL.length())_"INTEREST"
	set VL=VL_$J("",41-VL.length())_"LATE CHARGES"
	set VL=VL_$J("",58-VL.length())_"REAL ESTATE TAXES"
	do VOM
	set VL="     "_"BALANCE"
	set VL=VL_$J("",25-VL.length())_"PAID"
	set VL=VL_$J("",45-VL.length())_"PAID"
	set VL=VL_$J("",62-VL.length())_"REMITTED"
	do VOM
	set VL="" do VOM
	set VL="$"
	set VL=VL_$J("",2-VL.length())_$J($FN(vc5,",",2),12)
	set VL=VL_$J("",20-VL.length())_"$"
	set VL=VL_$J("",22-VL.length())_$J($FN(vc6,",",2),10)
	set VL=VL_$J("",40-VL.length())_"$"
	set VL=VL_$J("",42-VL.length())_$J($FN(vc7,",",2),11)
	set VL=VL_$J("",61-VL.length())_"$"
	set VL=VL_$J("",63-VL.length())_$J($FN(vc8,",",2),10)
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set V=vc9,VO=V do VP2 quit:VFMQ!verror.get()  set V=$E(V,1,25) set VL=V
	do VOM
	set VL=$E(CAD(1),1,25)
	do VOM
	set VL=$E(CAD(2),1,25)
	do VOM
	set VL=$E(CAD(3),1,25)
	do VOM
	set VL=$E(CAD(4),1,25)
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	quit

VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,ACN,CAD(),CONAM,FRM,RID,RN,TJD,VD(),VH(),VL,YEAR,YN,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+0,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit

VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	use IO if 'VLC,'vcrt set $Y=1
	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - [SYSDEV,LN]CID

	type public String vc4
 type public String V,VL
 
 type Number CID
 
 set CID=vc4
 if CID="" set (V,VL)=""
	quit

VP2	// Column pre-processor - [SYSDEV,LN]TITLE1

	type public String vc10
 type public Number ACN 

 set ACN=vc10
	do VLIB1	// User library - CUSAD
	quit
