R01S590	// SCA662 - IRS Form W-8BEN Request Report
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:53 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type public String TJD
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type Date VIN2=TJD.get()
	type Date VIN3=TJD.get()
	type String VIN4="ALL"

	set RID="SCA662"
	set RN="IRS Form W-8BEN Request Report"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN2")="|10||[CIFD]TJD|[CIFD]TJD:DISTINCT:NOVAL||||D|From Date|||||"
	set %TAB("VIN3")="|10||[CIFD]TJD|[CIFD]TJD:DISTINCT:NOVAL||||D|To Date|||||"
	set %TAB("VIN4")="|255||[CIFD]ACN|[CIF]:NOVAL||D EXT^DBSQRY||T|Customer Number|||||"

	set %READ="IO/REQ,VIN2#1,VIN3#1,VIN4#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type Boolean VHIT
	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String TJD
	type public Date VIN2,VIN3
	type public String VIN4
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,CONAM,FMD1,FMD10,FMD11,FMD12,FMD2,FMD3,FMD4,FMD5,FMD6,FMD7,FMD8,FMD9,RID,RN,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA662",RN="IRS Form W-8BEN Request Report"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA662","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()


	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[CIF]NR=1",SEQ=SEQ+1
		set DQQRY(SEQ)="[CIFD]TJD '< "_$$addqts^DBSRWUTL(VIN2),SEQ=SEQ+1
		set DQQRY(SEQ)="[CIFD]TJD '> "_$$addqts^DBSRWUTL(VIN3),SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[CIFD]ACN "_VIN4,SEQ=SEQ+1
		set DQQRY(SEQ)="[CIFD]DI=""CIF.MCNTRY"" OR [CIFD]DI=""CIF.PCNTRY""",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("CIFD,CIF") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",2)="WC1|"_"From Date"_"|VIN2|"_$$DAT^%ZM(VIN2.get(),%MSKD)
		set VBNRINFO("PROMPTS",3)="WC1|"_"To Date"_"|VIN3|"_$$DAT^%ZM(VIN3.get(),%MSKD)
		set VBNRINFO("PROMPTS",4)="WC2|"_"Customer Number"_"|VIN4|"_VIN4.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="IRS Form W-8BEN Request Report"
		set VBNRINFO("PGM")="R01S590"
		set VBNRINFO("RID")="SCA662"
		set VBNRINFO("TABLES")="CIFD,CIF"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,CIF]CC"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,CIFD]TJD"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,CIFD]ACN"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,CIFD]SEQ"

		set VBNRINFO("DOC",1)="/*"
		set VBNRINFO("DOC",2)="   ---------- Revision History --------------------------------------------"
		set VBNRINFO("DOC",3)="    12/22/05 - SWARNALP - 17293"
		set VBNRINFO("DOC",4)="              Converted to PSL"
		set VBNRINFO("DOC",5)="   ------------------------------------------------------------------------ "
		set VBNRINFO("DOC",6)="*/"

		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VHIT = 0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:4 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:0 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"CIFD.TCMT,CIF.CC,CIFD.TJD,CIFD.ACN,CIFD.SEQ,CIF.TA"
	set VSELECT=VSELECT_"XID,CIFD.UID,CIF.LNM,CIFD.HTIME,CIFD.TLO"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"CIFD,CIF",VWHERE,"CIF.CC,CIFD.TJD,CIFD.ACN,CIFD.SEQ","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
	type Boolean VSKIPREC = 0
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VFPOST quit:(VFMQ ! VSKIPREC)  set VHIT = 1
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT('VHIT)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc2,vovc3,vovc4,vovc5
	set vovc2="",vovc3="",vovc4="",vovc5=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc2,vc2,vovc3,vc3,vovc4,vc4,vovc5,vc5
	set vovc2=vc2,vovc3=vc3,vovc4=vc4,vovc5=vc5
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10
	set vc1=V.piece($C(9),1)			// CIFD.TCMT
	set vc2=V.piece($C(9),2)			// CIF.CC
	set vc3=V.piece($C(9),3)			// CIFD.TJD
	set vc4=V.piece($C(9),4)			// CIFD.ACN
	set vc5=V.piece($C(9),5)			// CIFD.SEQ
	set vc6=V.piece($C(9),6)			// CIF.TAXID
	set vc7=V.piece($C(9),7)			// CIFD.UID
	set vc8=V.piece($C(9),8)			// CIF.LNM
	set vc9=V.piece($C(9),9)			// CIFD.HTIME
	set vc10=V.piece($C(9),10)			// CIFD.TLO
	quit

	// User-defined pre/post-processor code

VFPOST	// FETCH post-processor

	type public String vc1
 type public Number ER
 type public String FMD1,FMD2,FMD3,FMD4,FMD5,FMD6,FMD7,FMD8,FMD9,FMD10,FMD11,FMD12

 type String FMD,TCMT

 set ER=0
 set (FMD1,FMD2,FMD3,FMD4,FMD5,FMD6,FMD7,FMD8,FMD9,FMD10,FMD11,FMD12)=""
 set TCMT=vc1
 if TCMT'["[" set FMD2=TCMT.extract(1,70) quit
 set TCMT="["_TCMT.piece("[",2)
 set FMD=TCMT.piece(":",1)_":  "
 do TCMT^DEPDI
 set FMD2=FMD_TCMT.piece(":",1),FMD3=$$^MSG(8331),FMD12=$$^MSG(3526)
 set FMD4=TCMT.piece(":",2),FMD8=TCMT.piece(":",3)
	quit

VRPOST	// Report post-processor

 type public Number ER

 set ER=0
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			do VRPOST			// Report Post-Processor
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1,vskp(4)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(4).get() do VDTL4 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(4)
	type Public String vc2,vovc2,vc3,vovc3,vc4,vovc4,vc5,vovc5
	type Number vb1,vb2,vb3,vb4
	set (vb1,vb2,vb3,vb4)=0
	if vb1!(+vovc2'=+vc2) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1,VH0=1
	if vb2!(vovc3'=vc3) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1
	if vb3!(+vovc4'=+vc4) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(4) set vs(4)=1 do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT()
	type Public String VSTATS

	set VT(4)=VT(4)+1
	quit

VDTL4	// Detail
	type public String %TIM,ER,FMD1,FMD10,FMD11,FMD12,FMD2,FMD3,FMD4,FMD5,FMD6,FMD7,FMD8,FMD9,IOSL,TJD,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VRG,VT(),vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate

	if VLC+9>IOSL do VHDG0 quit:VFMQ

	set VL=$J(vc4,12)
	set VL=VL_$J("",19-VL.length())_$E(vc6,1,20)
	set VL=VL_$J("",46-VL.length())_$J($$DAT^%ZM(vc3),10)
	set VL=VL_$J("",63-VL.length())_$E(vc7,1,12)
	set VL=VL_$J("",86-VL.length())_$E(FMD2,1,40)
	do VOM
	set VL="                   "_$E(vc8,1,20)
	set VL=VL_$J("",46-VL.length())_$J($$TIM^%ZM(vc9),8)
	set VL=VL_$J("",63-VL.length())_$E(vc10,1,12)
	set VL=VL_$J("",86-VL.length())_$E(FMD3,1,5)
	set VL=VL_$J("",92-VL.length())_$E(FMD4,1,34)
	do VOM
	set VL="                                                                                            "_$E(FMD5,1,34)
	if 'VL.translate(" ").isNull() do VOM
	set VL="                                                                                            "_$E(FMD6,1,34)
	if 'VL.translate(" ").isNull() do VOM
	set VL="                                                                                            "_$E(FMD7,1,34)
	if 'VL.translate(" ").isNull() do VOM
	set VL="                                                                                      "_$E(FMD12,1,5)
	set VL=VL_$J("",92-VL.length())_$E(FMD8,1,34)
	if 'VL.translate(" ").isNull() do VOM
	set VL="                                                                                            "_$E(FMD9,1,34)
	if 'VL.translate(" ").isNull() do VOM
	set VL="                                                                                            "_$E(FMD10,1,34)
	if 'VL.translate(" ").isNull() do VOM
	set VL="                                                                                            "_$E(FMD11,1,34)
	if 'VL.translate(" ").isNull() do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,CONAM,FMD1,FMD10,FMD11,FMD12,FMD2,FMD3,FMD4,FMD5,FMD6,FMD7,FMD8,FMD9,RID,RN,TJD,VL,vc1,vc10,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+8,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E(CONAM,1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  ("_RID_")"
	set VL=VL_$J("",99-VL.length())_"Effective:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$E($J(VPN,3),1,3)
	do VOM
	set VL="" do VOM
	set VL="  "_"Cost Center: "
	set VL=VL_$J("",16-VL.length())_$J(vc2,5)
	do VOM
	set VL="" do VOM
	set VL="  "_"CIF Number       Tax ID                     Date             User"
	do VOM
	set VL="                   "_"Last Name                  Time             Location               Description"
	do VOM
	set VL="===================================================================================================================================="
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors
