R01S089	// SCA017 - Closed Account Report
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:41 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN1="ALL"
	type String VIN2="ALL"
	type String VIN3="ALL"
	type String VIN4="ALL"
	type String VIN5="ALL"
	type String VIN6="ALL"

	set RID="SCA017"
	set RN="Closed Account Report"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN1")="|255||[DTJCL]TJD|[DTJCL]TJD:DISTINCT:NOVAL||D EXT^DBSQRY||T|System Processing Date|||||"
	set %TAB("VIN2")="|255||[DTJCL]CLS|[DTJCL]CLS:DISTINCT:NOVAL||D EXT^DBSQRY||T|Product Class|||||"
	set %TAB("VIN3")="|255||[DTJCL]GRP|[DTJCL]GRP:DISTINCT:NOVAL||D EXT^DBSQRY||T|Product Group|||||"
	set %TAB("VIN4")="|255||[DTJCL]TYP|[DTJCL]TYP:DISTINCT:NOVAL||D EXT^DBSQRY||T|Product Type|||||"
	set %TAB("VIN5")="|255||[DTJCL]CID|[ACN]:NOVAL||D EXT^DBSQRY||T|Account Number|||||"
	set %TAB("VIN6")="|255||[ACN]CC|[UTBLCCNTR]:NOVAL||D EXT^DBSQRY||T|Cost Center|||||"

	set %READ="IO/REQ,VIN1#0,VIN2#0,VIN3#0,VIN4#0,VIN5#0,VIN6#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type Boolean VHIT
	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String VIN1,VIN2,VIN3,VIN4,VIN5,VIN6
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,ANLMBO,AREF,ATM,CID,CLRDES,CLS,CONAM,ETC,GRP,HVAR,RID,RN,TAMT,TLO,TYP,UID,VARB,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc11,vc12,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc7,vovc8,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA017",RN="Closed Account Report"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA017","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[DTJCL]TJD#1#10,[ACN]CC#12#6,[ACN]BOO#19#6,[DTJCL]CID#26#12,[ACN]LNM#40#20\[ACN]CLR#1#2"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		if VIN1.get()="" set VIN1="ALL"
		if VIN1'="ALL" set DQQRY(SEQ)="[DTJCL]TJD "_VIN1,SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[DTJCL]CLS "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[DTJCL]GRP "_VIN3,SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[DTJCL]TYP "_VIN4,SEQ=SEQ+1
		if VIN5.get()="" set VIN5="ALL"
		if VIN5'="ALL" set DQQRY(SEQ)="[DTJCL]CID "_VIN5,SEQ=SEQ+1
		if VIN6.get()="" set VIN6="ALL"
		if VIN6'="ALL" set DQQRY(SEQ)="[ACN]CC "_VIN6,SEQ=SEQ+1
		set DQQRY(SEQ)="([ACN]PCIDSTAT=0)!([ACN]PCIDSTAT="""")",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("DTJCL,ACN") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",1)="WC2|"_"System Processing Date"_"|VIN1|"_VIN1.get()
		set VBNRINFO("PROMPTS",2)="WC2|"_"Product Class"_"|VIN2|"_VIN2.get()
		set VBNRINFO("PROMPTS",3)="WC2|"_"Product Group"_"|VIN3|"_VIN3.get()
		set VBNRINFO("PROMPTS",4)="WC2|"_"Product Type"_"|VIN4|"_VIN4.get()
		set VBNRINFO("PROMPTS",5)="WC2|"_"Account Number"_"|VIN5|"_VIN5.get()
		set VBNRINFO("PROMPTS",6)="WC2|"_"Cost Center"_"|VIN6|"_VIN6.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Closed Account Report"
		set VBNRINFO("PGM")="R01S089"
		set VBNRINFO("RID")="SCA017"
		set VBNRINFO("TABLES")="DTJCL,ACN"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,DTJCL]CLS"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,DTJCL]GRP"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,DTJCL]TYP"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,DTJCL]TJD"
		set VBNRINFO("ORDERBY",5)="[SYSDEV,DTJCL]CID"

		set VBNRINFO("DOC",1)="The Closed Account Report (SCA017) provides information about accounts that"
		set VBNRINFO("DOC",2)="were closed during an institution-defined period of time.  This report"
		set VBNRINFO("DOC",3)="provides a daily listing of closed accounts, and includes data regarding"
		set VBNRINFO("DOC",4)="the final transaction for each."
		set VBNRINFO("DOC",5)=""
		set VBNRINFO("DOC",6)="Refer to the Close/Re-Open Account Utilities Reference Manual for detailed"
		set VBNRINFO("DOC",7)="information about the SCA017 report."
		set VBNRINFO("DOC",8)=""

		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VHIT = 0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:5 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:2 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	if VDISTKEY.get()="" do { quit:VFMQ		// Report Pre-processor (after query)
		do VPREAQ
		if VFMQ set vh(0)=1 do VEXIT(0)
		}

	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"DTJCL.CID,DTJCL.GRP,DTJCL.CLS,ACN.ACN,ACN.IRN,ACN."
	set VSELECT=VSELECT_"MDT,DTJCL.TYP,DTJCL.TJD,ACN.CC,ACN.BOO,ACN.LNM,ACN"
	set VSELECT=VSELECT_".CLR"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"DTJCL,ACN",VWHERE,"DTJCL.CLS,DTJCL.GRP,DTJCL.TYP,DTJCL.TJD,DTJCL.CID","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
	type Boolean VSKIPREC = 0
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VFPOST quit:(VFMQ ! VSKIPREC)  set VHIT = 1
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT('VHIT)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc3,vovc2,vovc7,vovc8,vovc1
	set vovc3="",vovc2="",vovc7="",vovc8="",vovc1=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc3,vc3,vovc2,vc2,vovc7,vc7,vovc8,vc8,vovc1,vc1
	set vovc3=vc3,vovc2=vc2,vovc7=vc7,vovc8=vc8,vovc1=vc1
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12
	set vc1=V.piece($C(9),1)			// DTJCL.CID
	set vc2=V.piece($C(9),2)			// DTJCL.GRP
	set vc3=V.piece($C(9),3)			// DTJCL.CLS
	set vc4=V.piece($C(9),4)			// ACN.ACN
	set vc5=V.piece($C(9),5)			// ACN.IRN
	set vc6=V.piece($C(9),6)			// ACN.MDT
	set vc7=V.piece($C(9),7)			// DTJCL.TYP
	set vc8=V.piece($C(9),8)			// DTJCL.TJD
	set vc9=V.piece($C(9),9)			// ACN.CC
	set vc10=V.piece($C(9),10)			// ACN.BOO
	set vc11=V.piece($C(9),11)			// ACN.LNM
	set vc12=V.piece($C(9),12)			// ACN.CLR
	quit

	// User-defined pre/post-processor code

VFPOST	// FETCH post-processor

	type public String vc1,vc2,vc3,vc4,vc5,vc6
	type Public String ANLMBO,AREF,ATM,CID,CLS,ETC,GRP,HVAR,TAMT,TLO,UID,VARB
	type String ACN
	type Number FOUND

	set FOUND=0
	set (ETC,TAMT,TLO,VARB,UID)=""	
	set CID=vc1
	set GRP=vc2
	set CLS=vc3

	type DbSet ds=Db.selectDbSet("HIST","CID=:CID","TSEQ DESC")
	while ds.next() do { quit:FOUND

		//Make sure that transaction was a principal adjustment

		type RecordHIST hist=ds.getRecord("HIST")
		
		//Last monetary = closeout/payoff
		if $P(hist.tamt,"#",2)!((hist.tcmt["STAT")&($P(hist.tcmt,":",3)=4)) do { quit 
			set FOUND=1 
			set TAMT=hist.tamt
			set UID=hist.uid
			set TLO=hist.tlo
			if $P(hist.tcmt,":",3)=4 set ETC=$$^MSG(8324)
			else  set ETC=hist.etc
			}
		}

	//Determine if ATM Use Code
	set ATM=""
	set ACN=vc4
	if ACN'="" do {
		type RecordCIF cif=Db.getRecord("CIF","ACN=:ACN")
		set ATM=cif.atm
		}
	
	if "/SAV/DM/ACN/MTG/CM/"[("/"_GRP_"/") do {
		set VARB=$$^SCARND(vc5,0,CID)
		set HVAR=$$^MSG(6285)
		}

	if GRP="CD" do {
		set VARB=vc6
		set HVAR=$$^MSG(3860)
		set VARB=$$DAT^%ZM(VARB)
		}

	if CLS="D" do {
		type RecordDEP dep=Db.getRecord("DEP","CID=:CID")
		set ANLMBO=dep.anlmbo
		set AREF=dep.aref
		if GRP="ESC" do {
                	set VARB=AREF
	                set HVAR=$$^MSG(6288)
        	        }

		if "/DDA/WASH/"[("/"_GRP_"/") do {
	                set VARB=ANLMBO
        	        set HVAR=$$^MSG(6286)
                	}

		}

	if GRP="RC" do {
		type RecordLN ln=Db.getRecord("LN","CID=:CID")
		set VARB=ln.crlmt
		set HVAR=$$^MSG(3871)
		}

	if GRP="PART" do {
		set HVAR=$$^MSG(6287)
		}

	if VARB=0 set VARB=""


	quit

VPREAQ	// Pre-processor (after query)

 type Public String CLRDES,HVAR
 set (HVAR,CLRDES)=""
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0,vs(5)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1,vskp(4)=1,vskp(5)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(5).get() do VDTL5 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(5)
	type Public String vc3,vovc3,vc2,vovc2,vc7,vovc7,vc8,vovc8,vc1,vovc1
	type Number vb1,vb2,vb3,vb4,vb5
	set (vb1,vb2,vb3,vb4,vb5)=0
	if vb1!(vovc3'=vc3) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1,vb5=1
	if vb2!(vovc2'=vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1,vb5=1
	if vb3!(vovc7'=vc7) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1,vb5=1,VH0=1
	if vb4!(vovc8'=vc8) set vs(5)=0,vh(5)=0,VD(4)=0,vb5=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(5) set vs(5)=1 do VSUM5 quit:VFMQ  do stat^DBSRWUTL(5)
	if 'vs(4) set vs(4)=1 do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT(),TAMT
	type Public String VSTATS

	set VT(5)=VT(5)+1
	set VT(5,1,1)=VT(5,1,1)+TAMT			// @TOT(<<TAMT>>)
	quit

VDTL5	// Detail
	type public String %TIM,ANLMBO,AREF,ATM,CID,CLRDES,CLS,ETC,GRP,HVAR,IOSL,TAMT,TLO,TYP,UID,V,VARB,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc11,vc12,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc7,vovc8,vrundate,vsysdate

	if VLC+3>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	set VL=$J($$DAT^%ZM(vc8),10)
	set VL=VL_$J("",11-VL.length())_$$CTR^%ZM(vc9,6)
	set VL=VL_$J("",18-VL.length())_$$CTR^%ZM(vc10,6)
	set VL=VL_$J("",25-VL.length())_$J(vc1,12)
	set VL=VL_$J("",39-VL.length())_$E(vc11,1,20)
	set VL=VL_$J("",60-VL.length())_$E(ETC,1,8)
	set VL=VL_$J("",69-VL.length())_$J($FN(TAMT,",",2),12)
	set VL=VL_$J("",84-VL.length())_$E(ATM,1,1)
	set VL=VL_$J("",88-VL.length())_$E(UID,1,8)
	set VL=VL_$J("",98-VL.length())_$E(TLO,1,11)
	set VL=VL_$J("",110-VL.length())_$E(VARB,1,20)
	do VOM
	set VL=$J(vc12,2)
	set V=$$VP1(vc3,vc12)				// @TBL([ACN]CLR)
	set VL=VL_$J("",3-VL.length())_$E(V,1,40)
	do VOM
	quit

VSUM5	// Summary
	type public String %TIM,ANLMBO,AREF,ATM,CID,CLRDES,CLS,ETC,GRP,HVAR,I,IOSL,TAMT,TLO,TYP,UID,V,VARB,VFMQ,VL,VLC,VO,VOFFLG,VPN,VT(),VX(),vc1,vc10,vc11,vc12,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc7,vovc8,vrundate,vsysdate

	if 'VT(5) quit
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	set VL="" do VOM
	set VL="Number of Accounts:"
	set V=VT(5)					// @CNT(,N,4)
	set VL=VL_$J("",20-VL.length())_$J(V,4)
	set VL=VL_$J("",55-VL.length())_"Total Amount:"
	set V=VT(5,1,1)					// @TOT(<<TAMT>>,)
	set VL=VL_$J("",69-VL.length())_$J($FN(V,",",2),12)
	do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,ANLMBO,AREF,ATM,CID,CLRDES,CLS,CONAM,ETC,GRP,HVAR,RID,RN,TAMT,TLO,TYP,UID,VARB,VL,vc1,vc10,vc11,vc12,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc7,vovc8,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+9,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E($G(CONAM),1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  ("_RID_")"
	set VL=VL_$J("",102-VL.length())_"System:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$J(VPN,3)
	do VOM
	set VL="" do VOM
	set VL="Class "_vc3_"   Group "_vc2_"   Type "_vc7
	do VOM
	set VL="" do VOM
	set VL="            "_"Cost                                                Tran              ATM"
	do VOM
	set VL="  "_"Date     Center Branch    Account #  Account Title            Code       Amount Code   User     Location"
	set VL=VL_$J("",110-VL.length())_$E(HVAR,1,20)
	do VOM
	set VL="  "_"Closeout Reason Code/Description"
	do VOM
	set VL="===================================================================================================================================="
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1(KEY1,KEY2)	// @TBL([ACN]CLR)

	if KEY1="" quit ""
	if KEY2="" quit ""
	type Public Cache %CACHE()
	type RecordUTBLCLOSER tbl=%CACHE("UTBLCLOSER").getRecord("UTBLCLOSER","CLS=:KEY1,CLR=:KEY2")
	quit tbl.DES
