R01S144	// SCA076 - Neg Collect Bal Accts with Debit Act
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:43 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type public String TJD
	type String CLS
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type Date VIN1=%SystemDate
	type String VIN2="ALL"
	type String VIN3="ALL"
	type String VIN4="ALL"
	type String VIN5="ALL"

	set RID="SCA076"
	set RN="Neg Collect Bal Accts with Debit Act"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	do VPREBQ quit:VFMQ.get()			// Pre-processor (before query)

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN1")="|10||[DTJ]TJD|[DTJ]TJD:DISTINCT:NOVAL||||D|System Processing Date is equal to|||||"
	set %TAB("VIN2")="|255||[DEP]GRP|[STBLGRP]:QU ""[STBLGRP]CLS=""""D"""""":NOVAL||D EXT^DBSQRY||T|Product Group|||||"
	set %TAB("VIN3")="|255||[DEP]TYPE|[PRODCTL]:NOVAL||D EXT^DBSQRY||T|Product Type|||||"
	set %TAB("VIN4")="|255||[DTJ]CID|[ACN]:NOVAL||D EXT^DBSQRY||T|Account Number|||||"
	set %TAB("VIN5")="|255||[DEP]BOO|[UTBLBRCD]:NOVAL||D EXT^DBSQRY||T|Branch of Ownership|||||"

	set %READ="IO/REQ,VIN1#1,VIN2#0,VIN3#0,VIN4#0,VIN5#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=37
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String TJD
	type public String CLS
	type public Date VIN1
	type public String VIN2,VIN3,VIN4,VIN5
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %AVB,%TIM,BDESC,BOO,CONAM,HPH,RID,RN,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA076",RN="Neg Collect Bal Accts with Debit Act"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA076","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[DEP]CID#1#12,[DEP]GRP#15#4,[DEP]TYPE#21#4,[DEP]TITLE1#27#30,[DEP]ODT#59#10,[DEP]BALCOL#89#12,[DEP]BALAVL#103#12,[DEP]BAL#117#12"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[DTJ]TJD = "_$$addqts^DBSRWUTL(VIN1),SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[DEP]GRP "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[DEP]TYPE "_VIN3,SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[DTJ]CID "_VIN4,SEQ=SEQ+1
		if VIN5.get()="" set VIN5="ALL"
		if VIN5'="ALL" set DQQRY(SEQ)="[DEP]BOO "_VIN5,SEQ=SEQ+1
		set DQQRY(SEQ)="[DEP]BALCOL<0",SEQ=SEQ+1
		set DQQRY(SEQ)="[DTJ]ITC1=0",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("DTJ,DEP,CIF") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",1)="WC1|"_"System Processing Date is equal to"_"|VIN1|"_$$DAT^%ZM(VIN1.get(),%MSKD)
		set VBNRINFO("PROMPTS",2)="WC2|"_"Product Group"_"|VIN2|"_VIN2.get()
		set VBNRINFO("PROMPTS",3)="WC2|"_"Product Type"_"|VIN3|"_VIN3.get()
		set VBNRINFO("PROMPTS",4)="WC2|"_"Account Number"_"|VIN4|"_VIN4.get()
		set VBNRINFO("PROMPTS",5)="WC2|"_"Branch of Ownership"_"|VIN5|"_VIN5.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Neg Collect Bal Accts with Debit Act"
		set VBNRINFO("PGM")="R01S144"
		set VBNRINFO("RID")="SCA076"
		set VBNRINFO("TABLES")="DTJ,DEP,CIF"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,DTJ]TJD"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,DEP]BOO"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,DTJ]DATETIME"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,DTJ]CID"
		set VBNRINFO("ORDERBY",5)="[SYSDEV,DTJ]TSEQ"


		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:5 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:1 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"DTJ.TJD,DEP.BOO,DTJ.DATETIME,DTJ.CID,DTJ.TSEQ,DEP."
	set VSELECT=VSELECT_"CID,DEP.GRP,DEP.TYPE,DEP.TITLE1,DEP.ODT,DEP.BALCOL"
	set VSELECT=VSELECT_",DEP.BALAVL,DEP.BAL,DTJ.ETC,DTJ.TAMT,DTJ.TSO,DTJ.T"
	set VSELECT=VSELECT_"CMT,CIF.HPH,CIF.BPH"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"DTJ,DEP,CIF",VWHERE,"DTJ.TJD,DEP.BOO,DTJ.DATETIME,DTJ.CID,DTJ.TSEQ","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2,vovc3,vovc4,vovc5
	set vovc1="",vovc2="",vovc3="",vovc4="",vovc5=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2,vovc3,vc3,vovc4,vc4,vovc5,vc5
	set vovc1=vc1,vovc2=vc2,vovc3=vc3,vovc4=vc4,vovc5=vc5
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19
	set vc1=V.piece($C(9),1)			// DTJ.TJD
	set vc2=V.piece($C(9),2)			// DEP.BOO
	set vc3=V.piece($C(9),3)			// DTJ.DATETIME
	set vc4=V.piece($C(9),4)			// DTJ.CID
	set vc5=V.piece($C(9),5)			// DTJ.TSEQ
	set vc6=V.piece($C(9),6)			// DEP.CID
	set vc7=V.piece($C(9),7)			// DEP.GRP
	set vc8=V.piece($C(9),8)			// DEP.TYPE
	set vc9=V.piece($C(9),9)			// DEP.TITLE1
	set vc10=V.piece($C(9),10)			// DEP.ODT
	set vc11=V.piece($C(9),11)			// DEP.BALCOL
	set vc12=V.piece($C(9),12)			// DEP.BALAVL
	set vc13=V.piece($C(9),13)			// DEP.BAL
	set vc14=V.piece($C(9),14)			// DTJ.ETC
	set vc15=V.piece($C(9),15)			// DTJ.TAMT
	set vc16=V.piece($C(9),16)			// DTJ.TSO
	set vc17=V.piece($C(9),17)			// DTJ.TCMT
	set vc18=V.piece($C(9),18)			// CIF.HPH
	set vc19=V.piece($C(9),19)			// CIF.BPH
	quit

	// User-defined pre/post-processor code

VPREBQ	// Pre-processor (before query)

 //Incoming=TJD
 type Public Number TJD
 type Public String CLS  
 if '$D(TJD) do { 
 type RecordCUVAR cuvar
 set cuvar =Db.getRecord("CUVAR")
 set TJD=cuvar.tjd
	}

 set CLS="D"
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0,vs(5)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1,vskp(4)=1,vskp(5)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(3).get() do VDTL3 quit:VFMQ
	do VHDG5 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(5)
	type Public String vc1,vovc1,vc2,vovc2,vc3,vovc3,vc4,vovc4,vc5,vovc5
	type Number vb1,vb2,vb3,vb4,vb5
	set (vb1,vb2,vb3,vb4,vb5)=0
	if vb1!(vovc1'=vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1,vb5=1,VH0=1
	if vb2!(+vovc2'=+vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1,vb5=1,VH0=1
	if vb3!(+vovc3'=+vc3) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1,vb5=1,VH0=1
	if vb4!(+vovc4'=+vc4) set vs(5)=0,vh(5)=0,VD(4)=0,vb5=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(5) set vs(5)=1 do VSUM5 quit:VFMQ  do stat^DBSRWUTL(5)
	if 'vs(4) set vs(4)=1 do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT(),vc15
	type Public String VSTATS

	set VT(5)=VT(5)+1
	set VT(5,1,1)=VT(5,1,1)+vc15			// @TOT([DTJ]TAMT)
	quit

VDTL3	// Detail
	type public String %AVB,%TIM,BDESC,BOO,CLS,HPH,IOSL,TJD,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VRG,VT(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate

	quit:VD(3)  set VD(3)=1				// Print flag
	if VLC+1>IOSL do VHDG0 quit:VFMQ

	set VL=$J(vc6,12)
	set VL=VL_$J("",14-VL.length())_$E(vc7,1,4)
	set VL=VL_$J("",19-VL.length())_$J(vc8,5)
	set VL=VL_$J("",26-VL.length())_$E(vc9,1,30)
	set VL=VL_$J("",58-VL.length())_$J($$DAT^%ZM(vc10),10)
	do VP1 quit:VFMQ!verror.get()  set V=$J($FN(%AVB,",",2),12)
	set VL=VL_$J("",74-VL.length())_V
	set VL=VL_$J("",88-VL.length())_$J($FN(vc11,",",2),12)
	set VL=VL_$J("",102-VL.length())_$J($FN(vc12,",",2),12)
	set VL=VL_$J("",116-VL.length())_$J($FN(vc13,",",2),12)
	do VOM
	quit

VHDG5	// Group Header
	type public String %AVB,%MSKD,%TIM,BDESC,BOO,CLS,CONAM,ER,HPH,IOSL,RID,RN,TJD,V,VFMQ,VL,VLC,VNEWHDR,VO,VOFFLG,VPN,VRG,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vcrt,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate

	quit:vh(5)  set vh(5)=1				// Print flag
	if VLC+1>IOSL do VHDG0 quit:VFMQ

	set VL="                "_$E(vc14,1,8)
	set VL=VL_$J("",29-VL.length())_$J(vc15,12)
	set VL=VL_$J("",43-VL.length())_$E(vc16,1,5)
	set VL=VL_$J("",51-VL.length())_$E(vc17,1,30)
	do VOM
	quit

VSUM5	// Summary
	type public String %AVB,%TIM,BDESC,BOO,CLS,HPH,I,IOSL,TJD,V,VFMQ,VL,VLC,VO,VOFFLG,VT(),VX(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate

	if 'VT(5) quit
	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL="                "_"----------------------------------------------------"
	do VOM
	set VL="                "_"Total Debit"
	set V=VT(5,1,1)					// @TOT([DTJ]TAMT,)
	set VL=VL_$J("",29-VL.length())_$J($FN(V,",",2),12)
	set VL=VL_$J("",61-VL.length())_"Home Phone #"
	set V=vc18,VO=V do VP2 quit:VFMQ!verror.get()  set V=$E(V,1,12)
	set VL=VL_$J("",75-VL.length())_V
	do VOM
	set VL="" do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %AVB,%MSKD,%TIM,BDESC,BOO,CLS,CONAM,HPH,RID,RN,TJD,VL,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vovc5,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+9,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E(CONAM,1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  (SCA076)"
	set VL=VL_$J("",97-VL.length())_"System Date:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$E($J(VPN,3),1,3)
	do VOM
	set VL="" do VOM
	set VL="Branch: "
	set VL=VL_$J("",8-VL.length())_$E(vc2,1,6)
	do VP3 quit:VFMQ!verror.get()  set V=$E(BDESC,1,20)
	set VL=VL_$J("",16-VL.length())_V
	do VOM
	set VL="" do VOM
	set VL="                                                                     "_"------------------------- Balance -----------------------------"
	do VOM
	set VL="   "_"Account # Group  Type  Account Title                  Date Opened Last 30 Days' Avg     Collected     Available        Ledger"
	do VOM
	set VL="                "_"Tran Code         Amount   Source  Transaction Comment"
	do VOM
	set VL="===================================================================================================================================="
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - Variable: %AVB

	type public String vc4
 /* 03/17/05 - JERUCHIMC - 13430
    Made changes for DBI2.  Specifically,
    modify parameters for call to INIT^UAVB
    including defining an ACN record.
 */
 
 type Public String %AVB,UAVB()
 type Public Boolean ER
 type Number CID=vc4
 type RecordACN acn
 set acn=Db.getRecord("ACN","CID")
 set ER=0 do INIT^UAVB(.acn,CID,%SystemDate-30,%SystemDate,"")
 if ER set %AVB="ERR" quit
 set %AVB=+UAVB(1)
	quit

VP2	// Column pre-processor - [SYSDEV,CIF]HPH

	type public String vc18,vc19
 type Public String V
 if vc18="" set V=vc19 

	quit

VP3	// Column pre-processor - Variable: BDESC

	type public String vc2
 // 03/17/05 - JERUCHIMC - 13430
 // DBI2
 //-----------------------------
 
 type Public String BDESC
 type Public Number ZBRCD
 set ZBRCD=vc2
 set ZBRCD=+ZBRCD
 type RecordUTBLBRCD utblbrcd
 set utblbrcd = Db.getRecord("UTBLBRCD","BRCD=:ZBRCD")
 set BDESC=utblbrcd.desc
	quit
