R01S162	// SCA096 - Standard W-9 Forms
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:44 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type public String CLOS,FORM
	type String YEAR
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN2="ALL"
	type String VIN3="ALL"
	type Number YEAR

	set RID="SCA096"
	set RN="Standard W-9 Forms"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	do VPREBQ quit:VFMQ.get()			// Pre-processor (before query)

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN2")="|255||[CIF]ACN|[CIF]ACN:DISTINCT:NOVAL||D EXT^DBSQRY||T|Customer Number|||||"
	set %TAB("VIN3")="|255||[CIF]W9STAT|[UTBLW9ST]:NOVAL||D EXT^DBSQRY||T|W-9 Status|||||"
	set %TAB("YEAR")="|4|||||S CLOS=$$^SCAJD(""1/1/""_X)||N|Tax Year|||||"

	set %READ="IO/REQ,YEAR#1,VIN2#0,VIN3#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String CLOS,FORM
	type public String YEAR
	type public Number YEAR
	type public String VIN2,VIN3
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,ACN,AD(),CAD(),CONAM,MF,NAME,RID,RN,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc2,vc3,vc4,vc5,vovc1,vovc2,vovc3,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA096",RN="Standard W-9 Forms"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA096","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=99999999			// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()


	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[CIF]ACN "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[CIF]W9STAT "_VIN3,SEQ=SEQ+1
		set DQQRY(SEQ)="[ACN]STAT'=4 or ([ACN]STAT=4 and [ACN]DTC '< <<CLOS>>)",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("ACN,CIF") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}


	// Alignment pattern
	if cuvar.alcount,IOTYP'="TRM",'VRWOPT("NOALIGN").get() do ^DBSRWALN(RID,IO,cuvar.alcount)

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:3 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:0 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	if VDISTKEY.get()="" do { quit:VFMQ		// Report Pre-processor (after query)
		do VPREAQ
		if VFMQ set vh(0)=1 do VEXIT(0)
		}

	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT="CIF.MF,CIF.ACN,ACN.CID,CIF.TAXID,CIF.NAM"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"ACN,CIF",VWHERE,"CIF.MF,CIF.ACN,ACN.CID","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2,vovc3
	set vovc1="",vovc2="",vovc3=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2,vovc3,vc3
	set vovc1=vc1,vovc2=vc2,vovc3=vc3
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5
	set vc1=V.piece($C(9),1)			// CIF.MF
	set vc2=V.piece($C(9),2)			// CIF.ACN
	set vc3=V.piece($C(9),3)			// ACN.CID
	set vc4=V.piece($C(9),4)			// CIF.TAXID
	set vc5=V.piece($C(9),5)			// CIF.NAM
	quit

	// User-defined pre/post-processor code

VPREAQ	// Pre-processor (after query)

	do VLIB1	// User library - INSTAD
	quit

VPREBQ	// Pre-processor (before query)

 //Incoming=CLOS,FORM
 
 type Public Number FORM
 type Public String YEAR  
 
 set YEAR = %SystemDate.toString("YEAR")
 
 set FORM=0
	quit

	// Pre/post-processor library code

VLIB2	// User library - CUSAD
	type public String vc2
	/*
	---- Revision History -----------------------------------------------
	
	08/22/05 - SWARNALATHAP - CR 16781
	Converted to PSL
	
	---------------------------------------------------------------------
	*/
	// Format mailing address
	type Public String CAD()
	type Public Number ACN
	type Number I,N
	type String CNTRY
	type RecordCIF cif = Db.getRecord("CIF","ACN=:ACN")
	type RecordCUVAR cuvar = Db.getRecord("CUVAR")
	
	if cuvar.catsup,cif.mcntry = cuvar.cntry set CNTRY = ""
	else  set CNTRY = "  "_cif.mcntry
	set N = 0
	if cif.mad1 set N = N + 1,CAD(N) = cif.mad1.extract(1,30)
	if cif.mad2 set N = N + 1,CAD(N) = cif.mad2.extract(1,30)
	if cif.mad3 set N = N + 1,CAD(N) = cif.mad3.extract(1,30)
	if cif.mad4 set N = N + 1,CAD(N) = cif.mad4.extract(1,30)
	set N = N + 1
	set CAD(N) = cif.mcity.extract(1,15)_", "_cif.mstate_CNTRY_"  "_cif.mzip
	
	for I = N+1:1:5 set CAD(I) = ""
	quit

VLIB1	// User library - INSTAD
	/*
	---- Revision History------------------------------------------------
	08/22/05 - SWARNALATHAP - CR 16781
	Converted to PSL
	---------------------------------------------------------------------
	*/
	type Public String AD(),NAME
	
	type Number I,J
	type String TEMP,CCITY
	
	type RecordCUVAR cuvar = Db.getRecord("CUVAR")
	set NAME = cuvar.cname
	
	set AD(1) = cuvar.cad1
	set AD(2) = cuvar.cad2
	set AD(3) = cuvar.cad3
	set CCITY = cuvar.ccity
	if CCITY.length() > 15 set CCITY = CCITY.extract(1,15)
	
	set AD(4) = CCITY_", "_cuvar.cstate_"  "_cuvar.czip
	set AD(5) = cuvar.telephone
	set AD(6) = cuvar.poinst
	
	for I=6:-1:2 do {
		set TEMP = $$RTB^%ZFUNC(AD(I-1))
		if TEMP = "" for J=I-1:1:5 set AD(J) = AD(J+1),AD(J+1) = ""
	}
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0
	if 'VFMQ do VSUM
	if 'VFMQ do VRSUM
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(1).get() do VDTL1 quit:VFMQ
	if 'vskp(2).get() do VDTL2 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(3)
	type Public String vc1,vovc1,vc2,vovc2,vc3,vovc3
	type Number vb1,vb2,vb3
	set (vb1,vb2,vb3)=0
	if vb1!(+vovc1'=+vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1
	if vb2!(+vovc2'=+vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT()
	type Public String VSTATS

	set VT(3)=VT(3)+1
	quit

VDTL1	// Detail
	type public String ACN,AD(),CAD(),CLOS,FORM,IOSL,MF,NAME,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VRG,VT(),YEAR,vc1,vc2,vc3,vc4,vc5,verror,vh(),vovc1,vovc2,vovc3

	quit:VD(1)  set VD(1)=1				// Print flag
	if VLC+33>IOSL do VHDG0 quit:VFMQ

	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="MAIL FLAG "_vc1_" MAIL FLAG "_vc1_" MAIL FLAG "_vc1
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	quit

VDTL2	// Detail
	type public String ACN,AD(),CAD(),CLOS,FORM,IOSL,MF,NAME,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VRG,VT(),YEAR,vc1,vc2,vc3,vc4,vc5,verror,vh(),vovc1,vovc2,vovc3

	quit:VD(2)  set VD(2)=1				// Print flag
	if VLC+35>IOSL do VHDG0 quit:VFMQ

	set VL="    "_$E(NAME,1,34)
	do VOM
	set VL="    "_$E(AD(1),1,34)
	do VOM
	set VL="    "_$E(AD(2),1,34)
	do VOM
	set VL="    "_$E(AD(3),1,34)
	do VOM
	set VL="    "_$E(AD(4),1,34)
	do VOM
	set VL="" do VOM
	set VL="                         "_$J(vc2,12)
	set V=vc4,VO=V do VP1 quit:VFMQ!verror.get()  set V=$E(V,1,17)
	set VL=VL_$J("",55-VL.length())_V		// [SYSDEV,CIF]TAXID
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set V=vc5,VO=V do VP2 quit:VFMQ!verror.get()  set V=$E(V,1,34) set VL="    "_V
	do VOM
	set VL="    "_$E(CAD(1),1,34)
	do VOM
	set VL="    "_$E(CAD(2),1,34)
	do VOM
	set VL="    "_$E(CAD(3),1,34)
	do VOM
	set VL="    "_$E(CAD(4),1,34)
	do VOM
	set VL="    "_$E(CAD(5),1,34)
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	quit

VRSUM	// Report Summary
	type Public Number IOSL,verror,VFMQ,vh,VLC,VT(),VX()
	type Public String ACN,AD(),CAD(),CLOS,FORM,MF,NAME,vovc1,vovc2,vovc3
	type Number I
	type String V,VL

	set VL=""
	if 'vh(0) do VHDG0 quit:VFMQ
	if VLC+8>IOSL do VHDG0 quit:VFMQ

	set VL="    "_$E(NAME,1,40)
	do VOM
	set VL="    "_$E(AD(1),1,40)
	do VOM
	set VL="    "_$E(AD(2),1,40)
	do VOM
	set VL="    "_$E(AD(3),1,40)
	do VOM
	set VL="    "_$E(AD(4),1,40)
	do VOM
	set VL="" do VOM
	set VL="    "_"Run Date:  "
	do VP3 quit:VFMQ!verror.get()  set V=$J($$DAT^%ZM(CLOS),10)
	set VL=VL_$J("",25-VL.length())_V
	do VOM
	set VL="    "_"Total forms produced:  "
	set VL=VL_$J("",27-VL.length())_$J(FORM,8)
	do VOM
	quit

VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,ACN,AD(),CAD(),CLOS,CONAM,FORM,MF,NAME,RID,RN,VL,YEAR,vc1,vc2,vc3,vc4,vc5,vovc1,vovc2,vovc3,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+0,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit

VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	use IO if 'VLC,'vcrt set $Y=1
	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - [SYSDEV,CIF]TAXID

 type Public String V

 type Number I
 type String Z
  
 set Z = "" 
 for I = 1:1:V.length() if V.extract(I) '= "-" set Z = Z_V.extract(I)_" " 
 set V = Z

	quit

VP2	// Column pre-processor - [SYSDEV,CIF]NAM

	type public String vc2
 type Public Number ACN,FORM

 set FORM = FORM+1

 set ACN=vc2 
 
	do VLIB2	// User library - CUSAD
	quit

VP3	// Column pre-processor - Variable: CLOS

 type Public String CLOS,YEAR

 set CLOS=$$^SCAJD("1/1/"_YEAR)
	quit
