R01S048	// FORMRECTYPES - Form Layouts by Record Type
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:40 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN1="ALL"

	set RID="FORMRECTYPES"
	set RN="Form Layouts by Record Type"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN1")="|255||[UTBLFORM]RECTYPE|[UTBLFORM0]FID:NOVAL||D EXT^DBSQRY||T|Record Type|||||"

	set %READ="IO/REQ,VIN1#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String VIN1
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,ACCKEYS,CONAM,DESC,FID,FIDESC,FIELD,FROM,LENGTH,RID,RN,TO,TYPE,VL,VLOF,VRF(),VSTATS(),ZDIREF,vCOL,vHDG,vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="FORMRECTYPES",RN="Form Layouts by Record Type"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","FORMRECTYPES","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=81")
		write $$CLEARXY^%TRMVT
		}

	do INIT^%ZM()

	set vCOL="[UTBLFORM]CSEQ#1#3"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		if VIN1.get()="" set VIN1="ALL"
		if VIN1'="ALL" set DQQRY(SEQ)="[UTBLFORM]RECTYPE "_VIN1,SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("UTBLFORM") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",1)="WC2|"_"Record Type"_"|VIN1|"_VIN1.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Form Layouts by Record Type"
		set VBNRINFO("PGM")="R01S048"
		set VBNRINFO("RID")="FORMRECTYPES"
		set VBNRINFO("TABLES")="UTBLFORM"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,UTBLFORM]""FORM"""
		set VBNRINFO("ORDERBY",2)="[SYSDEV,UTBLFORM]RECTYPE"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,UTBLFORM]CSEQ"


		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:3 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:0 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"UTBLFORM.RECTYPE,UTBLFORM.CSEQ,UTBLFORM.DI,UTBLFOR"
	set VSELECT=VSELECT_"M.DES,UTBLFORM.LEN,UTBLFORM.DECPRE,UTBLFORM.TYP,UT"
	set VSELECT=VSELECT_"BLFORM.VARNAM,UTBLFORM.DIREF"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"UTBLFORM",VWHERE,"UTBLFORM.RECTYPE,UTBLFORM.CSEQ","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2
	set vovc1="",vovc2=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2
	set vovc1=vc1,vovc2=vc2
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9
	set vc1=V.piece($C(9),1)			// UTBLFORM.RECTYPE
	set vc2=V.piece($C(9),2)			// UTBLFORM.CSEQ
	set vc3=V.piece($C(9),3)			// UTBLFORM.DI
	set vc4=V.piece($C(9),4)			// UTBLFORM.DES
	set vc5=V.piece($C(9),5)			// UTBLFORM.LEN
	set vc6=V.piece($C(9),6)			// UTBLFORM.DECPRE
	set vc7=V.piece($C(9),7)			// UTBLFORM.TYP
	set vc8=V.piece($C(9),8)			// UTBLFORM.VARNAM
	set vc9=V.piece($C(9),9)			// UTBLFORM.DIREF
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(3).get() do VDTL3 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(3)
	type Public String vc1,vovc1,vc2,vovc2
	type Number vb1,vb2,vb3
	set (vb1,vb2,vb3)=0
	if vb2!(vovc1'=vc1) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,VH0=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT()
	type Public String VSTATS

	set VT(3)=VT(3)+1
	quit

VDTL3	// Detail
	type public String %TIM,ACCKEYS,DESC,FID,FIDESC,FIELD,FROM,IOSL,LENGTH,TO,TYPE,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),ZDIREF,vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vrundate,vsysdate

	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL=$J(vc2,3)
	do VP1 quit:VFMQ!verror.get()  set V=$E(DESC,1,30)
	set VL=VL_$J("",5-VL.length())_V
	do VP2 quit:VFMQ!verror.get()  set V=$E(LENGTH,1,6)
	set VL=VL_$J("",36-VL.length())_V
	do VP3 quit:VFMQ!verror.get()  set V=$E(TYPE,1,4)
	set VL=VL_$J("",43-VL.length())_V
	do VP4 quit:VFMQ!verror.get()  set V=$J(FROM,4)
	set VL=VL_$J("",49-VL.length())_V
	set VL=VL_$J("",54-VL.length())_$J(TO,4)
	do VP5 quit:VFMQ!verror.get()  set V=$E(FIELD,1,20)
	set VL=VL_$J("",60-VL.length())_V
	do VOM
	do VP6 quit:VFMQ!verror.get()  set V=$E(ZDIREF,1,25) set VL="                                                       "_V
	if 'VL.translate(" ").isNull() do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,ACCKEYS,CONAM,DESC,FID,FIDESC,FIELD,FROM,LENGTH,RID,RN,TO,TYPE,VL,ZDIREF,vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+10,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E($G(CONAM),1,40)
	set VL=VL_$J("",49-VL.length())_"Run Date: "
	set VL=VL_$J("",59-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",71-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=$E(RN,1,50)
	set VL=VL_$J("",51-VL.length())_"System:"
	set VL=VL_$J("",59-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",70-VL.length())_"Page:"
	set VL=VL_$J("",76-VL.length())_$J(VPN,3)
	do VOM
	set VL="" do VOM
	set VL="Record Type:"
	set V=vc1,VO=V set V=$E(V,1,3) do VP7 quit:VFMQ!verror.get()
	set VL=VL_$J("",13-VL.length())_V		// [SYSDEV,UTBLFORM]RECTYPE
	set VL=VL_$J("",23-VL.length())_"Description: "
	set VL=VL_$J("",36-VL.length())_$E(FIDESC,1,40)
	do VOM
	set VL="File ID: "
	set VL=VL_$J("",9-VL.length())_$E(FID,1,12)
	set VL=VL_$J("",23-VL.length())_"Access Keys:"
	set VL=VL_$J("",36-VL.length())_$E(ACCKEYS,1,40)
	do VOM
	set VL="" do VOM
	set VL="Field                                              Offset "
	do VOM
	set VL="Num  Field Name                     Length Type  Begin End  Profile Field"
	do VOM
	set VL="                                                            "_"Table.Col Reference"
	do VOM
	set VL="================================================================================"
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - Variable: DESC

	type public String vc3,vc4
 type public String DI
 type public String %LIBS,FID,DESC

 set DI=vc3
 if 'DI.isNull() do {
 	type RecordDBTBL1D dbtbl1d=Db.getRecord("DBTBL1D","%LIBS='SYSDEV',FID=:FID,DI=:DI",1)
 	set DESC=dbtbl1d.des
 	}
 else  set DESC=vc4
	quit

VP2	// Column pre-processor - Variable: LENGTH

	type public String vc5,vc6
 type public Number LENGTH
 type public String D

 set LENGTH=vc5
 set D=vc6

 if +D.get()>0 set LENGTH=LENGTH_","_D

	quit

VP3	// Column pre-processor - Variable: TYPE

	type public String vc7
 type public String T,TYPE

 set T=vc7
 set TYPE=$S(T="N":"Num",T="$":"Num",1:"Char")

	quit

VP4	// Column pre-processor - Variable: FROM

	type public String vc2,vc5
 type public String FROM,TO
 
 if vc2=1 do {
 	set FROM=4
 	set TO=vc5+3
 	}
 else  do {
 	set FROM=TO+1
 	set TO=TO+vc5
 	}
 
	quit

VP5	// Column pre-processor - Variable: FIELD

	type public String vc3,vc8
 type public String FIELD,FID

 if 'vc3.isNull() set FIELD=FID_"."_vc3 quit

 type RecordDBTBL1D dbtbl1d= Db.getRecord("DBTBL1D","%LIBS='SYSDEV',FID='UTBLFORM',DI='VARNAM'",1)

 set FIELD=dbtbl1d.rhd_" "_vc8
	quit

VP6	// Column pre-processor - Variable: ZDIREF

	type public String vc9
 type public String ZDIREF

 set ZDIREF=vc9
 if ZDIREF.isNull() quit
 if ZDIREF.length()<21 set ZDIREF="     "_ZDIREF

	quit

VP7	// Column post-processor - [SYSDEV,UTBLFORM]RECTYPE

	type public String vc1
 type public String RT,FIDESC,ACCKEYS,FID

 set RT=vc1
 set FIDESC="",FID="",ACCKEYS=""
 if 'RT.isNull() do {
	type RecordUTBLFORM0 form0=Db.getRecord("UTBLFORM0","RECTYPE=:RT",1)
	set FIDESC=form0.des
	set FID=form0.fid
	set ACCKEYS=form0.acckeys
	}
	quit
