R01S321	// SCA331 - Permanent Hold Report
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:48 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type String CLS
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type String VIN2="ALL"
	type String VIN3="ALL"
	type String VIN4="ALL"
	type String VIN5="ALL"
	type String VIN6="ALL"

	set RID="SCA331"
	set RN="Permanent Hold Report"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	do VPREBQ quit:VFMQ.get()			// Pre-processor (before query)

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN2")="|255||[PHLD]CID|[PHLD]CID:DISTINCT:NOVAL||D EXT^DBSQRY||T|Account Number|||||"
	set %TAB("VIN3")="|255||[DEP]GRP|[STBLGRP]:QU ""[STBLGRP]CLS=""""D"""""":NOVAL||D EXT^DBSQRY||T|Product Group|||||"
	set %TAB("VIN4")="|255||[PHLD]PHC|[UTBLPHC]:NOVAL||D EXT^DBSQRY||T|Hold Code|||||"
	set %TAB("VIN5")="|255||[PHLD]STDT|||D EXT^DBSQRY||T|Start Date|||||"
	set %TAB("VIN6")="|255||[PHLD]EXPDT|||D EXT^DBSQRY||T|Expiration Date|||||"

	set %READ="IO/REQ,VIN2#0,VIN3#0,VIN4#0,VIN5#0,VIN6#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String CLS
	type public String VIN2,VIN3,VIN4,VIN5,VIN6
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,CONAM,RID,RN,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA331",RN="Permanent Hold Report"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA331","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()


	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[DEP]STAT'=4",SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[PHLD]CID "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[DEP]GRP "_VIN3,SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[PHLD]PHC "_VIN4,SEQ=SEQ+1
		if VIN5.get()="" set VIN5="ALL"
		if VIN5'="ALL" set DQQRY(SEQ)="[PHLD]STDT "_VIN5,SEQ=SEQ+1
		if VIN6.get()="" set VIN6="ALL"
		if VIN6'="ALL" set DQQRY(SEQ)="[PHLD]EXPDT "_VIN6,SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("PHLD,DEP") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",2)="WC2|"_"Account Number"_"|VIN2|"_VIN2.get()
		set VBNRINFO("PROMPTS",3)="WC2|"_"Product Group"_"|VIN3|"_VIN3.get()
		set VBNRINFO("PROMPTS",4)="WC2|"_"Hold Code"_"|VIN4|"_VIN4.get()
		set VBNRINFO("PROMPTS",5)="WC2|"_"Start Date"_"|VIN5|"_VIN5.get()
		set VBNRINFO("PROMPTS",6)="WC2|"_"Expiration Date"_"|VIN6|"_VIN6.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Permanent Hold Report"
		set VBNRINFO("PGM")="R01S321"
		set VBNRINFO("RID")="SCA331"
		set VBNRINFO("TABLES")="PHLD,DEP"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,PHLD]3"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,PHLD]CID"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,PHLD]SEQ"

		set VBNRINFO("DOC",1)="The Permanent Hold Report (SCA331) contains permanent hold information for the"
		set VBNRINFO("DOC",2)="accounts selected.  Detail items on the SCA331 report vary depending on how"
		set VBNRINFO("DOC",3)="each particular permanent hold was calculated and whether optional fields were"
		set VBNRINFO("DOC",4)="completed on the Permanent Hold Maintenance screen (PHLD).  Users must complete"
		set VBNRINFO("DOC",5)="the Permanent Hold Report request screen to specify the scope of the SCA331"
		set VBNRINFO("DOC",6)="report contents."
		set VBNRINFO("DOC",7)=""
		set VBNRINFO("DOC",8)="Refer to the Permanent Holds Reference Manual for further information."

		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:3 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:1 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"PHLD.CID,PHLD.SEQ,DEP.LNM,PHLD.PHC,PHLD.THLDAMT,PH"
	set VSELECT=VSELECT_"LD.STDT,PHLD.EXPDT,PHLD.AREF,PHLD.TCMT,PHLD.AMT,PH"
	set VSELECT=VSELECT_"LD.BALAMT,PHLD.%UID,PHLD.CRDNUM,PHLD.CRDTYP,PHLD.O"
	set VSELECT=VSELECT_"RAMT,PHLD.ORCRCD,PHLD.AUTCODE"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"PHLD,DEP",VWHERE,"PHLD.CID,PHLD.SEQ","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2
	set vovc1="",vovc2=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2
	set vovc1=vc1,vovc2=vc2
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17
	set vc1=V.piece($C(9),1)			// PHLD.CID
	set vc2=V.piece($C(9),2)			// PHLD.SEQ
	set vc3=V.piece($C(9),3)			// DEP.LNM
	set vc4=V.piece($C(9),4)			// PHLD.PHC
	set vc5=V.piece($C(9),5)			// PHLD.THLDAMT
	set vc6=V.piece($C(9),6)			// PHLD.STDT
	set vc7=V.piece($C(9),7)			// PHLD.EXPDT
	set vc8=V.piece($C(9),8)			// PHLD.AREF
	set vc9=V.piece($C(9),9)			// PHLD.TCMT
	set vc10=V.piece($C(9),10)			// PHLD.AMT
	set vc11=V.piece($C(9),11)			// PHLD.BALAMT
	set vc12=V.piece($C(9),12)			// PHLD.%UID
	set vc13=V.piece($C(9),13)			// PHLD.CRDNUM
	set vc14=V.piece($C(9),14)			// PHLD.CRDTYP
	set vc15=V.piece($C(9),15)			// PHLD.ORAMT
	set vc16=V.piece($C(9),16)			// PHLD.ORCRCD
	set vc17=V.piece($C(9),17)			// PHLD.AUTCODE
	quit

	// User-defined pre/post-processor code

VPREBQ	// Pre-processor (before query)

	type Public String CLS

	set CLS="D"
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(3).get() do VDTL3 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(3)
	type Public String vc1,vovc1,vc2,vovc2
	type Number vb1,vb2,vb3
	set (vb1,vb2,vb3)=0
	if vb2!(+vovc1'=+vc1) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT()
	type Public String VSTATS

	set VT(3)=VT(3)+1
	quit

VDTL3	// Detail
	type public String %TIM,CLS,IOSL,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vrundate,vsysdate

	if VLC+4>IOSL do VHDG0 quit:VFMQ

	set VL=$J(vc1,12)
	set VL=VL_$J("",14-VL.length())_$E(vc3,1,20)
	set VL=VL_$J("",35-VL.length())_$J(vc4,4)
	set VL=VL_$J("",40-VL.length())_"-"
	set V=$$VP1(vc4)				// @TBL([PHLD]PHC)
	set VL=VL_$J("",42-VL.length())_$E(V,1,25)
	set VL=VL_$J("",68-VL.length())_$J($FN(vc5,",",2),19)
	set VL=VL_$J("",94-VL.length())_$J($$DAT^%ZM(vc6),10)
	set VL=VL_$J("",106-VL.length())_$J($$DAT^%ZM(vc7),10)
	set VL=VL_$J("",117-VL.length())_$J(vc8,13)
	do VOM
	set VL="              "_$E(vc9,1,40)
	set VL=VL_$J("",55-VL.length())_$J($FN(vc10,",",2),32)
	set VL=VL_$J("",88-VL.length())_$J($FN(vc11,",",2),20)
	set VL=VL_$J("",110-VL.length())_$E(vc12,1,20)
	if 'VL.translate(" ").isNull() do VOM
	set VL="              "_$E(vc13,1,20)
	set VL=VL_$J("",42-VL.length())_$E(vc14,1,12)
	set VL=VL_$J("",75-VL.length())_$S(+vc15=0:$J("",12),1:$J($FN(vc15,",",2),12))
	set VL=VL_$J("",101-VL.length())_$E(vc16,1,3)
	set VL=VL_$J("",105-VL.length())_$J(vc17,25)
	do VOM
	set VL="" do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,CLS,CONAM,RID,RN,VL,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+9,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E(CONAM,1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  ("_RID_")"
	set VL=VL_$J("",97-VL.length())_"System Date:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$J(VPN,3)
	do VOM
	set VL="" do VOM
	set VL="                                                                                         "_"--- Hold Dates ---"
	do VOM
	set VL="   "_"Account #  Account Title          Hold Code - Description                  Total Amt       Start       Expiration  Account Ref"
	do VOM
	set VL="              "_"Comment                                                         Fixed Amt         Computed Amt          User ID"
	do VOM
	set VL="              "_"Card Number                 Card Type                       Orig Tran Amt   Orig Tran Curr              Auth Code"
	do VOM
	set VL="===================================================================================================================================="
	do VOM
	set VL="" do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1(KEY1)	// @TBL([PHLD]PHC)

	if KEY1="" quit ""
	type Public Cache %CACHE()
	type RecordUTBLPHC tbl=%CACHE("UTBLPHC").getRecord("UTBLPHC","PHC=:KEY1")
	quit tbl.DESC
