R01S002	// AUDREP - Audit Report
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:40 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type Date VIN1
	type String VIN2="ALL"

	set RID="AUDREP"
	set RN="Audit Report"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB
	set %TAB("VIN1")="|10||[AUDIT]TJD|[AUDIT]TJD:DISTINCT:NOVAL||S AUDDATE=X||D|Run Date is equal to|||||"
	set %TAB("VIN2")="|255||[AUDIT]RUN|[AUDIT]RUN:QU ""[AUDIT]TJD=<<TJD>>"":DISTINCT:NOVAL||D EXT^DBSQRY||T|Run Number|||||"

	set %READ="IO/REQ,VIN1#1,VIN2#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public Date VIN1
	type public String VIN2
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %TIM,CID,CONAM,GRP,INIT,OPT,POS,RID,RN,RUN,TDEP,TLD,TLN,TOT,TYPE,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="AUDREP",RN="Audit Report"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","AUDREP","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[DEP]GRP#1#6,[AUDIT]CID#9#11,[DEP]TITLE1#22#40,[AUDIT]BAL#71#12,[AUDIT]TSEQ#85#4,[DEP]BAL#100#12,[DEP]TLSEQ#114#6,[DEP]TLD#121#10"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[AUDIT]TJD = "_$$addqts^DBSRWUTL(VIN1),SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[AUDIT]RUN "_VIN2,SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("AUDIT,DEP,AUDIT0") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",1)="WC1|"_"Run Date is equal to"_"|VIN1|"_$$DAT^%ZM(VIN1.get(),%MSKD)
		set VBNRINFO("PROMPTS",2)="WC2|"_"Run Number"_"|VIN2|"_VIN2.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Audit Report"
		set VBNRINFO("PGM")="R01S002"
		set VBNRINFO("RID")="AUDREP"
		set VBNRINFO("TABLES")="AUDIT,DEP,AUDIT0"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,AUDIT]TJD"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,AUDIT]RUN"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,AUDIT]CID"


		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:3 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:2 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"AUDIT.TJD,AUDIT.RUN,AUDIT.CID,DEP.GRP,DEP.TITLE1,A"
	set VSELECT=VSELECT_"UDIT.BAL,AUDIT.TSEQ,DEP.BAL,DEP.TLSEQ,DEP.TLD,AUDI"
	set VSELECT=VSELECT_"T0.OPT,AUDIT0.POS,AUDIT0.TOT,AUDIT0.CID,AUDIT0.GRP"
	set VSELECT=VSELECT_",AUDIT0.TYPE,AUDIT0.BAL,AUDIT0.TLD,DEP.CLS"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"AUDIT,DEP,AUDIT0",VWHERE,"AUDIT.TJD,AUDIT.RUN,AUDIT.CID","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2,vovc3
	set vovc1="",vovc2="",vovc3=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2,vovc3,vc3
	set vovc1=vc1,vovc2=vc2,vovc3=vc3
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19
	set vc1=V.piece($C(9),1)			// AUDIT.TJD
	set vc2=V.piece($C(9),2)			// AUDIT.RUN
	set vc3=V.piece($C(9),3)			// AUDIT.CID
	set vc4=V.piece($C(9),4)			// DEP.GRP
	set vc5=V.piece($C(9),5)			// DEP.TITLE1
	set vc6=V.piece($C(9),6)			// AUDIT.BAL
	set vc7=V.piece($C(9),7)			// AUDIT.TSEQ
	set vc8=V.piece($C(9),8)			// DEP.BAL
	set vc9=V.piece($C(9),9)			// DEP.TLSEQ
	set vc10=V.piece($C(9),10)			// DEP.TLD
	set vc11=V.piece($C(9),11)			// AUDIT0.OPT
	set vc12=V.piece($C(9),12)			// AUDIT0.POS
	set vc13=V.piece($C(9),13)			// AUDIT0.TOT
	set vc14=V.piece($C(9),14)			// AUDIT0.CID
	set vc15=V.piece($C(9),15)			// AUDIT0.GRP
	set vc16=V.piece($C(9),16)			// AUDIT0.TYPE
	set vc17=V.piece($C(9),17)			// AUDIT0.BAL
	set vc18=V.piece($C(9),18)			// AUDIT0.TLD
	set vc19=V.piece($C(9),19)			// DEP.CLS
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(2).get() do VDTL2 quit:VFMQ
	if 'vskp(3).get() do VDTL3 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(3)
	type Public String vc1,vovc1,vc2,vovc2,vc3,vovc3
	type Number vb1,vb2,vb3
	set (vb1,vb2,vb3)=0
	if vb1!(vovc1'=vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,VH0=1
	if vb2!(+vovc2'=+vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,VH0=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(3) set vs(3)=1 do VSUM3 quit:VFMQ  do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT(),vc6,vc8
	type Public String VSTATS

	set VT(3)=VT(3)+1
	set VT(3,1,1)=VT(3,1,1)+vc6			// @TOT([AUDIT]BAL)
	set VT(3,2,1)=VT(3,2,1)+vc8			// @TOT([DEP]BAL)
	quit

VDTL2	// Detail
	type public String %TIM,CID,GRP,INIT,IOSL,OPT,POS,RUN,TDEP,TLD,TLN,TOT,TYPE,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VRG,VT(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vrundate,vsysdate

	quit:VD(2)  set VD(2)=1				// Print flag
	if VLC+1>IOSL do VHDG0 quit:VFMQ

	do VP1 quit:VFMQ!verror.get()  set V=$E(INIT,1,1) set VL=V
	do VOM
	quit

VDTL3	// Detail
	type public String %TIM,CID,GRP,INIT,IOSL,OPT,POS,RUN,TDEP,TLD,TLN,TOT,TYPE,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VRG,VT(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vrundate,vsysdate

	if VLC+1>IOSL do VHDG0 quit:VFMQ

	set V=vc4,VO=V set V=$E(V,1,6) do VP2 quit:VFMQ!verror.get()  set VL=V
	set VL=VL_$J("",7-VL.length())_$J(vc3,12)
	set VL=VL_$J("",21-VL.length())_$E(vc5,1,40)
	set VL=VL_$J("",62-VL.length())_$J(vc6,20,2)
	set VL=VL_$J("",83-VL.length())_$J(vc7,5)
	set VL=VL_$J("",89-VL.length())_$J(vc8,22,2)
	set V=vc9,VO=V set V=$J(V,7) do VP3 quit:VFMQ!verror.get()
	set VL=VL_$J("",112-VL.length())_V		// [SYSDEV,DEP]TLSEQ
	set VL=VL_$J("",120-VL.length())_$J($$DAT^%ZM(vc10),10)
	do VOM
	quit

VSUM3	// Summary
	type public String %TIM,CID,GRP,I,INIT,IOSL,OPT,POS,RUN,TDEP,TLD,TLN,TOT,TYPE,V,VFMQ,VL,VLC,VO,VOFFLG,VT(),VX(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vrundate,vsysdate

	if 'VT(3) quit
	if VLC+19>IOSL do VHDG0 quit:VFMQ

	set VL="                                                                   "_"==============="
	set VL=VL_$J("",96-VL.length())_"==============="
	do VOM
	set VL="                                       "_"Run Totals:"
	set V=VT(3,1,1)					// @TOT([AUDIT]BAL,)
	set VL=VL_$J("",67-VL.length())_$J($FN(V,",",2),15)
	set V=VT(3,2,1)					// @TOT([DEP]BAL,)
	set VL=VL_$J("",96-VL.length())_$J($FN(V,",",2),15)
	do VOM
	set VL="" do VOM
	set VL="------------------------------------------------------------------------------------------------------------------------------------"
	do VOM
	set VL="" do VOM
	set VL="                                       "_"Query Conditions For Audit Run "_vc2_" - "_$$DAT^%ZM(AUDDATE,$G(%MSKD))
	do VOM
	set VL="Opt"
	set VL=VL_$J("",5-VL.length())_"Respond"
	set VL=VL_$J("",14-VL.length())_"Max Count"
	set VL=VL_$J("",25-VL.length())_"Account "
	set VL=VL_$J("",47-VL.length())_"Group"
	set VL=VL_$J("",69-VL.length())_"Type"
	set VL=VL_$J("",91-VL.length())_"Balance"
	set VL=VL_$J("",113-VL.length())_"Last Active"
	do VOM
	set VL=" "_$J(vc11,1)
	set VL=VL_$J("",11-VL.length())_$S(vc12:"Y",1:"N")
	set VL=VL_$J("",17-VL.length())_$J(vc13,6)
	set VL=VL_$J("",25-VL.length())_$E(vc14,1,20)
	set VL=VL_$J("",47-VL.length())_$E(vc15,1,20)
	set VL=VL_$J("",69-VL.length())_$E(vc16,1,20)
	set VL=VL_$J("",91-VL.length())_$E(vc17,1,20)
	set VL=VL_$J("",113-VL.length())_$E(vc18,1,18)
	do VOM
	set VL="" do VOM
	set VL="------------------------------------------------------------------------------------------------------------------------------------"
	do VOM
	set VL="                        "_"Group"
	set VL=VL_$J("",34-VL.length())_"Count"
	do VOM
	set VL="                        "_"-----"
	set VL=VL_$J("",34-VL.length())_"-----"
	do VOM
	set VL=""
	do VOM
	set VL="                        "_"Number of Accounts:"
	set V=VT(3)					// @CNT(,N,6)
	set VL=VL_$J("",44-VL.length())_$J(V,6)
	do VP4 quit:VFMQ!verror.get()  set V="( "_TLN_" LOANS, "_TDEP_" DEPOSITS )"
	set VL=VL_$J("",52-VL.length())_V
	do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	set VL="" do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,CID,CONAM,GRP,INIT,OPT,POS,RID,RN,RUN,TDEP,TLD,TLN,TOT,TYPE,VL,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+7,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E(CONAM,1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL="Audit Notice Run Report - "_$$DAT^%ZM(AUDDATE,$G(%MSKD))_" - Run "_vc2
	set VL=VL_$J("",102-VL.length())_"System:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$E($J(VPN,3),1,3)
	do VOM
	set VL="" do VOM
	set VL="                                                                          "_"Audit Date                    Current"
	do VOM
	set VL="                                                                      "_"------------------           ------------------       Last"
	do VOM
	set VL="Group       Account  Customer                                              Balance   Seq                Balance   Seq      Active"
	do VOM
	set VL="===================================================================================================================================="
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - Variable: INIT

	type public Number TOTDEP,TOTLN
	type public String INIT

	set INIT=""
	set (TOTDEP,TOTLN)=0
	quit

VP2	// Column post-processor - [SYSDEV,DEP]GRP

	type public String vc19
 type public String CLS,TGRP()
 type public Number TOTDEP,TOTLN
 
 if TGRP(V).exists() set TGRP(V)=TGRP(V)+1
 else  set TGRP(V)=1

 set CLS=vc19

 if CLS="L" set TOTLN=TOTLN+1 quit

 set TOTDEP=TOTDEP+1

	quit

VP3	// Column post-processor - [SYSDEV,DEP]TLSEQ

 type public Number X

 set X=X-1
	quit

VP4	// Column pre-processor - ( <<TLN>> LOANS, <<TDEP>> DEPOSITS )

 type public Number TOTDEP,TOTLN
 type public String TDEP,TLN

 set (TDEP,TLN)=""

 if 'TOTLN set TLN="NO"
 else  set TLN=TOTLN

 if 'TOTDEP set TDEP="NO"
 else  set TDEP=TOTDEP
	quit
