R01S426	// SCA463 - Miscellaneous Transaction Journal
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:49 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type public String TJD
	type String OPT
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ
	type Number DET=1
	type Number OPT=1
	type Date VIN1=TJD.get()
	type String VIN2="ALL"
	type String VIN3="ALL"
	type String VIN4="ALL"
	type String VIN5="ALL"
	type String VIN6="ALL"
	type String VIN7="ALL"
	type String VIN8="ALL"
	type String VIN9="ALL"

	set RID="SCA463"
	set RN="Miscellaneous Transaction Journal"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	do VPREBQ quit:VFMQ.get()			// Pre-processor (before query)

	set %TAB("DET")="|1|||||||L|Print Detail|||||"
	set %TAB("IO")=$$IO^SCATAB
	set %TAB("OPT")="|1|||OPT(||||N|Report Option|||||"
	set %TAB("VIN1")="|10||[DMJ]TJD|[DMJ]TJD:DISTINCT:NOVAL||||D|Transaction Date|||||"
	set %TAB("VIN2")="|255||[DMJ]CRCD|[CRCD]||D EXT^DBSQRY||T|Currency Code|||||"
	set %TAB("VIN3")="|255||[TRN]GRP|[STBLLIBS]:NOVAL||D EXT^DBSQRY||T|Transaction Group|||||"
	set %TAB("VIN4")="|255||[DMJ]CID|[GLAD]:NOVAL||D EXT^DBSQRY||T|Account Range|||||"
	set %TAB("VIN5")="|255||[DMJ]BRCD|[UTBLBRCD]:NOVAL||D EXT^DBSQRY||T|Branch Code|||||"
	set %TAB("VIN6")="|255||[DMJ]CC|[UTBLCCNTR]:NOVAL||D EXT^DBSQRY||T|Cost Center|||||"
	set %TAB("VIN7")="|255||[DMJ]UID|[SCAU]:NOVAL||D EXT^DBSQRY||T|Teller ID|||||"
	set %TAB("VIN8")="|255||[DMJ]ETC|[TRN]:NOVAL||D EXT^DBSQRY||T|Transaction Code|||||"
	set %TAB("VIN9")="|255||[DMJ]TAMT|||D EXT^DBSQRY||T|Transaction Amount|||||"

	set %READ="IO/REQ,VIN1#1,VIN2#0,VIN3#0,VIN4#0,VIN5#0,VIN6#0,VIN7#0,VIN8#0,VIN9#0,DET#0,OPT#0,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type Boolean VHIT
	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type public String TJD
	type public String OPT
	type public Date VIN1
	type public Number DET,OPT
	type public String VIN2,VIN3,VIN4,VIN5,VIN6,VIN7,VIN8,VIN9
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String VWHERE
	type Literal String VSELECT
	type String %BLK,%NOBANNER,%TIM,CONAM,POU,RID,RN,TAMT,TCMT1,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc4,vovc5,vovc6,vovc7,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA463",RN="Miscellaneous Transaction Journal"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA463","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[DMJ]CID#1#12,[DMJ]BRCD#14#6,[DMJ]TSEQ#21#6,[DMJ]ETC#28#8,[DMJ]TLO#50#10,[DMJ]UID#61#4,[DMJ]TIME#67#8,[DMJ]EFD#81#10,[DMJ]TSO#92#40\[DMJ]CC#21#6,[DMJ]BSEAMT#37#12,[DMJ]BCRCD#50#3,[DMJ]RATE#61#8,[DMJ]CUSTCD#76#3"

	// Build WHERE clause to use for dynamic query
	do {
		type Number SEQ=1
		type String DQQRY(),FROM
		set DQQRY(SEQ)="[DMJ]TJD = "_$$addqts^DBSRWUTL(VIN1),SEQ=SEQ+1
		if VIN2.get()="" set VIN2="ALL"
		if VIN2'="ALL" set DQQRY(SEQ)="[DMJ]CRCD "_VIN2,SEQ=SEQ+1
		if VIN3.get()="" set VIN3="ALL"
		if VIN3'="ALL" set DQQRY(SEQ)="[TRN]GRP "_VIN3,SEQ=SEQ+1
		if VIN4.get()="" set VIN4="ALL"
		if VIN4'="ALL" set DQQRY(SEQ)="[DMJ]CID "_VIN4,SEQ=SEQ+1
		if VIN5.get()="" set VIN5="ALL"
		if VIN5'="ALL" set DQQRY(SEQ)="[DMJ]BRCD "_VIN5,SEQ=SEQ+1
		if VIN6.get()="" set VIN6="ALL"
		if VIN6'="ALL" set DQQRY(SEQ)="[DMJ]CC "_VIN6,SEQ=SEQ+1
		if VIN7.get()="" set VIN7="ALL"
		if VIN7'="ALL" set DQQRY(SEQ)="[DMJ]UID "_VIN7,SEQ=SEQ+1
		if VIN8.get()="" set VIN8="ALL"
		if VIN8'="ALL" set DQQRY(SEQ)="[DMJ]ETC "_VIN8,SEQ=SEQ+1
		if VIN9.get()="" set VIN9="ALL"
		if VIN9'="ALL" set DQQRY(SEQ)="[DMJ]TAMT "_VIN9,SEQ=SEQ+1
		set DQQRY(SEQ)="[DMJ]ETC'=""""",SEQ=SEQ+1
		set FROM=$$DQJOIN^SQLCONV("DMJ,TRN") quit:ER
		set VWHERE=$$WHERE^SQLCONV(.DQQRY,"")
		}

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO()

		set VBNRINFO("PROMPTS",1)="WC1|"_"Transaction Date"_"|VIN1|"_$$DAT^%ZM(VIN1.get(),%MSKD)
		set VBNRINFO("PROMPTS",2)="WC2|"_"Currency Code"_"|VIN2|"_VIN2.get()
		set VBNRINFO("PROMPTS",3)="WC2|"_"Transaction Group"_"|VIN3|"_VIN3.get()
		set VBNRINFO("PROMPTS",4)="WC2|"_"Account Range"_"|VIN4|"_VIN4.get()
		set VBNRINFO("PROMPTS",5)="WC2|"_"Branch Code"_"|VIN5|"_VIN5.get()
		set VBNRINFO("PROMPTS",6)="WC2|"_"Cost Center"_"|VIN6|"_VIN6.get()
		set VBNRINFO("PROMPTS",7)="WC2|"_"Teller ID"_"|VIN7|"_VIN7.get()
		set VBNRINFO("PROMPTS",8)="WC2|"_"Transaction Code"_"|VIN8|"_VIN8.get()
		set VBNRINFO("PROMPTS",9)="WC2|"_"Transaction Amount"_"|VIN9|"_VIN9.get()


		do {
			type Number SEQ
			type String VALUE,VAR,X
			set X=VWHERE
			set SEQ=""
			for  set SEQ=VBNRINFO("PROMPTS",SEQ).order() quit:SEQ=""  do {
				set VAR=VBNRINFO("PROMPTS",SEQ).piece("|",3))
				set VALUE=VBNRINFO("PROMPTS",SEQ).piece("|",4,99)
				set X=$$replace^DBSRWUTL(X,":"_VAR,"'"_VALUE_"'")
				}
			set VBNRINFO("WHERE")=X
			}

		set VBNRINFO("DESC")="Miscellaneous Transaction Journal"
		set VBNRINFO("PGM")="R01S426"
		set VBNRINFO("RID")="SCA463"
		set VBNRINFO("TABLES")="DMJ,TRN"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,DMJ]TJD"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,DMJ]DATETIME"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,DMJ]CID"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,DMJ]TSEQ"


		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc20)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VHIT = 0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:4 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:0 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	if VDISTKEY.get()="" do { quit:VFMQ		// Report Pre-processor (after query)
		do VPREAQ
		if VFMQ set vh(0)=1 do VEXIT(0)
		}

	set vh(0)=0

	// Run report directly
	do VINILAST

	set VSELECT=""
	set VSELECT=VSELECT_"DMJ.ITC,DMJ.TAMT,DMJ.CRCD,DMJ.CID,DMJ.TJD,DMJ.DATE"
	set VSELECT=VSELECT_"TIME,DMJ.TSEQ,DMJ.BRCD,DMJ.ETC,DMJ.TLO,DMJ.UID,DMJ"
	set VSELECT=VSELECT_".TIME,DMJ.EFD,DMJ.TSO,DMJ.CC,DMJ.BSEAMT,DMJ.BCRCD,"
	set VSELECT=VSELECT_"DMJ.RATE,DMJ.CUSTCD,DMJ.TCMT"

	#ACCEPT DATE=01/31/2007;PGM=Report Writer Generator;CR=20967
	type ResultSet rwrs=Db.select(VSELECT,"DMJ,TRN",VWHERE,"DMJ.TJD,DMJ.DATETIME,DMJ.CID,DMJ.TSEQ","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
	type Boolean VSKIPREC = 0
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VFPOST quit:(VFMQ ! VSKIPREC)  set VHIT = 1
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT('VHIT)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc5,vovc6,vovc4,vovc7
	set vovc5="",vovc6="",vovc4="",vovc7=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc5,vc5,vovc6,vc6,vovc4,vc4,vovc7,vc7
	set vovc5=vc5,vovc6=vc6,vovc4=vc4,vovc7=vc7
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc20
	set vc1=V.piece($C(9),1)			// DMJ.ITC
	set vc2=V.piece($C(9),2)			// DMJ.TAMT
	set vc3=V.piece($C(9),3)			// DMJ.CRCD
	set vc4=V.piece($C(9),4)			// DMJ.CID
	set vc5=V.piece($C(9),5)			// DMJ.TJD
	set vc6=V.piece($C(9),6)			// DMJ.DATETIME
	set vc7=V.piece($C(9),7)			// DMJ.TSEQ
	set vc8=V.piece($C(9),8)			// DMJ.BRCD
	set vc9=V.piece($C(9),9)			// DMJ.ETC
	set vc10=V.piece($C(9),10)			// DMJ.TLO
	set vc11=V.piece($C(9),11)			// DMJ.UID
	set vc12=V.piece($C(9),12)			// DMJ.TIME
	set vc13=V.piece($C(9),13)			// DMJ.EFD
	set vc14=V.piece($C(9),14)			// DMJ.TSO
	set vc15=V.piece($C(9),15)			// DMJ.CC
	set vc16=V.piece($C(9),16)			// DMJ.BSEAMT
	set vc17=V.piece($C(9),17)			// DMJ.BCRCD
	set vc18=V.piece($C(9),18)			// DMJ.RATE
	set vc19=V.piece($C(9),19)			// DMJ.CUSTCD
	set vc20=V.piece($C(9),20)			// DMJ.TCMT
	quit

	// User-defined pre/post-processor code

VFPOST	// FETCH post-processor

	type public String vc1,vc2,vc3,vc4
	type Public String OPT,POU
	type String CID,CRCD,CRDR,ITC,PM,TAMT

	// Summarize activity by transaction code for report SCA464

	// Internal transaction code
	set ITC=vc1

	// Debit or credit indicator
	set CRDR=+$E(ITC)

	// PM indicator
	set PM=+$E(ITC,8)

	// PMed activity only.
	if OPT=2,'PM quit

	// Non PMed activity only.
	if OPT=3,PM quit

	set TAMT=vc2
	set CRCD=vc3
	if CRCD="" set CRCD=%SystemCurrency

	// SUM // Create summary record.
	set CID=vc4

	// select record from the database
	type RecordDMJTMP dmjtmp=Db.getRecord("DMJTMP","JOB=:%ProcessID,CRCD=:CRCD,ACN=:CID",1)

	if 'CRDR do {
		set dmjtmp.dramt=dmjtmp.dramt+vc2
		set dmjtmp.drcnt=dmjtmp.drcnt+1
		}
	else  do {
		set dmjtmp.cramt=dmjtmp.cramt+vc2
		set dmjtmp.crcnt=dmjtmp.crcnt+1
		}

	do dmjtmp.bypassSave()

	set POU=$S($E(ITC,8):"P",1:" ")
	set POU=POU_$S($E(ITC,10):"O",1:" ")
	set POU=POU_$S($E(ITC,11):"U",1:" ")	

	quit 

VPREAQ	// Pre-processor (after query)

	type Public Number DET

	// No Detail, just summaries.
	if DET=0 do rwopt^DBSRWUTL("NODTL","")

	quit

VPREBQ	// Pre-processor (before query)

	type Public String OPT

	// kill temp table
	do Db.fastDelete("DMJTMP","JOB=:%ProcessID")

	// Report options
	// All activity
	set OPT(1)=$$^MSG(4609)

	// PMed activity only
	set OPT(2)=$$^MSG(4611)

	// Non-PMed activity only
	set OPT(3)=$$^MSG(4610)

	quit

VRPOST	// Report post-processor

	type Public String %BLK,%NOBANNER
	type Public String IO,IOTYP
	set %BLK="/,"_IO

	if '($D(%NOBANNER)!(IOTYP="TRM")!('CUVAR.banner)) write #

	// Transaction Summary Report
	do rwopt^DBSRWUTL("LINKRPT","SCA464")

	// kill temp table
	do Db.fastDelete("DMJTMP","JOB=:%ProcessID")

	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0
	if 'VFMQ do VSUM
	if 'vh(0) do VHDG0
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VRPOST			// Report Post-Processor
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(1)=1,vskp(2)=1,vskp(3)=1,vskp(4)=1	// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(4).get() do VDTL4 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(4)
	type Public String vc5,vovc5,vc6,vovc6,vc4,vovc4,vc7,vovc7
	type Number vb1,vb2,vb3,vb4
	set (vb1,vb2,vb3,vb4)=0
	if vb1!(vovc5'=vc5) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1,VH0=1
	if vb2!(+vovc6'=+vc6) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1
	if vb3!(+vovc4'=+vc4) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(4) set vs(4)=1 do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT()
	type Public String VSTATS

	set VT(4)=VT(4)+1
	quit

VDTL4	// Detail
	type public String %BLK,%NOBANNER,%TIM,DET,IO,IOSL,IOTYP,OPT,POU,TAMT,TCMT1,TJD,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc4,vovc5,vovc6,vovc7,vrundate,vsysdate

	if VLC+2>IOSL do VHDG0 quit:VFMQ

	set VL=$J(vc4,12)
	set VL=VL_$J("",13-VL.length())_$J(vc8,6)
	set VL=VL_$J("",20-VL.length())_$J(vc7,6)
	set VL=VL_$J("",27-VL.length())_$J(vc9,8)
	set V=vc2,VO=V do VP1 quit:VFMQ!verror.get()  set V=$J($FN(V,",",2),12)
	set VL=VL_$J("",36-VL.length())_V
	set VL=VL_$J("",49-VL.length())_$E(vc10,1,10)
	set VL=VL_$J("",60-VL.length())_$J(vc11,4)
	set VL=VL_$J("",66-VL.length())_$J($$TIM^%ZM(vc12),8)
	set VL=VL_$J("",75-VL.length())_$E(POU,1,3)
	set VL=VL_$J("",80-VL.length())_$J($$DAT^%ZM(vc13),10)
	set VL=VL_$J("",91-VL.length())_$E(vc14,1,40)
	do VOM
	set VL="                    "_$J(vc15,6)
	set VL=VL_$J("",27-VL.length())_$J($FN(vc16,",",2),21)
	set VL=VL_$J("",49-VL.length())_$E(vc17,1,3)
	set VL=VL_$J("",60-VL.length())_$J(vc18,8,5)
	set VL=VL_$J("",75-VL.length())_$E(vc19,1,3)
	do VP2 quit:VFMQ!verror.get()  set V=$E(TCMT1,1,40)
	set VL=VL_$J("",91-VL.length())_V
	if 'VL.translate(" ").isNull() do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %BLK,%MSKD,%NOBANNER,%TIM,CONAM,DET,IO,IOTYP,OPT,POU,RID,RN,TAMT,TCMT1,TJD,VL,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc4,vovc5,vovc6,vovc7,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+7,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E($G(CONAM),1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  ("_RID_")"
	set VL=VL_$J("",102-VL.length())_"System:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$J(VPN,3)
	do VOM
	set VL="                                                                                              "_"Effective Date:"
	set VL=VL_$J("",110-VL.length())_$J($$DAT^%ZM(vc5),10)
	do VOM
	set VL="" do VOM
	set VL="     "_"Account Br Cd     Seq Tran Cd        Amount Location   User  Time     POU  Effective  Source"
	do VOM
	set VL="                        "_"CC              Base Amt Base Curr  Exch Rate      Cust Code       Transaction Comment"
	do VOM
	set VL="==================================================================================================================================="
	do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - Variable: TAMT

	type public String vc2
	type Public String TAMT

	set TAMT=vc2
	quit

VP2	// Column pre-processor - Variable: TCMT1

	type public String vc20
	type Public String TCMT1

	set TCMT1=vc20
	quit 
