R01S120	// SCA047 - Revolving Credit Loan Trial Balance
	// Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 12:42 - shetyes

	type public Number ER=0
	type public Number vbatchq
	type public String IO,RM,VRWOPT()
	type Number OLNTB
	type String %READ,RID,RN,%TAB,VFMQ

	set RID="SCA047"
	set RN="Revolving Credit Loan Trial Balance"
	if IO.get()="" set IO=$I

	do INIT^%ZM()

	set %TAB("IO")=$$IO^SCATAB

	set %READ="IO/REQ,"

	// Skip device prompt option
	if VRWOPT("NOOPEN").get() set %READ=%READ.piece(",",2,99)

	set VFMQ=""
	if %READ'="" do { quit:VFMQ.get()="Q"
		set OLNTB=30
		set %READ="@RN/CEN#1,,"_%READ
		do ^UTLREAD
		}

	if 'vbatchq.get() do V0
	quit

V0	// External report entry point

	type public Number AUXPTR,ER,VTBLNAM
	type public String IO,IOPAR,IOSL,IOTYP,%MSKD,RM,VDISTKEY,VRWOPT()
	type Number vcrt,VD(),VFMQ,vh(),vI,vlc,VLC,VNEWHDR,VOFFLG,VPN,VR,VRG,vs(),VSEQ,VT()
	type String %TIM,CONAM,GRP,RDES,RID,RN,RTDES,TRAIL,TTDES,TYPE,VL,VLOF,VRF(),VSTATS(),vCOL,vHDG,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc21,vc22,vc23,vc24,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	type RecordCUVAR cuvar=Db.getRecord("CUVAR")

	set CONAM=CUVAR.conam
	set ER=0,RID="SCA047",RN="Revolving Credit Loan Trial Balance"
	set VL=""

	use 0 if 'VRWOPT("NOOPEN").get() do { quit:ER
		if 'VRWOPT("IOPAR").get().isNull() set IOPAR = VRWOPT("IOPAR")
		else  if ((IOTYP.get()="RMS")!(IOTYP.get()="PNTQ")),('IOPAR.get().isLike("%/OCHSET=%")),$$VALID^%ZRTNS("UCIOENCD") do {
			// Accept warning if ^UCIOENCD does not exist
			#ACCEPT Date=07/26/06; Pgm=RussellDS; CR=22121; Group=MISMATCH
			type String CHRSET=$$^UCIOENCD("Report","SCA047","V0","*")
			if 'CHRSET.isNull() set IOPAR = IOPAR_"/OCHSET="_CHRSET
		}
		do OPEN^SCAIO
	}
	set vcrt=(IOTYP="TRM")
	if 'vcrt set IOSL=60				// Non-interactive
	else  do {					// Interactive
		do TERM^%ZUSE(IO,"WIDTH=133")
		write $$CLEARXY^%TRMVT
		write $$SCR132^%TRMVT			// Switch to 132 col mode
		}

	do INIT^%ZM()

	set vCOL="[LN]CID#1#12,[LN]CC#14#6,[LN]LNM#21#20,[LN]BALCMP#42#12,[LN]ODT#55#10,[LN]TLD#73#10,[LN]ACR#84#8,[LN]PMT#94#7,[LN]LCHG#108#6,[LN]DTNT#116#10\[LN]NCOA#42#12,[LN]CRLMT#55#8,[LN]IRN#64#8,[LN]DIST1ND#73#10,[LN]IYTD#84#8,[LN]DIST1FRE#94#12,[LN]MCHG#108#6"

	// Print Report Banner Page
	if cuvar.banner,'VRWOPT("NOBANNER").get(),IOTYP'="TRM",'AUXPTR.get() do {
		type String VBNRINFO(),VWHERE


		set VWHERE=""
		set VWHERE=VWHERE_"LN.CLS='L' AND LN.GRP='RC' AND LN.STAT NOT =4 AND "
		set VWHERE=VWHERE_"((LN.PCIDSTAT=0) OR (LN.PCIDSTAT=''))"
		set VBNRINFO("WHERE")=VWHERE

		set VBNRINFO("DESC")="Revolving Credit Loan Trial Balance"
		set VBNRINFO("PGM")="R01S120"
		set VBNRINFO("RID")="SCA047"
		set VBNRINFO("TABLES")="LN,PRODDFTL"

		set VBNRINFO("ORDERBY",1)="[SYSDEV,LN]CLS"
		set VBNRINFO("ORDERBY",2)="[SYSDEV,LN]GRP"
		set VBNRINFO("ORDERBY",3)="[SYSDEV,LN]TYPE"
		set VBNRINFO("ORDERBY",4)="[SYSDEV,LN]CID"


		do ^DBSRWBNR(IO,.VBNRINFO)		// Print banner
		}

	// Initialize variables
	set (vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc20,vc21,vc22,vc23,vc24)=""
	set (VFMQ,vlc,VLC,VOFFLG,VPN,VRG)=0
	set VNEWHDR=1
	set VLOF=""
	set %TIM=$$TIM^%ZM
	set vrundate=%CurrentDate.toString(),vsysdate=%SystemDate.toString()

	do {
		type Number I,J,K
		for I=0:1:4 do {
			set (vh(I),VD(I))=0,vs(I)=1	// Group break flags
			set VT(I)=0			// Group count
			for J=1:1:6 do {
				for K=1:1:3 set VT(I,J,K)=""	// Initialize function stats
				}
			}
		}

	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data
	if VDISTKEY.get()="" do { quit:VFMQ		// Report Pre-processor (after query)
		do VPREAQ
		if VFMQ set vh(0)=1 do VEXIT(0)
		}

	set vh(0)=0

	// Run report directly
	do VINILAST
	type ResultSet rwrs=Db.select("LN.CLS,LN.GRP,LN.TYPE,LN.CID,LN.IRN,LN.BAL,LN.INDEX,LN.COLCD,LN.CC,LN.BALCMP,LN.ACR,LN.LCHG,LN.NCOA,LN.IYTD,LN.MCHG,LN.LNM,LN.ODT,LN.TLD,LN.PMT,LN.DTNT,LN.CRLMT,LN.DIST1ND,LN.DIST1FRE,PRODDFTL.DES","LN,PRODDFTL","LN.CLS='L' AND LN.GRP='RC' AND LN.STAT NOT =4 AND ((LN.PCIDSTAT=0) OR (LN.PCIDSTAT=''))","LN.CLS,LN.GRP,LN.TYPE,LN.CID","","DQMODE=1")
	if ER.get() use 0 write $$MSG^%TRMVT(RM.get(),"",1)	// Debug Mode
	if rwrs.isEmpty() do VEXIT(1) quit
	while rwrs.next() do { quit:VFMQ
		type String V,VI
		set V=rwrs.getRow().toString()
		set VI=""
		do VGETDATA(V,VI)
		do VPRINT quit:VFMQ
		do VSAVLAST
		}
	do VEXIT(0)

	quit


VINILAST	// Initialize last access key values
	type Public String vovc1,vovc2,vovc3,vovc4
	set vovc1="",vovc2="",vovc3="",vovc4=""
	quit

VSAVLAST	// Save last access keys values
	type Public String vovc1,vc1,vovc2,vc2,vovc3,vc3,vovc4,vc4
	set vovc1=vc1,vovc2=vc2,vovc3=vc3,vovc4=vc4
	quit


VGETDATA(String V,String VI)	//
	type Public String vc1,vc2,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc20,vc21,vc22,vc23,vc24
	set vc1=V.piece($C(9),1)			// LN.CLS
	set vc2=V.piece($C(9),2)			// LN.GRP
	set vc3=V.piece($C(9),3)			// LN.TYPE
	set vc4=V.piece($C(9),4)			// LN.CID
	set vc5=V.piece($C(9),5)			// LN.IRN
	set vc6=V.piece($C(9),6)			// LN.BAL
	set vc7=V.piece($C(9),7)			// LN.INDEX
	set vc8=V.piece($C(9),8)			// LN.COLCD
	set vc9=V.piece($C(9),9)			// LN.CC
	set vc10=V.piece($C(9),10)			// LN.BALCMP
	set vc11=V.piece($C(9),11)			// LN.ACR
	set vc12=V.piece($C(9),12)			// LN.LCHG
	set vc13=V.piece($C(9),13)			// LN.NCOA
	set vc14=V.piece($C(9),14)			// LN.IYTD
	set vc15=V.piece($C(9),15)			// LN.MCHG
	set vc16=V.piece($C(9),16)			// LN.LNM
	set vc17=V.piece($C(9),17)			// LN.ODT
	set vc18=V.piece($C(9),18)			// LN.TLD
	set vc19=V.piece($C(9),19)			// LN.PMT
	set vc20=V.piece($C(9),20)			// LN.DTNT
	set vc21=V.piece($C(9),21)			// LN.CRLMT
	set vc22=V.piece($C(9),22)			// LN.DIST1ND
	set vc23=V.piece($C(9),23)			// LN.DIST1FRE
	set vc24=V.piece($C(9),24)			// PRODDFTL.DES
	quit

	// User-defined pre/post-processor code

VPREAQ	// Pre-processor (after query)

	type public Boolean TRAIL
	type public String GRP
	type public Number TYPE

 	set TRAIL=1
	set GRP=""
	set TYPE=""
	quit

VBRSAVE(Number LINE,String DATA)	// Save for report browser
	type RecordTMPRPTBR tmprptbr=Class.new("RecordTMPRPTBR")
	set tmprptbr.jobno=%ProcessID
	set tmprptbr.lineno=LINE
	set tmprptbr.pageno=0
	set tmprptbr.seq=0
	set tmprptbr.data=DATA
	do tmprptbr.bypassSave()
	quit

VEXIT(NOINFO)	// Exit from report
	type Public Number IOSL,vcrt,VFMQ,vh(),VLC,VPN,VRWOPT,VSTATS()
	type Public String IO,VTBLNAM
	type Number I,PN,vs(),z
	type String VL=""
	set vs(1)=0,vs(2)=0,vs(3)=0,vs(4)=0
	if 'VFMQ do VSUM
	if 'VFMQ do VRSUM
	if 'VFMQ do {
		// No information available to display
		if NOINFO=1 set VL=$$^MSG(4655) do VOM
		do VTRL0
		if vcrt set VL="" for z=VLC+1:1:IOSL do VOM

		set PN=VPN
		do ^DBSRWSTS(.VSTATS)			// Print statistics
		quit:VFMQ

		if 'VTBLNAM.exists() do {
			set vs(2)=0
			do VBREAK,stat^DBSRWUTL(2)
			}
		}

	if 'VFMQ,vcrt set PN=-1 do ^DBSRWBR(2)
	if 'VRWOPT("NOCLOSE").get() do CLOSE^SCAIO
	do Db.delete("TMPRPTBR","JOBNO=:%ProcessID")	// Report browser data

	quit

VPRINT	// Print section
	type Public Number VD(),VFMQ,VH0,vh(),VNEWHDR,VR,VRG,VRWOPT,VSEQ
	type Number vskp()

	if VRWOPT("NODTL").get() set vskp(4)=1		// Skip detail
	do VBREAK
	do VSUM quit:VFMQ

	if VH0.get() set vh(0)=0,VNEWHDR=1 kill VH0	// Page Break
	if 'vh(0) do VHDG0 quit:VFMQ
	if 'vskp(4).get() do VDTL4 quit:VFMQ
	do VSTAT
	quit

VBREAK	//
	type Public Number VD(),vh(),VH0,vs(),VT()
	quit:'VT(4)
	type Public String vc1,vovc1,vc2,vovc2,vc3,vovc3,vc4,vovc4
	type Number vb1,vb2,vb3,vb4
	set (vb1,vb2,vb3,vb4)=0
	if vb1!(vovc1'=vc1) set vs(2)=0,vh(2)=0,VD(1)=0,vb2=1,vb3=1,vb4=1
	if vb2!(vovc2'=vc2) set vs(3)=0,vh(3)=0,VD(2)=0,vb3=1,vb4=1
	if vb3!(+vovc3'=+vc3) set vs(4)=0,vh(4)=0,VD(3)=0,vb4=1,VH0=1
	quit

VSUM	// Report Group Summary
	type Public Number VFMQ,vs()
	if 'vs(4) set vs(4)=1 do VSUM4 quit:VFMQ  do stat^DBSRWUTL(4)
	if 'vs(3) set vs(3)=1 do stat^DBSRWUTL(3)
	if 'vs(2) set vs(2)=1 do stat^DBSRWUTL(2)
	quit

VSTAT	// Data field statistics
	type Public Number VRWOPT(),VT(),vc11,vc10,vc14,vc12,vc15,vc13,vc5,vc6,vc7,vc8,vc9
	type Public String VSTATS

	set VT(4)=VT(4)+1
	set VT(4,1,1)=VT(4,1,1)+vc11			// @TOT([LN]ACR)
	set VT(4,2,1)=VT(4,2,1)+vc10			// @TOT([LN]BALCMP)
	set VT(4,3,1)=VT(4,3,1)+vc14			// @TOT([LN]IYTD)
	set VT(4,4,1)=VT(4,4,1)+vc12			// @TOT([LN]LCHG)
	set VT(4,5,1)=VT(4,5,1)+vc15			// @TOT([LN]MCHG)
	set VT(4,6,1)=VT(4,6,1)+vc13			// @TOT([LN]NCOA)
	if VRWOPT("NOSTAT").get() quit
	do vstats^DBSRWUTL(1,vc5,vc6,"[LN]IRN|N|[LN]BAL|",.VSTATS)
	do vstats^DBSRWUTL(2,vc7,vc6,"[LN]INDEX|T|[LN]BAL|",.VSTATS)
	do vstats^DBSRWUTL(3,vc8,vc6,"[LN]COLCD|T|[LN]BAL|",.VSTATS)
	do vstats^DBSRWUTL(4,vc9,vc6,"[LN]CC|N|[LN]BAL|",.VSTATS)
	quit

VDTL4	// Detail
	type public String %TIM,GRP,IOSL,RDES,RTDES,TRAIL,TTDES,TYPE,V,VD(),VFMQ,VL,VLC,VO,VOFFLG,VPN,VRG,VT(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc21,vc22,vc23,vc24,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	if VLC+6>IOSL do VHDG0 quit:VFMQ

	set V=vc4,VO=V do VP1 quit:VFMQ!verror.get()  set V=$J(V,12) set VL=V
	set VL=VL_$J("",13-VL.length())_$J(vc9,6)
	set VL=VL_$J("",20-VL.length())_$E(vc16,1,20)
	set VL=VL_$J("",41-VL.length())_$J($FN(vc10,",",2),12)
	set VL=VL_$J("",54-VL.length())_$J($$DAT^%ZM(vc17),10)
	set VL=VL_$J("",72-VL.length())_$J($$DAT^%ZM(vc18),10)
	set VL=VL_$J("",83-VL.length())_$J($FN(vc11,",",2),8)
	set VL=VL_$J("",92-VL.length())_$J(vc19,8,2)
	set VL=VL_$J("",101-VL.length())_$J($FN(vc12,",",2),12)
	set VL=VL_$J("",115-VL.length())_$J($$DAT^%ZM(vc20),10)
	do VOM
	set VL="                                         "_$J($FN(vc13,",",2),12)
	set VL=VL_$J("",54-VL.length())_$J($FN(vc21,",",2),8)
	set VL=VL_$J("",63-VL.length())_$J(vc5,8,2)
	set VL=VL_$J("",72-VL.length())_$J($$DAT^%ZM(vc22),10)
	set VL=VL_$J("",83-VL.length())_$J($FN(vc14,",",2),8)
	set VL=VL_$J("",93-VL.length())_$E(vc23,1,12)
	set VL=VL_$J("",106-VL.length())_$J($FN(vc15,",",2),7)
	do VOM
	set VL="" do VOM
	quit

VSUM4	// Summary
	type public String %TIM,GRP,I,IOSL,RDES,RTDES,TRAIL,TTDES,TYPE,V,VFMQ,VL,VLC,VO,VOFFLG,VPN,VT(),VX(),vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc21,vc22,vc23,vc24,vc3,vc4,vc5,vc6,vc7,vc8,vc9,verror,vh(),vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate

	if 'VT(4) quit
	if VLC+4>IOSL do VHDG0 quit:VFMQ

	do VP2 quit:VFMQ!verror.get()  set V=$E(TTDES,1,30) set VL=V
	set V=VT(4,2,1)					// @TOT([LN]BALCMP,)
	set VL=VL_$J("",41-VL.length())_$J($FN(V,",",2),12)
	set V=VT(4,1,1)					// @TOT([LN]ACR,)
	set VL=VL_$J("",83-VL.length())_$J($FN(V,",",2),8)
	set V=VT(4,4,1)					// @TOT([LN]LCHG,)
	set VL=VL_$J("",105-VL.length())_$J($FN(V,",",2),8)
	do VOM
	set V=VT(4,6,1)					// @TOT([LN]NCOA,)
	set VL="                                         "_$J($FN(V,",",2),12)
	set V=VT(4,3,1)					// @TOT([LN]IYTD,)
	set VL=VL_$J("",83-VL.length())_$J($FN(V,",",2),8)
	set V=VT(4,5,1)					// @TOT([LN]MCHG,)
	set VL=VL_$J("",105-VL.length())_$J($FN(V,",",2),8)
	do VOM
	quit


VHDG0	// Page Header
	type Public Number ER,IOSL,vcrt,verror,VFMQ,vh(),VLC,VNEWHDR,VPN,VRG,VRWOPT()
	type public String %MSKD,%TIM,CONAM,GRP,RDES,RID,RN,RTDES,TRAIL,TTDES,TYPE,VL,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc21,vc22,vc23,vc24,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate
	type Number PN,V,VO
	if VRWOPT("NOHDR").get() quit			// Skip page header
	set vh(0)=1,VRG=0
	if VL'="" do VOM
	if VPN do VTRL0
	if vcrt,VPN>0 do { quit:VFMQ!'VNEWHDR
		type Number PN,X
		set VL=""
		for X=VLC+1:1:IOSL do VOM
		set PN=VPN
		do ^DBSRWBR(2)
		set VLC=0
		quit:VFMQ
		if VNEWHDR write $$CLEARXY^%TRMVT
		else  set VLC=VLC+9,VPN=VPN+1
		}

	set ER=0,VPN=VPN+1,VLC=0

	set VL=$E($G(CONAM),1,45)
	set VL=VL_$J("",100-VL.length())_"Run Date:"
	set VL=VL_$J("",110-VL.length())_$E(vrundate,1,10)
	set VL=VL_$J("",123-VL.length())_$E(%TIM,1,8)
	do VOM
	set VL=RN_"  ("_RID_")"
	set VL=VL_$J("",97-VL.length())_"System Date:"
	set VL=VL_$J("",110-VL.length())_$E(vsysdate,1,10)
	set VL=VL_$J("",122-VL.length())_"Page:"
	set VL=VL_$J("",128-VL.length())_$J(VPN,3)
	do VOM
	set VL="" do VOM
	do VP3 quit:VFMQ!verror.get()  set V=$E(RDES,1,80) set VL=V
	do VOM
	set VL="" do VOM
	set VL="   "_"Account #     CC Account Title             Balance Org Date          Last Tran  Accr Int  Pmt Amt       LC Due  Note Date"
	do VOM
	set VL="                                             "_"Chrg Off Crd Limt Int Rate  Next Due   Int YTD  Pmt Freq      MC Due"
	do VOM
	set VL="===================================================================================================================================="
	do VOM
	set VL="" do VOM

	set VNEWHDR=0
	if vcrt set PN=VPN do ^DBSRWBR(2,1)		// Lock report page heading

	quit


VTRL0	// Page Trailer
	type Public Number IOSL,verror,vh,VFMQ,VLC,VT(),VX()
	type Public String %TIM,GRP,RDES,RTDES,TRAIL,TTDES,TYPE,VPN,vc1,vc10,vc11,vc12,vc13,vc14,vc15,vc16,vc17,vc18,vc19,vc2,vc20,vc21,vc22,vc23,vc24,vc3,vc4,vc5,vc6,vc7,vc8,vc9,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate
	type Number I
	type String VL

	set VL=""
	for I=VLC:1:IOSL-3 do VOM

	do VP4 quit:VFMQ!verror.get()  set V=$E(RTDES,1,30) set VL=V
	set V=0						// @TOT([LN]BALCMP,)
	for I=0:1:4 set V=V+VT(I,2,1)
	set VL=VL_$J("",44-VL.length())_$J($FN(V,",",2),9)
	set V=0						// @TOT([LN]ACR,)
	for I=0:1:4 set V=V+VT(I,1,1)
	set VL=VL_$J("",83-VL.length())_$J($FN(V,",",2),8)
	set V=0						// @TOT([LN]LCHG,)
	for I=0:1:4 set V=V+VT(I,4,1)
	set V=$J($FN(V,",",2),8) do VP5 quit:VFMQ!verror.get()
	set VL=VL_$J("",105-VL.length())_V		// @TOT([LN]LCHG,)
	do VOM
	set V=0						// @TOT([LN]NCOA,)
	for I=0:1:4 set V=V+VT(I,6,1)
	set VL="                                            "_$J($FN(V,",",2),9)
	set V=0						// @TOT([LN]IYTD,)
	for I=0:1:4 set V=V+VT(I,3,1)
	set VL=VL_$J("",83-VL.length())_$J($FN(V,",",2),8)
	set V=0						// @TOT([LN]MCHG,)
	for I=0:1:4 set V=V+VT(I,5,1)
	set V=$J($FN(V,",",2),8) do VP6 quit:VFMQ!verror.get()
	set VL=VL_$J("",105-VL.length())_V		// @TOT([LN]MCHG,)
	do VOM
	quit

VRSUM	// Report Summary
	type Public Number IOSL,verror,VFMQ,vh,VLC,VT(),VX()
	type Public String %TIM,GRP,RDES,RTDES,TRAIL,TTDES,TYPE,VPN,vovc1,vovc2,vovc3,vovc4,vrundate,vsysdate
	type Number I
	type String V,VL

	set VL=""
	if 'vh(0) do VHDG0 quit:VFMQ
	if VLC+3>IOSL do VHDG0 quit:VFMQ

	do VP7 quit:VFMQ!verror.get()  set V="====================================================================================================================================" set VL=V
	do VOM
	set VL="Report Totals"
	set V=0						// @TOT([LN]BALCMP,0)
	for I=0:1:4 set V=V+VT(I,2,1)
	set VL=VL_$J("",41-VL.length())_$J($FN(V,",",2),12)
	set V=0						// @TOT([LN]ACR,0)
	for I=0:1:4 set V=V+VT(I,1,1)
	set VL=VL_$J("",81-VL.length())_$J($FN(V,",",2),10)
	set V=0						// @TOT([LN]LCHG,0)
	for I=0:1:4 set V=V+VT(I,4,1)
	set VL=VL_$J("",103-VL.length())_$J($FN(V,",",2),10)
	do VOM
	set V=0						// @TOT([LN]NCOA,0)
	for I=0:1:4 set V=V+VT(I,6,1)
	set VL="                                         "_$J($FN(V,",",2),12)
	set V=0						// @TOT([LN]IYTD,0)
	for I=0:1:4 set V=V+VT(I,3,1)
	set VL=VL_$J("",81-VL.length())_$J($FN(V,",",2),10)
	set V=0						// @TOT([LN]MCHG,0)
	for I=0:1:4 set V=V+VT(I,5,1)
	set VL=VL_$J("",103-VL.length())_$J($FN(V,",",2),10)
	do VOM
	quit

VOM	// Output print line
	type Public Number AUXPTR,vcrt,vlc,VLC,VRG
	type Public String IO,VL

	use IO

	// Advance to a new page
	if 'VLC,'vcrt do {				// Non-CRT device (form feed)
		if 'AUXPTR.get() write $C(12),!
		else  write $$PRNTFF^%TRMVT,!
		set $Y=1
		}

	if vcrt<2 write VL,!				// Output line buffer
	if vcrt set vlc=vlc+1 do VBRSAVE(vlc,VL)	// Save in BROWSER buffer
	set VLC=VLC+1,VL=""				// Reset line buffer
	quit

	// Pre/post-processors

VP1	// Column pre-processor - [SYSDEV,LN]CID

	type public Boolean TRAIL
 
	set TRAIL=1
	quit

VP2	// Column pre-processor - Variable: TTDES

	type public String TTDES
	type public Number TYPE
	type public Boolean TRAIL
 
	// Totals - Type
	set TTDES=$$^MSG(6307,TYPE)
	set TRAIL=0
	quit

VP3	// Column pre-processor - Variable: RDES

	type public String vc3,vc2,vc24
	type public String GRP,RDES
	type public Number TYPE
 
	set TYPE=vc3
	set GRP=vc2
 
	// Report Totals
	if TYPE.isNull() set RDES=$$^MSG(6304) quit
 
	// Group  Product Type
	set RDES=$$^MSG(6309,GRP,TYPE)
 
	set RDES=RDES_" - "_vc24
	quit

VP4	// Column pre-processor - Variable: RTDES

	type public String RTDES
	type public Number TYPE
 
	// Running Totals -
	set RTDES=$$^MSG(6308,TYPE)
 
	quit

VP5	// Column post-processor - @TOT([LN]LCHG,,E,8)

	type public Boolean TRAIL
	type public String V,VL
 
	if TRAIL quit
	set V=""
	set VL=""
 
	quit

VP6	// Column post-processor - @TOT([LN]MCHG,,E,8)

	type public Boolean TRAIL
	type public String V,VL

	if TRAIL quit
	set V=""
	set VL=""
 
	quit

VP7	// Column pre-processor - @CHR(=,132)

	type public Number VLC

	if VLC>10 do VHDG0
	quit
