SCAHDG	  /*
	ORIG: alagarss - 08/11/2005
	DESC: SCA standard heading routine

	-------------- Comments ----------------------------------------------

	-------------- Revision History --------------------------------------
	
	03/29/2006 - SATYANAS - CR19687
			Added the call to START and Replaced Public by public.
	
	08/11/2005 - ALAGARSS - CR16677
	                Converted to PSL.
	                Also removed the revision history prior to 2004.
	   
	----------------------------------------------------------------------
 	*/
 	
	do START
	quit
	
	
START	// 
	type public Number QUIT,PN,X,IORM,AUXPTR,%I,%HDR
	type public String IOTYP,CONAM,RN,HDG
	type public Date %ED,%MSKD
	type public IO IO
	
	set QUIT=""
	if 'PN.get() set PN=1
	if 'IORM.get() set IORM=79
	if '%ED.data() set %ED=(%CurrentDate).toString(%MSKD.get())
	if PN=-1 do EXIT quit
	if PN=1 do {
		if AUXPTR.get() write $$PRNTON^%TRMVT
	}
	else  do WAIT  quit:QUIT
	
	write !,#
	// Run date
	use IO write CONAM,?IORM-29,$$^MSG("3693"),(%CurrentDate).toString(%MSKD.get())," ",$$EXT^%T,!
	// EFFECTIVE:
	// PAGE
	write RN,?IORM-30,$$^MSG("3689"),%ED,$$^MSG(2125,$J(PN,3)),!
	set PN=PN+1
	set %HDR=0 
	for %I=1:1 set %HDR=$O(HDG(%HDR))  quit:%HDR=""  write !,HDG(%HDR)
	write !
	quit
	//
WAIT	//
	type public Number QUIT,AUXPTR,X
	type public IO IO
	
	//Aux port printer
	if AUXPTR.get() quit	
	if IO.data() quit
	//Not principal device			
	if IO'=$P quit		
	// Press RETURN to continue or <Q>uit:
	use 0 write !!,$$^MSG("4409")
	set X=$$TERM^%ZREAD("",2)
	if $$UPPER^%ZFUNC(X)="Q" set QUIT=1
	quit
	//
EXIT	//
	type public String IOTYP
	type public Number PN,X
	if IOTYP="TRM" do {
		//End of report .... Press RETURN to continue:
		use 0 W !!,$$^MSG("4819")
		set X=$$TERM^%ZREAD("",1)
	}
	//Close device
	else  do CLOSE^SCAIO 
	use 0
	kill PN
	quit

vSIG()	quit "60354^2099^Sethy, Satyanarayan^1732"	// Signature - LTD^TIME^USER^SIZE
