SCATIM1	//
 /*
 ORIG: chhabris - 07/31/2005
 DESC: CONVERT TIME IN SECONDS TO EXT PRNT FORM

 ---- Comments --------------------------------------------------------
	CALLED BY:  ^GLSPNT
	    CALLS:  
	 PROJ #'S:
	     DESC:  Convert Time in Seconds to External print format
	 	     Input  %TN (NNNNN)
		     Output %TS HH:MM PM/AM
	 GLOBALS -  
	     READ:
	      SET:
	
	 KEYWORDS: Date and Time
	
	 INPUTS:
		. %TN 	Time in seconds since 		/TYP=N
			Midnight
	 RETURNS:
		. %TS 	Time in string format		/TYP=T/REQ
			For example 1130   1:00P   13:00  2:00A  
			T or C (Current Time)
	
	 RELATED:
		. D NS^SCATIM	Returns formatted time from time in seconds
		. D ^SCATIM	Returns time in seconds from formatted time
	
 ---- Revision History ------------------------------------------------------
	03/29/2006 - GIRIDHARANL - CR20409
		     CR-20409. Changed existing conditional SET to a IF - DO 
		     structure to circumvent an issue where M was not 
		     recognizing the comma separator as an AND between the 
		     two SET statements. 
	07/29/2005 - CHHABRIS - CR16677
		     Converted to PSL.	
 ----------------------------------------------------------------------------
 
 */
 
	
 
public INT	// 
	type public Number ER,%I,%M,%S,%TN
	type public String %N,%TS
	type Number TS

	if %TN.isNull() set ER=1,%TS="" quit
	if %TN > 86400 set ER=1,%TS="" quit
	
	set %M = %TN , %S = $J(%M#60,2) , %M=%M\60

	//  AM
	//  PM
	set %N = $$^MSG("4891") 
	if %M '< 720 do {
		set %M=%M-720
		set %N=$$^MSG("4892")
		}
	set:%M < 60 %M = %M + 720
	set %I = %M\600
	set:'%I %I = " "
	set TS = %S+100
	set %S = TS.extract(2,3)
	set %TS=%I_((%M\60)#10)_":"_((%M#60)\10)_(%M#10)
	set %TS = %TS_%N
	quit
 

vSIG()	quit "60353^53381^Lakshmi Giridharan^1615"	// Signature - LTD^TIME^USER^SIZE
