STMREG // Statement Imaging file open and close
  /*
	ORIG: kumarb - 01/30/2006
	DESC: Statement Imaging file open and close

	---- Revision History ------------------------------------------------
	
	12/21/06 - PUTTASWH - CR 24538
		   Modified to declare OPNFILE and CLSFILE sections as public.
	
	01/30/06 - KUMARB - CR17423
		Retrofit the section called from BCHLETSTM. 

	----------------------------------------------------------------------
	
 */
 
 	quit

public OPNFILE	//

	type public String STMFILE

	type Number FILETYP,X
	type String DIR,INST
	
        set INST=CUVAR.co
        set FILETYP=2
        type RecordUTBLSTMDIR stmdir=Db.getRecord("UTBLSTMDIR","FILETYP=:FILETYP",1)
        set DIR=stmdir.dir
        set STMFILE=DIR_INST_"_STMT_"_%SystemDate.toString("YEARMMDD")_".dat"
	set X=0
        set X=$$FILE^%ZOPEN(STMFILE,"NEWV") if 'X do Runtime.setErrMSG("",2799,STMFILE) quit
        if X use STMFILE write INST,!! use 0

        quit
        
public CLSFILE //

	type public String STMFILE
	
	CLOSE STMFILE
	
        quit

vSIG()	quit "60627^21345^Hema Puttaswamy^955"	// Signature - LTD^TIME^USER^SIZE
