SUBPROC(CID,SEQ,ETC,TSO,XITC)
 /*
ORIG: MALTEPESA - 04/12/2000
DESC: Sub-account transaction processing


---- Revision History ------------------------------------------------

	
	06/18/03 - CARROLLJ - 51349
		   Modified PSTR section to change call to LNTRB.

	08/22/02 - MALTEPESA - 50894
		   Corrected logic, throughout the whole procedure.
		   Modiifed INIT section, remove zero after quit.

 */

INIT	//

	if SEQ#1 quit
	type RecordTRN trn=Db.getRecord("TRN","ETC")
	//allow bank transaction flag
	quit:'trn.pcfl40

	new currcid,nonacrcid,chgcid,ETCOFF,XCID
        new DRTRPR,CRTRPR,DRADIN,CRADIN,CRTRPE,DRTRPE,DRTRMF,CRTRMR
        new CIDOFF,CRCD,GLSC,OCC,TYPE

	set ER=0
        set TCMT=""
	set TLO=%UserStation
	type RecordLN ln=Db.getRecord("LN","CID")

      	//if not a problem loan account
	if 'ln.paoi quit
	
	//check if this is a sub-account for a problem loan
	if ln.pcidstat quit
	
	
	set TYPE=ln.type
	set GLSC=ln.glsc        // general leger set code
	set CRCD=ln.crcd
	set OCC=ln.cc		//cost center

	type RecordPRODCTL prod=Db.getRecord("PRODCTL","TYPE=:TYPE")
	set DRTRPR=prod.drtrpr          //DR Principal Tran Code
	set CRTRPR=prod.crtrpr  //CR Principal Tran Code
	set DRADIN=prod.dradin          //DR Interest Tr Code
	set CRADIN=prod.cradin          //CR Interst Tr code
	set DRTRPE=prod.drtrpe          //DR Late Chg Tr code
	set CRTRPE=prod.crtrpe          //CR Late Chg TR Code
	set DRTRMFI=prod.drtrmfi	//Curr DR Fee TR Code
	set CRTRMFR=prod.crtrmfr	//Curr CR fee TR code
	set COKO=prod.coko
 

	do OUT^UTSO(.TSO,TSO)
	// find the appropriate subaccount based upon a customer
        //view account number and status
 
        type ResultSet rs=Db.select("CID","LN","CVCID=:CID AND STAT=0 AND PCIDSTAT=1")
        if 'rs.isEmpty() set A=rs.next(),XCID=rs.getRow() do PROCCUR(XCID) quit:ER
 
        type ResultSet rs=Db.select("CID","LN","CVCID=:CID AND STAT=0 AND PCIDSTAT=2")
        if 'rs.isEmpty() set A=rs.next(),nonacrcid=rs.getRow() do PROCNA(nonacrcid) quit:ER
 
        type ResultSet rs=Db.select("CID","LN","CVCID=:CID AND STAT=0 AND PCIDSTAT=3")
        if 'rs.isEmpty() set A=rs.next(),chgcid=rs.getRow() do PROCCHG(chgcid) quit:ER 
	
	quit
	
PROCCUR(XCID)	// process current sub-account
			
	type RecordLN ln=Db.getRecord("LN","XCID")
	//gl set code for current sub-account
	set GLSC=ln.glsc              
	type RecordUTBLGLSC utblglsc=Db.getRecord("UTBLGLSC","GLSC")

	
	if TSO["CRNP" do { quit:ER
		set XTSO=$$FIELDIN^UTSO(TSO,"CRNP",XCID)
		set TAMT=$$FIELD^UTSO(TSO,"CRNP")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRPR,1:CRTRPR)
		set CIDOFF=utblglsc.lglpo
		do PSTR

		}
	
	if TSO["CRNI" do { quit:ER
		set XTSO=$$FIELDIN^UTSO(TSO,"CRNI",XCID)
		set TAMT=$$FIELD^UTSO(TSO,"CRNI")
 		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRADIN,1:CRADIN)
		set CIDOFF=utblglsc.lglio
                do PSTR
	}

	if TSO["CRNF" do { quit:ER
		set XTSO=$$FIELDIN^UTSO(TSO,"CRNF",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"CRNF")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRMFI,1:CRTRMFR)
		set CIDOFF=utblglsc.lglfee
                do PSTR 
		}
	
	if TSO["CRNLC" do { quit:ER
		set XTSO=$$FIELDIN^UTSO(TSO,"CRNLC",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"CRNLC")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRPE,1:CRTRPE)
		set CIDOFF=utblglsc.lgllc
                do PSTR
		}
	quit
	
	
PROCNA(XCID)	//	 process non-accural sub-accounts

	type RecordLN ln=Db.getRecord("LN","XCID")
	//gl set code for current sub-account
	set GLSC=ln.glsc              
	type RecordUTBLGLSC utblglsc=Db.getRecord("UTBLGLSC","GLSC")


	if TSO["NAP" do { quit:ER
		set XTSO=$$FIELDIN^UTSO(TSO,"NAP",XCID)
		set TAMT=$$FIELD^UTSO(TSO,"NAP")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRPR,1:CRTRPR)
		set CIDOFF=utblglsc.lglpo
		do PSTR
		}
	
	if TSO["NAI" do { quit:ER
                set XTSO=$$FIELDIN^UTSO(TSO,"NAI",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"NAI")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRADIN,1:CRADIN)
		set CIDOFF=utblglsc.lglio
                do PSTR
	}

	if TSO["NAF" do { quit:ER
                set XTSO=$$FIELDIN^UTSO(TSO,"NAF",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"NAF")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRMFI,1:CRTRMFR)
		set CIDOFF=utblglsc.lglfee
                do PSTR
		}	
	if TSO["NALC" do { quit:ER
		set XTSO=$$FIELDIN^UTSO(TSO,"NALC",XCID)
		set TAMT=$$FIELD^UTSO(TSO,"NALC")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRPE,1:CRTRPE)
		set CIDOFF=utblglsc.lgllc
		do PSTR 
		}
	quit

PROCCHG(XCID)		//Process the charge-off sub-account account

	type RecordLN ln=Db.getRecord("LN","XCID")
	//gl set code for current sub-account
	set GLSC=ln.glsc
	type RecordUTBLGLSC utblglsc=Db.getRecord("UTBLGLSC","GLSC")

	if TSO["COP" do { quit:ER
                set XTSO=$$FIELDIN^UTSO(TSO,"COP",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"COP")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRPR,1:CRTRPR)
		set CIDOFF=utblglsc.lglpo
                do PSTR
		}
	if TSO["COI" do { quit:ER
		set XCID=chgcid
                set XTSO=$$FIELDIN^UTSO(TSO,"COI",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"COI")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRADIN,1:CRADIN)
		set CIDOFF=utblglsc.lglio
		do PSTR
		}
	if TSO["COF" do { quit:ER
		set XCID=chgcid
                set XTSO=$$FIELDIN^UTSO(TSO,"COF",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"COF")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRMFI,1:CRTRMFR)
		set CIDOFF=utblglsc.lglfee
		do PSTR
		}
	if TSO["COLC" do { quit:ER
                set XTSO=$$FIELDIN^UTSO(TSO,"COLC",XCID)
                set TAMT=$$FIELD^UTSO(TSO,"COLC")
		set ETCOFF=$S(XITC=0:"MCR",1:"MDR")
		set XETC=$S(XITC=0:DRTRPE,1:CRTRPE)
		set CIDOFF=utblglsc.lgllc
		do PSTR
		}
	quit


PSTR	//   post secondary transactions for the sub-accounts


	/*
        Posting Offset Account Not Defined
        - Posting Halted for Sub-Account ~p1
        Posting Tran Code Not Defined
        - Posting Halted for Sub-Account  ~p1
        */


	if XETC="" set ER=1,RM=$$^MSG(4312,XCID) quit 
        if CIDOFF="" set ER=1,RM=$$^MSG(4311,XCID) quit

	do POST^LNTRB(,XCID,XETC,TAMT,%EffectiveDate,TLO,XTSO,TCMT,CRCD,OCC)
	do POST^LNTRB(,CIDOFF,ETCOFF,TAMT,%EffectiveDate,TLO,XTSO,TCMT,CRCD,OCC)

	quit
 

vSIG()	quit "59886^43612^Sanchez SCM Administrator^6176"	// Signature - LTD^TIME^USER^SIZE
