TMP031	// DBSEDIT temporary filer compiled program
	// Last compiled:  02/05/2007 09:37 AM - shetyes

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 310)
	type RecordCTBLCTC rec = Db.getRecord("CTBLCTC","CTYP='NATIVE'",1)
	do rec.setAuditFlag(1)
	set rec.DESC = "NATIVE CLIENT"
	set rec.DIR = "SCAU$DDP"
	set rec.CFILE = ""
	set rec.FILENO = "3958"
	do rec.save()
	quit
