TMP4078	// DBSEDIT temporary filer compiled program
	// Last compiled:  11/22/2006 11:59 PM - rd

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 4078)
	type RecordCTBLMTM rec = Db.getRecord("CTBLMTM","MTMID='P04DHA'",1)
	do rec.setAuditFlag(1)
	set rec.DESC = "MTM"
	set rec.STARTUP = "/v70modelbanklx/mtm/V70DHA"
	do ^DBSLOGIT(rec, rec.getMode())
	do rec.save()
	quit
