TMP4194	// DBSEDIT temporary filer compiled program
	// Last compiled:  09/13/2006 05:46 PM - kini

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 14194)
	type RecordSCATBL5 rec = Db.getRecord("SCATBL5","RPCID='121'",1)
	do rec.setAuditFlag(1)
	set rec.%SN = "PBS"
	set rec.DESC = "Profile Interface Toolbox"
	set rec.MRPC = "$$^MRPC121"
	set rec.LOGFLG = "1"
	set rec.PARAM01 = "1"
	set rec.PARAM02 = "1"
	set rec.PARAM03 = "1"
	set rec.PARAM04 = "1"
	set rec.PARAM05 = "1"
	set rec.PARAM06 = "1"
	set rec.PARAM07 = "1"
	set rec.PARAM08 = "1"
	set rec.PARAM09 = "0"
	set rec.PARAM10 = "0"
	set rec.PARAM11 = "0"
	set rec.PARAM12 = "0"
	set rec.PARAM13 = "0"
	set rec.PARAM14 = "0"
	set rec.PARAM15 = "0"
	set rec.PARAM16 = "0"
	set rec.PARAM17 = "0"
	set rec.PARAM18 = "0"
	set rec.PARAM19 = "0"
	set rec.PARAM20 = "0"
	set rec.PARAM21 = "0"
	set rec.PARAM22 = "0"
	set rec.PARAM23 = "0"
	set rec.PARAM24 = "0"
	set rec.PARAM25 = "0"
	do ^DBSLOGIT(rec, rec.getMode())
	do rec.save()
	quit
