TMP6296	// DBSEDIT temporary filer compiled program
	// Last compiled:  02/27/2007 06:49 AM - dasarav

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 16296)
	type RecordUTBLCOLLST rec = Db.getRecord("UTBLCOLLST","OPT='11'",1)
	do rec.setAuditFlag(1)
	set rec.DSPDESC = "Bankruptcy"
	set rec.DES = "Bankruptcy"
	set rec.COLEXTRFLG = "0"
	do ^DBSLOGIT(rec, rec.getMode())
	do rec.save()
	quit
