TMP7392	// DBSEDIT temporary filer compiled program
	// Last compiled:  09/18/2006 01:31 PM - mullend

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 7392)
	type RecordUTBLCDM rec = Db.getRecord("UTBLCDM","KEY='MOD10'",1)
	do rec.setAuditFlag(1)
	set rec.DESC = "MOD10"
	set rec.PGM = "^UCDC"
	set rec.WT = "37137137137"
	set rec.MOD = "10"
	set rec.POS = "1"
	set rec.SO = "1"
	set rec.SP = ""
	set rec.MSK = ""
	do ^DBSLOGIT(rec, rec.getMode())
	do rec.save()
	quit
