TMP9417	// DBSEDIT temporary filer compiled program
	// Last compiled:  12/06/2006 09:35 AM - root

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 19417)
	type RecordCTBLMTM rec = Db.getRecord("CTBLMTM","MTMID='V70GTM'",1)
	do rec.setAuditFlag(1)
	set rec.DESC = "mtm for v70gtm"
	set rec.STARTUP = "/v70gtm/mtm/V70GTM"
	do ^DBSLOGIT(rec, rec.getMode())
	do rec.save()
	quit
