TMP9244	// DBSEDIT temporary filer compiled program
	// Last compiled:  02/23/2007 07:11 AM - chennark

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 9244)
	type RecordUTBLRELMAT rec = Db.getRecord("UTBLRELMAT","MATRIX='TEST'",1)
	do rec.setAuditFlag(1)
	set rec.MATDESC = "TEST1"
	set rec.ROWATT = "2"
	set rec.COLATT = "1"
	do ^DBSLOGIT(rec, rec.getMode())
	do rec.save()
	quit
