TMP9859	// DBSEDIT temporary filer compiled program
	// Last compiled:  01/17/2007 08:53 AM - root

	// THIS IS A COMPILED ROUTINE.  Compiled by procedure DBSEDIT

	quit:(%ProcessID '= 29859)
	type RecordCTBLMTM rec = Db.getRecord("CTBLMTM","MTMID='V72QA'",1)
	do rec.setAuditFlag(1)
	set rec.DESC = "mtm for v72qa_gtmlx"
	set rec.STARTUP = "/v72qa_gtmlx/mtm/V72QA_GTMLX"
	do ^DBSLOGIT(rec, rec.getMode())
	do rec.save()
	quit
