UMLTCNT	//Public ;Compute total number of accounts per type
	/*
	   ORIG:
	   Calculates total number of accounts for a specified product type/
	   currency code.  Used to do the computation for PRODDFTD.CNT and
	   PRODDFTL.CNT.

	   KEYWORDS: Data dictionary

	   LIBRARY:
	   . CNT - Computes count based on accrual processing totals

	  ---- Revision History ------------------------------------------------
	  
	   01/26/06 - KinI - 16664
	              Removed CNT2 section as A) unused B) the logic based 
	              on calculating the number of accounts from obsolete 
	              XREFXCRCD index table.
	              
	   01/06/05 - ARPAVC - 13861
	  	      Fixed compile errors and miscellaneous issues
		      due to conversion.  
		      - Properly scoped all variables
		      
	   04/10/02 - CHHABRIAS - 49794
		      Converted to PSL
	*/
	
	quit


public	CNT(String CLS,		// Class   /REQ
	    String GRP,		// Group   /REQ
	    Number TYPE,	// Product type  /REQ
	    String CRCD)	// Currency Code  /NOREQ	

	/* Compute number of accounts for PRODDFTD/PRODDFTL.CNT

	   Based on values in ^TTL, which are set up by the prior day's
	   accrual processing.

	   KEYWORDS: Data dictionary

	   RETURNS:
	   . $$  Count of accounts /TYP=N

	   EXAMPLE:
	   S COUNT=$$CNT^UMLTCNT(CLS,GRP,TYPE,CRCD)

	*/

	type Number CC, CNT, CLOSED, OPEN
	type String GLSC
	type Date TTLDATE

	if CLS="" set CLS=0
	if GRP="" set GRP=0
	if TYPE="" set TYPE=0
	if (CRCD="")&(CLS="*") set CRCD=0
	if CRCD="" set CRCD=%SystemCurrency
	set (CNT,CLOSED,OPEN)=0

	// Find total from yesterday's accruals
	set TTLDATE=%SystemDate-1
	type ResultSet rs=Db.select("GLSC,CC","TTL","TJD=:TTLDATE AND CRCD=:CRCD AND CLS=:CLS AND GRP=:GRP AND TYPE=:TYPE","GLSC,CC")
	while rs.next()  do {
		set GLSC=rs.getCol("GLSC")
		set CC=rs.getCol("CC")
		type RecordTTL ttl=Db.getRecord("TTL","TJD=:TTLDATE,CRCD=:CRCD,CLS=:CLS,GRP=:GRP,TYPE=:TYPE,GLSC=:GLSC,CC=:CC")
		set CLOSED=CLOSED+ttl.closed
		set OPEN=OPEN+ttl.open
		}
	set CNT=CLOSED+OPEN

	quit CNT

vSIG()	quit "60291^54810^Irina Kin^1902"	// Signature - LTD^TIME^USER^SIZE
