URECL2	//
	/*
	ORIG: chhabris - 08/11/2005
	DESC: Non-replicated report delete

	---- Comments --------------------------------------------------------
	DESC:	Non-replicated report delete
	
	KEYWORDS:	Non-replicated Transaction
	
	The routine will be used to delete global ^norepd and ^norepr 
	used by non-replicated report.
	
	---- Revision History ------------------------------------------------

	*/

 	type public Number I,ON,SEQ,VFMQ
 	type public Date XDATE(),X1
 	type public String FILE(),OPT1()
 	type String %TAB,%READ,MS,TMP,X2

	// Delete non-replicated transaction file
	set MS=$$^MSG(3790)

	set X1="",I=1
	type ResultSet rs=Db.select("DATE1,FILE","URECL1",,"DATE1 DESC")
	while rs.next() do {
		set XDATE(I)=rs.getCol("DATE1")
		set FILE(I)=rs.getCol("FILE")
		set OPT1(I)=$$DAT^%ZM(XDATE(I))_$C(9)_FILE(I)
		set I=I+1
		}

	set %TAB("SEQ")="/DES=Non-replicated Transaction File/LEN=10/TBL=OPT1("

	set %READ="@MS/CEN/REV,,SEQ/REQ"
	do ^UTLREAD
	if VFMQ="Q" quit

	do Db.fastDelete("URECD","TIMESEQ=:XDATE(SEQ),JRNLFILE=:FILE(SEQ)")
	do Db.fastDelete("URECL1","DATE1=:XDATE(SEQ),FILE=:FILE(SEQ)")

	quit
 

vSIG()	quit "60178^29168^Sanjay Chhrabria^1069"	// Signature - LTD^TIME^USER^SIZE
