V00S438(%ProcessMode,RecordQUEUEJ fQUEUEJ)   //SCA - U - SID= <QUEUEJ> Job Level Maintenance (Queuing)
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:59 - kini
 //  /*
 //  This screen identifies user-specified values that control Queuing system
 //  processing at the job level and provides status information about the last job
 //  run.  It is used by the Create Batch/Job (QUECRE), Modify Batch/Job (QUEUPD),
 //  and Delete Batch/Job (QUEDEL) functions.
 //  */
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="QUEUEJ",VPGM=$T(+0),VSNAME="Job Level Maintenance (Queuing)"
 set VFSN("QUEUEJ")="zfQUEUEJ"
 set vPSL=1
 set KEYS(1)=fQUEUEJ.BCHNUM
 set KEYS(2)=fQUEUEJ.JOBNUM
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fQUEUEJ),VDA1(.fQUEUEJ),^DBSPNT()

 if '%ProcessMode do VNEW(.fQUEUEJ),VPR(.fQUEUEJ),VDA1(.fQUEUEJ)
 if %ProcessMode do VLOD(.fQUEUEJ) quit:$G(ER)  do VPR(.fQUEUEJ),VDA1(.fQUEUEJ)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fQUEUEJ)
	quit


VNEW(RecordQUEUEJ fQUEUEJ) // Initialize arrays if %O=0
 
 do VDEF(.fQUEUEJ)
 do VLOD(.fQUEUEJ)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordQUEUEJ fQUEUEJ)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordQUEUEJ fQUEUEJ) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordQUEUEJ fQUEUEJ) // Display screen prompts
 set VO="17||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,24,21,2,0,0,0,0,0,0)_"01TJob Level Maintenance"
 set VO(2)=$C(3,3,14,0,0,0,0,0,0,0)_"01T Batch Number:"
 set VO(3)=$C(3,36,12,0,0,0,0,0,0,0)_"01T Job Number:"
 set VO(4)=$C(4,2,15,0,0,0,0,0,0,0)_"01T Function Name:"
 set VO(5)=$C(7,4,13,0,0,0,0,0,0,0)_"01T Description:"
 set VO(6)=$C(9,14,34,0,0,0,0,0,0,0)_"01T Dependency Resubmission Interval:"
 set VO(7)=$C(9,58,7,0,0,0,0,0,0,0)_"01Tminutes"
 set VO(8)=$C(10,15,33,0,0,0,0,0,0,0)_"01T Maximum Number of Resubmissions:"
 set VO(9)=$C(11,16,32,0,0,0,0,0,0,0)_"01T Action on Resubmission Failure:"
 set VO(10)=$C(14,6,23,0,0,0,0,0,0,0)_"01TNumber of Times to Run:"
 set VO(11)=$C(14,38,22,0,0,0,0,0,0,0)_"01TDelete Job from Batch:"
 set VO(12)=$C(15,3,25,0,0,0,0,0,0,0)_"01TNumber of Times to Bypass"
 set VO(13)=$C(16,7,24,0,0,0,0,0,0,0)_"01T(""UNL"" for Unlimited):"
 set VO(14)=$C(18,10,14,0,0,0,0,0,0,0)_"01TLast Run Date:"
 set VO(15)=$C(19,11,13,0,0,0,0,0,0,0)_"01TTime Started:"
 set VO(16)=$C(20,9,15,0,0,0,0,0,0,0)_"01TTime Completed:"
 set VO(17)=$C(21,6,18,0,0,0,0,0,0,0)_"01TCompletion Status:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordQUEUEJ fQUEUEJ)  // Display screen data
 new V
 s BCHNUM=$G(BCHNUM)
 s COMPMSG=$G(COMPMSG)
 s JOBNUM=$G(JOBNUM)
 //
 set VO="32|18|13|"
 set VO(18)=$C(3,18,0,2,0,0,0,0,0,0)_"01T"_$G(BCHNUM)
 set VO(19)=$C(3,49,0,2,0,0,0,0,0,0)_"01T"_$G(JOBNUM)
 set VO(20)=$C(4,18,20,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEJ.FUN,1,20)
 set VO(21)=$C(7,18,50,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEJ.DESC,1,50)
 set VO(22)=$C(9,49,8,2,0,0,0,0,0,0)_"00N"_fQUEUEJ.RETI
 set VO(23)=$C(10,49,2,2,0,0,0,0,0,0)_"00N"_fQUEUEJ.MAXR
 set VO(24)=$C(11,49,1,2,0,0,0,0,0,0)_"00N"_fQUEUEJ.AOF
 set VO(25)=$C(14,30,2,2,0,0,0,0,0,0)_"00N"_fQUEUEJ.TTR
 set VO(26)=$C(14,61,1,2,0,0,0,0,0,0)_"00L"_$S(fQUEUEJ.DIZ:"Y",1:"N")
 set VO(27)=$C(16,30,4,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEJ.SKIP,1,4)
 set VO(28)=$C(18,25,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fQUEUEJ.LRD)
 set VO(29)=$C(19,25,11,2,0,0,0,0,0,0)_"01C"_$$TIM^%ZM(fQUEUEJ.STIM)
 set VO(30)=$C(20,25,11,2,0,0,0,0,0,0)_"01C"_$$TIM^%ZM(fQUEUEJ.CTIM)
 set VO(31)=$C(21,25,1,2,0,0,0,0,0,0)_"01N"_fQUEUEJ.LSTAT
 set VO(32)=$C(21,28,0,2,0,0,0,0,0,0)_"01T"_$G(COMPMSG)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordQUEUEJ fQUEUEJ)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=15,VPT=1,VPB=21,PGM=$T(+0),DLIB="SYSDEV",DFID="QUEUEJ"
 set OLNTB=21028
 
 set VFSN("QUEUEJ")="zfQUEUEJ"
 //
 // 
	
	
 set %TAB(1)=$C(2,17,0)_"21T|*BCHNUM|[*]@HBCHNUM1"
 set %TAB(2)=$C(2,48,0)_"21T|*JOBNUM|[*]@HJOBNUM1"
 set %TAB(3)=$C(3,17,20)_"00T12402|1|[QUEUEJ]FUN|[SCATBL]DESC,QUEUE||do VP1^V00S438(.fQUEUEJ)|do VP2^V00S438(.fQUEUEJ)"
 set %TAB(4)=$C(6,17,50)_"00T12401|1|[QUEUEJ]DESC||||do VP3^V00S438(.fQUEUEJ)"
 set %TAB(5)=$C(8,48,8)_"00N12410|1|[QUEUEJ]RETI||||do VP4^V00S438(.fQUEUEJ)"
 set %TAB(6)=$C(9,48,2)_"00N12411|1|[QUEUEJ]MAXR|||do VP5^V00S438(.fQUEUEJ)|do VP6^V00S438(.fQUEUEJ)"
 set %TAB(7)=$C(10,48,1)_"00N12413|1|[QUEUEJ]AOF||||do VP7^V00S438(.fQUEUEJ)"
 set %TAB(8)=$C(13,29,2)_"00N12408|1|[QUEUEJ]TTR"
 set %TAB(9)=$C(13,60,1)_"00L12409|1|[QUEUEJ]DIZ"
 set %TAB(10)=$C(15,29,4)_"00T12414|1|[QUEUEJ]SKIP|||do VP8^V00S438(.fQUEUEJ)"
 set %TAB(11)=$C(17,24,10)_"21D12403|1|[QUEUEJ]LRD"
 set %TAB(12)=$C(18,24,11)_"21C12404|1|[QUEUEJ]STIM||||||43200"
 set %TAB(13)=$C(19,24,11)_"21C12405|1|[QUEUEJ]CTIM||||||86400"
 set %TAB(14)=$C(20,24,1)_"21N12407|1|[QUEUEJ]LSTAT"
 set %TAB(15)=$C(20,27,0)_"21T|*COMPMSG|[*]@COMPMSG"
 do VTBL(.fQUEUEJ),VDEPRE(.fQUEUEJ) if $G(ER) quit
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordQUEUEJ fQUEUEJ) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDEPRE(RecordQUEUEJ fQUEUEJ)  // Data Entry Pre-processor
 
 if '$G(BATCH) quit 

 do PROTECT^DBSMACRO("QUEUEJ.FUN")

 do PROTECT^DBSMACRO("QUEUEJ.DESC")

 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordQUEUEJ fQUEUEJ) //
 if X="" quit 

 do DESC^QUEMANT

 if $G(ER) quit 

 type RecordSCATBL scatbl=Db.getRecord("SCATBL","FN=:X")
 if fQUEUEJ.desc="" D DEFAULT^DBSMACRO("QUEUEJ.DESC",scatbl.desc,"1","0","0")

 quit
VP2(RecordQUEUEJ fQUEUEJ) //
 if '$G(BATCH) do CHANGE^DBSMACRO("REQ","")
 quit
VP3(RecordQUEUEJ fQUEUEJ) //
 if '$G(BATCH) do CHANGE^DBSMACRO("REQ","")
 quit
VP4(RecordQUEUEJ fQUEUEJ) //
 if '$G(BATCH) do CHANGE^DBSMACRO("REQ","")
 quit
VP5(RecordQUEUEJ fQUEUEJ) //
 if $G(BATCH) quit

 do MAXR^QUEMANT(.fQUEUEJ)

 quit
VP6(RecordQUEUEJ fQUEUEJ) //
 if '$G(BATCH) do CHANGE^DBSMACRO("REQ","")
 quit
VP7(RecordQUEUEJ fQUEUEJ) //
 if '$G(BATCH) do CHANGE^DBSMACRO("REQ","")

 // CONTINUE WITH NEXT JOB
 set AOF(0)=$$^MSG(6177) 
 set AOF(1)=$$^MSG(6178)
 set I(3)="AOF("     

 quit
VP8(RecordQUEUEJ fQUEUEJ) //
 if (X?.N)!(X="") quit

 // Enter an integer, or 'UNL' for unlimited bypasses 
 if X'="UNL" set ER=1,RM=$$^MSG(931) 

 quit 
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordQUEUEJ fQUEUEJ
 do VPR(.fQUEUEJ)
 do VDA1(.fQUEUEJ)
 do ^DBSPNT()
 quit

VW(RecordQUEUEJ fQUEUEJ)
 do VDA1(.fQUEUEJ)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordQUEUEJ fQUEUEJ)
 do VDA1(.fQUEUEJ)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordQUEUEJ fQUEUEJ
 do VDA1(.fQUEUEJ)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordQUEUEJ fQUEUEJ
 if sn="QUEUEJ" do vSET1(.fQUEUEJ,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordQUEUEJ fQUEUEJ,di,X)
 do fQUEUEJ.setAuditFlag(1)
 set fQUEUEJ.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordQUEUEJ fQUEUEJ
 if fid="QUEUEJ" quit $$vREAD1(.fQUEUEJ,di)
 quit ""
vREAD1(RecordQUEUEJ fQUEUEJ,di)
 quit fQUEUEJ.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
