V00S082(%ProcessMode,RecordCUVAR fCUVAR)   // -  - SID= <CUVARGW> SWIFT Gateway Information
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:09 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="CUVARGW",VPGM=$T(+0),VSNAME="SWIFT Gateway Information"
 set VFSN("CUVAR")="zfCUVAR"
 set vPSL=1
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fCUVAR),VDA1(.fCUVAR),^DBSPNT()

 if '%ProcessMode do VNEW(.fCUVAR),VPR(.fCUVAR),VDA1(.fCUVAR)
 if %ProcessMode do VLOD(.fCUVAR) quit:$G(ER)  do VPR(.fCUVAR),VDA1(.fCUVAR)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fCUVAR)
	quit


VNEW(RecordCUVAR fCUVAR) // Initialize arrays if %O=0
 
 do VDEF(.fCUVAR)
 do VLOD(.fCUVAR)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordCUVAR fCUVAR)
 if fCUVAR.%ET="" set fCUVAR.%ET="ZE^UTLERR"
 if fCUVAR.%HELP="" set fCUVAR.%HELP=0
 if fCUVAR.%HELPCNT="" set fCUVAR.%HELPCNT=0
 if fCUVAR.ALCOUNT="" set fCUVAR.ALCOUNT=5
 if fCUVAR.BANNER="" set fCUVAR.BANNER=1
 if fCUVAR.BOBR="" set fCUVAR.BOBR=0
 if fCUVAR.DBSPH132="" set fCUVAR.DBSPH132="SCAU$HELP:OOE_SCA132.EXP"
 if fCUVAR.DBSPH80="" set fCUVAR.DBSPH80="SCAU$HELP:OOE_SCA80.EXP"
 if fCUVAR.EMURND="" set fCUVAR.EMURND=9
 if fCUVAR.IRAHIST="" set fCUVAR.IRAHIST=365
 if fCUVAR.LNCC="" set fCUVAR.LNCC=0
 if fCUVAR.LNCFP="" set fCUVAR.LNCFP=0
 if fCUVAR.LNCPI="" set fCUVAR.LNCPI=0
 if fCUVAR.LNCPP="" set fCUVAR.LNCPP=0
 if fCUVAR.MAXCIFL="" set fCUVAR.MAXCIFL=12
 if fCUVAR.MINCIFL="" set fCUVAR.MINCIFL=1
 if fCUVAR.ODP="" set fCUVAR.ODP=0
 if fCUVAR.ORCIFN="" set fCUVAR.ORCIFN=1
 if fCUVAR.SFEEOPT="" set fCUVAR.SFEEOPT=0
 if fCUVAR.TAXREQ="" set fCUVAR.TAXREQ=1
 if fCUVAR.USERNAME="" set fCUVAR.USERNAME=0
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordCUVAR fCUVAR) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordCUVAR fCUVAR) // Display screen prompts
 set VO="6||13|0"
 set VO(0)="|0"
 set VO(1)=$C(2,28,27,1,0,0,0,0,0,0)_"01T SWIFT Gateway Information "
 set VO(2)=$C(4,15,27,0,0,0,0,0,0,0)_"01TPayment Msg Hist Retention:"
 set VO(3)=$C(5,10,32,0,0,0,0,0,0,0)_"01TConfirmation Msg Hist Retention:"
 set VO(4)=$C(7,9,33,0,0,0,0,0,0,0)_"01TMT900 Time Interval (in minutes):"
 set VO(5)=$C(8,9,33,0,0,0,0,0,0,0)_"01TMT910 Time Interval (in minutes):"
 set VO(6)=$C(10,5,37,0,0,0,0,0,0,0)_"01TExtended Remittance MUG Registration:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordCUVAR fCUVAR)  // Display screen data
 new V
 //
 set VO="11|7|13|0"
 set VO(7)=$C(4,43,4,2,0,0,0,0,0,0)_"00N"_fCUVAR.PMTHIS
 set VO(8)=$C(5,43,4,2,0,0,0,0,0,0)_"00N"_fCUVAR.CNFRMHIS
 set VO(9)=$C(7,43,4,2,0,0,0,0,0,0)_"00N"_fCUVAR.MT900INT
 set VO(10)=$C(8,43,4,2,0,0,0,0,0,0)_"00N"_fCUVAR.MT910INT
 set VO(11)=$C(10,43,1,2,0,0,0,0,0,0)_"00L"_$S(fCUVAR.EXTREM:"Y",1:"N")
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordCUVAR fCUVAR)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=5,VPT=2,VPB=10,PGM=$T(+0),DLIB="SYSDEV",DFID="CUVAR"
 set OLNTB=10043
 
 set VFSN("CUVAR")="zfCUVAR"
 //
 // 
	
	
 set %TAB(1)=$C(3,42,4)_"00N12401|1|[CUVAR]PMTHIS"
 set %TAB(2)=$C(4,42,4)_"00N12402|1|[CUVAR]CNFRMHIS"
 set %TAB(3)=$C(6,42,4)_"00N12403|1|[CUVAR]MT900INT"
 set %TAB(4)=$C(7,42,4)_"00N12404|1|[CUVAR]MT910INT"
 set %TAB(5)=$C(9,42,1)_"00L12405|1|[CUVAR]EXTREM"
 do VTBL(.fCUVAR)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordCUVAR fCUVAR) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordCUVAR fCUVAR
 do VPR(.fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT()
 quit

VW(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordCUVAR fCUVAR
 do VDA1(.fCUVAR)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordCUVAR fCUVAR
 if sn="CUVAR" do vSET1(.fCUVAR,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordCUVAR fCUVAR,di,X)
 do fCUVAR.setAuditFlag(1)
 set fCUVAR.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordCUVAR fCUVAR
 if fid="CUVAR" quit $$vREAD1(.fCUVAR,di)
 quit ""
vREAD1(RecordCUVAR fCUVAR,di)
 quit fCUVAR.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
