V00S454(%ProcessMode,RecordSCASYS fSCASYS)   //SCA -  - SID= <SCASYS> Application Definition Table
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 12:02 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="SCASYS",VPGM=$T(+0),VSNAME="Application Definition Table"
 set VFSN("SCASYS")="zfSCASYS"
 set vPSL=1
 set KEYS(1)=fSCASYS.SYSSN
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fSCASYS),VDA1(.fSCASYS),^DBSPNT()

 if '%ProcessMode do VNEW(.fSCASYS),VPR(.fSCASYS),VDA1(.fSCASYS)
 if %ProcessMode do VLOD(.fSCASYS) quit:$G(ER)  do VPR(.fSCASYS),VDA1(.fSCASYS)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fSCASYS)
	quit


VNEW(RecordSCASYS fSCASYS) // Initialize arrays if %O=0
 
 do VDEF(.fSCASYS)
 do VLOD(.fSCASYS)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordSCASYS fSCASYS)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordSCASYS fSCASYS) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordSCASYS fSCASYS) // Display screen prompts
 set VO="42||13|"
 set VO(0)="|0"
 set VO(1)=$C(2,1,80,0,0,0,0,0,0,0)_"11Tlqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk"
 set VO(2)=$C(3,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(3)=$C(3,4,13,0,0,0,0,0,0,0)_"01T System Name:"
 set VO(4)=$C(3,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(5)=$C(4,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(6)=$C(4,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(7)=$C(5,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(8)=$C(5,4,13,0,0,0,0,0,0,0)_"01T Description:"
 set VO(9)=$C(5,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(10)=$C(6,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(11)=$C(6,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(12)=$C(7,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(13)=$C(7,4,46,1,0,0,0,0,0,0)_"01T Executable code to initiate this application "
 set VO(14)=$C(7,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(15)=$C(8,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(16)=$C(8,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(17)=$C(9,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(18)=$C(10,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(19)=$C(10,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(20)=$C(11,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(21)=$C(11,4,64,1,0,0,0,0,0,0)_"01T The driver saves (%ID,%MENU,%SN,%SYS,%TO,%UCLS,%UID,%UFN,%NET) "
 set VO(22)=$C(11,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(23)=$C(12,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(24)=$C(12,4,47,1,0,0,0,0,0,0)_"01T Enter additional variables to save within this"
 set VO(25)=$C(12,51,17,1,0,0,0,0,0,0)_"01T application     "
 set VO(26)=$C(12,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(27)=$C(13,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(28)=$C(13,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(29)=$C(14,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(30)=$C(14,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(31)=$C(15,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(32)=$C(15,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(33)=$C(16,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(34)=$C(16,12,32,0,0,0,0,0,0,0)_"01TUser-Defined Data Type Required:"
 set VO(35)=$C(16,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(36)=$C(17,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(37)=$C(17,12,32,0,0,0,0,0,0,0)_"01TMaster Data Dictionary Required:"
 set VO(38)=$C(17,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(39)=$C(18,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(40)=$C(18,16,28,0,0,0,0,0,0,0)_"01TMaster Data Dictionary Name:"
 set VO(41)=$C(18,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(42)=$C(19,1,80,0,0,0,0,0,0,0)_"11Tmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordSCASYS fSCASYS)  // Display screen data
 new V
 //
 set VO="50|43|13|"
 set VO(43)=$C(1,1,80,1,0,0,0,0,0,0)_"01T"_$S(%ProcessMode=5:"",1:$$BANNER^UTLREAD($G(%FN)))
 set VO(44)=$C(3,18,8,2,0,0,0,0,0,0)_"01T"_$E(fSCASYS.SYSSN,1,8)
 set VO(45)=$C(5,18,40,2,0,0,0,0,0,0)_"00T"_$E(fSCASYS.DES,1,40)
 set VO(46)=$C(9,4,77,2,0,0,0,0,0,0)_"00T"_$E(fSCASYS.XECUT,1,255)
 set VO(47)=$C(14,4,75,2,0,0,0,0,0,0)_"00T"_$E(fSCASYS.XKILL,1,75)
 set VO(48)=$C(16,45,1,2,0,0,0,0,0,0)_"00L"_$S(fSCASYS.DBSDOMREQ:"Y",1:"N")
 set VO(49)=$C(17,45,1,2,0,0,0,0,0,0)_"00L"_$S(fSCASYS.DBSMDDREQ:"Y",1:"N")
 set VO(50)=$C(18,45,12,2,0,0,0,0,0,0)_"00U"_$E(fSCASYS.DBSMDD,1,12)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordSCASYS fSCASYS)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=7,VPT=1,VPB=19,PGM=$T(+0),DLIB="SYSDEV",DFID="SCASYS"
 set OLNTB=19001
 
 set VFSN("SCASYS")="zfSCASYS"
 //
 // 
	
	
 set %TAB(1)=$C(2,17,8)_"21U12401|1|[SCASYS]SYSSN"
 set %TAB(2)=$C(4,17,40)_"00T12401|1|[SCASYS]DES"
 set %TAB(3)=$C(8,3,77)_"00T12402|1|[SCASYS]XECUT|||||||||255"
 set %TAB(4)=$C(13,3,75)_"00T12404|1|[SCASYS]XKILL|||do VP1^V00S454(.fSCASYS)"
 set %TAB(5)=$C(15,44,1)_"00L12405|1|[SCASYS]DBSDOMREQ"
 set %TAB(6)=$C(16,44,1)_"00L12406|1|[SCASYS]DBSMDDREQ"
 set %TAB(7)=$C(17,44,12)_"00U12407|1|[SCASYS]DBSMDD|[DBTBL1]"
 do VTBL(.fSCASYS)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordSCASYS fSCASYS) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordSCASYS fSCASYS) //
 type public String X

 //Do not use parentheses
 if X.isLike("(") do Runtime.setErrMSG("SCASYS",840)

 if X.length(),X.extract(1)'="," set X=","_X

	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordSCASYS fSCASYS
 do VPR(.fSCASYS)
 do VDA1(.fSCASYS)
 do ^DBSPNT()
 quit

VW(RecordSCASYS fSCASYS)
 do VDA1(.fSCASYS)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordSCASYS fSCASYS)
 do VDA1(.fSCASYS)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordSCASYS fSCASYS
 do VDA1(.fSCASYS)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordSCASYS fSCASYS
 if sn="SCASYS" do vSET1(.fSCASYS,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordSCASYS fSCASYS,di,X)
 do fSCASYS.setAuditFlag(1)
 set fSCASYS.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordSCASYS fSCASYS
 if fid="SCASYS" quit $$vREAD1(.fSCASYS,di)
 quit ""
vREAD1(RecordSCASYS fSCASYS,di)
 quit fSCASYS.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
