V00S304(%ProcessMode,RecordLNPAS2 fLNPAS)   //PBS - LN - SID= <LNPAS> Payment String
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:36 - kini
 // This screen identifies the master set of payment elements that
 // may make up loan payment strings, and defines the priorities
 // in which to apply loan payments to the amounts due for a loan
 // balance.  The user accesses the LNPAS screen via the Payment
 // String Maintenance function (LNPAS1).
 // 
 // For loan fee processing purposes, the LNPAS screen enables users to:
 // 
 // - Include loan fee plans in the loan payment string ([LNPAS2]DISTRIB).
 // 
 // - Indicate whether (Y) or not (N) to include fees linked to payment
 //   elements when calculating the payment amounts due for new loans
 //   ([LNPAS2]ILFF).
 // 
 // For further information, refer to the Loan Fee Processing Reference
 // Manual.
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="LNPAS",VPGM=$T(+0),VSNAME="Payment String"
 set VFSN("LNPAS2")="zfLNPAS"
 set vPSL=1
 set KEYS(1)=fLNPAS.TABLE
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fLNPAS),VDA1(.fLNPAS),^DBSPNT()

 if '%ProcessMode do VNEW(.fLNPAS),VPR(.fLNPAS),VDA1(.fLNPAS)
 if %ProcessMode do VLOD(.fLNPAS) quit:$G(ER)  do VPR(.fLNPAS),VDA1(.fLNPAS)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fLNPAS)
	quit


VNEW(RecordLNPAS2 fLNPAS) // Initialize arrays if %O=0
 
 do VDEF(.fLNPAS)
 do VLOD(.fLNPAS)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordLNPAS2 fLNPAS)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordLNPAS2 fLNPAS) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordLNPAS2 fLNPAS) // Display screen prompts
 set VO="7||13|"
 set VO(0)="|"
 set VO(1)=$C(1,28,16,1,0,0,0,0,0,0)_"01T Payment String "
 set VO(2)=$C(3,13,7,0,0,0,0,0,0,0)_"01T Table:"
 set VO(3)=$C(5,5,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(4)=$C(6,8,10,1,0,0,0,0,0,0)_"01T Elements:"
 set VO(5)=$C(7,1,17,1,0,0,0,0,0,0)_"01T Add Linked Fees:"
 set VO(6)=$C(8,6,12,1,0,0,0,0,0,0)_"01T Start Date:"
 set VO(7)=$C(9,8,10,0,0,0,0,0,0,0)_"01T End Date:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordLNPAS2 fLNPAS)  // Display screen data
 new V
 //
 set VO="13|8|13|"
 set VO(8)=$C(3,21,8,2,0,0,0,0,0,0)_"01T"_$E(fLNPAS.TABLE,1,8)
 set VO(9)=$C(5,19,40,2,0,0,0,0,0,0)_"00T"_$E(fLNPAS.TDES,1,40)
 set VO(10)=$C(6,19,60,2,0,0,0,0,0,0)_"00T"_$E(fLNPAS.DISTRIB,1,60)
 set VO(11)=$C(7,19,1,2,0,0,0,0,0,0)_"00L"_$S(fLNPAS.ILFF:"Y",1:"N")
 set VO(12)=$C(8,19,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fLNPAS.STDT)
 set VO(13)=$C(9,19,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fLNPAS.EDDT)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordLNPAS2 fLNPAS)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=6,VPT=1,VPB=9,PGM=$T(+0),DLIB="SYSDEV",DFID="LNPAS2"
 set OLNTB=9019
 
 set VFSN("LNPAS2")="zfLNPAS"
 //
 // 
	
	
 set %TAB(1)=$C(2,20,8)_"21T12401|1|[LNPAS2]TABLE|[LNPAS2]"
 set %TAB(2)=$C(4,18,40)_"01T12401|1|[LNPAS2]TDES|||do VP1^V00S304(.fLNPAS)"
 set %TAB(3)=$C(5,18,60)_"01T12402|1|[LNPAS2]DISTRIB|||do VP2^V00S304(.fLNPAS)|do VP3^V00S304(.fLNPAS)"
 set %TAB(4)=$C(6,18,1)_"00L12408|1|[LNPAS2]ILFF"
 set %TAB(5)=$C(7,18,10)_"01D12403|1|[LNPAS2]STDT|||do VP4^V00S304(.fLNPAS)"
 set %TAB(6)=$C(8,18,10)_"00D12404|1|[LNPAS2]EDDT|||do VP5^V00S304(.fLNPAS)"
 do VTBL(.fLNPAS)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordLNPAS2 fLNPAS) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordLNPAS2 fLNPAS) //
 set TDES=X
 quit

VP2(RecordLNPAS2 fLNPAS) //
 set I(3)=""

 if X=""!(X=V) quit

 do PRI1^LNPRI1 

 set DISTRIB=X

 quit
 
VP3(RecordLNPAS2 fLNPAS) //
 do TBL3^LNFEEU(.distrib)

 quit

VP4(RecordLNPAS2 fLNPAS) //
 set STDT=$$^SCAJD(X) 
 
 // Invalid date ~p1
 if STDT<0 set ER=1 set RM=$$^MSG(1308)    

 quit

VP5(RecordLNPAS2 fLNPAS) //
 set EDDT=X 

 if X="" quit

 set EDDT=$$^SCAJD(X) 

 if EDDT<0 set ER=1,RM=$$^MSG(1308) // Invalid date ~p1
 else  if EDDT'>STDT set ER=1 set RM=$$^MSG(891) // End date must be after start date
 
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordLNPAS2 fLNPAS
 do VPR(.fLNPAS)
 do VDA1(.fLNPAS)
 do ^DBSPNT()
 quit

VW(RecordLNPAS2 fLNPAS)
 do VDA1(.fLNPAS)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordLNPAS2 fLNPAS)
 do VDA1(.fLNPAS)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordLNPAS2 fLNPAS
 do VDA1(.fLNPAS)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordLNPAS2 fLNPAS
 if sn="LNPAS2" do vSET1(.fLNPAS,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordLNPAS2 fLNPAS,di,X)
 do fLNPAS.setAuditFlag(1)
 set fLNPAS.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordLNPAS2 fLNPAS
 if fid="LNPAS2" quit $$vREAD1(.fLNPAS,di)
 quit ""
vREAD1(RecordLNPAS2 fLNPAS,di)
 quit fLNPAS.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
