V00S044(%ProcessMode,RecordCUVAR fCUVAR)   //PBS - SCA - SID= <CUVAR> Institution Variables
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:07 - kini
 	/*
 	ORIG: CHENARDP - 02/27/2003
 	DESC: Linked Screen Template

 	---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4


	 ---- Revision History ------------------------------------------------
	09/24/03 - Pete Chenard - 45497
		       Created linked screen template for screen compiler.
	-----------------------------------------------------------------------

	 */
 
V0 
 set VSID="CUVAR"
 set KVAR="kill %A,%TAB,vtab,VFSN,%OLD,%NEW,%FILE,%INDEX,%PAGE,%PG,UX,MULSCR"
 set:'$D(%PG) %PG=1 set %PAG=%PG+26 set %PAGE=$S($D(%PAGE):%PAGE-1,1:0)+27
 set vPSL=1  //compiled for PSL
 //
 set VPG(%PG+0)="General Information (Inst. Identity)|CUVARGEN1"
 set VPG(%PG+1)="General Information (Software, Misc)|CUVARGEN2"
 set VPG(%PG+2)="Year-End Reporting|CUVARIRS"
 set VPG(%PG+3)="Magnetic Media Processing Institution|CUVMEDIA"
 set VPG(%PG+4)="General Ledger|CUVARGL"
 set VPG(%PG+5)="CIF/Membership Information|CUVARCIF"
 set VPG(%PG+6)="Deposit & Loan |CUVARCTL"
 set VPG(%PG+7)="Account Integrity Control Options|CUVARINT"
 set VPG(%PG+8)="Deposit (General)|CUVARDEP1"
 set VPG(%PG+9)="Deposit (Dormancy, Escheat)|CUVARDEP2"
 set VPG(%PG+10)="Deposit (Retirement Accts)|CUVARDEP3"
 set VPG(%PG+11)="Reg CC Control Options|CUVARRCC"
 set VPG(%PG+12)="Loan (General)|CUVARLN1"
 set VPG(%PG+13)="Loan (Escrow, Manual Conv)|CUVARLN2"
 set VPG(%PG+14)="Loan (Delq, Credit Bureau)|CUVARLN3"
 set VPG(%PG+15)="Provision/ Asset Reclassification|CUVARLN4"
 set VPG(%PG+16)="Teller Processing I|CUVARTELL"
 set VPG(%PG+17)="System Management (General)|CUVARMGR1"
 set VPG(%PG+18)="Custom Program Linkages|CUVARMGR1B"
 set VPG(%PG+19)="System Management (Dayend, Jnl, Maint)|CUVARMGR2"
 set VPG(%PG+20)="DATA-QWIK|CUVARDQ"
 set VPG(%PG+21)="Foreign Currency|CUVARMCP"
 set VPG(%PG+22)="Account Lookup Display Format Definition|CUVARLOOKUP"
 set VPG(%PG+23)="SWIFT Gateway Information|CUVARGW"
 set VPG(%PG+24)="Payment Systems|CUVARPAY"
 set VPG(%PG+25)="Euro Currency Information|CUVAREUR"
 set VPG(%PG+26)="Securities|CUVARSEC"
	set:'$D(%PG) %PG=1 set %PGSV=%PG,MULSCR=""
 if '%ProcessMode do VNEW(.fCUVAR)
 if %ProcessMode do VLOD(.fCUVAR) if $G(ER) set VFMQ="Q" quit
 do VPG(.fCUVAR)
 quit

VNEW(RecordCUVAR fCUVAR)
 
 quit
 //
 ;
VLOD(RecordCUVAR fCUVAR)  // User defined access section
	quit

VPG(RecordCUVAR fCUVAR)
 new vDONE
 set vDONE=0
 for  do { quit:vDONE
  if %PG=(%PGSV+0) do VPG1(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+1) do VPG2(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+2) do VPG3(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+3) do VPG4(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+4) do VPG5(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+5) do VPG6(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+6) do VPG7(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+7) do VPG8(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+8) do VPG9(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+9) do VPG10(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+10) do VPG11(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+11) do VPG12(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+12) do VPG13(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+13) do VPG14(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+14) do VPG15(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+15) do VPG16(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+16) do VPG17(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+17) do VPG18(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+18) do VPG19(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+19) do VPG20(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+20) do VPG21(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+21) do VPG22(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+22) do VPG23(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+23) do VPG24(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+24) do VPG25(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+25) do VPG26(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  if %PG=(%PGSV+26) do VPG27(.fCUVAR),VPG0(.fCUVAR) quit:vDONE
  }
 quit

VPG0(RecordCUVAR fCUVAR)
 set %LINK=""
 if %ProcessMode=2!(%ProcessMode=3)!(%ProcessMode=4) do VBTM(.fCUVAR) if $G(VFMQ)="D" set vDONE=1 quit
 if '$D(%PAGE) set vDONE=1 quit
 if %PG'<%PAG kill %PAG,%PGSV,VPG set vDONE=1 quit
 set %PG=%PG+1
 quit

 
VPG1(RecordCUVAR fCUVAR)  // General Information (Inst. Identity)
 
 new x
 set SID="CUVARGEN1",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S079
 if %ProcessMode>1 quit
 do VTAB^V00S079(.fCUVAR)
 quit
 
VPG2(RecordCUVAR fCUVAR)  // General Information (Software, Misc)
 
 new x
 set SID="CUVARGEN2",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S080
 if %ProcessMode>1 quit
 do VTAB^V00S080(.fCUVAR)
 quit
 
VPG3(RecordCUVAR fCUVAR)  // Year-End Reporting
 
 new x
 set SID="CUVARIRS",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S084
 if %ProcessMode>1 quit
 do VTAB^V00S084(.fCUVAR)
 quit
 
VPG4(RecordCUVAR fCUVAR)  // Magnetic Media Processing Institution
 
 new x
 set SID="CUVMEDIA",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S098
 if %ProcessMode>1 quit
 do VTAB^V00S098(.fCUVAR)
 quit
 
VPG5(RecordCUVAR fCUVAR)  // General Ledger
 
 new x
 set SID="CUVARGL",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S081
 if %ProcessMode>1 quit
 do VTAB^V00S081(.fCUVAR)
 quit
 
VPG6(RecordCUVAR fCUVAR)  // CIF/Membership Information
 
 new x
 set SID="CUVARCIF",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S072
 if %ProcessMode>1 quit
 do VTAB^V00S072(.fCUVAR)
 quit
 
VPG7(RecordCUVAR fCUVAR)  // Deposit & Loan 
 
 new x
 set SID="CUVARCTL",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S073
 if %ProcessMode>1 quit
 do VTAB^V00S073(.fCUVAR)
 quit
 
VPG8(RecordCUVAR fCUVAR)  // Account Integrity Control Options
 
 new x
 set SID="CUVARINT",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S083
 if %ProcessMode>1 quit
 do VTAB^V00S083(.fCUVAR)
 quit
 
VPG9(RecordCUVAR fCUVAR)  // Deposit (General)
 
 new x
 set SID="CUVARDEP1",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S074
 if %ProcessMode>1 quit
 do VTAB^V00S074(.fCUVAR)
 quit
 
VPG10(RecordCUVAR fCUVAR)  // Deposit (Dormancy, Escheat)
 
 new x
 set SID="CUVARDEP2",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S075
 if %ProcessMode>1 quit
 do VTAB^V00S075(.fCUVAR)
 quit
 
VPG11(RecordCUVAR fCUVAR)  // Deposit (Retirement Accts)
 
 new x
 set SID="CUVARDEP3",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S076
 if %ProcessMode>1 quit
 do VTAB^V00S076(.fCUVAR)
 quit
 
VPG12(RecordCUVAR fCUVAR)  // Reg CC Control Options
 
 new x
 set SID="CUVARRCC",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S095
 if %ProcessMode>1 quit
 do VTAB^V00S095(.fCUVAR)
 quit
 
VPG13(RecordCUVAR fCUVAR)  // Loan (General)
 
 new x
 set SID="CUVARLN1",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S085
 if %ProcessMode>1 quit
 do VTAB^V00S085(.fCUVAR)
 quit
 
VPG14(RecordCUVAR fCUVAR)  // Loan (Escrow, Manual Conv)
 
 new x
 set SID="CUVARLN2",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S086
 if %ProcessMode>1 quit
 do VTAB^V00S086(.fCUVAR)
 quit
 
VPG15(RecordCUVAR fCUVAR)  // Loan (Delq, Credit Bureau)
 
 new x
 set SID="CUVARLN3",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S087
 if %ProcessMode>1 quit
 do VTAB^V00S087(.fCUVAR)
 quit
 
VPG16(RecordCUVAR fCUVAR)  // Provision/ Asset Reclassification
 
 new x
 set SID="CUVARLN4",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S088
 if %ProcessMode>1 quit
 do VTAB^V00S088(.fCUVAR)
 quit
 
VPG17(RecordCUVAR fCUVAR)  // Teller Processing I
 
 new x
 set SID="CUVARTELL",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S097
 if %ProcessMode>1 quit
 do VTAB^V00S097(.fCUVAR)
 quit
 
VPG18(RecordCUVAR fCUVAR)  // System Management (General)
 
 new x
 set SID="CUVARMGR1",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S091
 if %ProcessMode>1 quit
 do VTAB^V00S091(.fCUVAR)
 quit
 
VPG19(RecordCUVAR fCUVAR)  // Custom Program Linkages
 
 new x
 set SID="CUVARMGR1B",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S092
 if %ProcessMode>1 quit
 do VTAB^V00S092(.fCUVAR)
 quit
 
VPG20(RecordCUVAR fCUVAR)  // System Management (Dayend, Jnl, Maint)
 
 new x
 set SID="CUVARMGR2",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S093
 if %ProcessMode>1 quit
 do VTAB^V00S093(.fCUVAR)
 quit
 
VPG21(RecordCUVAR fCUVAR)  // DATA-QWIK
 
 new x
 set SID="CUVARDQ",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S077
 if %ProcessMode>1 quit
 do VTAB^V00S077(.fCUVAR)
 quit
 
VPG22(RecordCUVAR fCUVAR)  // Foreign Currency
 
 new x
 set SID="CUVARMCP",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S090
 if %ProcessMode>1 quit
 do VTAB^V00S090(.fCUVAR)
 quit
 
VPG23(RecordCUVAR fCUVAR)  // Account Lookup Display Format Definition
 
 new x
 set SID="CUVARLOOKUP",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S089
 if %ProcessMode>1 quit
 do VTAB^V00S089(.fCUVAR)
 quit
 
VPG24(RecordCUVAR fCUVAR)  // SWIFT Gateway Information
 
 new x
 set SID="CUVARGW",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S082
 if %ProcessMode>1 quit
 do VTAB^V00S082(.fCUVAR)
 quit
 
VPG25(RecordCUVAR fCUVAR)  // Payment Systems
 
 new x
 set SID="CUVARPAY",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S094
 if %ProcessMode>1 quit
 do VTAB^V00S094(.fCUVAR)
 quit
 
VPG26(RecordCUVAR fCUVAR)  // Euro Currency Information
 
 new x
 set SID="CUVAREUR",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S078
 if %ProcessMode>1 quit
 do VTAB^V00S078(.fCUVAR)
 quit
 
VPG27(RecordCUVAR fCUVAR)  // Securities
 
 new x
 set SID="CUVARSEC",DFID="CUVAR"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S096
 if %ProcessMode>1 quit
 do VTAB^V00S096(.fCUVAR)
 quit
 

VBTM(RecordCUVAR fCUVAR)

	if %ProcessMode=4,IO'=$P quit
	do ^DBSCRT8A
	quit
