V00S418(%ProcessMode,RecordNOSTTRF fNOSTTRF)   //PBS -  - SID= <NOSTTRF> Nostro Transfer Screen Linkage
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:56 - kini
 	/*
 	ORIG: CHENARDP - 02/27/2003
 	DESC: Linked Screen Template

 	---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4


	 ---- Revision History ------------------------------------------------
	09/24/03 - Pete Chenard - 45497
		       Created linked screen template for screen compiler.
	-----------------------------------------------------------------------

	 */
 
V0 
 set ER=0 do VSCRPRE(.fNOSTTRF) if ER quit  // Screen Pre-Processor
 //
 set VSID="NOSTTRF"
 set KVAR="kill %A,%TAB,vtab,VFSN,%OLD,%NEW,%FILE,%INDEX,%PAGE,%PG,UX,MULSCR"
 set:'$D(%PG) %PG=1 set %PAG=%PG+1 set %PAGE=$S($D(%PAGE):%PAGE-1,1:0)+2
 set vPSL=1  //compiled for PSL
 //
 set VPG(%PG+0)="Nostro Transfer Screen 1|NOSTTRF1"
 set VPG(%PG+1)="Nostro Transfer Screen 2|NOSTTRF2"
	set:'$D(%PG) %PG=1 set %PGSV=%PG,MULSCR=""
 if '%ProcessMode do VNEW(.fNOSTTRF)
 if %ProcessMode do VLOD(.fNOSTTRF) if $G(ER) set VFMQ="Q" quit
 do VPG(.fNOSTTRF)
 quit

VNEW(RecordNOSTTRF fNOSTTRF)
 
 quit
 //
 ;
VLOD(RecordNOSTTRF fNOSTTRF)  // User defined access section
	quit

VPG(RecordNOSTTRF fNOSTTRF)
 new vDONE
 set vDONE=0
 for  do { quit:vDONE
  if %PG=(%PGSV+0) do VPG1(.fNOSTTRF),VPG0(.fNOSTTRF) quit:vDONE
  if %PG=(%PGSV+1) do VPG2(.fNOSTTRF),VPG0(.fNOSTTRF) quit:vDONE
  }
 quit

VPG0(RecordNOSTTRF fNOSTTRF)
 set %LINK=""
 if %ProcessMode=2!(%ProcessMode=3)!(%ProcessMode=4) do VBTM(.fNOSTTRF) if $G(VFMQ)="D" set vDONE=1 quit
 if '$D(%PAGE) set vDONE=1 quit
 if %PG'<%PAG kill %PAG,%PGSV,VPG set vDONE=1 quit
 set %PG=%PG+1
 quit

 
VPG1(RecordNOSTTRF fNOSTTRF)  // Nostro Transfer Screen 1
 
 new x
 set SID="NOSTTRF1",DFID="NOSTTRF"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S421
 if %ProcessMode>1 quit
 do VTAB^V00S421(.fNOSTTRF)
 quit
 
VPG2(RecordNOSTTRF fNOSTTRF)  // Nostro Transfer Screen 2
 
 new x
 set SID="NOSTTRF2",DFID="NOSTTRF"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S422
 if %ProcessMode>1 quit
 do VTAB^V00S422(.fNOSTTRF)
 quit
 

VBTM(RecordNOSTTRF fNOSTTRF)

	if %ProcessMode=4,IO'=$P quit
	do ^DBSCRT8A
	quit
VSCRPRE(RecordNOSTTRF fNOSTTRF) // Screen Pre-Processor
 new %TAB,vtab  // Disable .MACRO. references to %TAB()
 //
 set CO=CUVAR.co
 if %ProcessMode'=0 quit
 
 set fNOSTTRF.status=1
 set fNOSTTRF.edt=%SystemDate
 set fNOSTTRF.uid=%UserID
 type RecordNOSTTRF nosttrf=Db.getRecord("NOSTTRF","TRREFNO=:TRREFNO",1)
 set STATDSC=$$DSTATDSC^PROCOMP(nosttrf.status)
 quit
 quit
