V00S185(%ProcessMode,RecordGLAD fGLAD)   //PBS - DEP - SID= <GLACN> Create/Modify G/L Account
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:19 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="GLACN",VPGM=$T(+0),VSNAME="Create/Modify G/L Account"
 set VFSN("GLAD")="zfGLAD"
 set vPSL=1
 set KEYS(1)=fGLAD.ACN
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fGLAD),VDA1(.fGLAD),^DBSPNT()

 if '%ProcessMode do VNEW(.fGLAD),VPR(.fGLAD),VDA1(.fGLAD)
 if %ProcessMode do VLOD(.fGLAD) quit:$G(ER)  do VPR(.fGLAD),VDA1(.fGLAD)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fGLAD)
	quit


VNEW(RecordGLAD fGLAD) // Initialize arrays if %O=0
 
 do VDEF(.fGLAD)
 do VLOD(.fGLAD)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordGLAD fGLAD)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordGLAD fGLAD) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordGLAD fGLAD) // Display screen prompts
 set VO="7||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,25,25,1,0,0,0,0,0,0)_"01T G/L Account Maintenance "
 set VO(2)=$C(4,5,22,0,0,0,0,0,0,0)_"01TGeneral Ledger Number:"
 set VO(3)=$C(5,6,1,1,0,0,0,0,0,0)_"01T "
 set VO(4)=$C(5,7,20,1,0,0,0,0,0,0)_"01TGeneral Ledger Type:"
 set VO(5)=$C(6,14,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(6)=$C(7,1,12,1,0,0,0,0,0,0)_"01T Base Ledger"
 set VO(7)=$C(7,13,14,1,0,0,0,0,0,0)_"01T Account Only:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordGLAD fGLAD)  // Display screen data
 new V
 //
 set VO="11|8|13|"
 set VO(8)=$C(4,28,12,2,0,0,0,0,0,0)_"01N"_fGLAD.ACN
 set VO(9)=$C(5,28,1,2,0,0,0,0,0,0)_"00T"_$E(fGLAD.TYPE,1,1)
 set VO(10)=$C(6,28,40,2,0,0,0,0,0,0)_"00T"_$E(fGLAD.DESC1,1,40)
 set VO(11)=$C(7,28,1,2,0,0,0,0,0,0)_"00L"_$S(fGLAD.BONLY:"Y",1:"N")
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordGLAD fGLAD)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=4,VPT=1,VPB=7,PGM=$T(+0),DLIB="SYSDEV",DFID="GLAD"
 set OLNTB=7028
 
 set VFSN("GLAD")="zfGLAD"
 //
 // 
	
	
 set %TAB(1)=$C(3,27,12)_"21N12401|1|[GLAD]ACN"
 set %TAB(2)=$C(4,27,1)_"01T12401|1|[GLAD]TYPE|[STBLGLTYP]GLTYP"
 set %TAB(3)=$C(5,27,40)_"01T12402|1|[GLAD]DESC1"
 set %TAB(4)=$C(6,27,1)_"00L12409|1|[GLAD]BONLY"
 do VTBL(.fGLAD)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordGLAD fGLAD) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordGLAD fGLAD
 do VPR(.fGLAD)
 do VDA1(.fGLAD)
 do ^DBSPNT()
 quit

VW(RecordGLAD fGLAD)
 do VDA1(.fGLAD)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordGLAD fGLAD)
 do VDA1(.fGLAD)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordGLAD fGLAD
 do VDA1(.fGLAD)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordGLAD fGLAD
 if sn="GLAD" do vSET1(.fGLAD,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordGLAD fGLAD,di,X)
 do fGLAD.setAuditFlag(1)
 set fGLAD.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordGLAD fGLAD
 if fid="GLAD" quit $$vREAD1(.fGLAD,di)
 quit ""
vREAD1(RecordGLAD fGLAD,di)
 quit fGLAD.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
