V00S436(%ProcessMode,RecordQUEUEB fQUEUEB)   //SCA - U - SID= <QUEUEB> Batch Level Maintenance (Queuing)
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:58 - kini
 //  /*
 //  This screen identifies user-specified values that control Queuing System
 //  processing at the batch level and provides status information about the last
 //  batch run.  It is used by the Create Batch/Job (QUECRE), Modify Batch/Job
 //  (QUEUPD), and Delete Batch/Job (QUEDEL) functions.
 //  */
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="QUEUEB",VPGM=$T(+0),VSNAME="Batch Level Maintenance (Queuing)"
 set VFSN("QUEUEB")="zfQUEUEB"
 set vPSL=1
 set KEYS(1)=fQUEUEB.BCHNUM
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fQUEUEB),VDA1(.fQUEUEB),^DBSPNT()

 if '%ProcessMode do VNEW(.fQUEUEB),VPR(.fQUEUEB),VDA1(.fQUEUEB)
 if %ProcessMode do VLOD(.fQUEUEB) quit:$G(ER)  do VPR(.fQUEUEB),VDA1(.fQUEUEB)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fQUEUEB)
	quit


VNEW(RecordQUEUEB fQUEUEB) // Initialize arrays if %O=0
 
 do VDEF(.fQUEUEB)
 do VLOD(.fQUEUEB)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordQUEUEB fQUEUEB)
 if fQUEUEB.BRCD="" set fQUEUEB.BRCD=0
 if fQUEUEB.MAIL="" set fQUEUEB.MAIL=0
 if fQUEUEB.REST="" set fQUEUEB.REST=0
 if fQUEUEB.STOP="" set fQUEUEB.STOP=0
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordQUEUEB fQUEUEB) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordQUEUEB fQUEUEB) // Display screen prompts
 set VO="16||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,27,23,2,0,0,0,0,0,0)_"01TBatch Level Maintenance"
 set VO(2)=$C(3,3,14,0,0,0,0,0,0,0)_"01T Batch Number:"
 set VO(3)=$C(4,4,13,0,0,0,0,0,0,0)_"01T Description:"
 set VO(4)=$C(5,6,11,0,0,0,0,0,0,0)_"01T Frequency:"
 set VO(5)=$C(5,32,15,0,0,0,0,0,0,0)_"01T Next Run Date:"
 set VO(6)=$C(5,58,8,0,0,0,0,0,0,0)_"01T Offset:"
 set VO(7)=$C(7,10,17,0,0,0,0,0,0,0)_"01T Action on Error:"
 set VO(8)=$C(7,41,22,0,0,0,0,0,0,0)_"01T Restrict Job Restore:"
 set VO(9)=$C(10,6,21,0,0,0,0,0,0,0)_"01TMail on Condition(s):"
 set VO(10)=$C(11,13,14,0,0,0,0,0,0,0)_"01TMail to Users:"
 set VO(11)=$C(12,1,26,0,0,0,0,0,0,0)_"01TBroadcast on Condition(s):"
 set VO(12)=$C(13,8,19,0,0,0,0,0,0,0)_"01TBroadcast to Users:"
 set VO(13)=$C(16,13,14,0,0,0,0,0,0,0)_"01TLast Run Date:"
 set VO(14)=$C(17,14,13,0,0,0,0,0,0,0)_"01TTime Started:"
 set VO(15)=$C(18,12,15,0,0,0,0,0,0,0)_"01TTime Completed:"
 set VO(16)=$C(19,9,18,0,0,0,0,0,0,0)_"01TCompletion Status:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordQUEUEB fQUEUEB)  // Display screen data
 new V
 s BCHNUM=$G(BCHNUM)
 s COMPMSG=$G(COMPMSG)
 //
 set VO="32|17|13|"
 set VO(17)=$C(3,18,4,2,0,0,0,0,0,0)_"01N"_$G(BCHNUM)
 set VO(18)=$C(4,18,40,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEB.DESC,1,40)
 set VO(19)=$C(5,18,12,2,0,0,0,0,0,0)_"00F"_$E(fQUEUEB.FRE,1,12)
 set VO(20)=$C(5,48,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fQUEUEB.NRD)
 set VO(21)=$C(5,67,3,2,0,0,0,0,0,0)_"00N"_fQUEUEB.STRT
 set VO(22)=$C(7,28,1,2,0,0,0,0,0,0)_"00N"_fQUEUEB.AOE
 set VO(23)=$C(7,64,1,2,0,0,0,0,0,0)_"00L"_$S(fQUEUEB.REST:"Y",1:"N")
 set VO(24)=$C(10,28,10,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEB.MAIL,1,10)
 set VO(25)=$C(11,28,50,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEB.MAILF,1,50)
 set VO(26)=$C(12,28,10,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEB.BRCD,1,10)
 set VO(27)=$C(13,28,50,2,0,0,0,0,0,0)_"00T"_$E(fQUEUEB.BRCDF,1,50)
 set VO(28)=$C(16,28,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fQUEUEB.LRD)
 set VO(29)=$C(17,28,11,2,0,0,0,0,0,0)_"01C"_$$TIM^%ZM(fQUEUEB.STIM)
 set VO(30)=$C(18,28,11,2,0,0,0,0,0,0)_"01C"_$$TIM^%ZM(fQUEUEB.CTIM)
 set VO(31)=$C(19,28,1,2,0,0,0,0,0,0)_"01N"_fQUEUEB.LSTAT
 set VO(32)=$C(19,31,0,2,0,0,0,0,0,0)_"01T"_$G(COMPMSG)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordQUEUEB fQUEUEB)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=16,VPT=1,VPB=19,PGM=$T(+0),DLIB="SYSDEV",DFID="QUEUEB"
 set OLNTB=19031
 
 set VFSN("QUEUEB")="zfQUEUEB"
 //
 // 
	
	
 set %TAB(1)=$C(2,17,4)_"21N|*BCHNUM|[*]@HBCHNUM1"
 set %TAB(2)=$C(3,17,40)_"00T12401|1|[QUEUEB]DESC||||do VP1^V00S436(.fQUEUEB)"
 set %TAB(3)=$C(4,17,12)_"00F12402|1|[QUEUEB]FRE|||do VP2^V00S436(.fQUEUEB)|do VP3^V00S436(.fQUEUEB)"
 set %TAB(4)=$C(4,47,10)_"00D12404|1|[QUEUEB]NRD||||do VP4^V00S436(.fQUEUEB)"
 set %TAB(5)=$C(4,66,3)_"00N12405|1|[QUEUEB]STRT"
 set %TAB(6)=$C(6,27,1)_"00N12406|1|[QUEUEB]AOE||||do VP5^V00S436(.fQUEUEB)"
 set %TAB(7)=$C(6,63,1)_"00L12414|1|[QUEUEB]REST||||do VP6^V00S436(.fQUEUEB)"
 set %TAB(8)=$C(9,27,10)_"00T12410|1|[QUEUEB]MAIL|||do VP7^V00S436(.fQUEUEB)"
 set %TAB(9)=$C(10,27,50)_"00T12411|1|[QUEUEB]MAILF"
 set %TAB(10)=$C(11,27,10)_"00T12412|1|[QUEUEB]BRCD|||do VP8^V00S436(.fQUEUEB)"
 set %TAB(11)=$C(12,27,50)_"00T12413|1|[QUEUEB]BRCDF"
 set %TAB(12)=$C(15,27,10)_"21D12403|1|[QUEUEB]LRD"
 set %TAB(13)=$C(16,27,11)_"21C12407|1|[QUEUEB]STIM||||||86400"
 set %TAB(14)=$C(17,27,11)_"21C12408|1|[QUEUEB]CTIM||||||86400"
 set %TAB(15)=$C(18,27,1)_"21N12409|1|[QUEUEB]LSTAT"
 set %TAB(16)=$C(18,30,0)_"21T|*COMPMSG|[*]@COMPMSG"
 do VTBL(.fQUEUEB),VDEPRE(.fQUEUEB) if $G(ER) quit
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordQUEUEB fQUEUEB) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDEPRE(RecordQUEUEB fQUEUEB)  // Data Entry Pre-processor
 
 if BATCH.get() do PROTECT^DBSMACRO("QUEUEB.DESC")
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordQUEUEB fQUEUEB) //
 if 'BATCH.get() do CHANGE^DBSMACRO("REQ")
 quit
VP2(RecordQUEUEB fQUEUEB) //
 if BATCH.get() ! X.isNull() ! (X=V) quit
 set JD=CUVAR.tjd
 set FRE=X
 do ^UFRE

 // Invalid frequency
 if NJD=-1 set ER=1,RM=$$^MSG(1353) quit   
 set fQUEUEB.nrd=NJD
 set RM=$$DAT^%ZM(NJD)_"|"_(NI+1)
 quit 

VP3(RecordQUEUEB fQUEUEB) //
 if 'BATCH.get() do CHANGE^DBSMACRO("REQ","")
 quit

VP4(RecordQUEUEB fQUEUEB) //
 if 'BATCH.get() do CHANGE^DBSMACRO("REQ","")
 quit
VP5(RecordQUEUEB fQUEUEB) //
 if 'BATCH.get() do CHANGE^DBSMACRO("REQ","")

 // CONTINUE WITH NEXT JOB
 set AOE(0)=$$^MSG(6177)
 set AOE(1)=$$^MSG(6178)
 set I(3)="AOE("    
 quit
VP6(RecordQUEUEB fQUEUEB) //
 if 'BATCH.get() do CHANGE^DBSMACRO("REQ","")
 quit
VP7(RecordQUEUEB fQUEUEB) //
 if 'X.isNull() do COND^QUEMANT
 quit
VP8(RecordQUEUEB fQUEUEB) //
 if 'X.isNull() do COND^QUEMANT
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordQUEUEB fQUEUEB
 do VPR(.fQUEUEB)
 do VDA1(.fQUEUEB)
 do ^DBSPNT()
 quit

VW(RecordQUEUEB fQUEUEB)
 do VDA1(.fQUEUEB)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordQUEUEB fQUEUEB)
 do VDA1(.fQUEUEB)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordQUEUEB fQUEUEB
 do VDA1(.fQUEUEB)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordQUEUEB fQUEUEB
 if sn="QUEUEB" do vSET1(.fQUEUEB,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordQUEUEB fQUEUEB,di,X)
 do fQUEUEB.setAuditFlag(1)
 set fQUEUEB.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordQUEUEB fQUEUEB
 if fid="QUEUEB" quit $$vREAD1(.fQUEUEB,di)
 quit ""
vREAD1(RecordQUEUEB fQUEUEB,di)
 quit fQUEUEB.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
