V00S625(%ProcessMode,RecordUTBLREGION UTBL)   // -  - SID= <UTBLREGION> Region Code User Table
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 12:38 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="UTBLREGION",VPGM=$T(+0),VSNAME="Region Code User Table"
 set VFSN("UTBLREGION")="zUTBL"
 set vPSL=1
 set KEYS(1)=UTBL.KEY
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.UTBL),VDA1(.UTBL),^DBSPNT()

 set ER=0 do VSCRPRE(.UTBL) if ER quit  // Screen Pre-Processor
 
 if '%ProcessMode do VNEW(.UTBL),VPR(.UTBL),VDA1(.UTBL)
 if %ProcessMode do VLOD(.UTBL) quit:$G(ER)  do VPR(.UTBL),VDA1(.UTBL)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.UTBL)
	quit


VNEW(RecordUTBLREGION UTBL) // Initialize arrays if %O=0
 
 do VDEF(.UTBL)
 do VLOD(.UTBL)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordUTBLREGION UTBL)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordUTBLREGION UTBL) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordUTBLREGION UTBL) // Display screen prompts
 set VO="12||13|"
 set VO(0)="|0"
 set VO(1)=$C(2,27,25,1,0,0,0,0,0,0)_"01T Region Code Maintenance "
 set VO(2)=$C(4,8,13,0,0,0,0,0,0,0)_"01T Region Code:"
 set VO(3)=$C(6,8,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(4)=$C(9,24,25,2,0,0,0,0,0,0)_"01T1098/1099-INT Information"
 set VO(5)=$C(11,9,26,0,0,0,0,0,0,0)_"01TApply Cutoff Option  1098:"
 set VO(6)=$C(11,45,9,0,0,0,0,0,0,0)_"01T1099-INT:"
 set VO(7)=$C(13,5,16,0,0,0,0,0,0,0)_"01TPayer ID Number:"
 set VO(8)=$C(15,12,9,0,0,0,0,0,0,0)_"01T Address:"
 set VO(9)=$C(19,16,5,0,0,0,0,0,0,0)_"01TCity:"
 set VO(10)=$C(20,13,8,0,0,0,0,0,0,0)_"01TCountry:"
 set VO(11)=$C(20,26,15,0,0,0,0,0,0,0)_"01TState/Province:"
 set VO(12)=$C(20,46,12,0,0,0,0,0,0,0)_"01TPostal Code:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordUTBLREGION UTBL)  // Display screen data
 new V
 //
 set VO="25|13|13|"
 set VO(13)=$C(4,22,10,2,0,0,0,0,0,0)_"01T"_$E(UTBL.KEY,1,10)
 set VO(14)=$C(6,22,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.DESC,1,40)
 set VO(15)=$C(11,36,1,2,0,0,0,0,0,0)_"00N"_UTBL.CTOF1098
 set VO(16)=$C(11,55,1,2,0,0,0,0,0,0)_"00N"_UTBL.CTOF1099
 set VO(17)=$C(13,22,11,2,0,0,0,0,0,0)_"00T"_$E(UTBL.TAXID,1,11)
 set VO(18)=$C(15,22,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.AD1,1,40)
 set VO(19)=$C(16,22,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.AD2,1,40)
 set VO(20)=$C(17,22,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.AD3,1,40)
 set VO(21)=$C(18,22,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.AD4,1,40)
 set VO(22)=$C(19,22,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.CITY,1,40)
 set VO(23)=$C(20,22,2,2,0,0,0,0,0,0)_"00T"_$E(UTBL.CNTRY,1,2)
 set VO(24)=$C(20,42,2,2,0,0,0,0,0,0)_"00T"_$E(UTBL.STATE,1,2)
 set VO(25)=$C(20,59,10,2,0,0,0,0,0,0)_"00T"_$E(UTBL.MZIP,1,10)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordUTBLREGION UTBL)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=13,VPT=2,VPB=20,PGM=$T(+0),DLIB="SYSDEV",DFID="UTBLREGION"
 set OLNTB=20059
 
 set VFSN("UTBLREGION")="zUTBL"
 //
 // 
	
	
 set %TAB(1)=$C(3,21,10)_"21T12401|1|[UTBLREGION]KEY"
 set %TAB(2)=$C(5,21,40)_"01T12401|1|[UTBLREGION]DESC"
 set %TAB(3)=$C(10,35,1)_"00N12411|1|[UTBLREGION]CTOF1098|[STBLIRSCTOF]"
 set %TAB(4)=$C(10,54,1)_"00N12412|1|[UTBLREGION]CTOF1099|[STBLIRSCTOF]"
 set %TAB(5)=$C(12,21,11)_"00T12402|1|[UTBLREGION]TAXID||if ((X="""")!(X?3N1""-""2N1""-""4N)!(X?2N1""-""7N))"
 set %TAB(6)=$C(14,21,40)_"00T12407|1|[UTBLREGION]AD1"
 set %TAB(7)=$C(15,21,40)_"00T12408|1|[UTBLREGION]AD2"
 set %TAB(8)=$C(16,21,40)_"00T12409|1|[UTBLREGION]AD3"
 set %TAB(9)=$C(17,21,40)_"00T12410|1|[UTBLREGION]AD4"
 set %TAB(10)=$C(18,21,40)_"00T12403|1|[UTBLREGION]CITY"
 set %TAB(11)=$C(19,21,2)_"00T12406|1|[UTBLREGION]CNTRY|[STBLCNTRY]||do VP1^V00S625(.UTBL)"
 set %TAB(12)=$C(19,41,2)_"00T12404|1|[UTBLREGION]STATE|[STBLCNTRY1]||do VP2^V00S625(.UTBL)"
 set %TAB(13)=$C(19,58,10)_"00T12405|1|[UTBLREGION]MZIP|||do VP3^V00S625(.UTBL)"
 do VTBL(.UTBL)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordUTBLREGION UTBL) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordUTBLREGION UTBL) //
 /* 

    ---- Revision History------------------------------------------------
   
	 04/18/05 - SWARNALATHA P - CR 13769
    	 Converted to PSL

    ---------------------------------------------------------------------
 */

 type Public String CNTRY,X

 if X.isNull() set CNTRY="0"
 else  set CNTRY=X
   
 if UTBL.city.isNull() quit

 // Required
 if X.isNull() do Runtime.setErrMSG("UTBLREGION","2385") quit:ER

 quit
VP2(RecordUTBLREGION UTBL) //
 /*
 
    ---- Revision History------------------------------------------------
 
         04/18/05 - SWARNALATHA P - CR 13769
         Converted to PSL
 
    ---------------------------------------------------------------------
 */ 

 type Public String CNTRY, PROV, X

 if CNTRY = "CA" set PROV = X

 type ResultSet rs=Db.select("STATE","STBLCNTRY1","CNTRY=:UTBL.cntry")

 // Allow city with no state if country has no states
 if rs.isEmpty() quit
 
 // Country has states, city is defined, state is therefore required

 // Required

 if ('UTBL.city.isNull() & (X.isNull())) do Runtime.setErrMSG("UTBLREGION","2385") quit:ER
 
 quit
VP3(RecordUTBLREGION UTBL) //
 /*
 
    ---- Revision History------------------------------------------------
 
         04/18/05 - SWARNALATHA P - CR 13769
         Converted to PSL
 
    ---------------------------------------------------------------------
 */ 

 type Public String CNTRY, ST, X

 // Required
 if ((CNTRY = "US") & 'UTBL.city.isNull() & (X.isNull())) do Runtime.setErrMSG("UTBLREGION", 2385) quit:ER

 set ST = UTBL.state
 do VPO1(.UTBL)

 quit
VPO1(RecordUTBLREGION UTBL)  // user library ZIP
 ; The code previously found in this routine has been moved to the new filer
 ; processer library.  This library contains code shared by the filers and by
 ; DQ screens. ; code removed 12/9/96 Spier
 ; Zip Code Verification
 ;
 D ZIP^PROCZIP($G(CNTRY),$G(ST),$G(X))
 Q
 #ACCEPT DATE=11/05/03;pgm=screen compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordUTBLREGION UTBL
 do VPR(.UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT()
 quit

VW(RecordUTBLREGION UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordUTBLREGION UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordUTBLREGION UTBL
 do VDA1(.UTBL)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordUTBLREGION UTBL
 if sn="UTBLREGION" do vSET1(.UTBL,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordUTBLREGION UTBL,di,X)
 do UTBL.setAuditFlag(1)
 set UTBL.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordUTBLREGION UTBL
 if fid="UTBLREGION" quit $$vREAD1(.UTBL,di)
 quit ""
vREAD1(RecordUTBLREGION UTBL,di)
 quit UTBL.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 //
VSCRPRE(RecordUTBLREGION UTBL)  // Screen Pre-Processor
 new %TAB,vtab // Disable .MACRO. references to %TAB()
 //
 /*
 
    ---- Revision History------------------------------------------------
 
         04/18/05 - SWARNALATHA P - CR 13769
         Converted to PSL
 
    ---------------------------------------------------------------------
 */
 
 type Public String PS, PZ
 if CUVAR.ccntry = "CA" do {
        
        //set PZ with the value Province:      
	set PS = "Province:"
        // set PZ with the message Postal Code:
	set PZ = $$^MSG(6009)
 	}
 else  do {
        
        // set PS with the message State
 	set PS = $$^MSG(6012)
 
	// set PS with the message Zip Code:
        set PZ = $$^MSG(6015)
 	}
 
 quit
 #ACCEPT date=11/05/03;PGM=Screen Compiler
 quit
