V00S228(%ProcessMode,RecordEFTPAY fEFTPAY,RecordDEP DEP)   // -  - SID= <INTRTNHQ10> Int'l Payment (In) HQ Screen (Return)
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:23 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="INTRTNHQ10",VPGM=$T(+0),VSNAME="Int'l Payment (In) HQ Screen (Return)"
 set VFSN("DEP")="zDEP",VFSN("EFTPAY")="zfEFTPAY"
 set vPSL=1
 set KEYS(1)=DEP.CID
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fEFTPAY,.DEP),VDA1(.fEFTPAY,.DEP),^DBSPNT()

 // Display Pre-Processor
 //
 if '%ProcessMode do VNEW(.fEFTPAY,.DEP),VDSPPRE(.fEFTPAY,.DEP) quit:$G(ER)  do VPR(.fEFTPAY,.DEP),VDA1(.fEFTPAY,.DEP)
 if %ProcessMode do VLOD(.fEFTPAY,.DEP) quit:$G(ER)  do VDSPPRE(.fEFTPAY,.DEP) quit:$G(ER)  do VPR(.fEFTPAY,.DEP),VDA1(.fEFTPAY,.DEP)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fEFTPAY,.DEP)
	quit


VNEW(RecordEFTPAY fEFTPAY,RecordDEP DEP) // Initialize arrays if %O=0
 
 do VDEF(.fEFTPAY,.DEP)
 do VLOD(.fEFTPAY,.DEP)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordEFTPAY fEFTPAY,RecordDEP DEP)
 if fEFTPAY.DATECRE="" set fEFTPAY.DATECRE=TJD
 if fEFTPAY.TIMECRE="" set fEFTPAY.TIMECRE=$P($H,",",2)
 if fEFTPAY.UID="" set fEFTPAY.UID=%UID
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordEFTPAY fEFTPAY,RecordDEP DEP) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordEFTPAY fEFTPAY,RecordDEP DEP) // Display screen prompts
 set VO="20||13|0"
 set VO(0)="|"
 set VO(1)=$C(3,8,16,0,0,0,0,0,0,0)_"01T Account Number:"
 set VO(2)=$C(3,51,10,0,0,0,0,0,0,0)_"01T Sequence:"
 set VO(3)=$C(4,5,19,0,0,0,0,0,0,0)_"01TTran Reference Nbr:"
 set VO(4)=$C(4,54,7,0,0,0,0,0,0,0)_"01TStatus:"
 set VO(5)=$C(6,22,36,2,0,0,0,0,0,0)_"01T-- Return Payment/Fee Information --"
 set VO(6)=$C(8,10,14,0,0,0,0,0,0,0)_"01T Payment Date:"
 set VO(7)=$C(8,46,15,0,0,0,0,0,0,0)_"01T Exchange Rate:"
 set VO(8)=$C(9,3,21,1,0,0,0,0,0,0)_"01T Return Payment Date:"
 set VO(9)=$C(11,8,16,0,0,0,0,0,0,0)_"01T Payment Amount:"
 set VO(10)=$C(11,46,15,0,0,0,0,0,0,0)_"01T Actual Amount:"
 set VO(11)=$C(13,3,21,1,0,0,0,0,0,0)_"01T Retain Original Fee:"
 set VO(12)=$C(14,11,13,0,0,0,0,0,0,0)_"01TOriginal Fee:"
 set VO(13)=$C(14,47,14,0,0,0,0,0,0,0)_"01T Original Fee:"
 set VO(14)=$C(16,5,19,0,0,0,0,0,0,0)_"01T Return Fee Method:"
 set VO(15)=$C(17,13,11,0,0,0,0,0,0,0)_"01TReturn Fee:"
 set VO(16)=$C(17,50,11,0,0,0,0,0,0,0)_"01TReturn Fee:"
 set VO(17)=$C(19,9,15,0,0,0,0,0,0,0)_"01TTotal Returned:"
 set VO(18)=$C(19,46,15,0,0,0,0,0,0,0)_"01TTotal Returned:"
 set VO(19)=$C(20,4,20,0,0,0,0,0,0,0)_"01TReturned to Account:"
 set VO(20)=$C(20,46,15,0,0,0,0,0,0,0)_"01TRepair Message:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordEFTPAY fEFTPAY,RecordDEP DEP)  // Display screen data
 new V
 s D2CRCD=$G(D2CRCD)
 s DCRCD=$G(DCRCD)
 //
 set VO="45|21|13|0"
 set VO(21)=$C(1,1,80,1,0,0,0,0,0,0)_"01T"_$S(%ProcessMode=5:"",1:$$BANNER^DBSGETID(%FN))
 set VO(22)=$C(3,25,12,2,0,0,0,0,0,0)_"01N"_fEFTPAY.CID
 set VO(23)=$C(3,62,12,2,0,0,0,0,0,0)_"01N"_fEFTPAY.SEQ
 set VO(24)=$C(4,25,14,2,0,0,0,0,0,0)_"01T"_$E(fEFTPAY.REFNO,1,14)
 set VO(25)=$C(4,62,3,2,0,0,0,0,0,0)_"01T"_$E(fEFTPAY.STATUS,1,3)
 set VO(26)=$C(4,66,12,2,0,0,0,0,0,0)_"01T"_$E(fEFTPAY.STATDSC,1,12)
 set VO(27)=$C(8,25,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fEFTPAY.PROCDT)
 set V=$S(fEFTPAY.RATE="":"",1:$J(fEFTPAY.RATE,0,6)) set VO(28)=$C(8,62,12,2,0,0,0,0,0,0)_"01N"_$S(fEFTPAY.RATE="":"",1:$J(fEFTPAY.RATE,0,6))
 set VO(29)=$C(9,25,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fEFTPAY.RTNDT)
 set V=$S(fEFTPAY.AMOUNT="":"",1:$J(fEFTPAY.AMOUNT,0,2)) set VO(30)=$C(11,25,15,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.AMOUNT="":"",1:$J(fEFTPAY.AMOUNT,0,2))
 set V=$S(fEFTPAY.ACTAMT="":"",1:$J(fEFTPAY.ACTAMT,0,2)) set VO(31)=$C(11,62,15,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.ACTAMT="":"",1:$J(fEFTPAY.ACTAMT,0,2))
 set VO(32)=$C(13,25,1,2,0,0,0,0,0,0)_"00L"_$S(fEFTPAY.ORIGFEE:"Y",1:"N")
 set V=$S(fEFTPAY.FEEAMTPMT="":"",1:$J(fEFTPAY.FEEAMTPMT,0,2)) set VO(33)=$C(14,25,12,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.FEEAMTPMT="":"",1:$J(fEFTPAY.FEEAMTPMT,0,2))
 set VO(34)=$C(14,38,3,2,0,0,0,0,0,0)_"01T"_$E(fEFTPAY.CRCD,1,3)
 set V=$S(fEFTPAY.ACTFEE="":"",1:$J(fEFTPAY.ACTFEE,0,2)) set VO(35)=$C(14,62,12,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.ACTFEE="":"",1:$J(fEFTPAY.ACTFEE,0,2))
 set VO(36)=$C(14,75,3,2,0,0,0,0,0,0)_"01T"_$G(DCRCD)
 set VO(37)=$C(16,25,12,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RTNFEETYPE,1,12)
 set V=$S(fEFTPAY.RTNFEEAMT2="":"",1:$J(fEFTPAY.RTNFEEAMT2,0,2)) set VO(38)=$C(17,25,12,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.RTNFEEAMT2="":"",1:$J(fEFTPAY.RTNFEEAMT2,0,2))
 set VO(39)=$C(17,38,3,2,0,0,0,0,0,0)_"01T"_$E(fEFTPAY.CRCD,1,3)
 set V=$S(fEFTPAY.RTNFEEAMT="":"",1:$J(fEFTPAY.RTNFEEAMT,0,2)) set VO(40)=$C(17,62,12,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.RTNFEEAMT="":"",1:$J(fEFTPAY.RTNFEEAMT,0,2))
 set VO(41)=$C(17,75,3,2,0,0,0,0,0,0)_"01T"_$G(D2CRCD)
 set V=$S(fEFTPAY.RTNTOTPMT="":"",1:$J(fEFTPAY.RTNTOTPMT,0,2)) set VO(42)=$C(19,25,15,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.RTNTOTPMT="":"",1:$J(fEFTPAY.RTNTOTPMT,0,2))
 set V=$S(fEFTPAY.RTNTOTCID="":"",1:$J(fEFTPAY.RTNTOTCID,0,2)) set VO(43)=$C(19,62,15,2,0,0,0,0,0,0)_"01$"_$S(fEFTPAY.RTNTOTCID="":"",1:$J(fEFTPAY.RTNTOTCID,0,2))
 set VO(44)=$C(20,25,12,2,0,0,0,0,0,0)_"01N"_fEFTPAY.SENDNOS
 set VO(45)=$C(20,62,1,2,0,0,0,0,0,0)_"00L"_$S(fEFTPAY.REPAIR:"Y",1:"N")
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordEFTPAY fEFTPAY,RecordDEP DEP)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=24,VPT=1,VPB=20,PGM=$T(+0),DLIB="SYSDEV",DFID="EFTPAY"
 set OLNTB=20062
 
 set VFSN("DEP")="zDEP",VFSN("EFTPAY")="zfEFTPAY"
 //
 // 
	
	
 set %TAB(1)=$C(2,24,12)_"20N12401|1|[EFTPAY]CID"
 set %TAB(2)=$C(2,61,12)_"20N12402|1|[EFTPAY]SEQ|[EFTPAY]"
 set %TAB(3)=$C(3,24,14)_"20T12404|1|[EFTPAY]REFNO|||||||||20"
 set %TAB(4)=$C(3,61,3)_"20T12412|1|[EFTPAY]STATUS|[STBLESTAT]"
 set %TAB(5)=$C(3,65,12)_"20T12400|*STATDSC|[EFTPAY]STATDSC|||||||||15"
 set %TAB(6)=$C(7,24,10)_"20D12417|1|[EFTPAY]PROCDT"
 set %TAB(7)=$C(7,61,12)_"20N12434|1|[EFTPAY]RATE|||||||6"
 set %TAB(8)=$C(8,24,10)_"01D12414|1|[EFTPAY]RTNDT|||do VP1^V00S228(.fEFTPAY,.DEP)"
 set %TAB(9)=$C(10,24,15)_"20$12403|1|[EFTPAY]AMOUNT|||||||2"
 set %TAB(10)=$C(10,61,15)_"20$12415|1|[EFTPAY]ACTAMT|||||||2"
 set %TAB(11)=$C(12,24,1)_"00L12410|1|[EFTPAY]ORIGFEE|||do VP2^V00S228(.fEFTPAY,.DEP)"
 set %TAB(12)=$C(13,24,12)_"20$12413|1|[EFTPAY]FEEAMTPMT|||||||2"
 set %TAB(13)=$C(13,37,3)_"20T12404|1|[EFTPAY]CRCD|[CRCD]:QU ""[CRCD]CO=<<%CO>>"""
 set %TAB(14)=$C(13,61,12)_"21$12436|1|[EFTPAY]ACTFEE|||||||2"
 set %TAB(15)=$C(13,74,3)_"20T|*DCRCD|[*]@DCRCD"
 set %TAB(16)=$C(15,24,12)_"00T12406|1|[EFTPAY]RTNFEETYPE|[EFTFEE]||do VP3^V00S228(.fEFTPAY,.DEP)"
 set %TAB(17)=$C(16,24,12)_"20$12412|1|[EFTPAY]RTNFEEAMT2|||||||2"
 set %TAB(18)=$C(16,37,3)_"20T12404|1|[EFTPAY]CRCD|[CRCD]:QU ""[CRCD]CO=<<%CO>>"""
 set %TAB(19)=$C(16,61,12)_"20$12407|1|[EFTPAY]RTNFEEAMT|||||||2"
 set %TAB(20)=$C(16,74,3)_"20T|*D2CRCD|[*]@D2CRCD"
 set %TAB(21)=$C(18,24,15)_"20$12409|1|[EFTPAY]RTNTOTPMT|||||||2"
 set %TAB(22)=$C(18,61,15)_"20$12411|1|[EFTPAY]RTNTOTCID|||||||2"
 set %TAB(23)=$C(19,24,12)_"20N12424|1|[EFTPAY]SENDNOS"
 set %TAB(24)=$C(19,61,1)_"00L12420|1|[EFTPAY]REPAIR"
 do VTBL(.fEFTPAY,.DEP)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordEFTPAY fEFTPAY,RecordDEP DEP) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Date X
 
 if X<%SystemDate do Runtime.setErrMSG("EFTPAY",7647) quit

 quit
VP2(RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type Number FAMT
 type String CIDCRCD,PMTCRCD
 
 type public Number X
 type public String CO
 
 if 'X do { quit
 	set fEFTPAY.FEEAMTPMT=0
 	do DISPLAY^DBSMACRO("EFTPAY.FEEAMTPMT",fEFTPAY.FEEAMTPMT)
 	}
 
 set CO=CUVAR.co
 set PMTCRCD=fEFTPAY.CRCD
 type RecordDEP dep=Db.getRecord("DEP","CID=:fEFTPAY.CID",1)
 set CIDCRCD=dep.crcd
 if CIDCRCD="" set CIDCRCD=PMTCRCD
 
 set FAMT=fEFTPAY.ACTFEE
 if PMTCRCD'=CIDCRCD do CAMT^CRCDUTL(CIDCRCD,PMTCRCD,.FAMT) set fEFTPAY.FEEAMTPMT=FAMT
 if PMTCRCD=CIDCRCD set fEFTPAY.FEEAMTPMT=fEFTPAY.ACTFEE
 do DISPLAY^DBSMACRO("EFTPAY.FEEAMTPMT",fEFTPAY.FEEAMTPMT)
 
 quit
VP3(RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type Number ORIGFEE,RTNCCY,RTNFEE,RFEEAMT
 type String CIDCRCD,PMTCRCD
 
 type public String CO,D2CRCD,X
 
 type RecordEFTFEE eftfee=Db.getRecord("EFTFEE","CODE=:X",1)
 if (X'="")&('eftfee.getMode()) do Runtime.setErrMSG("EFTFEE",7194) quit
 if X="" set RTNFEE=0
 
 set (RTNFEE,RTNCCY)=""
 
 do RTNFEE^EFTPAY2(.RTNFEE,.RTNCCY)
 if RTNFEE="" set RTNFEE=0
 
 set fEFTPAY.RTNFEEAMT=RTNFEE
 
 set CO=CUVAR.co
 type RecordDEP dep=Db.getRecord("DEP","CID=:fEFTPAY.CID",1)
 set CIDCRCD=dep.crcd
 if CIDCRCD="" set CIDCRCD=fEFTPAY.CRCD
 
 set PMTCRCD=fEFTPAY.CRCD
 set RFEEAMT=fEFTPAY.RTNFEEAMT
 if PMTCRCD'=D2CRCD do CAMT^CRCDUTL(D2CRCD,PMTCRCD,.RFEEAMT) set fEFTPAY.RTNFEEAMT2=RFEEAMT
 if PMTCRCD=D2CRCD set fEFTPAY.RTNFEEAMT2=fEFTPAY.RTNFEEAMT
 
 set fEFTPAY.RTNTOTPMT=fEFTPAY.AMOUNT-(fEFTPAY.FEEAMTPMT+fEFTPAY.RTNFEEAMT2)
 if fEFTPAY.ORIGFEE set ORIGFEE=fEFTPAY.FEEAMT
 else  set ORIGFEE=0
 
 if fEFTPAY.RTNFEETYPE'="" set RTNFEE=fEFTPAY.RTNFEEAMT
 else  set RTNFEE=0
 
 set fEFTPAY.RTNTOTCID=fEFTPAY.ACTAMT-(ORIGFEE+RTNFEE)
 
 if CIDCRCD=fEFTPAY.CRCD set fEFTPAY.RTNTOTCID=fEFTPAY.RTNTOTPMT
 
 do DISPLAY^DBSMACRO("EFTPAY.RTNFEEAMT",fEFTPAY.RTNFEEAMT)
 do DISPLAY^DBSMACRO("EFTPAY.RTNFEEAMT2",fEFTPAY.RTNFEEAMT2)
 do DISPLAY^DBSMACRO("EFTPAY.RTNTOTCID",fEFTPAY.RTNTOTCID)
 do DISPLAY^DBSMACRO("EFTPAY.RTNTOTPMT",fEFTPAY.RTNTOTPMT)
 
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordEFTPAY fEFTPAY
 type Public RecordDEP DEP
 do VPR(.fEFTPAY,.DEP)
 do VDA1(.fEFTPAY,.DEP)
 do ^DBSPNT()
 quit

VW(RecordEFTPAY fEFTPAY,RecordDEP DEP)
 do VDA1(.fEFTPAY,.DEP)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordEFTPAY fEFTPAY,RecordDEP DEP)
 do VDA1(.fEFTPAY,.DEP)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordEFTPAY fEFTPAY
 type Public RecordDEP DEP
 do VDA1(.fEFTPAY,.DEP)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordEFTPAY fEFTPAY
 if sn="EFTPAY" do vSET1(.fEFTPAY,di,X)
 type Public RecordDEP DEP
 if sn="DEP" do vSET2(.DEP,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordEFTPAY fEFTPAY,di,X)
 do fEFTPAY.setAuditFlag(1)
 set fEFTPAY.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET2(RecordDEP DEP,di,X)
 do DEP.setAuditFlag(1)
 set DEP.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordEFTPAY fEFTPAY
 if fid="EFTPAY" quit $$vREAD1(.fEFTPAY,di)
 type Public RecordDEP DEP
 if fid="DEP" quit $$vREAD2(.DEP,di)
 quit ""
vREAD1(RecordEFTPAY fEFTPAY,di)
 quit fEFTPAY.@di
vREAD2(RecordDEP DEP,di)
 quit DEP.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 //
VDSPPRE(RecordEFTPAY fEFTPAY,RecordDEP DEP)  // Display Pre-Processor
 new %TAB,vtab // Disable .MACRO. references to %TAB()
 //
 type public String CID,D2CRCD,DCRCD,SEQ
 
 if 'fEFTPAY.getMode() do {
 	type RecordEFTPAY fEFTPAY=Db.getRecord("EFTPAY","CID=:CID,SEQ=:SEQ",1)
 	if 'fEFTPAY.getMode() quit
 	}
 if fEFTPAY.TTYPE=0 do {
 	type RecordDEP dep=Db.getRecord("DEP","CID=:fEFTPAY.CID",1)
 	set (DCRCD,D2CRCD)=dep.crcd
 	}
 else  set (DCRCD,D2CRCD)=fEFTPAY.CRCD
 #ACCEPT date=11/05/03;PGM=Screen Compiler
 quit
