V00S085(%ProcessMode,RecordCUVAR fCUVAR)   // -  - SID= <CUVARLN1> Loan (General)
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:09 - kini
 // This screen enables the institution to establish general loan
 // processing parameters.  The user accesses this screen via
 // the Institution Variables Maintenance function (CUV001).
 // 
 // For loan fee processing purposes, the CUVARLN1 screen identifies
 // the debit ([CUVAR]FEEIDRTC) and credit ([CUVAR]FEEICRTC) offset
 // transaction codes which adjust the general ledger fee income
 // and deferred fee income accounts.  The system references these
 // transaction codes when assessing and/or adjusting loan fees.
 // For further information, refer to the Loan Fee Processing Reference
 // Manual.
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="CUVARLN1",VPGM=$T(+0),VSNAME="Loan (General)"
 set VFSN("CUVAR")="zfCUVAR"
 set vPSL=1
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fCUVAR),VDA1(.fCUVAR),^DBSPNT()

 if '%ProcessMode do VNEW(.fCUVAR),VPR(.fCUVAR),VDA1(.fCUVAR)
 if %ProcessMode do VLOD(.fCUVAR) quit:$G(ER)  do VPR(.fCUVAR),VDA1(.fCUVAR)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fCUVAR)
	quit


VNEW(RecordCUVAR fCUVAR) // Initialize arrays if %O=0
 
 do VDEF(.fCUVAR)
 do VLOD(.fCUVAR)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordCUVAR fCUVAR)
 if fCUVAR.%ET="" set fCUVAR.%ET="ZE^UTLERR"
 if fCUVAR.%HELP="" set fCUVAR.%HELP=0
 if fCUVAR.%HELPCNT="" set fCUVAR.%HELPCNT=0
 if fCUVAR.ALCOUNT="" set fCUVAR.ALCOUNT=5
 if fCUVAR.BANNER="" set fCUVAR.BANNER=1
 if fCUVAR.BOBR="" set fCUVAR.BOBR=0
 if fCUVAR.DBSPH132="" set fCUVAR.DBSPH132="SCAU$HELP:OOE_SCA132.EXP"
 if fCUVAR.DBSPH80="" set fCUVAR.DBSPH80="SCAU$HELP:OOE_SCA80.EXP"
 if fCUVAR.EMURND="" set fCUVAR.EMURND=9
 if fCUVAR.IRAHIST="" set fCUVAR.IRAHIST=365
 if fCUVAR.LNCC="" set fCUVAR.LNCC=0
 if fCUVAR.LNCFP="" set fCUVAR.LNCFP=0
 if fCUVAR.LNCPI="" set fCUVAR.LNCPI=0
 if fCUVAR.LNCPP="" set fCUVAR.LNCPP=0
 if fCUVAR.MAXCIFL="" set fCUVAR.MAXCIFL=12
 if fCUVAR.MINCIFL="" set fCUVAR.MINCIFL=1
 if fCUVAR.ODP="" set fCUVAR.ODP=0
 if fCUVAR.ORCIFN="" set fCUVAR.ORCIFN=1
 if fCUVAR.SFEEOPT="" set fCUVAR.SFEEOPT=0
 if fCUVAR.TAXREQ="" set fCUVAR.TAXREQ=1
 if fCUVAR.USERNAME="" set fCUVAR.USERNAME=0
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordCUVAR fCUVAR) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordCUVAR fCUVAR) // Display screen prompts
 set VO="21||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,28,26,1,0,0,0,0,0,0)_"01T Loan Account Information "
 set VO(2)=$C(3,7,21,2,0,0,0,0,0,0)_"01TInvestor Transactions"
 set VO(3)=$C(3,44,18,2,0,0,0,0,0,0)_"01TRenewal Processing"
 set VO(4)=$C(5,4,19,0,0,0,0,0,0,0)_"01TInv Wash Offset DR:"
 set VO(5)=$C(5,40,20,0,0,0,0,0,0,0)_"01TRenewal Custom Code:"
 set VO(6)=$C(6,4,19,0,0,0,0,0,0,0)_"01TInv Wash Offset CR:"
 set VO(7)=$C(6,37,23,0,0,0,0,0,0,0)_"01TRenew Delinquent Loans:"
 set VO(8)=$C(9,8,24,2,0,0,0,0,0,0)_"01TLoan Accrual Adjustment "
 set VO(9)=$C(9,44,21,2,0,0,0,0,0,0)_"01TFee Income Tran Codes"
 set VO(10)=$C(11,9,10,0,0,0,0,0,0,0)_"01TFrequency:"
 set VO(11)=$C(11,44,9,0,0,0,0,0,0,0)_"01TIncrease:"
 set VO(12)=$C(12,9,10,0,0,0,0,0,0,0)_"01TNext Date:"
 set VO(13)=$C(12,44,9,0,0,0,0,0,0,0)_"01TDecrease:"
 set VO(14)=$C(13,9,10,0,0,0,0,0,0,0)_"01TLast Date:"
 set VO(15)=$C(15,27,16,2,0,0,0,0,0,0)_"01TLoan Projections"
 set VO(16)=$C(17,11,26,0,0,0,0,0,0,0)_"01TDAYEND Projected Activity:"
 set VO(17)=$C(19,25,24,2,0,0,0,0,0,0)_"01TMass Payment Application"
 set VO(18)=$C(21,17,13,0,0,0,0,0,0,0)_"01TFull Payment:"
 set VO(19)=$C(21,41,25,0,0,0,0,0,0,0)_"01TPartial Interest Payment:"
 set VO(20)=$C(22,4,26,0,0,0,0,0,0,0)_"01TPartial Principal Payment:"
 set VO(21)=$C(22,53,13,0,0,0,0,0,0,0)_"01TCurtailments:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordCUVAR fCUVAR)  // Display screen data
 new V
 //
 set VO="35|22|13|"
 set VO(22)=$C(5,24,8,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.IWUODC,1,8)
 set VO(23)=$C(5,61,15,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.LRNCPGM,1,15)
 set VO(24)=$C(6,24,8,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.IWUOCC,1,8)
 set VO(25)=$C(6,61,1,2,0,0,0,0,0,0)_"00L"_$S(fCUVAR.LNRENDEL:"Y",1:"N")
 set VO(26)=$C(11,20,12,2,0,0,0,0,0,0)_"00F"_$E(fCUVAR.AAF,1,12)
 set VO(27)=$C(11,54,8,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.FEEICRTC,1,8)
 set VO(28)=$C(12,20,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fCUVAR.AAND)
 set VO(29)=$C(12,54,8,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.FEEIDRTC,1,8)
 set VO(30)=$C(13,20,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fCUVAR.AALD)
 set VO(31)=$C(17,38,12,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.LNPROJREP,1,12)
 set VO(32)=$C(21,31,1,2,0,0,0,0,0,0)_"00N"_fCUVAR.LNCFP
 set VO(33)=$C(21,67,1,2,0,0,0,0,0,0)_"00N"_fCUVAR.LNCPI
 set VO(34)=$C(22,31,1,2,0,0,0,0,0,0)_"00N"_fCUVAR.LNCPP
 set VO(35)=$C(22,67,1,2,0,0,0,0,0,0)_"00N"_fCUVAR.LNCC
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordCUVAR fCUVAR)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=14,VPT=1,VPB=22,PGM=$T(+0),DLIB="SYSDEV",DFID="CUVAR"
 set OLNTB=22067
 
 set VFSN("CUVAR")="zfCUVAR"
 //
 // 
	
	
 set %TAB(1)=$C(4,23,8)_"00T12411|1|[CUVAR]IWUODC|[TRN]:QUERY ""[TRN]CLS=""""M""""""||do VP1^V00S085(.fCUVAR)"
 set %TAB(2)=$C(4,60,15)_"00T12402|1|[CUVAR]LRNCPGM|||do VP2^V00S085(.fCUVAR)"
 set %TAB(3)=$C(5,23,8)_"00T12410|1|[CUVAR]IWUOCC|[TRN]:QUERY ""[TRN]CLS=""""M""""""||do VP3^V00S085(.fCUVAR)"
 set %TAB(4)=$C(5,60,1)_"00L12432|1|[CUVAR]LNRENDEL"
 set %TAB(5)=$C(10,19,12)_"00F12403|1|[CUVAR]AAF|||do VP4^V00S085(.fCUVAR)|do VP5^V00S085(.fCUVAR)"
 set %TAB(6)=$C(10,53,8)_"00T12412|1|[CUVAR]FEEICRTC|[TRN]:QUERY ""[TRN]CLS=""""M""""""||do VP6^V00S085(.fCUVAR)"
 set %TAB(7)=$C(11,19,10)_"00D12401|1|[CUVAR]AAND|||do VP7^V00S085(.fCUVAR)"
 set %TAB(8)=$C(11,53,8)_"00T12413|1|[CUVAR]FEEIDRTC|[TRN]:QUERY ""[TRN]CLS=""""M""""""||do VP8^V00S085(.fCUVAR)"
 set %TAB(9)=$C(12,19,10)_"21D12402|1|[CUVAR]AALD"
 set %TAB(10)=$C(16,37,12)_"00T12439|1|[CUVAR]LNPROJREP|[DBTBL5H]"
 set %TAB(11)=$C(20,30,1)_"00N12434|1|[CUVAR]LNCFP|[STBLMPA]"
 set %TAB(12)=$C(20,66,1)_"00N12436|1|[CUVAR]LNCPI|[STBLMPA]"
 set %TAB(13)=$C(21,30,1)_"00N12435|1|[CUVAR]LNCPP|[STBLMPA]"
 set %TAB(14)=$C(21,66,1)_"00N12437|1|[CUVAR]LNCC|[STBLMPA]"
 do VTBL(.fCUVAR)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordCUVAR fCUVAR) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordCUVAR fCUVAR) //
 if X="" quit 

 type RecordTRN trn=Db.getRecord("TRN","ETC=:X",1)
 if trn.getMode()=0 set ER=1,RM=$$^MSG(1498,X) quit
 if trn.cls'="M" set ER=1,RM=$$^MSG(1813) quit
 if $E(trn.itc) set ER=1,RM=$$^MSG(772)
 quit

VP2(RecordCUVAR fCUVAR) //
 // Invalid routine name ~p1
 if $L(X) set ER='$$VALID^%ZRTNS(X) set:ER RM=$$^MSG(1454)      
 quit

VP3(RecordCUVAR fCUVAR) //
 if X="" quit 
 type RecordTRN trn=Db.getRecord("TRN","ETC=:X",1)
 if trn.getMode()=0 set ER=1,RM=$$^MSG(1498,X) quit
 if trn.cls'="M" set ER=1,RM=$$^MSG(1813) quit
 if '$E(trn.itc) set ER=1,RM=$$^MSG(1790)
 quit 

VP4(RecordCUVAR fCUVAR) //
 if X="" quit  
 set JD=%SystemDate-1 
 set FRE=X 
 do ^UFRE 

 // Invalid frequency
 if ER set RM=$$^MSG(1353) quit      
 if MODAAF'=X do {
 	do DEFAULT^DBSMACRO("CUVAR.AAND",NJD,"1","0","0")
 	}

 kill MODAAF
 quit

VP5(RecordCUVAR fCUVAR) //
 set MODAAF=fCUVAR.aaf
 quit

VP6(RecordCUVAR fCUVAR) //
 if X="" quit 

 type RecordTRN trn=Db.getRecord("TRN","ETC=:X",1)
 if trn.getMode()=0 set ER=1,RM=$$^MSG(1498,X) quit
 if trn.cls'="M" set ER=1,RM=$$^MSG(1813) quit
 if '$E(trn.itc) set ER=1,RM=$$^MSG(1790)
 quit

VP7(RecordCUVAR fCUVAR) //
 if X="" quit
 set %JD=$$^SCAJD(X) quit:ER 

 // Date must be in the future
 if %JD<%SystemDate set ER=1,RM=$$^MSG(752) quit    
 quit

VP8(RecordCUVAR fCUVAR) //
 if X="" quit 

 type RecordTRN trn=Db.getRecord("TRN","ETC=:X",1)
 if trn.getMode()=0 set ER=1,RM=$$^MSG(1498,X) quit
 if trn.cls'="M" set ER=1,RM=$$^MSG(1813) quit
 if $E(trn.itc) set ER=1,RM=$$^MSG(772)        
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordCUVAR fCUVAR
 do VPR(.fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT()
 quit

VW(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordCUVAR fCUVAR
 do VDA1(.fCUVAR)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordCUVAR fCUVAR
 if sn="CUVAR" do vSET1(.fCUVAR,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordCUVAR fCUVAR,di,X)
 do fCUVAR.setAuditFlag(1)
 set fCUVAR.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordCUVAR fCUVAR
 if fid="CUVAR" quit $$vREAD1(.fCUVAR,di)
 quit ""
vREAD1(RecordCUVAR fCUVAR,di)
 quit fCUVAR.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
