V00S539(%ProcessMode,RecordUTBLABDM UTBL)   //PBS - LN - SID= <UTBLABDM> Asset Class Base Method Table Support
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 12:19 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab,APP1,APP2,APP3,APP4",VSID="UTBLABDM",VPGM=$T(+0),VSNAME="Asset Class Base Method Table Support"
 set VFSN("UTBLABDM")="zUTBL"
 set vPSL=1
 set KEYS(1)=UTBL.KEY
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.UTBL),VDA1(.UTBL),^DBSPNT()

 set ER=0 do VSCRPRE(.UTBL) if ER quit  // Screen Pre-Processor
 
 if '%ProcessMode do VNEW(.UTBL),VPR(.UTBL),VDA1(.UTBL)
 if %ProcessMode do VLOD(.UTBL) quit:$G(ER)  do VPR(.UTBL),VDA1(.UTBL)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.UTBL)
	quit


VNEW(RecordUTBLABDM UTBL) // Initialize arrays if %O=0
 
 do VDEF(.UTBL)
 do VLOD(.UTBL)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordUTBLABDM UTBL)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordUTBLABDM UTBL) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordUTBLABDM UTBL) // Display screen prompts
 set VO="9||13|"
 set VO(0)="|0"
 set VO(1)=$C(3,16,48,1,0,0,0,0,0,0)_"01T Asset Classification Base Determination Method "
 set VO(2)=$C(6,17,7,0,0,0,0,0,0,0)_"01TMethod:"
 set VO(3)=$C(7,11,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(4)=$C(10,25,11,0,0,0,0,0,0,0)_"01TAdjustments"
 set VO(5)=$C(10,48,10,0,0,0,0,0,0,0)_"01TApplicable"
 set VO(6)=$C(12,23,30,0,0,0,0,0,0,0)_"01T+ Interest Accrued            "
 set VO(7)=$C(13,23,30,0,0,0,0,0,0,0)_"01T+ Late Charges Due            "
 set VO(8)=$C(14,23,30,0,0,0,0,0,0,0)_"01T+ Misc Charges Due            "
 set VO(9)=$C(15,23,30,0,0,0,0,0,0,0)_"01T- Unapplied Funds             "
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordUTBLABDM UTBL)  // Display screen data
 new V
 s APP1=$G(APP1)
 s APP2=$G(APP2)
 s APP3=$G(APP3)
 s APP4=$G(APP4)
 //
 set VO="15|10|13|"
 set VO(10)=$C(6,25,4,2,0,0,0,0,0,0)_"01T"_$E(UTBL.KEY,1,4)
 set VO(11)=$C(7,25,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.DESC,1,40)
 set VO(12)=$C(12,53,1,2,0,0,0,0,0,0)_"00L"_$S($G(APP1):"Y",1:"N")
 set VO(13)=$C(13,53,1,2,0,0,0,0,0,0)_"00L"_$S($G(APP2):"Y",1:"N")
 set VO(14)=$C(14,53,1,2,0,0,0,0,0,0)_"00L"_$S($G(APP3):"Y",1:"N")
 set VO(15)=$C(15,53,1,2,0,0,0,0,0,0)_"00L"_$S($G(APP4):"Y",1:"N")
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordUTBLABDM UTBL)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=6,VPT=3,VPB=15,PGM=$T(+0),DLIB="SYSDEV",DFID="UTBLABDM",VSCRPP=1,VSCRPP=1
 set OLNTB=15053
 
 set VFSN("UTBLABDM")="zUTBL"
 //
 // 
	
	
 set %TAB(1)=$C(5,24,4)_"20T12401|1|[UTBLABDM]KEY"
 set %TAB(2)=$C(6,24,40)_"01T12401|1|[UTBLABDM]DESC"
 set %TAB(3)=$C(11,52,1)_"00L|*APP1|[*]@T4"
 set %TAB(4)=$C(12,52,1)_"00L|*APP2|[*]@T5"
 set %TAB(5)=$C(13,52,1)_"00L|*APP3|[*]@T6"
 set %TAB(6)=$C(14,52,1)_"00L|*APP4|[*]@T8"
 do VTBL(.UTBL)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordUTBLABDM UTBL) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VSPP   // screen post proc
 type Public RecordUTBLABDM UTBL
 do VSPP1(.UTBL)
 #ACCEPT Date=11/05/03; pgm=Screen Compilerxxx
 quit
VSPP1(RecordUTBLABDM UTBL)
 /*
 ---- Revision History ------------------------------------------------
 
        08/11/05 - TITOVE - CR 16844
                   Converted into PSL as part of DBI3 project.
 
 */
 type public String APP1, APP2, APP3, APP4
 
 type String A = +APP1_+APP2_+APP3_+APP4
 
 // No changes have been made
 if A = UTBL.act quit
 
 set UTBL.act = A
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordUTBLABDM UTBL
 do VPR(.UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT()
 quit

VW(RecordUTBLABDM UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordUTBLABDM UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordUTBLABDM UTBL
 do VDA1(.UTBL)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordUTBLABDM UTBL
 if sn="UTBLABDM" do vSET1(.UTBL,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordUTBLABDM UTBL,di,X)
 do UTBL.setAuditFlag(1)
 set UTBL.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordUTBLABDM UTBL
 if fid="UTBLABDM" quit $$vREAD1(.UTBL,di)
 quit ""
vREAD1(RecordUTBLABDM UTBL,di)
 quit UTBL.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 //
VSCRPRE(RecordUTBLABDM UTBL)  // Screen Pre-Processor
 new %TAB,vtab // Disable .MACRO. references to %TAB()
 //
 /*
 ---- Revision History ------------------------------------------------
	08/11/05 - TITOVE - CR 16844
		   Converted into PSL as part of DBI3 project.
 */
 type public String APP1, APP2, APP3, APP4
 
 set APP1 = UTBL.act.extract(1)
 set APP2 = UTBL.act.extract(2)
 set APP3 = UTBL.act.extract(3)
 set APP4 = UTBL.act.extract(4)
 #ACCEPT date=11/05/03;PGM=Screen Compiler
 quit
