V00S549(%ProcessMode,RecordUTBLACHRT fUTACHRT)   // -  - SID= <UTBLACHRT> ACH Routing and Transit Numbers
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 12:19 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="UTBLACHRT",VPGM=$T(+0),VSNAME="ACH Routing and Transit Numbers"
 set VFSN("UTBLACHRT")="zfUTACHRT"
 set vPSL=1
 set KEYS(1)=fUTACHRT.KEY
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fUTACHRT),VDA1(.fUTACHRT),^DBSPNT()

 if '%ProcessMode do VNEW(.fUTACHRT),VPR(.fUTACHRT),VDA1(.fUTACHRT)
 if %ProcessMode do VLOD(.fUTACHRT) quit:$G(ER)  do VPR(.fUTACHRT),VDA1(.fUTACHRT)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fUTACHRT)
	quit


VNEW(RecordUTBLACHRT fUTACHRT) // Initialize arrays if %O=0
 
 do VDEF(.fUTACHRT)
 do VLOD(.fUTACHRT)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordUTBLACHRT fUTACHRT)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordUTBLACHRT fUTACHRT) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordUTBLACHRT fUTACHRT) // Display screen prompts
 set VO="8||13|"
 set VO(0)="6|0"
 set VO(1)=$C(6,1,5,0,0,0,0,0,0,0)_"01T     "
 set VO(2)=$C(8,26,31,2,0,0,0,0,0,0)_"01TACH Routing and Transit Numbers"
 set VO(3)=$C(10,4,25,0,0,0,0,0,0,0)_"01TRouting & Transit Number:"
 set VO(4)=$C(11,11,18,1,0,0,0,0,0,0)_"01T Institution Name:"
 set VO(5)=$C(13,4,25,1,0,0,0,0,0,0)_"01T On-Us Routing & Transit:"
 set VO(6)=$C(14,6,23,1,0,0,0,0,0,0)_"01T Valid File Originator:"
 set VO(7)=$C(15,5,24,1,0,0,0,0,0,0)_"01T Valid Batch Originator:"
 set VO(8)=$C(16,5,24,1,0,0,0,0,0,0)_"01T Valid File Destination:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordUTBLACHRT fUTACHRT)  // Display screen data
 new V
 //
 set VO="14|9|13|"
 set VO(9)=$C(10,30,9,2,0,0,0,0,0,0)_"01T"_$E(fUTACHRT.KEY,1,9)
 set VO(10)=$C(11,30,36,2,0,0,0,0,0,0)_"00T"_$E(fUTACHRT.INAME,1,36)
 set VO(11)=$C(13,30,1,2,0,0,0,0,0,0)_"00L"_$S(fUTACHRT.ONUS:"Y",1:"N")
 set VO(12)=$C(14,30,1,2,0,0,0,0,0,0)_"00L"_$S(fUTACHRT.FORIG:"Y",1:"N")
 set VO(13)=$C(15,30,1,2,0,0,0,0,0,0)_"00L"_$S(fUTACHRT.BORIG:"Y",1:"N")
 set VO(14)=$C(16,30,1,2,0,0,0,0,0,0)_"00L"_$S(fUTACHRT.FDEST:"Y",1:"N")
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordUTBLACHRT fUTACHRT)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=6,VPT=6,VPB=16,PGM=$T(+0),DLIB="SYSDEV",DFID="UTBLACHRT"
 set OLNTB=16030
 
 set VFSN("UTBLACHRT")="zfUTACHRT"
 //
 // 
	
	
 set %TAB(1)=$C(9,29,9)_"21T12401|1|[UTBLACHRT]KEY"
 set %TAB(2)=$C(10,29,36)_"01T12401|1|[UTBLACHRT]INAME"
 set %TAB(3)=$C(12,29,1)_"00L12402|1|[UTBLACHRT]ONUS"
 set %TAB(4)=$C(13,29,1)_"00L12404|1|[UTBLACHRT]FORIG"
 set %TAB(5)=$C(14,29,1)_"00L12403|1|[UTBLACHRT]BORIG"
 set %TAB(6)=$C(15,29,1)_"00L12405|1|[UTBLACHRT]FDEST|||do VP1^V00S549(.fUTACHRT)"
 do VTBL(.fUTACHRT)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordUTBLACHRT fUTACHRT) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordUTBLACHRT fUTACHRT) //
 /* If the R & T is a valid file destination, it cannot be an
    on-us, file or batch originator. */

 type public String X

 // R & T cannot also be an on-us R & T
 if X,fUTACHRT.onus do Runtime.setErrMSG("UTBLACHRT",2302) quit

 // R & T cannot also be a file originator
 if X,fUTACHRT.forig do Runtime.setErrMSG("UTBLACHRT",2301) quit

 // R & T cannot also be a batch originator
 if X,fUTACHRT.borig do Runtime.setErrMSG("UTBLACHRT",2300) quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordUTBLACHRT fUTACHRT
 do VPR(.fUTACHRT)
 do VDA1(.fUTACHRT)
 do ^DBSPNT()
 quit

VW(RecordUTBLACHRT fUTACHRT)
 do VDA1(.fUTACHRT)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordUTBLACHRT fUTACHRT)
 do VDA1(.fUTACHRT)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordUTBLACHRT fUTACHRT
 do VDA1(.fUTACHRT)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordUTBLACHRT fUTACHRT
 if sn="UTBLACHRT" do vSET1(.fUTACHRT,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordUTBLACHRT fUTACHRT,di,X)
 do fUTACHRT.setAuditFlag(1)
 set fUTACHRT.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordUTBLACHRT fUTACHRT
 if fid="UTBLACHRT" quit $$vREAD1(.fUTACHRT,di)
 quit ""
vREAD1(RecordUTBLACHRT fUTACHRT,di)
 quit fUTACHRT.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
