V00S459(%ProcessMode,RecordSCAU fSCAU)   // -  - SID= <SCAUSR1> System User Input (With CIF Restrict)
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 12:03 - kini
 	/*
 	ORIG: CHENARDP - 02/27/2003
 	DESC: Linked Screen Template

 	---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4


	 ---- Revision History ------------------------------------------------
	09/24/03 - Pete Chenard - 45497
		       Created linked screen template for screen compiler.
	-----------------------------------------------------------------------

	 */
 
V0 
 set VSID="SCAUSR1"
 set KVAR="kill %A,%TAB,vtab,VFSN,%OLD,%NEW,%FILE,%INDEX,%PAGE,%PG,UX,MULSCR"
 set:'$D(%PG) %PG=1 set %PAG=%PG+2 set %PAGE=$S($D(%PAGE):%PAGE-1,1:0)+3
 set vPSL=1  //compiled for PSL
 //
 set VPG(%PG+0)="PROFILE User Set-Up (Tables/ G/L Link)|SCAUSR"
 set VPG(%PG+1)="User Status Information|SCAUSTAT"
 set VPG(%PG+2)="User Related CIF Input|SCAUR"
	set:'$D(%PG) %PG=1 set %PGSV=%PG,MULSCR=""
 if '%ProcessMode do VNEW(.fSCAU)
 if %ProcessMode do VLOD(.fSCAU) if $G(ER) set VFMQ="Q" quit
 do VPG(.fSCAU)
 quit

VNEW(RecordSCAU fSCAU)
 
 quit
 //
 ;
VLOD(RecordSCAU fSCAU)  // User defined access section
	quit

VPG(RecordSCAU fSCAU)
 new vDONE
 set vDONE=0
 for  do { quit:vDONE
  if %PG=(%PGSV+0) do VPG1(.fSCAU),VPG0(.fSCAU) quit:vDONE
  if %PG=(%PGSV+1) do VPG2(.fSCAU),VPG0(.fSCAU) quit:vDONE
  if %PG=(%PGSV+2) do VPG3(.fSCAU),VPG0(.fSCAU) quit:vDONE
  }
 quit

VPG0(RecordSCAU fSCAU)
 set %LINK=""
 if %ProcessMode=2!(%ProcessMode=3)!(%ProcessMode=4) do VBTM(.fSCAU) if $G(VFMQ)="D" set vDONE=1 quit
 if '$D(%PAGE) set vDONE=1 quit
 if %PG'<%PAG kill %PAG,%PGSV,VPG set vDONE=1 quit
 set %PG=%PG+1
 quit

 
VPG1(RecordSCAU fSCAU)  // PROFILE User Set-Up (Tables/ G/L Link)
 
 new x
 set SID="SCAUSR",DFID="SCAU"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S458
 if %ProcessMode>1 quit
 do VTAB^V00S458(.fSCAU)
 quit
 
VPG2(RecordSCAU fSCAU)  // User Status Information
 
 new x
 set SID="SCAUSTAT",DFID="SCAU"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S462
 if %ProcessMode>1 quit
 do VTAB^V00S462(.fSCAU)
 quit
 
VPG3(RecordSCAU fSCAU)  // User Related CIF Input
 
 new x
 set SID="SCAUR",DFID="SCAU"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 S %MODS=1 I '$D(%REPEAT) S %REPEAT=16
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S457
 if %ProcessMode>1 quit
 do VTAB^V00S457(.fSCAU)
 quit
 

VBTM(RecordSCAU fSCAU)

	if %ProcessMode=4,IO'=$P quit
	do ^DBSCRT8A
	quit
