V00S309(%ProcessMode,RecordLNPDS fLNPDS)   //PBS - LN - SID= <LNPDSA> PDS Table Information
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:36 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="LNPDSA",VPGM=$T(+0),VSNAME="PDS Table Information"
 set VFSN("LNPDS")="zfLNPDS"
 set vPSL=1
 set KEYS(1)=fLNPDS.TABLE
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fLNPDS),VDA1(.fLNPDS),^DBSPNT()

 if '%ProcessMode do VNEW(.fLNPDS),VPR(.fLNPDS),VDA1(.fLNPDS)
 if %ProcessMode do VLOD(.fLNPDS) quit:$G(ER)  do VPR(.fLNPDS),VDA1(.fLNPDS)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fLNPDS)
	quit


VNEW(RecordLNPDS fLNPDS) // Initialize arrays if %O=0
 
 do VDEF(.fLNPDS)
 do VLOD(.fLNPDS)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordLNPDS fLNPDS)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordLNPDS fLNPDS) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordLNPDS fLNPDS) // Display screen prompts
 set VO="4||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,7,7,1,0,0,0,0,0,0)_"01T Table:"
 set VO(2)=$C(1,57,12,1,0,0,0,0,0,0)_"01T Start Date:"
 set VO(3)=$C(2,1,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(4)=$C(2,59,10,0,0,0,0,0,0,0)_"01T End Date:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordLNPDS fLNPDS)  // Display screen data
 new V
 //
 set VO="8|5|13|"
 set VO(5)=$C(1,15,12,2,0,0,0,0,0,0)_"01T"_$E(fLNPDS.TABLE,1,12)
 set VO(6)=$C(1,70,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fLNPDS.STDT)
 set VO(7)=$C(2,15,40,2,0,0,0,0,0,0)_"00T"_$E(fLNPDS.TDES,1,40)
 set VO(8)=$C(2,70,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fLNPDS.EDDT)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordLNPDS fLNPDS)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=4,VPT=1,VPB=2,PGM=$T(+0),DLIB="SYSDEV",DFID="LNPDS"
 set OLNTB=2070
 
 set VFSN("LNPDS")="zfLNPDS"
 //
 // 
	
	
 set %TAB(1)=$C(0,14,12)_"21T12401|1|[LNPDS]TABLE|[LNPDS]||do VP1^V00S309(.fLNPDS)"
 set %TAB(2)=$C(0,69,10)_"01D12402|1|[LNPDS]STDT|||do VP2^V00S309(.fLNPDS)"
 set %TAB(3)=$C(1,14,40)_"01T12401|1|[LNPDS]TDES|||do VP3^V00S309(.fLNPDS)"
 set %TAB(4)=$C(1,69,10)_"00D12403|1|[LNPDS]EDDT|||do VP4^V00S309(.fLNPDS)"
 do VTBL(.fLNPDS)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordLNPDS fLNPDS) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordLNPDS fLNPDS) //
 set TABLE=X
VP2(RecordLNPDS fLNPDS) //
 ; 04/14/00 - TANY - 37915
 ;            Modified ^SCADAT1 to ^SCAJD
 ;
 if X="" quit
 set BDATE=$$^SCAJD(X)
 if BDATE<0 set ER=1,RM=$$^MSG(1308)
VP3(RecordLNPDS fLNPDS) //
 set TDES=X
VP4(RecordLNPDS fLNPDS) //
 ; 04/14/00 - TANY - 37915
 ;            Modified ^SCADAT1 to ^SCAJD
 ;
 if X="" quit
 set %JD=$$^SCAJD(X)
 if %JD<BDATE set ER=1,RM=$$^MSG(891)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordLNPDS fLNPDS
 do VPR(.fLNPDS)
 do VDA1(.fLNPDS)
 do ^DBSPNT()
 quit

VW(RecordLNPDS fLNPDS)
 do VDA1(.fLNPDS)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordLNPDS fLNPDS)
 do VDA1(.fLNPDS)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordLNPDS fLNPDS
 do VDA1(.fLNPDS)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordLNPDS fLNPDS
 if sn="LNPDS" do vSET1(.fLNPDS,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordLNPDS fLNPDS,di,X)
 do fLNPDS.setAuditFlag(1)
 set fLNPDS.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordLNPDS fLNPDS
 if fid="LNPDS" quit $$vREAD1(.fLNPDS,di)
 quit ""
vREAD1(RecordLNPDS fLNPDS,di)
 quit fLNPDS.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
