V00S447(%ProcessMode,RecordUTBLRSPDEF fUTBLRSP)   // -  - SID= <RSPDEFL> RSP Definition Linkage Screen
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 12:01 - kini
 	/*
 	ORIG: CHENARDP - 02/27/2003
 	DESC: Linked Screen Template

 	---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4


	 ---- Revision History ------------------------------------------------
	09/24/03 - Pete Chenard - 45497
		       Created linked screen template for screen compiler.
	-----------------------------------------------------------------------

	 */
 
V0 
 set VSID="RSPDEFL"
 set KVAR="kill %A,%TAB,vtab,VFSN,%OLD,%NEW,%FILE,%INDEX,%PAGE,%PG,UX,MULSCR"
 set:'$D(%PG) %PG=1 set %PAG=%PG+1 set %PAGE=$S($D(%PAGE):%PAGE-1,1:0)+2
 set vPSL=1  //compiled for PSL
 //
 set VPG(%PG+0)="Retirement Savings Plan Definition|RSPDEF"
 set VPG(%PG+1)="Retirement Savings Plan Definition, WTHG|RSPDEF1"
	set:'$D(%PG) %PG=1 set %PGSV=%PG,MULSCR=""
 if '%ProcessMode do VNEW(.fUTBLRSP)
 if %ProcessMode do VLOD(.fUTBLRSP) if $G(ER) set VFMQ="Q" quit
 do VPG(.fUTBLRSP)
 quit

VNEW(RecordUTBLRSPDEF fUTBLRSP)
 
 quit
 //
 ;
VLOD(RecordUTBLRSPDEF fUTBLRSP)  // User defined access section
	quit

VPG(RecordUTBLRSPDEF fUTBLRSP)
 new vDONE
 set vDONE=0
 for  do { quit:vDONE
  if %PG=(%PGSV+0) do VPG1(.fUTBLRSP),VPG0(.fUTBLRSP) quit:vDONE
  if %PG=(%PGSV+1) do VPG2(.fUTBLRSP),VPG0(.fUTBLRSP) quit:vDONE
  }
 quit

VPG0(RecordUTBLRSPDEF fUTBLRSP)
 set %LINK=""
 if %ProcessMode=2!(%ProcessMode=3)!(%ProcessMode=4) do VBTM(.fUTBLRSP) if $G(VFMQ)="D" set vDONE=1 quit
 if '$D(%PAGE) set vDONE=1 quit
 if %PG'<%PAG kill %PAG,%PGSV,VPG set vDONE=1 quit
 set %PG=%PG+1
 quit

 
VPG1(RecordUTBLRSPDEF fUTBLRSP)  // Retirement Savings Plan Definition
 
 new x
 set SID="RSPDEF",DFID="UTBLRSPDEF"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S445
 if %ProcessMode>1 quit
 do VTAB^V00S445(.fUTBLRSP)
 quit
 
VPG2(RecordUTBLRSPDEF fUTBLRSP)  // Retirement Savings Plan Definition, WTHG
 
 new x
 set SID="RSPDEF1",DFID="UTBLRSPDEF"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V00S446
 if %ProcessMode>1 quit
 do VTAB^V00S446(.fUTBLRSP)
 quit
 

VBTM(RecordUTBLRSPDEF fUTBLRSP)

	if %ProcessMode=4,IO'=$P quit
	do ^DBSCRT8A
	quit
