V00S264(%ProcessMode,RecordAOAMO fAOAMO)   //PBS - LN - SID= <LNAMOPTS1> Deferred Fee Plan Inq/Maint (Page 1) 
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:27 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="LNAMOPTS1",VPGM=$T(+0),VSNAME="Deferred Fee Plan Inq/Maint (Page 1) "
 set VFSN("AOAMO")="zfAOAMO"
 set vPSL=1
 set KEYS(1)=fAOAMO.TYP
 set KEYS(2)=fAOAMO.PAYEE
 set KEYS(3)=fAOAMO.PLAN
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fAOAMO),VDA1(.fAOAMO),^DBSPNT()

 if '%ProcessMode do VNEW(.fAOAMO),VPR(.fAOAMO),VDA1(.fAOAMO)
 if %ProcessMode do VLOD(.fAOAMO) quit:$G(ER)  do VPR(.fAOAMO),VDA1(.fAOAMO)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fAOAMO)
	quit


VNEW(RecordAOAMO fAOAMO) // Initialize arrays if %O=0
 
 do VDEF(.fAOAMO)
 do VLOD(.fAOAMO)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordAOAMO fAOAMO)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordAOAMO fAOAMO) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordAOAMO fAOAMO) // Display screen prompts
 set VO="19||13|"
 set VO(0)="|0"
 set VO(1)=$C(2,27,25,1,0,0,0,0,0,0)_"01T Net Deferred Fee Income "
 set VO(2)=$C(5,1,8,2,0,0,0,0,0,0)_"01TGeneral:"
 set VO(3)=$C(5,18,6,1,0,0,0,0,0,0)_"01T Plan:"
 set VO(4)=$C(5,48,16,1,0,0,0,0,0,0)_"01T # Times in Use:"
 set VO(5)=$C(6,11,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(6)=$C(7,8,16,1,0,0,0,0,0,0)_"01T Beginning Date:"
 set VO(7)=$C(7,52,12,0,0,0,0,0,0,0)_"01TEnding Date:"
 set VO(8)=$C(10,1,13,2,0,0,0,0,0,0)_"01TAmortization:"
 set VO(9)=$C(10,18,6,1,0,0,0,0,0,0)_"01T Freq:"
 set VO(10)=$C(10,44,20,1,0,0,0,0,0,0)_"01T Calculation Method:"
 set VO(11)=$C(11,4,20,1,0,0,0,0,0,0)_"01T Use Ledger Balance:"
 set VO(12)=$C(11,50,14,0,0,0,0,0,0,0)_"01TTerm Estimate:"
 set VO(13)=$C(12,2,22,1,0,0,0,0,0,0)_"01T Calculate in Advance:"
 set VO(14)=$C(12,43,21,1,0,0,0,0,0,0)_"01T File Posting Detail:"
 set VO(15)=$C(15,1,13,2,0,0,0,0,0,0)_"01TNew Accounts:"
 set VO(16)=$C(15,35,21,1,0,0,0,0,0,0)_"01T Odd Period Rounding:"
 set VO(17)=$C(17,1,20,2,0,0,0,0,0,0)_"01TPeriodic Processing:"
 set VO(18)=$C(17,24,32,1,0,0,0,0,0,0)_"01T Recalc Yield At Payment Change:"
 set VO(19)=$C(18,26,30,0,0,0,0,0,0,0)_"01TYield Recalculation Frequency:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordAOAMO fAOAMO)  // Display screen data
 new V
 //
 set VO="33|20|13|"
 set VO(20)=$C(5,25,6,2,0,0,0,0,0,0)_"01T"_$E(fAOAMO.PLAN,1,6)
 set VO(21)=$C(5,65,12,2,0,0,0,0,0,0)_"01N"_fAOAMO.CNT
 set VO(22)=$C(6,25,30,2,0,0,0,0,0,0)_"00T"_$E(fAOAMO.PDES,1,30)
 set VO(23)=$C(7,25,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fAOAMO.PBDATE)
 set VO(24)=$C(7,65,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fAOAMO.PLDATE)
 set VO(25)=$C(10,25,12,2,0,0,0,0,0,0)_"00F"_$E(fAOAMO.FRE,1,12)
 set VO(26)=$C(10,65,1,2,0,0,0,0,0,0)_"00N"_fAOAMO.FMET
 set VO(27)=$C(11,25,1,2,0,0,0,0,0,0)_"00L"_$S(fAOAMO.SPP:"Y",1:"N")
 set VO(28)=$C(11,65,10,2,0,0,0,0,0,0)_"00T"_$E(fAOAMO.TES,1,10)
 set VO(29)=$C(12,25,1,2,0,0,0,0,0,0)_"00L"_$S(fAOAMO.BES:"Y",1:"N")
 set VO(30)=$C(12,65,1,2,0,0,0,0,0,0)_"00L"_$S(fAOAMO.RDTL:"Y",1:"N")
 set VO(31)=$C(15,57,1,2,0,0,0,0,0,0)_"00N"_fAOAMO.OPRF
 set VO(32)=$C(17,57,1,2,0,0,0,0,0,0)_"00L"_$S(fAOAMO.RYPC:"Y",1:"N")
 set VO(33)=$C(18,57,12,2,0,0,0,0,0,0)_"00F"_$E(fAOAMO.RYFRE,1,12)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordAOAMO fAOAMO)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=14,VPT=2,VPB=18,PGM=$T(+0),DLIB="SYSDEV",DFID="AOAMO"
 set OLNTB=18057
 
 set VFSN("AOAMO")="zfAOAMO"
 //
 // 
	
	
 set %TAB(1)=$C(4,24,6)_"21T12403|1|[AOAMO]PLAN"
 set %TAB(2)=$C(4,64,12)_"21N12415|1|[AOAMO]CNT"
 set %TAB(3)=$C(5,24,30)_"01T12401|1|[AOAMO]PDES"
 set %TAB(4)=$C(6,24,10)_"01D12413|1|[AOAMO]PBDATE"
 set %TAB(5)=$C(6,64,10)_"00D12414|1|[AOAMO]PLDATE"
 set %TAB(6)=$C(9,24,12)_"01F12402|1|[AOAMO]FRE|||do VP1^V00S264(.fAOAMO)"
 set %TAB(7)=$C(9,64,1)_"01N12443|1|[AOAMO]FMET|[STBLFMET]"
 set %TAB(8)=$C(10,24,1)_"00L12445|1|[AOAMO]SPP|||do VP2^V00S264(.fAOAMO)"
 set %TAB(9)=$C(10,64,10)_"00T12444|1|[AOAMO]TES|||do VP3^V00S264(.fAOAMO)"
 set %TAB(10)=$C(11,24,1)_"00L12418|1|[AOAMO]BES"
 set %TAB(11)=$C(11,64,1)_"00L12452|1|[AOAMO]RDTL"
 set %TAB(12)=$C(14,56,1)_"01N12442|1|[AOAMO]OPRF|[STBLOPRF]"
 set %TAB(13)=$C(16,56,1)_"00L12437|1|[AOAMO]RYPC|||do VP4^V00S264(.fAOAMO)"
 set %TAB(14)=$C(17,56,12)_"00F12438|1|[AOAMO]RYFRE|||do VP5^V00S264(.fAOAMO)"
 do VTBL(.fAOAMO)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordAOAMO fAOAMO) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordAOAMO fAOAMO) //
 if '$L(X) quit 

 do EDT^UFRE

 quit

VP2(RecordAOAMO fAOAMO) //
 if 'fAOAMO.fmet do GOTO^DBSMACRO("AOAMO.BES")

 quit

VP3(RecordAOAMO fAOAMO) //
 if '$L(X),fAOAMO.fmet set ER=1,ET="LNNFMRT" do ^UTLERR quit 

 if $L(X),'fAOAMO.fmet set ER=1,ET="INVLD" do ^UTLERR quit 

 set ODT=%SystemDate

 set TRM=X 
 
 do ^UMDT
 
 quit
 
VP4(RecordAOAMO fAOAMO) //
 if '$L(X) quit

 if X,fAOAMO.fmet set ER=1,ET="NFPFMET" do ^UTLERR

 quit

VP5(RecordAOAMO fAOAMO) //
 if '$L(X) quit
 
 do EDT^UFRE
 
 if ER quit

 if fAOAMO.rypc set ER=1,ET="NFRPCF" do ^UTLERR quit

 if 'fAOAMO.spp set ER=1,ET="NFRSPP" do ^UTLERR quit

 if fAOAMO.fmet set ER=1,ET="NFRFMET" do ^UTLERR

 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordAOAMO fAOAMO
 do VPR(.fAOAMO)
 do VDA1(.fAOAMO)
 do ^DBSPNT()
 quit

VW(RecordAOAMO fAOAMO)
 do VDA1(.fAOAMO)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordAOAMO fAOAMO)
 do VDA1(.fAOAMO)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordAOAMO fAOAMO
 do VDA1(.fAOAMO)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordAOAMO fAOAMO
 if sn="AOAMO" do vSET1(.fAOAMO,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordAOAMO fAOAMO,di,X)
 do fAOAMO.setAuditFlag(1)
 set fAOAMO.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordAOAMO fAOAMO
 if fid="AOAMO" quit $$vREAD1(.fAOAMO,di)
 quit ""
vREAD1(RecordAOAMO fAOAMO,di)
 quit fAOAMO.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
