V00S190(%ProcessMode,RecordI18NTS2 fI18NTS)   // -  - SID= <I18NTS2> I18N  Translation Set
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:19 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="I18NTS2",VPGM=$T(+0),VSNAME="I18N  Translation Set"
 set VFSN("I18NTS2")="zfI18NTS"
 set vPSL=1
 set KEYS(1)=fI18NTS.TSID
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fI18NTS),VDA1(.fI18NTS),^DBSPNT()

 if '%ProcessMode do VNEW(.fI18NTS),VPR(.fI18NTS),VDA1(.fI18NTS)
 if %ProcessMode do VLOD(.fI18NTS) quit:$G(ER)  do VPR(.fI18NTS),VDA1(.fI18NTS)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fI18NTS)
	quit


VNEW(RecordI18NTS2 fI18NTS) // Initialize arrays if %O=0
 
 do VDEF(.fI18NTS)
 do VLOD(.fI18NTS)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordI18NTS2 fI18NTS)
 if fI18NTS.EFFWORK="" set fI18NTS.EFFWORK=0
 if fI18NTS.ESTWORK="" set fI18NTS.ESTWORK=0
 if fI18NTS.NONORM="" set fI18NTS.NONORM=0
 if fI18NTS.NONORMAUT="" set fI18NTS.NONORMAUT=0
 if fI18NTS.NONORMMAN="" set fI18NTS.NONORMMAN=0
 if fI18NTS.NOPHR="" set fI18NTS.NOPHR=0
 if fI18NTS.NOTRANS="" set fI18NTS.NOTRANS=0
 if fI18NTS.SELDBTBL="" set fI18NTS.SELDBTBL="*"
 if fI18NTS.SELNMSK="" set fI18NTS.SELNMSK="*"
 if fI18NTS.SELPMSK="" set fI18NTS.SELPMSK="*"
 if fI18NTS.SELPTYPE="" set fI18NTS.SELPTYPE="*"
 if fI18NTS.SELSORT="" set fI18NTS.SELSORT=0
 if fI18NTS.SELTRNSTAT="" set fI18NTS.SELTRNSTAT="*"
 if fI18NTS.SELTRNSTAT2="" set fI18NTS.SELTRNSTAT2="*"
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordI18NTS2 fI18NTS) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordI18NTS2 fI18NTS) // Display screen prompts
 set VO="29||13|"
 set VO(0)="|0"
 set VO(1)=$C(2,15,8,0,0,0,0,0,0,0)_"01TTset ID:"
 set VO(2)=$C(2,51,15,0,0,0,0,0,0,0)_"01T Creation Date:"
 set VO(3)=$C(3,10,13,0,0,0,0,0,0,0)_"01TTset Creator:"
 set VO(4)=$C(3,60,6,0,0,0,0,0,0,0)_"01T Time:"
 set VO(5)=$C(5,30,20,1,0,0,0,0,0,0)_"01T Selection Criteria "
 set VO(6)=$C(7,13,13,1,0,0,0,0,0,0)_"01T Name Filter:"
 set VO(7)=$C(7,52,11,1,0,0,0,0,0,0)_"01T Component:"
 set VO(8)=$C(8,11,15,1,0,0,0,0,0,0)_"01T Phrase Filter:"
 set VO(9)=$C(8,50,13,1,0,0,0,0,0,0)_"01T Phrase Type:"
 set VO(10)=$C(9,5,21,1,0,0,0,0,0,0)_"01T Sort by Freq of Use:"
 set VO(11)=$C(9,50,13,1,0,0,0,0,0,0)_"01TExtract Date:"
 set VO(12)=$C(10,14,12,0,0,0,0,0,0,0)_"01TSource Tset:"
 set VO(13)=$C(10,41,22,0,0,0,0,0,0,0)_"01TMax Number of Phrases:"
 set VO(14)=$C(11,56,7,0,0,0,0,0,0,0)_"01TModule:"
 set VO(15)=$C(12,28,25,2,0,0,0,0,0,0)_"01TPhrase Translation Method"
 set VO(16)=$C(13,6,20,1,0,0,0,0,0,0)_"01T Normalized Phrases:"
 set VO(17)=$C(13,47,16,1,0,0,0,0,0,0)_"01T Detail Phrases:"
 set VO(18)=$C(15,32,17,1,0,0,0,0,0,0)_"01T Tset Statistics "
 set VO(19)=$C(16,17,18,2,0,0,0,0,0,0)_"01TNormalized Phrases"
 set VO(20)=$C(16,56,14,2,0,0,0,0,0,0)_"01TDetail Phrases"
 set VO(21)=$C(17,20,6,0,0,0,0,0,0,0)_"01TTotal:"
 set VO(22)=$C(17,57,6,0,0,0,0,0,0,0)_"01TTotal:"
 set VO(23)=$C(18,6,20,0,0,0,0,0,0,0)_"01TManually Translated:"
 set VO(24)=$C(18,43,20,0,0,0,0,0,0,0)_"01TManually Translated:"
 set VO(25)=$C(19,10,16,0,0,0,0,0,0,0)_"01TAuto Translated:"
 set VO(26)=$C(21,9,17,0,0,0,0,0,0,0)_"01TReplacement Date:"
 set VO(27)=$C(21,44,19,0,0,0,0,0,0,0)_"01T Worktime - Actual:"
 set VO(28)=$C(22,52,11,1,0,0,0,0,0,0)_"01T Estimated:"
 set VO(29)=$C(22,68,5,0,0,0,0,0,0,0)_"01Thours"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordI18NTS2 fI18NTS)  // Display screen data
 new V
 //
 set VO="53|30|13|"
 set VO(30)=$C(1,1,80,1,0,0,0,0,0,0)_"01T"_$S(%ProcessMode=5:"",1:$$BANNER^DBSGETID(%FN))
 set VO(31)=$C(2,24,12,0,0,0,0,0,0,0)_"01T"_$E(fI18NTS.TSID,1,12)
 set VO(32)=$C(2,67,10,0,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fI18NTS.CREDT)
 set VO(33)=$C(3,24,20,0,0,0,0,0,0,0)_"01T"_$E(fI18NTS.UID,1,20)
 set VO(34)=$C(3,67,8,0,0,0,0,0,0,0)_"01C"_$$TIM^%ZM(fI18NTS.CRETIM)
 set VO(35)=$C(7,27,12,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELNMSK,1,12)
 set VO(36)=$C(7,64,2,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELDBTBL,1,2)
 set VO(37)=$C(8,27,12,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELPMSK,1,12)
 set VO(38)=$C(8,64,2,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELPTYPE,1,2)
 set VO(39)=$C(9,27,1,0,0,0,0,0,0,0)_"00L"_$S(fI18NTS.SELSORT:"Y",1:"N")
 set VO(40)=$C(9,64,10,0,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fI18NTS.SELEXTDT)
 set VO(41)=$C(10,27,12,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELSUBTS,1,12)
 set VO(42)=$C(10,64,6,0,0,0,0,0,0,0)_"00N"_fI18NTS.SELNONORM
 set VO(43)=$C(11,64,12,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELSUBSYS,1,12)
 set VO(44)=$C(13,27,1,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELTRNSTAT,1,1)
 set VO(45)=$C(13,64,1,0,0,0,0,0,0,0)_"00T"_$E(fI18NTS.SELTRNSTAT2,1,1)
 set VO(46)=$C(17,27,6,0,0,0,0,0,0,0)_"01N"_fI18NTS.NONORM
 set VO(47)=$C(17,64,6,0,0,0,0,0,0,0)_"01N"_fI18NTS.NOPHR
 set VO(48)=$C(18,27,6,0,0,0,0,0,0,0)_"01N"_fI18NTS.NONORMMAN
 set VO(49)=$C(18,64,6,0,0,0,0,0,0,0)_"01N"_fI18NTS.NOTRANS
 set VO(50)=$C(19,27,6,0,0,0,0,0,0,0)_"01N"_fI18NTS.NONORMAUT
 set VO(51)=$C(21,27,10,0,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fI18NTS.REPDT)
 set VO(52)=$C(21,64,9,0,0,0,0,0,0,0)_"01T"_$E(fI18NTS.EFFWORKF,1,9)
 set VO(53)=$C(22,64,3,0,0,0,0,0,0,0)_"00N"_fI18NTS.ESTWORK
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordI18NTS2 fI18NTS)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=23,VPT=1,VPB=22,PGM=$T(+0),DLIB="SYSDEV",DFID="I18NTS2",VSCRPP=1,VSCRPP=1
 set OLNTB=22068
 
 set VFSN("I18NTS2")="zfI18NTS"
 //
 // 
	
	
 set %TAB(1)=$C(1,23,12)_"21T12401|1|[I18NTS2]TSID|[I18NTS2]TSID"
 set %TAB(2)=$C(1,66,10)_"21D12402|1|[I18NTS2]CREDT"
 set %TAB(3)=$C(2,23,20)_"20T12401|1|[I18NTS2]UID"
 set %TAB(4)=$C(2,66,8)_"21C12403|1|[I18NTS2]CRETIM"
 set %TAB(5)=$C(6,26,12)_"01T12415|1|[I18NTS2]SELNMSK"
 set %TAB(6)=$C(6,63,2)_"01T12414|1|[I18NTS2]SELDBTBL|[STBLI18NDB]"
 set %TAB(7)=$C(7,26,12)_"01T12416|1|[I18NTS2]SELPMSK"
 set %TAB(8)=$C(7,63,2)_"01T12417|1|[I18NTS2]SELPTYPE|[STBLI18NPT]"
 set %TAB(9)=$C(8,26,1)_"00L12422|1|[I18NTS2]SELSORT"
 set %TAB(10)=$C(8,63,10)_"01D12418|1|[I18NTS2]SELEXTDT|[I18NEXTH]EXTDT:DISTINCT"
 set %TAB(11)=$C(9,26,12)_"00T12421|1|[I18NTS2]SELSUBTS|[I18NTS2]TSID"
 set %TAB(12)=$C(9,63,6)_"00N12423|1|[I18NTS2]SELNONORM"
 set %TAB(13)=$C(10,63,12)_"00T12419|1|[I18NTS2]SELSUBSYS|[I18NMOD]MOD,DES"
 set %TAB(14)=$C(12,26,1)_"01T12420|1|[I18NTS2]SELTRNSTAT|[STBLI18NNORM]OPT,FMDESC"
 set %TAB(15)=$C(12,63,1)_"01T12424|1|[I18NTS2]SELTRNSTAT2|[STBLI18NDET]OPT,FMDESC"
 set %TAB(16)=$C(16,26,6)_"21N12408|1|[I18NTS2]NONORM"
 set %TAB(17)=$C(16,63,6)_"21N12411|1|[I18NTS2]NOPHR"
 set %TAB(18)=$C(17,26,6)_"21N12409|1|[I18NTS2]NONORMMAN"
 set %TAB(19)=$C(17,63,6)_"21N12412|1|[I18NTS2]NOTRANS"
 set %TAB(20)=$C(18,26,6)_"21N12410|1|[I18NTS2]NONORMAUT"
 set %TAB(21)=$C(20,26,10)_"21D12404|1|[I18NTS2]REPDT"
 set %TAB(22)=$C(20,63,9)_"20T|*EFFWORKF|[I18NTS2]EFFWORKF"
 set %TAB(23)=$C(21,63,3)_"01N12406|1|[I18NTS2]ESTWORK"
 do VTBL(.fI18NTS),VDEPRE(.fI18NTS) if $G(ER) quit
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordI18NTS2 fI18NTS) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VSPP   // screen post proc
 type Public RecordI18NTS2 fI18NTS
 do VSPP1(.fI18NTS)
 #ACCEPT Date=11/05/03; pgm=Screen Compilerxxx
 quit
VSPP1(RecordI18NTS2 fI18NTS)
 // Word Tsets can not be a subset of other tsets.
 if (fI18NTS.SELSUBTS'=""),(fI18NTS.SELPTYPE=10) do Runtime.setErrMSG("I18NTS2",6093)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
VDEPRE(RecordI18NTS2 fI18NTS)  // Data Entry Pre-processor
 
 if fI18NTS.UID.isNull() do DEFAULT^DBSMACRO("I18NTS2.UID",%UserID)
 if fI18NTS.CRETIM.isNull() do DEFAULT^DBSMACRO("I18NTS2.CRETIM",%CurrentTime)
 if fI18NTS.CREDT.isNull() do DEFAULT^DBSMACRO("I18NTS2.CREDT",%CurrentDate)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordI18NTS2 fI18NTS
 do VPR(.fI18NTS)
 do VDA1(.fI18NTS)
 do ^DBSPNT()
 quit

VW(RecordI18NTS2 fI18NTS)
 do VDA1(.fI18NTS)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordI18NTS2 fI18NTS)
 do VDA1(.fI18NTS)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordI18NTS2 fI18NTS
 do VDA1(.fI18NTS)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordI18NTS2 fI18NTS
 if sn="I18NTS2" do vSET1(.fI18NTS,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordI18NTS2 fI18NTS,di,X)
 do fI18NTS.setAuditFlag(1)
 set fI18NTS.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordI18NTS2 fI18NTS
 if fid="I18NTS2" quit $$vREAD1(.fI18NTS,di)
 quit ""
vREAD1(RecordI18NTS2 fI18NTS,di)
 quit fI18NTS.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
