V00S098(%ProcessMode,RecordCUVAR fCUVAR)   // -  - SID= <CUVMEDIA> Magnetic Media Processing Institution
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:13 - kini
 //  ;------------------------- Revision history --------------------------------
 //  ;	
 //  ; 08/10/01 - ANTONOVS - 45510
 //  ;	      Two new columns "Technical Contact Name" and "Phone" were added to
 //  ;	      the screen.
 //  ;
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="CUVMEDIA",VPGM=$T(+0),VSNAME="Magnetic Media Processing Institution"
 set VFSN("CUVAR")="zfCUVAR"
 set vPSL=1
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fCUVAR),VDA1(.fCUVAR),^DBSPNT()

 if '%ProcessMode do VNEW(.fCUVAR),VPR(.fCUVAR),VDA1(.fCUVAR)
 if %ProcessMode do VLOD(.fCUVAR) quit:$G(ER)  do VPR(.fCUVAR),VDA1(.fCUVAR)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fCUVAR)
	quit


VNEW(RecordCUVAR fCUVAR) // Initialize arrays if %O=0
 
 do VDEF(.fCUVAR)
 do VLOD(.fCUVAR)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordCUVAR fCUVAR)
 if fCUVAR.%ET="" set fCUVAR.%ET="ZE^UTLERR"
 if fCUVAR.%HELP="" set fCUVAR.%HELP=0
 if fCUVAR.%HELPCNT="" set fCUVAR.%HELPCNT=0
 if fCUVAR.ALCOUNT="" set fCUVAR.ALCOUNT=5
 if fCUVAR.BANNER="" set fCUVAR.BANNER=1
 if fCUVAR.BOBR="" set fCUVAR.BOBR=0
 if fCUVAR.DBSPH132="" set fCUVAR.DBSPH132="SCAU$HELP:OOE_SCA132.EXP"
 if fCUVAR.DBSPH80="" set fCUVAR.DBSPH80="SCAU$HELP:OOE_SCA80.EXP"
 if fCUVAR.EMURND="" set fCUVAR.EMURND=9
 if fCUVAR.IRAHIST="" set fCUVAR.IRAHIST=365
 if fCUVAR.LNCC="" set fCUVAR.LNCC=0
 if fCUVAR.LNCFP="" set fCUVAR.LNCFP=0
 if fCUVAR.LNCPI="" set fCUVAR.LNCPI=0
 if fCUVAR.LNCPP="" set fCUVAR.LNCPP=0
 if fCUVAR.MAXCIFL="" set fCUVAR.MAXCIFL=12
 if fCUVAR.MINCIFL="" set fCUVAR.MINCIFL=1
 if fCUVAR.ODP="" set fCUVAR.ODP=0
 if fCUVAR.ORCIFN="" set fCUVAR.ORCIFN=1
 if fCUVAR.SFEEOPT="" set fCUVAR.SFEEOPT=0
 if fCUVAR.TAXREQ="" set fCUVAR.TAXREQ=1
 if fCUVAR.USERNAME="" set fCUVAR.USERNAME=0
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordCUVAR fCUVAR) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordCUVAR fCUVAR) // Display screen prompts
 set VO="20||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,21,39,1,0,0,0,0,0,0)_"01T Magnetic Media Processing Institution "
 set VO(2)=$C(3,18,6,1,0,0,0,0,0,0)_"01T Name:"
 set VO(3)=$C(4,15,9,1,0,0,0,0,0,0)_"01T Address:"
 set VO(4)=$C(7,18,6,1,0,0,0,0,0,0)_"01T City:"
 set VO(5)=$C(8,8,16,1,0,0,0,0,0,0)_"01T State/Province:"
 set VO(6)=$C(8,29,13,1,0,0,0,0,0,0)_"01T Postal Code:"
 set VO(7)=$C(8,56,8,0,0,0,0,0,0,0)_"01TCountry:"
 set VO(8)=$C(10,2,22,0,0,0,0,0,0,0)_"01TTransmitter ID Number:"
 set VO(9)=$C(11,1,23,0,0,0,0,0,0,0)_"01TTechnical Contact Name:"
 set VO(10)=$C(11,49,6,0,0,0,0,0,0,0)_"01TPhone:"
 set VO(11)=$C(12,4,20,0,0,0,0,0,0,0)_"01TTech Contact E-mail:"
 set VO(12)=$C(14,26,29,1,0,0,0,0,0,0)_"01T Software Vendor Information "
 set VO(13)=$C(16,8,16,0,0,0,0,0,0,0)_"01T Vendor Contact:"
 set VO(14)=$C(17,2,22,0,0,0,0,0,0,0)_"01T Vendor Email Address:"
 set VO(15)=$C(18,10,14,0,0,0,0,0,0,0)_"01T Vendor Phone:"
 set VO(16)=$C(19,11,13,0,0,0,0,0,0,0)_"01T Vendor Name:"
 set VO(17)=$C(20,8,16,0,0,0,0,0,0,0)_"01T Vendor Address:"
 set VO(18)=$C(21,11,13,0,0,0,0,0,0,0)_"01T Vendor City:"
 set VO(19)=$C(22,10,14,0,0,0,0,0,0,0)_"01T Vendor State:"
 set VO(20)=$C(22,35,20,0,0,0,0,0,0,0)_"01T Vendor Postal Code:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordCUVAR fCUVAR)  // Display screen data
 new V
 //
 set VO="42|21|13|"
 set VO(21)=$C(3,25,30,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.INAME,1,30)
 set VO(22)=$C(4,25,30,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.IAD1,1,30)
 set VO(23)=$C(5,25,30,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.IAD2,1,30)
 set VO(24)=$C(6,25,30,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.IAD3,1,30)
 set VO(25)=$C(7,25,40,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.ICITY,1,40)
 set VO(26)=$C(8,25,2,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.ISTATE,1,2)
 set VO(27)=$C(8,43,10,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.IZIP,1,10)
 set VO(28)=$C(8,65,2,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.ICNTRY,1,2)
 set VO(29)=$C(10,25,11,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.IEIN,1,11)
 set VO(30)=$C(11,25,20,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.CONTACT,1,20)
 set VO(31)=$C(11,56,3,2,0,0,0,0,0,0)_"00N"_fCUVAR.CAC
 set VO(32)=$C(11,60,7,2,0,0,0,0,0,0)_"00N"_fCUVAR.CTELE
 set VO(33)=$C(12,25,35,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.CEMAIL,1,35)
 set VO(34)=$C(16,25,40,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.VCNAME,1,40)
 set VO(35)=$C(17,25,35,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.VEMAIL,1,35)
 set VO(36)=$C(18,25,3,2,0,0,0,0,0,0)_"00N"_fCUVAR.VCCODE
 set VO(37)=$C(18,29,7,2,0,0,0,0,0,0)_"00N"_fCUVAR.VPHONE
 set VO(38)=$C(19,25,40,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.VNAME,1,40)
 set VO(39)=$C(20,25,40,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.VADDR,1,40)
 set VO(40)=$C(21,25,40,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.VCITY,1,40)
 set VO(41)=$C(22,25,2,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.VSTATE,1,2)
 set VO(42)=$C(22,56,9,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.VZIP,1,9)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordCUVAR fCUVAR)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=22,VPT=1,VPB=22,PGM=$T(+0),DLIB="SYSDEV",DFID="CUVAR"
 set OLNTB=22056
 
 set VFSN("CUVAR")="zfCUVAR"
 //
 // 
	
	
 set %TAB(1)=$C(2,24,30)_"01T12407|1|[CUVAR]INAME"
 set %TAB(2)=$C(3,24,30)_"01T12404|1|[CUVAR]IAD1"
 set %TAB(3)=$C(4,24,30)_"00T12405|1|[CUVAR]IAD2"
 set %TAB(4)=$C(5,24,30)_"00T12406|1|[CUVAR]IAD3"
 set %TAB(5)=$C(6,24,40)_"01T12401|1|[CUVAR]ICITY"
 set %TAB(6)=$C(7,24,2)_"01T12402|1|[CUVAR]ISTATE|[STBLCNTRY1]:QU ""[STBLCNTRY1]CNTRY=""""US""""""||do VP1^V00S098(.fCUVAR)|do VP2^V00S098(.fCUVAR)"
 set %TAB(7)=$C(7,42,10)_"01T12403|1|[CUVAR]IZIP|||do VP3^V00S098(.fCUVAR)"
 set %TAB(8)=$C(7,64,2)_"00T12412|1|[CUVAR]ICNTRY|[STBLCNTRY]"
 set %TAB(9)=$C(9,24,11)_"00T12403|1|[CUVAR]IEIN"
 set %TAB(10)=$C(10,24,20)_"00T12413|1|[CUVAR]CONTACT"
 set %TAB(11)=$C(10,55,3)_"00N12414|1|[CUVAR]CAC"
 set %TAB(12)=$C(10,59,7)_"00N12415|1|[CUVAR]CTELE"
 set %TAB(13)=$C(11,24,35)_"00T12417|1|[CUVAR]CEMAIL"
 set %TAB(14)=$C(15,24,40)_"00T12406|1|[CUVAR]VCNAME"
 set %TAB(15)=$C(16,24,35)_"00T12409|1|[CUVAR]VEMAIL"
 set %TAB(16)=$C(17,24,3)_"00N12407|1|[CUVAR]VCCODE"
 set %TAB(17)=$C(17,28,7)_"00N12408|1|[CUVAR]VPHONE"
 set %TAB(18)=$C(18,24,40)_"00T12401|1|[CUVAR]VNAME"
 set %TAB(19)=$C(19,24,40)_"00T12402|1|[CUVAR]VADDR"
 set %TAB(20)=$C(20,24,40)_"00T12403|1|[CUVAR]VCITY"
 set %TAB(21)=$C(21,24,2)_"00T12404|1|[CUVAR]VSTATE|[STBLCNTRY1]"
 set %TAB(22)=$C(21,55,9)_"00T12405|1|[CUVAR]VZIP"
 do VTBL(.fCUVAR)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordCUVAR fCUVAR) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordCUVAR fCUVAR) //
 //Required
 if CNTRY="US",'$L(X) set ER=1,RM=$$^MSG(2385) quit
 quit 

VP2(RecordCUVAR fCUVAR) //
 /* 04/18/05 - SWARNALATHA PONMAR RUPAKUMAR - 13665
    Corrected code to include enough quotes ("), so that the lookup table 
    is popped out without any errors.
 */

 type Public String CNTRY 

 set CNTRY = fCUVAR.cntry
 do CHANGE^DBSMACRO("TBL", "[STBLCNTRY1]:QU ""[STBLCNTRY1]CNTRY=<<CNTRY>>""")
 quit 
 
VP3(RecordCUVAR fCUVAR) //
 //Required
 if CNTRY="US",'$L(X) set ER=1 set RM=$$^MSG(2385) quit
 set ST=fCUVAR.istate
 do VPO1(.fCUVAR)
 quit 

VPO1(RecordCUVAR fCUVAR)  // user library ZIP
 ; The code previously found in this routine has been moved to the new filer
 ; processer library.  This library contains code shared by the filers and by
 ; DQ screens. ; code removed 12/9/96 Spier
 ; Zip Code Verification
 ;
 D ZIP^PROCZIP($G(CNTRY),$G(ST),$G(X))
 Q
 #ACCEPT DATE=11/05/03;pgm=screen compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordCUVAR fCUVAR
 do VPR(.fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT()
 quit

VW(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordCUVAR fCUVAR
 do VDA1(.fCUVAR)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordCUVAR fCUVAR
 if sn="CUVAR" do vSET1(.fCUVAR,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordCUVAR fCUVAR,di,X)
 do fCUVAR.setAuditFlag(1)
 set fCUVAR.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordCUVAR fCUVAR
 if fid="CUVAR" quit $$vREAD1(.fCUVAR,di)
 quit ""
vREAD1(RecordCUVAR fCUVAR,di)
 quit fCUVAR.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
