V00S487(%ProcessMode,RecordSTBLMBAR fSTMBAR)   // -  - SID= <STBLMBAR> Menu options update screen
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 12:09 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab,MENUID",VSID="STBLMBAR",VPGM=$T(+0),VSNAME="Menu options update screen"
 set VFSN("STBLMBAR")="zfSTMBAR"
 set vPSL=1
 set KEYS(1)=fSTMBAR.MENUID
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fSTMBAR),VDA1(.fSTMBAR),^DBSPNT()

 set ER=0 do VSCRPRE(.fSTMBAR) if ER quit  // Screen Pre-Processor
 
 if '%ProcessMode do VNEW(.fSTMBAR),VPR(.fSTMBAR),VDA1(.fSTMBAR)
 if %ProcessMode do VLOD(.fSTMBAR) quit:$G(ER)  do VPR(.fSTMBAR),VDA1(.fSTMBAR)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fSTMBAR)
	quit


VNEW(RecordSTBLMBAR fSTMBAR) // Initialize arrays if %O=0
 
 do VDEF(.fSTMBAR)
 do VLOD(.fSTMBAR)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordSTBLMBAR fSTMBAR)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordSTBLMBAR fSTMBAR) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordSTBLMBAR fSTMBAR) // Display screen prompts
 set VO="36||13|"
 set VO(0)="|0"
 set VO(1)=$C(2,1,80,0,0,0,0,0,0,0)_"11Tlqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk"
 set VO(2)=$C(3,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(3)=$C(3,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(4)=$C(4,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(5)=$C(4,13,9,1,0,0,0,0,0,0)_"01T Menu ID:"
 set VO(6)=$C(4,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(7)=$C(5,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(8)=$C(5,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(9)=$C(6,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(10)=$C(6,29,19,1,0,0,0,0,0,0)_"01T Menu options list "
 set VO(11)=$C(6,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(12)=$C(7,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(13)=$C(7,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(14)=$C(8,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(15)=$C(8,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(16)=$C(9,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(17)=$C(9,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(18)=$C(10,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(19)=$C(10,27,24,1,0,0,0,0,0,0)_"01T Menu Prompt (optional) "
 set VO(20)=$C(10,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(21)=$C(11,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(22)=$C(11,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(23)=$C(12,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(24)=$C(12,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(25)=$C(13,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(26)=$C(13,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(27)=$C(14,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(28)=$C(14,28,22,1,0,0,0,0,0,0)_"01T  Comments (optional) "
 set VO(29)=$C(14,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(30)=$C(15,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(31)=$C(15,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(32)=$C(16,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(33)=$C(16,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(34)=$C(17,1,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(35)=$C(17,80,1,0,0,0,0,0,0,0)_"11Tx"
 set VO(36)=$C(18,1,80,0,0,0,0,0,0,0)_"11Tmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordSTBLMBAR fSTMBAR)  // Display screen data
 new V
 s MENUID=$G(MENUID)
 //
 set VO="41|37|13|"
 set VO(37)=$C(1,1,80,1,0,0,0,0,0,0)_"01T"_$S(%ProcessMode=5:"",1:$$BANNER^UTLREAD($G(%FN)))
 set VO(38)=$C(4,23,8,2,0,0,0,0,0,0)_"00N"_$G(MENUID)
 set VO(39)=$C(8,3,78,2,0,0,0,0,0,0)_"00T"_$E(fSTMBAR.OPTIONS,1,255)
 set VO(40)=$C(12,3,78,2,0,0,0,0,0,0)_"00T"_$E(fSTMBAR.PROMPT,1,80)
 set VO(41)=$C(16,3,78,2,0,0,0,0,0,0)_"00T"_$E(fSTMBAR.COMMENT,1,254)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordSTBLMBAR fSTMBAR)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=4,VPT=1,VPB=18,PGM=$T(+0),DLIB="SYSDEV",DFID="STBLMBAR"
 set OLNTB=18001
 
 set VFSN("STBLMBAR")="zfSTMBAR"
 //
 // 
	
	
 set %TAB(1)=$C(3,22,8)_"01N|*MENUID|[*]@MENUID|[STBLMBAR]||do VP1^V00S487(.fSTMBAR)"
 set %TAB(2)=$C(7,2,78)_"01T12401|1|[STBLMBAR]OPTIONS|||||||||255"
 set %TAB(3)=$C(11,2,78)_"00T12402|1|[STBLMBAR]PROMPT|||||||||80"
 set %TAB(4)=$C(15,2,78)_"00T12403|1|[STBLMBAR]COMMENT|||||||||254"
 do VTBL(.fSTMBAR)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordSTBLMBAR fSTMBAR) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordSTBLMBAR fSTMBAR) //
 type Public String X,V,MENUID
 
 if X="" Q
 
 If X=V Q
 
 set MENUID=X
 
 do CHANGE^DBSMACRO("TBL","")
 do LOAD^DBSMACRO("ALL") 
 do DISPLAY^DBSMACRO("ALL")
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordSTBLMBAR fSTMBAR
 do VPR(.fSTMBAR)
 do VDA1(.fSTMBAR)
 do ^DBSPNT()
 quit

VW(RecordSTBLMBAR fSTMBAR)
 do VDA1(.fSTMBAR)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordSTBLMBAR fSTMBAR)
 do VDA1(.fSTMBAR)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordSTBLMBAR fSTMBAR
 do VDA1(.fSTMBAR)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordSTBLMBAR fSTMBAR
 if sn="STBLMBAR" do vSET1(.fSTMBAR,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordSTBLMBAR fSTMBAR,di,X)
 do fSTMBAR.setAuditFlag(1)
 set fSTMBAR.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordSTBLMBAR fSTMBAR
 if fid="STBLMBAR" quit $$vREAD1(.fSTMBAR,di)
 quit ""
vREAD1(RecordSTBLMBAR fSTMBAR,di)
 quit fSTMBAR.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 //
VSCRPRE(RecordSTBLMBAR fSTMBAR)  // Screen Pre-Processor
 new %TAB,vtab // Disable .MACRO. references to %TAB()
 //
 type Public String MENUID
 set MENUID=" "
 #ACCEPT date=11/05/03;PGM=Screen Compiler
 quit
