V00S093(%ProcessMode,RecordCUVAR fCUVAR)   // -  - SID= <CUVARMGR2> System Management (Dayend, Jnl, Maint)
 ;;Copyright(c)2006 Sanchez Computer Associates, Inc.  All Rights Reserved - 08/24/2006 11:11 - kini
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="CUVARMGR2",VPGM=$T(+0),VSNAME="System Management (Dayend, Jnl, Maint)"
 set VFSN("CUVAR")="zfCUVAR"
 set vPSL=1
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fCUVAR),VDA1(.fCUVAR),^DBSPNT()

 if '%ProcessMode do VNEW(.fCUVAR),VPR(.fCUVAR),VDA1(.fCUVAR)
 if %ProcessMode do VLOD(.fCUVAR) quit:$G(ER)  do VPR(.fCUVAR),VDA1(.fCUVAR)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fCUVAR)
	quit


VNEW(RecordCUVAR fCUVAR) // Initialize arrays if %O=0
 
 do VDEF(.fCUVAR)
 do VLOD(.fCUVAR)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordCUVAR fCUVAR)
 if fCUVAR.%ET="" set fCUVAR.%ET="ZE^UTLERR"
 if fCUVAR.%HELP="" set fCUVAR.%HELP=0
 if fCUVAR.%HELPCNT="" set fCUVAR.%HELPCNT=0
 if fCUVAR.ALCOUNT="" set fCUVAR.ALCOUNT=5
 if fCUVAR.BANNER="" set fCUVAR.BANNER=1
 if fCUVAR.BOBR="" set fCUVAR.BOBR=0
 if fCUVAR.DBSPH132="" set fCUVAR.DBSPH132="SCAU$HELP:OOE_SCA132.EXP"
 if fCUVAR.DBSPH80="" set fCUVAR.DBSPH80="SCAU$HELP:OOE_SCA80.EXP"
 if fCUVAR.EMURND="" set fCUVAR.EMURND=9
 if fCUVAR.IRAHIST="" set fCUVAR.IRAHIST=365
 if fCUVAR.LNCC="" set fCUVAR.LNCC=0
 if fCUVAR.LNCFP="" set fCUVAR.LNCFP=0
 if fCUVAR.LNCPI="" set fCUVAR.LNCPI=0
 if fCUVAR.LNCPP="" set fCUVAR.LNCPP=0
 if fCUVAR.MAXCIFL="" set fCUVAR.MAXCIFL=12
 if fCUVAR.MINCIFL="" set fCUVAR.MINCIFL=1
 if fCUVAR.ODP="" set fCUVAR.ODP=0
 if fCUVAR.ORCIFN="" set fCUVAR.ORCIFN=1
 if fCUVAR.SFEEOPT="" set fCUVAR.SFEEOPT=0
 if fCUVAR.TAXREQ="" set fCUVAR.TAXREQ=1
 if fCUVAR.USERNAME="" set fCUVAR.USERNAME=0
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordCUVAR fCUVAR) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordCUVAR fCUVAR) // Display screen prompts
 set VO="19||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,25,31,1,0,0,0,0,0,0)_"01T System Management Information "
 set VO(2)=$C(3,32,18,2,0,0,0,0,0,0)_"01TDAYEND Processing "
 set VO(3)=$C(5,9,17,1,0,0,0,0,0,0)_"01T Concurrent Jobs:"
 set VO(4)=$C(5,31,31,0,0,0,0,0,0,0)_"01TTransfer All Accts to All FEPs:"
 set VO(5)=$C(6,6,20,0,0,0,0,0,0,0)_"01TNo REG D Statistics:"
 set VO(6)=$C(8,5,21,0,0,0,0,0,0,0)_"01TUsername(s) to Notify"
 set VO(7)=$C(8,27,22,0,0,0,0,0,0,0)_"01TOf Accrual Suspension:"
 set VO(8)=$C(10,26,32,2,0,0,0,0,0,0)_"01TSoftware Maintenance Information"
 set VO(9)=$C(12,14,28,0,0,0,0,0,0,0)_"01TRunning Executable Image(s):"
 set VO(10)=$C(14,3,16,0,0,0,0,0,0,0)_"01T Pre-release ID:"
 set VO(11)=$C(14,29,13,0,0,0,0,0,0,0)_"01T Date Loaded:"
 set VO(12)=$C(14,54,13,0,0,0,0,0,0,0)_"01T Time Loaded:"
 set VO(13)=$C(15,7,12,0,0,0,0,0,0,0)_"01T Release ID:"
 set VO(14)=$C(15,29,13,0,0,0,0,0,0,0)_"01T Date Loaded:"
 set VO(15)=$C(15,54,13,0,0,0,0,0,0,0)_"01T Time Loaded:"
 set VO(16)=$C(17,17,46,2,0,0,0,0,0,0)_"01TAccount/Customer Number Assignment Information"
 set VO(17)=$C(19,3,22,0,0,0,0,0,0,0)_"01TAllocation Block Size:"
 set VO(18)=$C(19,39,24,0,0,0,0,0,0,0)_"01TLow Limit Trigger Count:"
 set VO(19)=$C(21,3,19,0,0,0,0,0,0,0)_"01THealth Check Files:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordCUVAR fCUVAR)  // Display screen data
 new V
 //
 set VO="33|20|13|"
 set VO(20)=$C(5,27,2,2,0,0,0,0,0,0)_"00N"_fCUVAR.BTTJOB
 set VO(21)=$C(5,63,1,2,0,0,0,0,0,0)_"00L"_$S(fCUVAR.FEPXALL:"Y",1:"N")
 set VO(22)=$C(6,27,1,2,0,0,0,0,0,0)_"00L"_$S(fCUVAR.NOREGD:"Y",1:"N")
 set VO(23)=$C(8,50,31,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.REPLY,1,50)
 set VO(24)=$C(12,43,1,2,0,0,0,0,0,0)_"00L"_$S(fCUVAR.IMAGE:"Y",1:"N")
 set VO(25)=$C(14,20,8,2,0,0,0,0,0,0)_"01T"_$E(fCUVAR.PRELID,1,8)
 set VO(26)=$C(14,43,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fCUVAR.DPREL)
 set VO(27)=$C(14,68,8,2,0,0,0,0,0,0)_"01C"_$$TIM^%ZM(fCUVAR.TPREL)
 set VO(28)=$C(15,20,8,2,0,0,0,0,0,0)_"01T"_$E(fCUVAR.RELID,1,8)
 set VO(29)=$C(15,43,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fCUVAR.DREL)
 set VO(30)=$C(15,68,8,2,0,0,0,0,0,0)_"01C"_$$TIM^%ZM(fCUVAR.TREL)
 set VO(31)=$C(19,26,12,2,0,0,0,0,0,0)_"00N"_fCUVAR.CIDBLK
 set VO(32)=$C(19,64,12,2,0,0,0,0,0,0)_"00N"_fCUVAR.CIDLOWLM
 set VO(33)=$C(21,23,58,2,0,0,0,0,0,0)_"00T"_$E(fCUVAR.TBLS,1,500)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordCUVAR fCUVAR)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=14,VPT=1,VPB=21,PGM=$T(+0),DLIB="SYSDEV",DFID="CUVAR",VSCRPP=1,VSCRPP=1
 set OLNTB=21023
 
 set VFSN("CUVAR")="zfCUVAR"
 //
 // 
	
	
 set %TAB(1)=$C(4,26,2)_"01N12401|1|[CUVAR]BTTJOB"
 set %TAB(2)=$C(4,62,1)_"00L12401|1|[CUVAR]FEPXALL"
 set %TAB(3)=$C(5,26,1)_"00L12401|1|[CUVAR]NOREGD"
 set %TAB(4)=$C(7,49,31)_"00T12401|1|[CUVAR]REPLY|||||||||50"
 set %TAB(5)=$C(11,42,1)_"00L12401|1|[CUVAR]IMAGE|||do VP1^V00S093(.fCUVAR)"
 set %TAB(6)=$C(13,19,8)_"20T12401|1|[CUVAR]PRELID"
 set %TAB(7)=$C(13,42,10)_"20D12402|1|[CUVAR]DPREL"
 set %TAB(8)=$C(13,67,8)_"20C12403|1|[CUVAR]TPREL|||||1|86399"
 set %TAB(9)=$C(14,19,8)_"20T12401|1|[CUVAR]RELID"
 set %TAB(10)=$C(14,42,10)_"20D12402|1|[CUVAR]DREL"
 set %TAB(11)=$C(14,67,8)_"20C12403|1|[CUVAR]TREL|||||1|86399"
 set %TAB(12)=$C(18,25,12)_"00N12401|1|[CUVAR]CIDBLK|||do VP2^V00S093(.fCUVAR)"
 set %TAB(13)=$C(18,63,12)_"00N12401|1|[CUVAR]CIDLOWLM"
 set %TAB(14)=$C(20,22,58)_"00T12401|1|[CUVAR]TBLS|||do VP3^V00S093(.fCUVAR)||||||500"
 do VTBL(.fCUVAR)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordCUVAR fCUVAR) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VSPP   // screen post proc
 type Public RecordCUVAR fCUVAR
 do VSPP1(.fCUVAR)
 #ACCEPT Date=11/05/03; pgm=Screen Compilerxxx
 quit
VSPP1(RecordCUVAR fCUVAR)
 if $G(file1)="" quit

 if (fCUVAR.tbls'="")&($E(fCUVAR.tbls,$L(fCUVAR.tbls))'=",")&($E(file1,1)'=",") set fCUVAR.tbls=fCUVAR.tbls_","_file1 quit 

 set fCUVAR.tbls=fCUVAR.tbls_file1

 quit

 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordCUVAR fCUVAR) //
 /* 04/18/05 - SWARNALATHA PONMAR RUPAKUMAR - 13665
    Modified the reference to $ZSEARCH and $ZTRNLNM with $$SEARCH^%ZFUNC 
    and $$TRNLNM^%ZFUNC respectively.
 */

 type Public Boolean PASS, X
 type Public String ER, RM

 type String DIR, EXE, VAR, VER

 // Seed (reset) $ZSEARCH
 set VAR = $$SEARCH^%ZFUNC("")
 
 if X <> 1 quit

 set DIR = $$TRNLNM^%ZFUNC("SCAU$DIR")
 set VER = $$^%ZSYS()

 // Applicable only to VMS
 if VER '= "VMS" quit 

 set EXE = $$SEARCH^%ZFUNC(DIR_":*.EXE")
 
 // There is no *.EXE file currently in ~p1
 if EXE.isNull() set ER = "W" set RM = $$^MSG(6036, DIR) quit

 quit
 
VP2(RecordCUVAR fCUVAR) //
 do UNPROT^DBSMACRO("CUVAR.CIDLOWLM")

 if X'="" quit 

 do DELETE^DBSMACRO("CUVAR.CIDLOWLM","1","0")

 do PROTECT^DBSMACRO("CUVAR.CIDLOWLM")

 quit

VP3(RecordCUVAR fCUVAR) //
 if X="" quit 

 for I=1:1:$L(X,",") do {
 	set XFID=$P(X,",",I)
 	if XFID="",($L(X,",")=I) quit 
	if 'Db.isDefined("DBTBL1","%LIBS='SYSDEV',FID=:XFID") set ER=1,RM=$$^MSG(1334,XFID) do GOTO^DBSMACRO("CUVAR.TBLS") quit      
 	}

 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordCUVAR fCUVAR
 do VPR(.fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT()
 quit

VW(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordCUVAR fCUVAR)
 do VDA1(.fCUVAR)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordCUVAR fCUVAR
 do VDA1(.fCUVAR)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordCUVAR fCUVAR
 if sn="CUVAR" do vSET1(.fCUVAR,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordCUVAR fCUVAR,di,X)
 do fCUVAR.setAuditFlag(1)
 set fCUVAR.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordCUVAR fCUVAR
 if fid="CUVAR" quit $$vREAD1(.fCUVAR,di)
 quit ""
vREAD1(RecordCUVAR fCUVAR,di)
 quit fCUVAR.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
