V01S247(%ProcessMode,)   // -  - SID= <DEBAUTO> Debit Authorization Override
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:53 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab,debit",VSID="DEBAUTO",VPGM=$T(+0),VSNAME="Debit Authorization Override"
 set vPSL=1
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 set %MODS=1,%REPEAT=16 do VPR(),VDA1(),V5^DBSPNT quit

 if '%ProcessMode do VNEW(),VPR(),VDA1()
 if %ProcessMode do VLOD() quit:$G(ER)  do VPR(),VDA1()

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB()
	quit


VNEW() // Initialize arrays if %O=0
 
 do VDEF()
 do VLOD()
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF()
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD() // Load data from disc - %O = (1-5)
 if '$D(%REPEAT) set %REPEAT=16
 if '$D(%MODS) set %MODS=1
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR() // Display screen prompts
 set VO="7||13|"
 set VO(0)="|0"
 set VO(1)=$C(2,21,31,1,0,0,0,0,0,0)_"01T Debit Authorization Overrides "
 set VO(2)=$C(5,3,7,2,0,0,0,0,0,0)_"01TPre Num"
 set VO(3)=$C(5,16,11,2,0,0,0,0,0,0)_"01TAccount Num"
 set VO(4)=$C(5,33,11,2,0,0,0,0,0,0)_"01TDescription"
 set VO(5)=$C(6,3,7,2,0,0,0,0,0,0)_"11Tooooooo"
 set VO(6)=$C(6,16,11,2,0,0,0,0,0,0)_"11Tooooooooooo"
 set VO(7)=$C(6,33,40,2,0,0,0,0,0,0)_"11Toooooooooooooooooooooooooooooooooooooooo"
 if '$D(%MODS) set %MODS=1
 set DY=7 for I=%MODS:1:%REPEAT+%MODS-1 do VRPR()
 set VO=(+VO)_"|"_(VO+1)_"|13" quit  // BOD pointer
 
VRPR()  // Display prompts %REPEAT times
 
 set VO(VO+1)=$C(DY,13,1,2,0,0,0,0,0,0)_"01T-"
 set VO=VO+1,DY=DY+1
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1()  // Display screen data
 new V
 s debit=$G(debit)
 //
 set VX=$P(VO,"|",2)
  
 set:'$D(%MODS) %MODS=1 set VX=$P(VO,"|",2)+-1,DY=7 for I=%MODS:1:%REPEAT+%MODS-1 do VRDA()
 set $piece(VO,"|",1)=VX quit  // EOD pointer
 
VRDA()  // Display data %REPEAT times
 //instantiate new object if necessary
 if %ProcessMode=5 new v1
 if  set (v1)=""
 else  new v1
 else  set (v1,debit(I))=$G(debit(I))
 
 set VO(VX+1)=$C(DY,4,6,0,0,0,0,0,0,0)_"00N"_$P(v1,"|",1)
 set VO(VX+2)=$C(DY,17,10,0,0,0,0,0,0,0)_"00N"_$P(v1,"|",2)
 set VO(VX+3)=$C(DY,33,40,0,0,0,0,0,0,0)_"00T"_$P(v1,"|",3)
 set DY=DY+1,VX=VX+3
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB()
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab set %MODGRP=1
 set %MODOFF=0,%MOD=3,%MAX=(%MOD*%REPEAT)+%MODOFF,VPT=2,VPB=6+%REPEAT,BLKSIZ=(56*%REPEAT)+0,PGM=$T(+0),DLIB="SYSDEV",DFID=""
 set OLNTB=VPB*1000
 
 for I=4:1:%MAX set %TAB(I)=""
	
	
 set %TAB(1)=$C(6,3,6)_"00N12401|*debit(1)|[*]@debit"
 set %TAB(2)=$C(6,16,10)_"00N12402|*debit(1)|[*]@DEBIT"
 set %TAB(3)=$C(6,32,40)_"00T12403|*debit(1)|[*]@DEBIT"
 do VTBL()
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL() //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 do VPR()
 do VDA1()
 do ^DBSPNT()
 quit

VW()
 do VDA1()
 do ^DBSPNT(10)
 quit

VDAPNT()
 do VDA1()
 do ^DBSPNT(0,2)
 quit

VDA
 do VDA1()
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 quit ""
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
