V01S508(%ProcessMode,RecordDEP DEP)   //PBS -  - SID= <PRYR> Mod Int Bkup W/Holding Pen Prior Year
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:51 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="PRYR",VPGM=$T(+0),VSNAME="Mod Int Bkup W/Holding Pen Prior Year"
 set VFSN("DEP")="zDEP"
 set vPSL=1
 set KEYS(1)=DEP.CID
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.DEP),VDA1(.DEP),^DBSPNT()

 if '%ProcessMode do VNEW(.DEP),VPR(.DEP),VDA1(.DEP)
 if %ProcessMode do VLOD(.DEP) quit:$G(ER)  do VPR(.DEP),VDA1(.DEP)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.DEP)
	quit


VNEW(RecordDEP DEP) // Initialize arrays if %O=0
 
 do VDEF(.DEP)
 do VLOD(.DEP)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordDEP DEP)
 if DEP.AOMCODE="" set DEP.AOMCODE=0
 if DEP.NRNEGIPTY="" set DEP.NRNEGIPTY=0
 if DEP.NRPOSIPTY="" set DEP.NRPOSIPTY=0
 if DEP.NRPPTY="" set DEP.NRPPTY=0
 if DEP.NRWHPTY="" set DEP.NRWHPTY=0
 if DEP.ODT="" set DEP.ODT=TJD
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordDEP DEP) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordDEP DEP) // Display screen prompts
 set VO="7||13|"
 set VO(0)="|"
 set VO(1)=$C(1,5,16,0,0,0,0,0,0,0)_"01T Account Number:"
 set VO(2)=$C(1,53,9,0,0,0,0,0,0,0)_"01T Balance:"
 set VO(3)=$C(2,11,10,0,0,0,0,0,0,0)_"01T Customer:"
 set VO(4)=$C(5,22,34,1,0,0,0,0,0,0)_"01T Prior Financial Year Information "
 set VO(5)=$C(7,15,9,0,0,0,0,0,0,0)_"01TInterest:"
 set VO(6)=$C(8,16,8,0,0,0,0,0,0,0)_"01TPenalty:"
 set VO(7)=$C(9,12,12,0,0,0,0,0,0,0)_"01TWithholding:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordDEP DEP)  // Display screen data
 new V
 //
 set VO="13|8|13|"
 set VO(8)=$C(1,22,12,2,0,0,0,0,0,0)_"01N"_DEP.CID
 set V=$S(DEP.BAL="":"",1:$J(DEP.BAL,0,2)) set VO(9)=$C(1,63,15,2,0,0,0,0,0,0)_"01$"_$S(DEP.BAL="":"",1:$J(DEP.BAL,0,2))
 set VO(10)=$C(2,22,40,2,0,0,0,0,0,0)_"01T"_$E(DEP.TITLE1,1,40)
 set V=$S(DEP.IPY="":"",1:$J(DEP.IPY,0,2)) set VO(11)=$C(7,25,15,2,0,0,0,0,0,0)_"00$"_$S(DEP.IPY="":"",1:$J(DEP.IPY,0,2))
 set V=$S(DEP.PPY="":"",1:$J(DEP.PPY,0,2)) set VO(12)=$C(8,25,12,2,0,0,0,0,0,0)_"00$"_$S(DEP.PPY="":"",1:$J(DEP.PPY,0,2))
 set V=$S(DEP.BWP="":"",1:$J(DEP.BWP,0,2)) set VO(13)=$C(9,25,18,2,0,0,0,0,0,0)_"00$"_$S(DEP.BWP="":"",1:$J(DEP.BWP,0,2))
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordDEP DEP)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=6,VPT=1,VPB=9,PGM=$T(+0),DLIB="SYSDEV",DFID="DEP"
 set OLNTB=9025
 
 set VFSN("DEP")="zDEP"
 //
 // 
	
	
 set %TAB(1)=$C(0,21,12)_"21N12401|1|[DEP]CID|[ACN]"
 set %TAB(2)=$C(0,62,15)_"21$12401|1|[DEP]BAL|||||||2"
 set %TAB(3)=$C(1,21,40)_"21T12401|1|[DEP]TITLE1"
 set %TAB(4)=$C(6,24,15)_"00$12407|1|[DEP]IPY|||||||2"
 set %TAB(5)=$C(7,24,12)_"00$12402|1|[DEP]PPY|||||||2"
 set %TAB(6)=$C(8,24,18)_"00$12410|1|[DEP]BWP|||||||2"
 do VTBL(.DEP)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordDEP DEP) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordDEP DEP
 do VPR(.DEP)
 do VDA1(.DEP)
 do ^DBSPNT()
 quit

VW(RecordDEP DEP)
 do VDA1(.DEP)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordDEP DEP)
 do VDA1(.DEP)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordDEP DEP
 do VDA1(.DEP)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordDEP DEP
 if sn="DEP" do vSET1(.DEP,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordDEP DEP,di,X)
 do DEP.setAuditFlag(1)
 set DEP.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordDEP DEP
 if fid="DEP" quit $$vREAD1(.DEP,di)
 quit ""
vREAD1(RecordDEP DEP,di)
 quit DEP.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
