V01S553( Number %ProcessMode,RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)   // -  - SID= <SRVPLN2L> Service Fee Plan Definition Linkage
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:52 - shetyes
 #WARN ACCESS,MISMATCH OFF
 	/*
 	ORIG: CHENARDP - 02/27/2003
 	DESC: Linked Screen Template

 	---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4


	 ---- Revision History ------------------------------------------------
	09/24/03 - Pete Chenard - 45497
		       Created linked screen template for screen compiler.
	-----------------------------------------------------------------------

	 */
 
 type Public Number ER
 type Public String %PAG,%PAGE,%PG,%PGSV,MULSCR,RM,VFMQ
 type String KVAR,VPG(),vPSL,VSID
 set VSID="SRVPLN2L"
 set KVAR="kill %A,%TAB,vtab,VFSN,%OLD,%NEW,%FILE,%INDEX,%PAGE,%PG,UX,MULSCR"
 set:'%PG.exists() %PG=1 set %PAG=%PG+1 set %PAGE=$S(%PAGE.exists():%PAGE-1,1:0)+2
 set vPSL=1  //compiled for PSL
 //
 set VPG(%PG+0)="Service Fee Plan Definition |SRVPLN2"
 set VPG(%PG+1)="Service Fee Plan Definition |SRVPLN2B"
	set:'$D(%PG) %PG=1 set %PGSV=%PG,MULSCR=""
 if '%ProcessMode do VNEW(.fFEEPLN,.FEESRV2)
 if %ProcessMode do VLOD(.fFEEPLN,.FEESRV2) if $G(ER) set VFMQ="Q" quit
 do VPG(.fFEEPLN,.FEESRV2)
 quit

VNEW(RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)
 
 quit
 //
 ;
VLOD(RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)  // User defined access section
	quit

VPG(RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)
 type Public Number %PG,%PGSV
 type Number vDONE
 set vDONE=0
 for  do { quit:vDONE
  if %PG=(%PGSV+0) do VPG1(.fFEEPLN,.FEESRV2),VPG0(.fFEEPLN,.FEESRV2) quit:vDONE
  if %PG=(%PGSV+1) do VPG2(.fFEEPLN,.FEESRV2),VPG0(.fFEEPLN,.FEESRV2) quit:vDONE
  }
 quit

VPG0(RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)
 type Public String vDONE,VFMQ,VPG()
 type Public Number %PAG,%PAGE,%PG,%PGSV
 type String %LINK
 set %LINK=""
 if %ProcessMode=2!(%ProcessMode=3)!(%ProcessMode=4) do VBTM(.fFEEPLN,.FEESRV2) if VFMQ.get()="D" set vDONE=1 quit
 if '%PAGE.exists() set vDONE=1 quit
 if %PG'<%PAG kill %PAG,%PGSV,VPG set vDONE=1 quit
 set %PG=%PG+1
 quit

 
VPG1(RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)  // Service Fee Plan Definition 
 type Public String %MODS,%REPEAT,ET,VPGM,VPTBL
 type String DFID,PGM,SID
 set SID="SRVPLN2",DFID="FEEPLN"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V01S551
 if %ProcessMode>1 quit
 do VTAB^V01S551(.fFEEPLN,.FEESRV2)
 quit
 
VPG2(RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)  // Service Fee Plan Definition 
 type Public String %MODS,%REPEAT,ET,VPGM,VPTBL
 type String DFID,PGM,SID
 set SID="SRVPLN2B",DFID="FEEPLN"
 do ^USID if PGM="" set ET="INVLDSCR" do ^UTLERR Q
 kill VPTBL
 set VPGM=PGM
 do VREPRNT^V01S552
 if %ProcessMode>1 quit
 do VTAB^V01S552(.fFEEPLN,.FEESRV2)
 quit
 

VBTM(RecordFEEPLN fFEEPLN,RecordFEESRV2 FEESRV2)

	if %ProcessMode=4,IO'=$P quit
	do ^DBSCRT8A
	quit
