V01S304(%ProcessMode,RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP)   // -  - SID= <INTPAYHQ40A> Outgoing Foreign Pmt-HQ Page 4 (MT103)
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:54 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab,PARTYI",VSID="INTPAYHQ40A",VPGM=$T(+0),VSNAME="Outgoing Foreign Pmt-HQ Page 4 (MT103)"
 set VFSN("EFTPAY")="zfEFTPAY"
 set vPSL=1
 set KEYS(1)=DEP.CID
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fEFTHLD,.fEFTPAY,.DEP),VDA1(.fEFTHLD,.fEFTPAY,.DEP),^DBSPNT()

 if '%ProcessMode do VNEW(.fEFTHLD,.fEFTPAY,.DEP),VPR(.fEFTHLD,.fEFTPAY,.DEP),VDA1(.fEFTHLD,.fEFTPAY,.DEP)
 if %ProcessMode do VLOD(.fEFTHLD,.fEFTPAY,.DEP) quit:$G(ER)  do VPR(.fEFTHLD,.fEFTPAY,.DEP),VDA1(.fEFTHLD,.fEFTPAY,.DEP)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fEFTHLD,.fEFTPAY,.DEP)
	quit


VNEW(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) // Initialize arrays if %O=0
 
 do VDEF(.fEFTHLD,.fEFTPAY,.DEP)
 do VLOD(.fEFTHLD,.fEFTPAY,.DEP)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) // Display screen prompts
 set VO="16||13|0"
 set VO(0)="|0"
 set VO(1)=$C(3,5,19,1,0,0,0,0,0,0)_"01T Internal/External:"
 set VO(2)=$C(3,42,19,0,0,0,0,0,0,0)_"01T Sender Corr (53A):"
 set VO(3)=$C(4,8,16,1,52,0,0,0,0,0)_"01T Credit Account:"
 set VO(4)=$C(4,41,20,0,0,0,0,0,0,0)_"01TReceiver Corr (54A):"
 set VO(5)=$C(5,41,20,0,52,0,0,0,0,0)_"01TReceiver Corr (54B):"
 set VO(6)=$C(6,8,16,1,0,0,0,0,0,0)_"01T Generate MT103:"
 set VO(7)=$C(6,42,19,0,52,0,0,0,0,0)_"01TModify Party Ident:"
 set VO(8)=$C(7,8,16,1,52,0,0,0,0,0)_"01T Generate MT202:"
 set VO(9)=$C(8,7,17,1,0,0,0,0,0,0)_"01T Settlement Date:"
 set VO(10)=$C(8,46,15,0,0,0,0,0,0,0)_"01T Creation Date:"
 set VO(11)=$C(9,10,14,1,0,0,0,0,0,0)_"01T Payment Date:"
 set VO(12)=$C(9,49,12,0,52,0,0,0,0,0)_"01T Updated on:"
 set VO(13)=$C(11,3,20,0,0,0,0,0,0,0)_"01TOrdering Inst (52A):"
 set VO(14)=$C(11,41,20,0,0,0,0,0,0,0)_"01T Intermediary (56A):"
 set VO(15)=$C(17,3,21,0,52,0,0,0,0,0)_"01TReceiver/Destination:"
 set VO(16)=$C(17,42,19,0,52,0,0,0,0,0)_"01TSender to Rec (72):"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP)  // Display screen data
 new V
 s PARTYI=$G(PARTYI)
 //
 set VO="52|17|13|0"
 set VO(17)=$C(1,1,80,1,0,0,0,0,0,0)_"01T"_$S(%ProcessMode=5:"",1:$$BANNER^DBSGETID(%FN))
 set VO(18)=$C(3,25,1,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.INTEXT,1,1)
 set VO(19)=$C(3,62,12,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.SENDCORR,1,12)
 set VO(20)=$C(4,25,12,2,0,0,0,0,0,0)_"00N"_fEFTPAY.SENDNOS
 set VO(21)=$C(4,62,12,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECVCORR,1,12)
 set VO(22)=$C(5,62,17,2,0,0,0,0,0,0)_"01T"_$E(fEFTPAY.RECACCT,1,17)
 set VO(23)=$C(6,25,1,2,0,0,0,0,0,0)_"00L"_$S(fEFTPAY.MT103FLG:"Y",1:"N")
 set VO(24)=$C(6,62,1,2,0,0,0,0,0,0)_"00L"_$S($G(PARTYI):"Y",1:"N")
 set VO(25)=$C(7,25,1,2,0,0,0,0,0,0)_"00L"_$S(fEFTPAY.MT202FLG:"Y",1:"N")
 set VO(26)=$C(8,25,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fEFTPAY.EFD)
 set VO(27)=$C(8,62,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fEFTPAY.DATECRE)
 set VO(28)=$C(9,25,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fEFTPAY.PROCDT)
 set VO(29)=$C(9,62,10,2,0,0,0,0,0,0)_"01D"_$$DAT^%ZM(fEFTPAY.LCHDT)
 set VO(30)=$C(11,24,11,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.ORDINST,1,11)
 set VO(31)=$C(11,62,11,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.INTER,1,11)
 set VO(32)=$C(12,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.ORDINST1,1,35)
 set VO(33)=$C(12,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.INTER1,1,35)
 set VO(34)=$C(13,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.ORDINST2,1,35)
 set VO(35)=$C(13,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.INTER2,1,35)
 set VO(36)=$C(14,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.ORDINST3,1,35)
 set VO(37)=$C(14,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.INTER3,1,35)
 set VO(38)=$C(15,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.ORDINST4,1,35)
 set VO(39)=$C(15,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.INTER4,1,35)
 set VO(40)=$C(17,25,11,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECV,1,11)
 set VO(41)=$C(18,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECV1,1,35)
 set VO(42)=$C(18,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.MSGFP1,1,35)
 set VO(43)=$C(19,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECV2,1,35)
 set VO(44)=$C(19,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.MSGFP2,1,35)
 set VO(45)=$C(20,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECV3,1,35)
 set VO(46)=$C(20,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.MSGFP3,1,35)
 set VO(47)=$C(21,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECV4,1,35)
 set VO(48)=$C(21,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.MSGFP4,1,35)
 set VO(49)=$C(22,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECV5,1,35)
 set VO(50)=$C(22,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.MSGFP5,1,35)
 set VO(51)=$C(23,3,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.RECV6,1,35)
 set VO(52)=$C(23,42,35,2,0,0,0,0,0,0)_"00T"_$E(fEFTPAY.MSGFP6,1,35)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=35,VPT=1,VPB=23,PGM=$T(+0),DLIB="SYSDEV",DFID="EFTHLD,EFTPAY,DEP"
 set OLNTB=23042
 
 set VFSN("EFTPAY")="zfEFTPAY"
 //
 // 
	
	
 set %TAB(1)=$C(2,24,1)_"01T12434|1|[EFTPAY]INTEXT|,0#Internal - Vostro Account,1#External - Nostro Account||do VP1^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(2)=$C(2,61,12)_"00T12435|1|[EFTPAY]SENDCORR|[UTBLCORRE]||do VP2^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(3)=$C(3,24,12)_"01N12424|1|[EFTPAY]SENDNOS|||do VP3^V01S304(.fEFTHLD,.fEFTPAY,.DEP)|do VP4^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(4)=$C(3,61,12)_"00T12436|1|[EFTPAY]RECVCORR|||do VP5^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(5)=$C(4,61,17)_"20T12401|1|[EFTPAY]RECACCT|||||||||34"
 set %TAB(6)=$C(5,24,1)_"00L12403|1|[EFTPAY]MT103FLG"
 set %TAB(7)=$C(5,61,1)_"00L|*PARTYI|[*]@PARTYI|||do VP6^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(8)=$C(6,24,1)_"00L12401|1|[EFTPAY]MT202FLG"
 set %TAB(9)=$C(7,24,10)_"01D12408|1|[EFTPAY]EFD|||do VP7^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(10)=$C(7,61,10)_"20D12430|1|[EFTPAY]DATECRE"
 set %TAB(11)=$C(8,24,10)_"01D12417|1|[EFTPAY]PROCDT|||do VP8^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(12)=$C(8,61,10)_"20D12426|1|[EFTPAY]LCHDT"
 set %TAB(13)=$C(10,23,11)_"00T12401|1|[EFTPAY]ORDINST|[UTBLCORRE]||do VP9^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(14)=$C(10,61,11)_"00T12420|1|[EFTPAY]INTER|[UTBLCORRE]||do VP10^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(15)=$C(11,2,35)_"00T12402|1|[EFTPAY]ORDINST1|||do VP11^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(16)=$C(11,41,35)_"00T12438|1|[EFTPAY]INTER1|||do VP12^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(17)=$C(12,2,35)_"00T12403|1|[EFTPAY]ORDINST2|||do VP13^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(18)=$C(12,41,35)_"00T12439|1|[EFTPAY]INTER2|||do VP14^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(19)=$C(13,2,35)_"00T12404|1|[EFTPAY]ORDINST3|||do VP15^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(20)=$C(13,41,35)_"00T12440|1|[EFTPAY]INTER3|||do VP16^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(21)=$C(14,2,35)_"00T12405|1|[EFTPAY]ORDINST4|||do VP17^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(22)=$C(14,41,35)_"00T12441|1|[EFTPAY]INTER4|||do VP18^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(23)=$C(16,24,11)_"00T12421|1|[EFTPAY]RECV|[UTBLCORRE]||do VP19^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(24)=$C(17,2,35)_"00T12402|1|[EFTPAY]RECV1|||do VP20^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(25)=$C(17,41,35)_"00T12401|1|[EFTPAY]MSGFP1|||do VP21^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(26)=$C(18,2,35)_"00T12403|1|[EFTPAY]RECV2|||do VP22^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(27)=$C(18,41,35)_"00T12402|1|[EFTPAY]MSGFP2|||do VP23^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(28)=$C(19,2,35)_"00T12404|1|[EFTPAY]RECV3|||do VP24^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(29)=$C(19,41,35)_"00T12403|1|[EFTPAY]MSGFP3|||do VP25^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(30)=$C(20,2,35)_"00T12405|1|[EFTPAY]RECV4|||do VP26^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(31)=$C(20,41,35)_"00T12404|1|[EFTPAY]MSGFP4|||do VP27^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(32)=$C(21,2,35)_"00T12406|1|[EFTPAY]RECV5|||do VP28^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(33)=$C(21,41,35)_"00T12405|1|[EFTPAY]MSGFP5|||do VP29^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(34)=$C(22,2,35)_"00T12407|1|[EFTPAY]RECV6|||do VP30^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 set %TAB(35)=$C(22,41,35)_"00T12406|1|[EFTPAY]MSGFP6|||do VP31^V01S304(.fEFTHLD,.fEFTPAY,.DEP)"
 do VTBL(.fEFTHLD,.fEFTPAY,.DEP),VDEPRE(.fEFTHLD,.fEFTPAY,.DEP) if $G(ER) quit
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDEPRE(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP)  // Data Entry Pre-processor
 
 type public Boolean APPFLG
 
 if APPFLG.get() do { quit
 	do PROTECT^DBSMACRO("ALL")
 }
 
 if fEFTPAY.STATUS="V" do DEFAULT^DBSMACRO("EFTPAY.MT202FLG",$S(fEFTPAY.SENDCORR=fEFTPAY.RECV:0,1:1))
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Number X
 
 if X=0 do DEFAULT^DBSMACRO("EFTPAY.SENDCORR","")
 
 quit
VP2(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public String X
 
 do DEFAULT^DBSMACRO("EFTPAY.MT202FLG",$S(X=fEFTPAY.RECV:0,1:1))
VP3(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type Date PROCDT,VALDT
 type String RECACCT,SENDCORR
 
 type public Boolean ER
 type public Number X
 
 if X=fEFTPAY.CID do Runtime.setErrMSG("EFTPAY",7657) quit
 
 // Default SENDCORR
 set SENDCORR=fEFTPAY.SENDCORR
 do NOSIP^PROCEFT(.fEFTPAY)
 if ER quit
 
 if fEFTPAY.SENDCORR'=SENDCORR do DEFAULT^DBSMACRO("EFTPAY.SENDCORR",SENDCORR)
 
 // Validate SENDNOS and SENDCORR
 do NOSCHECK^PROCEFT(.fEFTPAY)
 if ER quit
 
 // Default PROCDT & EFD
 set PROCDT=fEFTPAY.PROCDT
 set VALDT=fEFTPAY.EFD
 do DATIP^PROCEFT(fEFTPAY.CRCD,fEFTPAY.EFTTYPE,fEFTPAY.SENDCORR,.PROCDT,.VALDT)
 if ER quit
 
 if fEFTPAY.PROCDT'=PROCDT do DEFAULT^DBSMACRO("EFTPAY.PROCDT",PROCDT)
 if fEFTPAY.EFD'=VALDT do DEFAULT^DBSMACRO("EFTPAY.EFD",VALDT)
 
 set RECACCT=$S(fEFTPAY.INTEXT=0:"/C"_X,1:"")
 if fEFTPAY.RECACCT'=RECACCT do DEFAULT^DBSMACRO("EFTPAY.RECACCT",RECACCT)
 
 quit
VP4(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type String CRCD,SETCRCD
 
 // Reset currency to EMU currency if SETCRCD=1
 set CRCD=fEFTPAY.CRCD
 set SETCRCD=fEFTPAY.SETCRCD
 if SETCRCD=1 set CRCD=CUVAR.emucrcd
 
 if fEFTPAY.INTEXT=0 do CHANGE^DBSMACRO("TBL","[DEP]")
 if fEFTPAY.INTEXT'=0 do CHANGE^DBSMACRO("TBL","[DEP]CORRE,[DEP]CRCD:QU ""[DEP]CRCD="_CRCD_"""")
 
 quit
VP5(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public String X
 
 if X=fEFTPAY.SENDCORR do DEFAULT^DBSMACRO("EFTPAY.SENDCORR","")
 
 quit
VP6(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Number X
 
 if X do {
 	do PID(.fEFTPAY)
 	set X=0
 	do VDA
 	do ^DBSPNT()
 	}
 
 quit
 
PID(RecordEFTPAY fEFTPAY) //
 type String SID
 
 do INIT^%ZM()
 set SID="INTPAYHQPI"
 do DRV^USID(%ProcessMode,SID,.fEFTPAY)

 quit
VP7(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 // Settlement date cannot be less than date of creation
 if X<fEFTPAY.DATECRE do Runtime.setErrMSG("EFTPAY",8368) quit
 
 // Validate EFD
 do DATCHK^PROCEFT(1,X,fEFTPAY.SENDCORR)
 if ER quit
 
 quit
VP8(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 // Process date cannot be greater than payment date
 if X>fEFTPAY.EFD do Runtime.setErrMSG("EFTPAY",7760) quit
 
 // Validate PROCDT
 do DATCHK^PROCEFT(0,X,fEFTPAY.SENDCORR)
 if ER quit
 
 quit
VP9(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 if X="" do GOTO^DBSMACRO("EFTPAY.ORDINST1") quit
 else  do GOTO^DBSMACRO("EFTPAY.RECV") quit
VP10(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do { quit
 	// Intermediary may not be present if BANKOP = SPRI
 	if (fEFTPAY.BANKOP="SPRI") do { quit
 		set X="" do DISPLAY^DBSMACRO("EFTPAY.INTER",fEFTPAY.INTER)
 		do Runtime.setErrMSG("EFTPAY",4616,fEFTPAY.BANKOP_"~56")
 		}
 	do CHECKUP^SWFTEDIT quit:ER
 	do GOTO^DBSMACRO("EFTPAY.MSGFP1") quit
 	}
 else  do GOTO^DBSMACRO("EFTPAY.INTER1") quit
 
 quit
VP11(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.ORDINST2") quit
VP12(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do { quit
 	// Intermediary may not be present if BANKOP = SPRI
 	if (fEFTPAY.BANKOP="SPRI") do { quit
 		set X="" do DISPLAY^DBSMACRO("EFTPAY.INTER1",fEFTPAY.INTER1)
 		do Runtime.setErrMSG("EFTPAY",4616,fEFTPAY.BANKOP_"~56")
 		}
 	do CHECKUP^SWFTEDIT quit:ER
 	do GOTO^DBSMACRO("EFTPAY.INTER2")
 	}
 
 do GOTO^DBSMACRO("EFTPAY.INTER2")
 
 quit
VP13(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.ORDINST3") quit
VP14(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do { quit
 	// Intermediary may not be present if BANKOP = SPRI
 	if (fEFTPAY.BANKOP="SPRI") do { quit
 		set X="" do DISPLAY^DBSMACRO("EFTPAY.INTER2",fEFTPAY.INTER2)
 		do Runtime.setErrMSG("EFTPAY",4616,fEFTPAY.BANKOP_"~56")
 		}
 	do CHECKUP^SWFTEDIT quit:ER
 	if (X=""),(fEFTPAY.INTER1'="") do Runtime.setErrMSG("EFTPAY",741) quit
 	do GOTO^DBSMACRO("EFTPAY.INTER3")
 	}
 
 if (X=""),(fEFTPAY.INTER1'="") do Runtime.setErrMSG("EFTPAY",741) quit
 do GOTO^DBSMACRO("EFTPAY.INTER3")
 
 quit
VP15(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.ORDINST4") quit
VP16(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do { quit
 	// Intermediary may not be present if BANKOP = SPRI
 	if (fEFTPAY.BANKOP="SPRI") do { quit
 		set X="" do DISPLAY^DBSMACRO("EFTPAY.INTER3",fEFTPAY.INTER3)
 		do Runtime.setErrMSG("EFTPAY",4616,fEFTPAY.BANKOP_"~56")
 		}
 	do CHECKUP^SWFTEDIT quit:ER
 	do GOTO^DBSMACRO("EFTPAY.INTER4")
 	}
 
 do GOTO^DBSMACRO("EFTPAY.INTER4")
 
 quit
VP17(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.RECV") quit
VP18(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do { quit
 	// Intermediary may not be present if BANKOP = SPRI
 	if (fEFTPAY.BANKOP="SPRI") do { quit
 		set X="" do DISPLAY^DBSMACRO("EFTPAY.INTER4",fEFTPAY.INTER4)
 		do Runtime.setErrMSG("EFTPAY",4616,fEFTPAY.BANKOP_"~56")
 		}
 	do CHECKUP^SWFTEDIT quit:ER
 	do GOTO^DBSMACRO("EFTPAY.MSGFP1")
 	}
 
 do GOTO^DBSMACRO("EFTPAY.MSGFP1")
 
 quit
VP19(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 do DEFAULT^DBSMACRO("EFTPAY.MT202FLG",$S(X=fEFTPAY.SENDCORR:0,1:1))
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 if X'="" do GOTO^DBSMACRO("EFTPAY.INTER") quit
 if X="" do GOTO^DBSMACRO("EFTPAY.RECV1") quit
VP20(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 if (X=""),(fEFTPAY.RECV="") do Runtime.setErrMSG("EFTPAY",741) quit
 do GOTO^DBSMACRO("EFTPAY.RECV2") quit
VP21(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X="" do GOTO^DBSMACRO("EFTPAY.MSGFP2") quit
 do MSGCHK1^PROCEFT
 if ER quit
 
 do GOTO^DBSMACRO("EFTPAY.MSGFP2") quit
VP22(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.RECV3") quit
VP23(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X="" do GOTO^DBSMACRO("EFTPAY.MSGFP3") quit
 do MSGCHK^PROCEFT(1,fEFTPAY.MSGFP2)
 if ER quit
 
 do GOTO^DBSMACRO("EFTPAY.MSGFP3") quit
VP24(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.RECV4") quit
VP25(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X="" do GOTO^DBSMACRO("EFTPAY.MSGFP4") quit
 do MSGCHK^PROCEFT(1,fEFTPAY.MSGFP3)
 if ER quit
 
 do GOTO^DBSMACRO("EFTPAY.MSGFP4") quit
VP26(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.RECV5") quit
VP27(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X="" do GOTO^DBSMACRO("EFTPAY.MSGFP5") quit
 do MSGCHK^PROCEFT(1,fEFTPAY.MSGFP4)
 if ER quit
 
 do GOTO^DBSMACRO("EFTPAY.MSGFP5") quit
VP28(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.RECV6") quit
VP29(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X="" do GOTO^DBSMACRO("EFTPAY.MSGFP6") quit
 do MSGCHK^PROCEFT(1,fEFTPAY.MSGFP5)
 if ER quit
 
 do GOTO^DBSMACRO("EFTPAY.MSGFP6") quit
VP30(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do GOTO^DBSMACRO("EFTPAY.INTER") quit
VP31(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP) //
 type public Boolean ER
 type public String X
 
 if X="" quit
 if X'="" do CHECKUP^SWFTEDIT quit:ER
 do MSGCHK^PROCEFT(1,fEFTPAY.MSGFP6)
 if ER quit
 
 do GOTO^DBSMACRO("END") quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordEFTHLD fEFTHLD
 type Public RecordEFTPAY fEFTPAY
 type Public RecordDEP DEP
 do VPR(.fEFTHLD,.fEFTPAY,.DEP)
 do VDA1(.fEFTHLD,.fEFTPAY,.DEP)
 do ^DBSPNT()
 quit

VW(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP)
 do VDA1(.fEFTHLD,.fEFTPAY,.DEP)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordEFTHLD fEFTHLD,RecordEFTPAY fEFTPAY,RecordDEP DEP)
 do VDA1(.fEFTHLD,.fEFTPAY,.DEP)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordEFTHLD fEFTHLD
 type Public RecordEFTPAY fEFTPAY
 type Public RecordDEP DEP
 do VDA1(.fEFTHLD,.fEFTPAY,.DEP)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordEFTHLD fEFTHLD
 if sn="EFTHLD" do vSET1(.fEFTHLD,di,X)
 type Public RecordEFTPAY fEFTPAY
 if sn="EFTPAY" do vSET2(.fEFTPAY,di,X)
 type Public RecordDEP DEP
 if sn="DEP" do vSET3(.DEP,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordEFTHLD fEFTHLD,di,X)
 do fEFTHLD.setAuditFlag(1)
 set fEFTHLD.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET2(RecordEFTPAY fEFTPAY,di,X)
 do fEFTPAY.setAuditFlag(1)
 set fEFTPAY.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET3(RecordDEP DEP,di,X)
 do DEP.setAuditFlag(1)
 set DEP.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordEFTHLD fEFTHLD
 if fid="EFTHLD" quit $$vREAD1(.fEFTHLD,di)
 type Public RecordEFTPAY fEFTPAY
 if fid="EFTPAY" quit $$vREAD2(.fEFTPAY,di)
 type Public RecordDEP DEP
 if fid="DEP" quit $$vREAD3(.DEP,di)
 quit ""
vREAD1(RecordEFTHLD fEFTHLD,di)
 quit fEFTHLD.@di
vREAD2(RecordEFTPAY fEFTPAY,di)
 quit fEFTPAY.@di
vREAD3(RecordDEP DEP,di)
 quit DEP.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
