V01S410(%ProcessMode,RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)   //PBS - LN - SID= <LNRNWOPT2> Loan Renewal Options Screen 2
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:59 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="LNRNWOPT2",VPGM=$T(+0),VSNAME="Loan Renewal Options Screen 2"
 set VFSN("CIF")="zCIF",VFSN("LNRENEW")="zfLNRNW"
 set vPSL=1
 set KEYS(1)=LN.CID
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fLNRNW,.LN,.CIF),VDA1(.fLNRNW,.LN,.CIF),^DBSPNT()

 if '%ProcessMode do VNEW(.fLNRNW,.LN,.CIF),VPR(.fLNRNW,.LN,.CIF),VDA1(.fLNRNW,.LN,.CIF)
 if %ProcessMode do VLOD(.fLNRNW,.LN,.CIF) quit:$G(ER)  do VPR(.fLNRNW,.LN,.CIF),VDA1(.fLNRNW,.LN,.CIF)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fLNRNW,.LN,.CIF)
	quit


VNEW(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) // Initialize arrays if %O=0
 
 do VDEF(.fLNRNW,.LN,.CIF)
 do VLOD(.fLNRNW,.LN,.CIF)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) // Display screen prompts
 set VO="28||13|0"
 set VO(0)="|0"
 set VO(1)=$C(2,6,13,1,0,0,0,0,0,0)_"01T Loan Number:"
 set VO(2)=$C(3,3,16,1,0,0,0,0,0,0)_"01T Renewal Option:"
 set VO(3)=$C(6,24,32,1,0,0,0,0,0,0)_"01T Adjustable Interest Parameters "
 set VO(4)=$C(8,14,13,0,0,0,0,0,0,0)_"01TNominal Rate:"
 set VO(5)=$C(8,52,15,0,0,0,0,0,0,0)_"01TEffective Rate:"
 set VO(6)=$C(9,4,23,0,0,0,0,0,0,0)_"01TInterest Review Offset:"
 set VO(7)=$C(9,35,32,0,0,0,0,0,0,0)_"01TInterest Review Offset Calendar:"
 set VO(8)=$C(10,12,15,0,0,0,0,0,0,0)_"01TInterest Index:"
 set VO(9)=$C(10,51,16,0,0,0,0,0,0,0)_"01TRounding Method:"
 set VO(10)=$C(11,12,15,0,0,0,0,0,0,0)_"01TInt/Div Spread:"
 set VO(11)=$C(11,52,15,0,0,0,0,0,0,0)_"01TInt/Div Matrix:"
 set VO(12)=$C(12,1,26,0,0,0,0,0,0,0)_"01TInt Rate Change Frequency:"
 set VO(13)=$C(12,41,26,0,0,0,0,0,0,0)_"01TInterest Rate Change Date:"
 set VO(14)=$C(13,4,23,0,0,0,0,0,0,0)_"01TInterest Change Method:"
 set VO(15)=$C(13,43,24,0,0,0,0,0,0,0)_"01TInt Determination Point:"
 set VO(16)=$C(14,4,23,0,0,0,0,0,0,0)_"01TAdjust Rate at Renewal:"
 set VO(17)=$C(14,47,20,0,0,0,0,0,0,0)_"01TRate Renewal Option:"
 set VO(18)=$C(16,32,15,1,0,0,0,0,0,0)_"01T Interest Rate "
 set VO(19)=$C(18,13,14,0,0,0,0,0,0,0)_"01TRate Schedule:"
 set VO(20)=$C(18,53,12,1,0,0,0,0,0,0)_"01T Per Change "
 set VO(21)=$C(18,67,10,1,0,0,0,0,0,0)_"01T Per Year "
 set VO(22)=$C(19,14,13,0,0,0,0,0,0,0)_"01TMaximum Rate:"
 set VO(23)=$C(19,40,12,0,0,0,0,0,0,0)_"01TMax Increase"
 set VO(24)=$C(20,14,13,0,0,0,0,0,0,0)_"01TMinimum Rate:"
 set VO(25)=$C(20,40,12,0,0,0,0,0,0,0)_"01TMin Increase"
 set VO(26)=$C(21,3,24,0,0,0,0,0,0,0)_"01TInt Accrual Calc Method:"
 set VO(27)=$C(21,40,12,0,0,0,0,0,0,0)_"01TMax Decrease"
 set VO(28)=$C(22,40,12,0,0,0,0,0,0,0)_"01TMin Decrease"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)  // Display screen data
 new V
 //
 set VO="55|29|13|0"
 set VO(29)=$C(2,20,12,2,0,0,0,0,0,0)_"01N"_fLNRNW.CID
 set VO(30)=$C(2,34,40,2,0,0,0,0,0,0)_"01T"_$E(CIF.NAM,1,40)
 set VO(31)=$C(3,20,3,2,0,0,0,0,0,0)_"01N"_fLNRNW.ROSEQ
 set V=$S(fLNRNW.IRN="":"",1:$J(fLNRNW.IRN,0,5)) set VO(32)=$C(8,28,8,2,0,0,0,0,0,0)_"00N"_$S(fLNRNW.IRN="":"",1:$J(fLNRNW.IRN,0,5))
 set V=$S(fLNRNW.EIRN="":"",1:$J(fLNRNW.EIRN,0,5)) set VO(33)=$C(8,68,8,2,0,0,0,0,0,0)_"00N"_$S(fLNRNW.EIRN="":"",1:$J(fLNRNW.EIRN,0,5))
 set VO(34)=$C(9,28,3,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTOFF
 set VO(35)=$C(9,68,6,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.INTOFFCL,1,6)
 set VO(36)=$C(10,28,20,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.INDEX,1,20)
 set VO(37)=$C(10,68,3,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.RNDMTD,1,3)
 set VO(38)=$C(11,28,9,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.INTSPR,1,9)
 set VO(39)=$C(11,68,12,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.INTMAT,1,12)
 set VO(40)=$C(12,28,12,2,0,0,0,0,0,0)_"00F"_$E(fLNRNW.INTFRE,1,12)
 set VO(41)=$C(12,68,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fLNRNW.ICHND)
 set VO(42)=$C(13,28,1,2,0,0,0,0,0,0)_"00N"_fLNRNW.ICHM
 set VO(43)=$C(13,68,1,2,0,0,0,0,0,0)_"00N"_fLNRNW.IDP
 set VO(44)=$C(14,28,1,2,0,0,0,0,0,0)_"00L"_$S(fLNRNW.RFMO:"Y",1:"N")
 set VO(45)=$C(14,68,1,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.RRMO,1,1)
 set VO(46)=$C(18,28,8,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.SCH,1,8)
 set VO(47)=$C(19,28,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMX
 set VO(48)=$C(19,55,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMXIC
 set VO(49)=$C(19,68,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMXIY
 set VO(50)=$C(20,28,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMN
 set VO(51)=$C(20,55,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMNIC
 set VO(52)=$C(21,28,2,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.IACM,1,2)
 set VO(53)=$C(21,55,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMXDC
 set VO(54)=$C(21,68,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMXDY
 set VO(55)=$C(22,55,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.INTMNDC
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=27,VPT=2,VPB=22,PGM=$T(+0),DLIB="SYSDEV",DFID="LNRENEW,LN,CIF"
 set OLNTB=22055
 
 set VFSN("CIF")="zCIF",VFSN("LNRENEW")="zfLNRNW"
 //
 // 
	
	
 set %TAB(1)=$C(1,19,12)_"21N12401|1|[LNRENEW]CID|[ACN]"
 set %TAB(2)=$C(1,33,40)_"21T12401|1|[CIF]NAM"
 set %TAB(3)=$C(2,19,3)_"21N12402|1|[LNRENEW]ROSEQ|||||||||12"
 set %TAB(4)=$C(7,27,8)_"00N12401|1|[LNRENEW]IRN|||do VP1^V01S410(.fLNRNW,.LN,.CIF)||||5"
 set %TAB(5)=$C(7,67,8)_"00N12412|1|[LNRENEW]EIRN|||do VP2^V01S410(.fLNRNW,.LN,.CIF)||||5"
 set %TAB(6)=$C(8,27,3)_"00N12406|1|[LNRENEW]INTOFF"
 set %TAB(7)=$C(8,67,6)_"00T12464|1|[LNRENEW]INTOFFCL|[UTBLNBD]"
 set %TAB(8)=$C(9,27,20)_"00T12401|1|[LNRENEW]INDEX|[INDEX]:QU ""[INDEX]DIAUTH'=1"":NOVAL"
 set %TAB(9)=$C(9,67,3)_"00T12467|1|[LNRENEW]RNDMTD"
 set %TAB(10)=$C(10,27,9)_"00T12466|1|[LNRENEW]INTSPR"
 set %TAB(11)=$C(10,67,12)_"00T12465|1|[LNRENEW]INTMAT|[UTBLMATATT]"
 set %TAB(12)=$C(11,27,12)_"00F12405|1|[LNRENEW]INTFRE|||do VP3^V01S410(.fLNRNW,.LN,.CIF)"
 set %TAB(13)=$C(11,67,10)_"00D12403|1|[LNRENEW]ICHND|||do VP4^V01S410(.fLNRNW,.LN,.CIF)"
 set %TAB(14)=$C(12,27,1)_"00N12443|1|[LNRENEW]ICHM|[STBLICHM]"
 set %TAB(15)=$C(12,67,1)_"00N12429|1|[LNRENEW]IDP|[STBLIDP]"
 set %TAB(16)=$C(13,27,1)_"00L12413|1|[LNRENEW]RFMO"
 set %TAB(17)=$C(13,67,1)_"00T12415|1|[LNRENEW]RRMO|[UTBLRRMO]"
 set %TAB(18)=$C(17,27,8)_"00T12409|1|[LNRENEW]SCH|[UTBLRATE]"
 set %TAB(19)=$C(18,27,8)_"00N12405|1|[LNRENEW]INTMX"
 set %TAB(20)=$C(18,54,8)_"00N12407|1|[LNRENEW]INTMXIC"
 set %TAB(21)=$C(18,67,8)_"00N12419|1|[LNRENEW]INTMXIY"
 set %TAB(22)=$C(19,27,8)_"00N12406|1|[LNRENEW]INTMN"
 set %TAB(23)=$C(19,54,8)_"00N12434|1|[LNRENEW]INTMNIC"
 set %TAB(24)=$C(20,27,2)_"00T12405|1|[LNRENEW]IACM|[UTBLIACML]"
 set %TAB(25)=$C(20,54,8)_"00N12409|1|[LNRENEW]INTMXDC"
 set %TAB(26)=$C(20,67,8)_"00N12420|1|[LNRENEW]INTMXDY"
 set %TAB(27)=$C(21,54,8)_"00N12435|1|[LNRENEW]INTMNDC"
 do VTBL(.fLNRNW,.LN,.CIF)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //
 /*
 -----Revision History---------------------------------------------------
 
 05/25/05 - MBUIM - CR15982
            Converted to PSL.
 */

 type RecordLNRENEW lnrenew=Db.getRecord("LNRENEW","CID=:CID,ROSEQ=:ROSEQ")

 // Enter effective rate or nominal rate, not both  
 if X'="",lnrenew.eirn'="" set ER=1,RM=$$^MSG(2444) quit

 quit

VP2(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //
 /*
 -----Revision History---------------------------------------------------
 
 05/25/05 - MBUIM - CR15982
            Converted to PSL.
 */

 type RecordLNRENEW lnrenew=Db.getRecord("LNRENEW","CID=:CID,ROSEQ=:ROSEQ")

 // Enter effective rate or nominal rate, not both
 if X'="",lnrenew.irn'="" set ER=1,RM=$$^MSG(2444) quit

 quit

VP3(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //
 /*
 -----Revision History---------------------------------------------------
 
 05/25/05 - MBUIM - CR15982
            Converted to PSL.
 */

 quit:X="" 

 type String DIST1FRE,DIST1ND,SCHLD,PCM,PCMVAL

 type RecordLNRENEW lnrenew=Db.getRecord("LNRENEW","CID=:CID,ROSEQ=:ROSEQ")

 set DIST1ND=LN.DIST1ND if lnrenew.dist1nd'="" set DIST1ND=lnrenew.dist1nd
 set DIST1FRE=LN.DIST1FRE if lnrenew.dist1fre'="" set DIST1FRE=lnrenew.dist1fre
 set PCM=LN.PCM if lnrenew.pcm'="" set PCM=lnrenew.pcm
 set SCHLD=LN.SCHLD
 set PCMVAL=$$PCMVAL^LNCDI(PCM)

 do INTFREF^LNPPC3(X,DIST1ND,PCMVAL,DIST1FRE,SCHLD)
 
 // Int/Div change frequency does not match master frequency
 if $G(ER) set RM=$$^MSG(3240) quit:ER 

 quit

VP4(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //
 /*
 -----Revision History---------------------------------------------------
 
 05/25/05 - MBUIM - CR15982
            Converted to PSL.
 */

 quit:X="" 

 type String DIST1FRE,DIST1ND,INTFRE,INTOFF,PCM,PCMVAL

 type RecordLNRENEW lnrenew=Db.getRecord("LNRENEW","CID=:CID,ROSEQ=:ROSEQ")
 
 set DIST1ND=LN.DIST1ND if lnrenew.dist1nd'="" set DIST1ND=lnrenew.dist1nd
 set DIST1FRE=LN.DIST1FRE if lnrenew.dist1fre'="" set DIST1FRE=lnrenew.dist1fre
 set INTFRE=LN.INTFRE if lnrenew.intfre'="" set INTFRE=lnrenew.intfre
 set INTOFF=LN.INTOFF if lnrenew.intoff'="" set INTOFF=lnrenew.intoff
 set PCM=LN.PCM if lnrenew.pcm'="" set PCM=lnrenew.pcm
 set PCMVAL=$$PCMVAL^LNCDI(PCM)

 // Int/Div change offset required with int/div change date 
 if INTOFF="" set ER=1 set RM=$$^MSG(3238) quit         

 // Int/Div change next date requires int/div change frequency
 if INTFRE="" set ER=1 set RM=$$^MSG(3215) quit         
 
 do ICHNDF^LNPPC3(X,DIST1ND,PCMVAL,DIST1FRE,INTFRE)

 // Int/Div change next date does not match master frequency
 if $G(ER) set RM=$$^MSG(3239) quit:ER  

 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordLNRENEW fLNRNW
 type Public RecordLN LN
 type Public RecordCIF CIF
 do VPR(.fLNRNW,.LN,.CIF)
 do VDA1(.fLNRNW,.LN,.CIF)
 do ^DBSPNT()
 quit

VW(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 do VDA1(.fLNRNW,.LN,.CIF)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 do VDA1(.fLNRNW,.LN,.CIF)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordLNRENEW fLNRNW
 type Public RecordLN LN
 type Public RecordCIF CIF
 do VDA1(.fLNRNW,.LN,.CIF)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordLNRENEW fLNRNW
 if sn="LNRENEW" do vSET1(.fLNRNW,di,X)
 type Public RecordLN LN
 if sn="LN" do vSET2(.LN,di,X)
 type Public RecordCIF CIF
 if sn="CIF" do vSET3(.CIF,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordLNRENEW fLNRNW,di,X)
 do fLNRNW.setAuditFlag(1)
 set fLNRNW.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET2(RecordLN LN,di,X)
 do LN.setAuditFlag(1)
 set LN.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET3(RecordCIF CIF,di,X)
 do CIF.setAuditFlag(1)
 set CIF.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordLNRENEW fLNRNW
 if fid="LNRENEW" quit $$vREAD1(.fLNRNW,di)
 type Public RecordLN LN
 if fid="LN" quit $$vREAD2(.LN,di)
 type Public RecordCIF CIF
 if fid="CIF" quit $$vREAD3(.CIF,di)
 quit ""
vREAD1(RecordLNRENEW fLNRNW,di)
 quit fLNRNW.@di
vREAD2(RecordLN LN,di)
 quit LN.@di
vREAD3(RecordCIF CIF,di)
 quit CIF.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
