V01S636(%ProcessMode,RecordUTBLCHKDEF2 fCHKDEF2)   // -  - SID= <UTBLCHKDEF2> Check Line Definition
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:54 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="UTBLCHKDEF2",VPGM=$T(+0),VSNAME="Check Line Definition"
 set VFSN("UTBLCHKDEF2")="zfCHKDEF2"
 set vPSL=1
 set KEYS(1)=fCHKDEF2.DEFCHK
 set KEYS(2)=fCHKDEF2.CHKLIN
 set KEYS(3)=fCHKDEF2.CHKCOL
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fCHKDEF2),VDA1(.fCHKDEF2),^DBSPNT()

 if '%ProcessMode do VNEW(.fCHKDEF2),VPR(.fCHKDEF2),VDA1(.fCHKDEF2)
 if %ProcessMode do VLOD(.fCHKDEF2) quit:$G(ER)  do VPR(.fCHKDEF2),VDA1(.fCHKDEF2)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fCHKDEF2)
	quit


VNEW(RecordUTBLCHKDEF2 fCHKDEF2) // Initialize arrays if %O=0
 
 do VDEF(.fCHKDEF2)
 do VLOD(.fCHKDEF2)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordUTBLCHKDEF2 fCHKDEF2)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordUTBLCHKDEF2 fCHKDEF2) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordUTBLCHKDEF2 fCHKDEF2) // Display screen prompts
 set VO="9||13|0"
 set VO(0)="|0"
 set VO(1)=$C(1,29,23,1,0,0,0,0,0,0)_"01T CHECK LINE DEFINITION "
 set VO(2)=$C(4,6,18,1,0,0,0,0,0,0)_"01T Check Definition:"
 set VO(3)=$C(6,18,6,1,0,0,0,0,0,0)_"01T Line:"
 set VO(4)=$C(8,4,20,1,0,0,0,0,0,0)_"01T Character Position:"
 set VO(5)=$C(11,8,16,1,0,0,0,0,0,0)_"01T Format Display:"
 set VO(6)=$C(13,16,8,1,0,0,0,0,0,0)_"01T Length:"
 set VO(7)=$C(15,5,19,0,0,0,0,0,0,0)_"01T Decimal Precision:"
 set VO(8)=$C(17,9,15,1,0,0,0,0,0,0)_"01T Variable Type:"
 set VO(9)=$C(19,9,15,1,0,0,0,0,0,0)_"01T Variable Name:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordUTBLCHKDEF2 fCHKDEF2)  // Display screen data
 new V
 //
 set VO="17|10|13|0"
 set VO(10)=$C(4,25,6,2,0,0,0,0,0,0)_"01T"_$E(fCHKDEF2.DEFCHK,1,6)
 set VO(11)=$C(6,25,12,2,0,0,0,0,0,0)_"01N"_fCHKDEF2.CHKLIN
 set VO(12)=$C(8,25,12,2,0,0,0,0,0,0)_"01N"_fCHKDEF2.CHKCOL
 set VO(13)=$C(11,25,12,2,0,0,0,0,0,0)_"00T"_$E(fCHKDEF2.DISP,1,12)
 set VO(14)=$C(13,25,3,2,0,0,0,0,0,0)_"00N"_fCHKDEF2.LGTH
 set VO(15)=$C(15,25,2,2,0,0,0,0,0,0)_"00N"_fCHKDEF2.DEC
 set VO(16)=$C(17,25,1,2,0,0,0,0,0,0)_"00N"_fCHKDEF2.VARTYP
 set VO(17)=$C(19,25,40,2,0,0,0,0,0,0)_"00T"_$E(fCHKDEF2.VARNAM,1,40)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordUTBLCHKDEF2 fCHKDEF2)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=8,VPT=1,VPB=19,PGM=$T(+0),DLIB="SYSDEV",DFID="UTBLCHKDEF2"
 set OLNTB=19025
 
 set VFSN("UTBLCHKDEF2")="zfCHKDEF2"
 //
 // 
	
	
 set %TAB(1)=$C(3,24,6)_"21T12401|1|[UTBLCHKDEF2]DEFCHK|[UTBLCHKDEF1]"
 set %TAB(2)=$C(5,24,12)_"21N12402|1|[UTBLCHKDEF2]CHKLIN"
 set %TAB(3)=$C(7,24,12)_"21N12403|1|[UTBLCHKDEF2]CHKCOL|[UTBLCHKDEF2]"
 set %TAB(4)=$C(10,24,12)_"01T12401|1|[UTBLCHKDEF2]DISP|[DBCTLDVFM]"
 set %TAB(5)=$C(12,24,3)_"01N12402|1|[UTBLCHKDEF2]LGTH"
 set %TAB(6)=$C(14,24,2)_"00N12403|1|[UTBLCHKDEF2]DEC|||||0|18|0"
 set %TAB(7)=$C(16,24,1)_"01N12404|1|[UTBLCHKDEF2]VARTYP|,1#Data Item,2#Text,3#Variable"
 set %TAB(8)=$C(18,24,40)_"01T12405|1|[UTBLCHKDEF2]VARNAM|||do VP1^V01S636(.fCHKDEF2)"
 do VTBL(.fCHKDEF2)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordUTBLCHKDEF2 fCHKDEF2) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordUTBLCHKDEF2 fCHKDEF2) //
	type public String X	

	// valid data item?

	if fCHKDEF2.chkcol=1 do PARSE^DBSDD(X)
	
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordUTBLCHKDEF2 fCHKDEF2
 do VPR(.fCHKDEF2)
 do VDA1(.fCHKDEF2)
 do ^DBSPNT()
 quit

VW(RecordUTBLCHKDEF2 fCHKDEF2)
 do VDA1(.fCHKDEF2)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordUTBLCHKDEF2 fCHKDEF2)
 do VDA1(.fCHKDEF2)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordUTBLCHKDEF2 fCHKDEF2
 do VDA1(.fCHKDEF2)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordUTBLCHKDEF2 fCHKDEF2
 if sn="UTBLCHKDEF2" do vSET1(.fCHKDEF2,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordUTBLCHKDEF2 fCHKDEF2,di,X)
 do fCHKDEF2.setAuditFlag(1)
 set fCHKDEF2.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordUTBLCHKDEF2 fCHKDEF2
 if fid="UTBLCHKDEF2" quit $$vREAD1(.fCHKDEF2,di)
 quit ""
vREAD1(RecordUTBLCHKDEF2 fCHKDEF2,di)
 quit fCHKDEF2.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
