V01S443(%ProcessMode,RecordSWIFT fSWIFT)   // -  - SID= <MT103PG5> Single Customer Credit Transfer Page 5
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:50 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab,SNDRCHG1,SNDRCHG2,SNDRCHG3,SNDRCHG4,SNDRCHG5,SNDRCHG6",VSID="MT103PG5",VPGM=$T(+0),VSNAME="Single Customer Credit Transfer Page 5"
 set VFSN("SWIFT")="zfSWIFT"
 set vPSL=1
 set KEYS(1)=fSWIFT.SWDIRECT
 set KEYS(2)=fSWIFT.TRREFNO
 set KEYS(3)=fSWIFT.MSG
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fSWIFT),VDA1(.fSWIFT),^DBSPNT()

 if '%ProcessMode do VNEW(.fSWIFT),VPR(.fSWIFT),VDA1(.fSWIFT)
 if %ProcessMode do VLOD(.fSWIFT) quit:$G(ER)  do VPR(.fSWIFT),VDA1(.fSWIFT)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fSWIFT)
	quit


VNEW(RecordSWIFT fSWIFT) // Initialize arrays if %O=0
 
 do VDEF(.fSWIFT)
 do VLOD(.fSWIFT)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordSWIFT fSWIFT)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordSWIFT fSWIFT) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordSWIFT fSWIFT) // Display screen prompts
 set VO="9||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,24,33,1,0,0,0,0,0,0)_"01T Single Customer Credit Transfer "
 set VO(2)=$C(3,25,12,0,0,0,0,0,0,0)_"01T Error Code:"
 set VO(3)=$C(4,24,13,0,0,0,0,0,0,0)_"01T Line Number:"
 set VO(4)=$C(6,3,31,0,0,0,0,0,0,0)_"01TO: 70 :  Remittance Information"
 set VO(5)=$C(6,36,1,0,0,0,0,0,0,0)_"01T:"
 set VO(6)=$C(10,3,34,0,0,0,0,0,0,0)_"01TM: 71A:  Details of Charges      :"
 set VO(7)=$C(11,3,34,0,0,0,0,0,0,0)_"01TO: 71F:  Sender's Charges        :"
 set VO(8)=$C(17,3,34,0,0,0,0,0,0,0)_"01TO: 71G:  Receiver's Charges      :"
 set VO(9)=$C(18,3,34,0,0,0,0,0,0,0)_"01TO: 72 :  Sender/Receiver         :"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordSWIFT fSWIFT)  // Display screen data
 new V
 s SNDRCHG1=$G(SNDRCHG1)
 s SNDRCHG2=$G(SNDRCHG2)
 s SNDRCHG3=$G(SNDRCHG3)
 s SNDRCHG4=$G(SNDRCHG4)
 s SNDRCHG5=$G(SNDRCHG5)
 s SNDRCHG6=$G(SNDRCHG6)
 //
 set VO="29|10|13|"
 set VO(10)=$C(3,38,4,0,0,0,0,0,0,0)_"01T"_$E(fSWIFT.ERCD,1,4)
 set VO(11)=$C(4,38,3,0,0,0,0,0,0,0)_"01N"_fSWIFT.LINENO
 set VO(12)=$C(6,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.DTLPMT1,1,35)
 set VO(13)=$C(7,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.DTLPMT2,1,35)
 set VO(14)=$C(8,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.DTLPMT3,1,35)
 set VO(15)=$C(9,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.DTLPMT4,1,35)
 set VO(16)=$C(10,38,10,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.DTLCHGS,1,10)
 set VO(17)=$C(11,38,18,0,0,0,0,0,0,0)_"00T"_$G(SNDRCHG1)
 set VO(18)=$C(12,38,18,0,0,0,0,0,0,0)_"00T"_$G(SNDRCHG2)
 set VO(19)=$C(13,38,18,0,0,0,0,0,0,0)_"00T"_$G(SNDRCHG3)
 set VO(20)=$C(14,38,18,0,0,0,0,0,0,0)_"00T"_$G(SNDRCHG4)
 set VO(21)=$C(15,38,18,0,0,0,0,0,0,0)_"00T"_$G(SNDRCHG5)
 set VO(22)=$C(16,38,18,0,0,0,0,0,0,0)_"00T"_$G(SNDRCHG6)
 set VO(23)=$C(17,38,18,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.RCVRCHG,1,18)
 set VO(24)=$C(18,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.BY1,1,35)
 set VO(25)=$C(19,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.BY2,1,35)
 set VO(26)=$C(20,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.BY3,1,35)
 set VO(27)=$C(21,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.BY4,1,35)
 set VO(28)=$C(22,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.BY5,1,35)
 set VO(29)=$C(23,38,35,0,0,0,0,0,0,0)_"00T"_$E(fSWIFT.BY6,1,35)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordSWIFT fSWIFT)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=20,VPT=1,VPB=23,PGM=$T(+0),DLIB="SYSDEV",DFID="SWIFT"
 set OLNTB=23038
 
 set VFSN("SWIFT")="zfSWIFT"
 //
 // 
	
	
 set %TAB(1)=$C(2,37,4)_"21T12403|1|[SWIFT]ERCD"
 set %TAB(2)=$C(3,37,3)_"21N12404|1|[SWIFT]LINENO"
 set %TAB(3)=$C(5,37,35)_"00T12401|1|[SWIFT]DTLPMT1"
 set %TAB(4)=$C(6,37,35)_"00T12402|1|[SWIFT]DTLPMT2"
 set %TAB(5)=$C(7,37,35)_"00T12403|1|[SWIFT]DTLPMT3"
 set %TAB(6)=$C(8,37,35)_"00T12404|1|[SWIFT]DTLPMT4"
 set %TAB(7)=$C(9,37,10)_"00T12401|1|[SWIFT]DTLCHGS"
 set %TAB(8)=$C(10,37,18)_"00T|*SNDRCHG1|[*]@SNDRCHG1||||do VP1^V01S443(.fSWIFT)"
 set %TAB(9)=$C(11,37,18)_"00T|*SNDRCHG2|[*]@SNDRCHG2"
 set %TAB(10)=$C(12,37,18)_"00T|*SNDRCHG3|[*]@SNDRCHG3"
 set %TAB(11)=$C(13,37,18)_"00T|*SNDRCHG4|[*]@SNDRCHG4"
 set %TAB(12)=$C(14,37,18)_"00T|*SNDRCHG5|[*]@SNDRCHG5"
 set %TAB(13)=$C(15,37,18)_"00T|*SNDRCHG6|[*]@SNDRCHG6"
 set %TAB(14)=$C(16,37,18)_"00T12403|1|[SWIFT]RCVRCHG"
 set %TAB(15)=$C(17,37,35)_"00T12401|1|[SWIFT]BY1"
 set %TAB(16)=$C(18,37,35)_"00T12402|1|[SWIFT]BY2"
 set %TAB(17)=$C(19,37,35)_"00T12403|1|[SWIFT]BY3"
 set %TAB(18)=$C(20,37,35)_"00T12404|1|[SWIFT]BY4"
 set %TAB(19)=$C(21,37,35)_"00T12405|1|[SWIFT]BY5"
 set %TAB(20)=$C(22,37,35)_"00T12406|1|[SWIFT]BY6"
 do VTBL(.fSWIFT)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordSWIFT fSWIFT) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordSWIFT fSWIFT) //
 ; Set Sender's Charges local variables
 set sndrchg=$$MULT2^SWIFTCDI(fSWIFT.swdirect,fSWIFT.freeptr,"71F")
 set SNDRCHG1=$P(sndrchg,$C(13,10),1)
 set SNDRCHG2=$P(sndrchg,$C(13,10),2)
 set SNDRCHG3=$P(sndrchg,$C(13,10),3)
 set SNDRCHG4=$P(sndrchg,$C(13,10),4)
 set SNDRCHG5=$P(sndrchg,$C(13,10),5)
 set SNDRCHG6=$P(sndrchg,$C(13,10),6)
 Q
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordSWIFT fSWIFT
 do VPR(.fSWIFT)
 do VDA1(.fSWIFT)
 do ^DBSPNT()
 quit

VW(RecordSWIFT fSWIFT)
 do VDA1(.fSWIFT)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordSWIFT fSWIFT)
 do VDA1(.fSWIFT)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordSWIFT fSWIFT
 do VDA1(.fSWIFT)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordSWIFT fSWIFT
 if sn="SWIFT" do vSET1(.fSWIFT,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordSWIFT fSWIFT,di,X)
 do fSWIFT.setAuditFlag(1)
 set fSWIFT.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordSWIFT fSWIFT
 if fid="SWIFT" quit $$vREAD1(.fSWIFT,di)
 quit ""
vREAD1(RecordSWIFT fSWIFT,di)
 quit fSWIFT.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
