V01S564(%ProcessMode,RecordSTBLIAM UTBL)   // -  - SID= <STBLIAM> Ins Add-On/Disc Methods
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:52 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="STBLIAM",VPGM=$T(+0),VSNAME="Ins Add-On/Disc Methods"
 set VFSN("STBLIAM")="zUTBL"
 set vPSL=1
 set KEYS(1)=UTBL.KEY
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.UTBL),VDA1(.UTBL),^DBSPNT()

 if '%ProcessMode do VNEW(.UTBL),VPR(.UTBL),VDA1(.UTBL)
 if %ProcessMode do VLOD(.UTBL) quit:$G(ER)  do VPR(.UTBL),VDA1(.UTBL)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.UTBL)
	quit


VNEW(RecordSTBLIAM UTBL) // Initialize arrays if %O=0
 
 do VDEF(.UTBL)
 do VLOD(.UTBL)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordSTBLIAM UTBL)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordSTBLIAM UTBL) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordSTBLIAM UTBL) // Display screen prompts
 set VO="3||13|"
 set VO(0)="12|0"
 set VO(1)=$C(12,11,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(2)=$C(13,16,8,0,0,0,0,0,0,0)_"01T Method:"
 set VO(3)=$C(14,2,22,1,0,0,0,0,0,0)_"01T Advance First Period:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordSTBLIAM UTBL)  // Display screen data
 new V
 //
 set VO="6|4|13|"
 set VO(4)=$C(12,25,40,2,0,0,0,0,0,0)_"00T"_$E(UTBL.DESC,1,40)
 set VO(5)=$C(13,25,8,2,0,0,0,0,0,0)_"00N"_UTBL.METHOD
 set VO(6)=$C(14,25,1,2,0,0,0,0,0,0)_"00L"_$S(UTBL.BES:"Y",1:"N")
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordSTBLIAM UTBL)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=3,VPT=12,VPB=14,PGM=$T(+0),DLIB="SYSDEV",DFID="STBLIAM"
 set OLNTB=14025
 
 set VFSN("STBLIAM")="zUTBL"
 //
 // 
	
	
 set %TAB(1)=$C(11,24,40)_"01T12401|1|[STBLIAM]DESC"
 set %TAB(2)=$C(12,24,8)_"00N12402|1|[STBLIAM]METHOD|[STBLAOAMO]"
 set %TAB(3)=$C(13,24,1)_"00L12403|1|[STBLIAM]BES"
 do VTBL(.UTBL)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordSTBLIAM UTBL) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordSTBLIAM UTBL
 do VPR(.UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT()
 quit

VW(RecordSTBLIAM UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordSTBLIAM UTBL)
 do VDA1(.UTBL)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordSTBLIAM UTBL
 do VDA1(.UTBL)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordSTBLIAM UTBL
 if sn="STBLIAM" do vSET1(.UTBL,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordSTBLIAM UTBL,di,X)
 do UTBL.setAuditFlag(1)
 set UTBL.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordSTBLIAM UTBL
 if fid="STBLIAM" quit $$vREAD1(.UTBL,di)
 quit ""
vREAD1(RecordSTBLIAM UTBL,di)
 quit UTBL.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
