V01S610(%ProcessMode,RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())   //PBS - LN - SID= <USRFRE2A> Irregular Frequency - Changes Yearly
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:53 - shetyes
 // /* 
 // This screen contains fields used to specify attributes for irregular user
 // frequencies that change yearly (Type 2).  It is the first of two linked screens
 // displayed when a user runs the New User-Defined Frequency (UFRE001),
 // User-Defined Frequency Maintenance (UFRE002), User-Defined Frequency Inquiry
 // (UFRE003), or User-Defined Frequency Deletion (UFRE004) function for a
 // frequency type of 2.
 // See the Frequencies/Calendars Manual for further information.
 // */
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab,YEAR,MOREP,COPY",VSID="USRFRE2A",VPGM=$T(+0),VSNAME="Irregular Frequency - Changes Yearly"
 set VFSN("USRFRE")="zfUSRFRE",VFSN("USRFRER")="zfUSRFRER"
 set vPSL=1
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 set %MODS=1,%REPEAT=15 do VPR(.fUSRFRE,.fUSRFRER()),VDA1(.fUSRFRE,.fUSRFRER()),V5^DBSPNT quit

 if '%ProcessMode do VNEW(.fUSRFRE,.fUSRFRER()),VPR(.fUSRFRE,.fUSRFRER()),VDA1(.fUSRFRE,.fUSRFRER())
 if %ProcessMode do VLOD(.fUSRFRE,.fUSRFRER()) quit:$G(ER)  do VPR(.fUSRFRE,.fUSRFRER()),VDA1(.fUSRFRE,.fUSRFRER())

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fUSRFRE,.fUSRFRER())
	quit


VNEW(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER()) // Initialize arrays if %O=0
 
 do VDEF(.fUSRFRE,.fUSRFRER())
 do VLOD(.fUSRFRE,.fUSRFRER())
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())
 if fUSRFRE.BD="" set fUSRFRE.BD="A"
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER()) // Load data from disc - %O = (1-5)
 if '$D(%REPEAT) set %REPEAT=15
 if '$D(%MODS) set %MODS=1
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER()) // Display screen prompts
 set VO="8||13|"
 set VO(0)="|0"
 set VO(1)=$C(1,22,38,1,0,0,0,0,0,0)_"01T Irregular Frequency - Changes Yearly "
 set VO(2)=$C(3,13,10,0,0,0,0,0,0,0)_"01TFrequency:"
 set VO(3)=$C(3,63,6,1,0,0,0,0,0,0)_"01T Year:"
 set VO(4)=$C(4,10,13,1,0,0,0,0,0,0)_"01T Description:"
 set VO(5)=$C(4,57,12,0,0,0,0,0,0,0)_"01T More Pages:"
 set VO(6)=$C(5,1,22,1,0,0,0,0,0,0)_"01T Business Date Option:"
 set VO(7)=$C(5,45,24,0,0,0,0,0,0,0)_"01TNumber of Years to Copy:"
 set VO(8)=$C(6,51,18,0,0,0,0,0,0,0)_"01T Ending Frequency:"
 if '$D(%MODS) set %MODS=1
 set DY=8 for I=%MODS:1:%REPEAT+%MODS-1 do VRPR(.fUSRFRE,.fUSRFRER())
 set VO=(+VO)_"|"_(VO+1)_"|13" quit  // BOD pointer
 
VRPR(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())  // Display prompts %REPEAT times
 
 set VO(VO+1)=$C(DY,15,1,0,0,0,0,0,0,0)_"01T:"
 set VO=VO+1,DY=DY+1
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())  // Display screen data
 new V
 s COPY=$G(COPY)
 s MOREP=$G(MOREP)
 s YEAR=$G(YEAR)
 //
 set VX=$P(VO,"|",2)
 set VO(VX+0)=$C(3,24,12,2,0,0,0,0,0,0)_"01T"_$E(fUSRFRE.UFRE,1,12)
 set VO(VX+1)=$C(3,70,4,2,0,0,0,0,0,0)_"00N"_$G(YEAR)
 set VO(VX+2)=$C(4,24,30,2,0,0,0,0,0,0)_"00T"_$E(fUSRFRE.DESC,1,30)
 set VO(VX+3)=$C(4,70,1,2,0,0,0,0,0,0)_"00L"_$S($G(MOREP):"Y",1:"N")
 set VO(VX+4)=$C(5,24,1,2,0,0,0,0,0,0)_"00U"_$E(fUSRFRE.BD,1,1)
 set VO(VX+5)=$C(5,70,2,2,0,0,0,0,0,0)_"00N"_$G(COPY)
 set VO(VX+6)=$C(6,70,11,2,0,0,0,0,0,0)_"00F"_$E(fUSRFRE.ENDF,1,12)
  
 set:'$D(%MODS) %MODS=1 set VX=$P(VO,"|",2)+6,DY=8 for I=%MODS:1:%REPEAT+%MODS-1 do VRDA(.fUSRFRE,.fUSRFRER())
 set $piece(VO,"|",1)=VX quit  // EOD pointer
 
VRDA(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())  // Display data %REPEAT times
 //instantiate new object if necessary
  if 'fUSRFRER(I).getPointer() do {
     set fUSRFRER(I)=Class.new("RecordUSRFRER","")
     }
 set VO(VX+1)=$C(DY,5,10,2,0,0,0,0,0,0)_"01T"_$E(fUSRFRER(I).MONNAME,1,10)
 set VO(VX+2)=$C(DY,20,2,2,0,0,0,0,0,0)_"00T"_$E(fUSRFRER(I).DATE1,1,2)
 set VO(VX+3)=$C(DY,30,2,2,0,0,0,0,0,0)_"00T"_$E(fUSRFRER(I).DATE2,1,2)
 set VO(VX+4)=$C(DY,40,2,2,0,0,0,0,0,0)_"00T"_$E(fUSRFRER(I).DATE3,1,2)
 set VO(VX+5)=$C(DY,50,2,2,0,0,0,0,0,0)_"00T"_$E(fUSRFRER(I).DATE4,1,2)
 set VO(VX+6)=$C(DY,60,2,2,0,0,0,0,0,0)_"00T"_$E(fUSRFRER(I).DATE5,1,2)
 set VO(VX+7)=$C(DY,70,2,2,0,0,0,0,0,0)_"00T"_$E(fUSRFRER(I).DATE6,1,2)
 set DY=DY+1,VX=VX+7
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab set %MODGRP=1
 set %MODOFF=7,%MOD=7,%MAX=(%MOD*%REPEAT)+%MODOFF,VPT=1,VPB=7+%REPEAT,BLKSIZ=(22*%REPEAT)+62,PGM=$T(+0),DLIB="SYSDEV",DFID="USRFRE,USRFRER",VSCRPP=1,VSCRPP=1
 set OLNTB=VPB*1000
 
 set VFSN("USRFRE")="zfUSRFRE",VFSN("USRFRER")="zfUSRFRER"
 //
 for I=15:1:%MAX set %TAB(I)=""
	
	
 set %TAB(1)=$C(2,23,12)_"21T12401|1|[USRFRE]UFRE"
 set %TAB(2)=$C(2,69,4)_"01N|*YEAR|[*]@YEAR|||do VP1^V01S610(.fUSRFRE,.fUSRFRER)"
 set %TAB(3)=$C(3,23,30)_"01T12401||[USRFRE]DESC"
 set %TAB(4)=$C(3,69,1)_"00L|*MOREP|[*]@PAG|||do VP2^V01S610(.fUSRFRE,.fUSRFRER)"
 set %TAB(5)=$C(4,23,1)_"01U12407||[USRFRE]BD|[STBLBUSOPT]"
 set %TAB(6)=$C(4,69,2)_"00N|*COPY|[*]@COPY"
 set %TAB(7)=$C(5,69,11)_"00F12408||[USRFRE]ENDF|||do VP3^V01S610(.fUSRFRE,.fUSRFRER)||||||12"
 set %TAB(8)=$C(7,4,10)_"20T12401|1|[USRFRER]MONNAME"
 set %TAB(9)=$C(7,19,2)_"00T12402|1|[USRFRER]DATE1||if X?1""e""!(X?1""E"")!(X?1N.N)|||1"
 set %TAB(10)=$C(7,29,2)_"00T12403|1|[USRFRER]DATE2||if X?1""e""!(X?1""E"")!(X?1N.N)|||1"
 set %TAB(11)=$C(7,39,2)_"00T12404|1|[USRFRER]DATE3||if X?1""e""!(X?1""E"")!(X?1N.N)|||1"
 set %TAB(12)=$C(7,49,2)_"00T12405|1|[USRFRER]DATE4||if X?1""e""!(X?1""E"")!(X?1N.N)|||1"
 set %TAB(13)=$C(7,59,2)_"00T12406|1|[USRFRER]DATE5||if X?1""e""!(X?1""E"")!(X?1N.N)|||1"
 set %TAB(14)=$C(7,69,2)_"00T12407|1|[USRFRER]DATE6||if X?1""e""!(X?1""E"")!(X?1N.N)|||1"
 do VTBL(.fUSRFRE,.fUSRFRER())
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER()) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VSPP   // screen post proc
 type Public RecordUSRFRE fUSRFRE
 type Public RecordUSRFRER fUSRFRER()
 do VSPP1(.fUSRFRE,.fUSRFRER())
 #ACCEPT Date=11/05/03; pgm=Screen Compilerxxx
 quit
VSPP1(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())
 /*
  ---- Revision History ------------------------------------------------
 
        12/03/05 - TITOVE - CR 17040
                   Converted into PSL.
 */
 type public Number COPY, ER, YEAR
 type Number II, YY
 do SPP^USRFRE(.fUSRFRER()) quit:ER
 type Number FAF
 if COPY set YY = YEAR for II = YY:1:(YY + (COPY - 1)) do { quit:ER
        set YEAR = YEAR + 1
        do SPP^USRFRE(.fUSRFRER()) quit:ER
        }
 set COPY = ""
 
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER()) //
 /*
  ---- Revision History ------------------------------------------------
 
        12/03/05 - TITOVE - CR 17040
                   Converted into PSL.
 */
 type public Number ER, X

 if 'X quit
 
 // Enter four-digit year
 if (X.length() '= 4) do Runtime.setErrSTBLER("USRFRE","UFRE001") quit:ER
 
 quit
 
VP2(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER()) //
 if X,%PAGE=%PG set %PAGE=%PG+1
 if 'X set %PAGE=TPG

 quit

VP3(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER()) //
 do VPO1(.fUSRFRE,.fUSRFRER())

 quit

VPO1(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())  // user library FRE_TYPE2
 /*
 ---- Revision History ------------------------------------------------
 
        01/29/05 - TITOVE - CR 13727
                   Converted into PSL.
 
 */
 type public Number ER
 type public String X
 if 'X.length() quit
 type RecordUSRFRE usrfre = Db.getRecord("USRFRE", "UFRE = :X",1)
 // Cannot enter another type 2 frequency
 if usrfre.fretyp = 2 do Runtime.setErrSTBLER("USRFRE","UFRE002") quit:ER
 quit
 #ACCEPT DATE=11/05/03;pgm=screen compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordUSRFRE fUSRFRE
 type Public RecordUSRFRER fUSRFRER()
 do VPR(.fUSRFRE,.fUSRFRER())
 do VDA1(.fUSRFRE,.fUSRFRER())
 do ^DBSPNT()
 quit

VW(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())
 do VDA1(.fUSRFRE,.fUSRFRER())
 do ^DBSPNT(10)
 quit

VDAPNT(RecordUSRFRE fUSRFRE,RecordUSRFRER fUSRFRER())
 do VDA1(.fUSRFRE,.fUSRFRER())
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordUSRFRE fUSRFRE
 type Public RecordUSRFRER fUSRFRER()
 do VDA1(.fUSRFRE,.fUSRFRER())
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordUSRFRE fUSRFRE
 if sn="USRFRE" do vSET1(.fUSRFRE,di,X)
 type Public RecordUSRFRER fUSRFRER()
 if sn="USRFRER" do vSET2(fUSRFRER(I(1)),di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordUSRFRE fUSRFRE,di,X)
 do fUSRFRE.setAuditFlag(1)
 set fUSRFRE.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET2(RecordUSRFRER fUSRFRER,di,X)
 do fUSRFRER.setAuditFlag(1)
 set fUSRFRER.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordUSRFRE fUSRFRE
 if fid="USRFRE" quit $$vREAD1(.fUSRFRE,di)
 type Public RecordUSRFRER fUSRFRER()
 if fid="USRFRER" quit $$vREAD2(fUSRFRER(I(1)),di)
 quit ""
vREAD1(RecordUSRFRE fUSRFRE,di)
 quit fUSRFRE.@di
vREAD2(RecordUSRFRER fUSRFRER,di)
 quit fUSRFRER.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
