V01S411(%ProcessMode,RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)   //PBS - LN - SID= <LNRNWOPT3> Loan Renewal Options Screen 3
 ;;Copyright(c)2007 Sanchez Computer Associates, Inc.  All Rights Reserved - 01/31/2007 11:59 - shetyes
  /*
ORIG: CHENARDP - 03/03/2003
DESC: PSL Screen Compiler Template

---- Comments --------------------------------------------------------
	This procedure is used as the base template for the PSL screen compiler.
	It is referenced by the PSL screen compiler - procedure DBS2PSL4
	
	
---- Revision History ------------------------------------------------
	02/23/06 - Pete Chenard - CR19551
		   Fixed routine label.
		   
	05/19/05 - Pete Chenard - CR 14146
		   Modified to type variables.
		   
	12/1/03 - Spier -cr7178
	   	     Modifications to correct dead code warnings and
	   	     other issues that occurred during mass compile of screens.

	09/24/03 - Pete Chenard - 45497
		       Created screen template for compiler.
----------------------------------------------------------------------

 */

 #WARN SCOPE OFF
	type Public String %MODS,%PAGE,%PG,%REPEAT,ER,RM
	type String KEYS(),KVAR,VFSN(),VO,VODFT,VPGM,vPSL,VSID,VSNAME

	// %O (0-Create  1-Modify  2-Inquiry  3-Delete  4-Print  5-Blank screen)

	set:'$D(%ProcessMode) %ProcessMode=5
 set KVAR="kill %TAB,VFSN,VO,VPTBL,vtab",VSID="LNRNWOPT3",VPGM=$T(+0),VSNAME="Loan Renewal Options Screen 3"
 set VFSN("CIF")="zCIF",VFSN("LNRENEW")="zfLNRNW"
 set vPSL=1
 set KEYS(1)=LN.CID
 //
	// ==================== Display blank screen         (%O=5)

 if %ProcessMode=5 do VPR(.fLNRNW,.LN,.CIF),VDA1(.fLNRNW,.LN,.CIF),^DBSPNT()

 if '%ProcessMode do VNEW(.fLNRNW,.LN,.CIF),VPR(.fLNRNW,.LN,.CIF),VDA1(.fLNRNW,.LN,.CIF)
 if %ProcessMode do VLOD(.fLNRNW,.LN,.CIF) quit:$G(ER)  do VPR(.fLNRNW,.LN,.CIF),VDA1(.fLNRNW,.LN,.CIF)

	// ====================  Display Form
	do ^DBSPNT()
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	if %ProcessMode=2!(%ProcessMode=3) do ^DBSCRT8A X:'$D(%PAGE) KVAR quit  // Inquiry/Delete
	// ====================  Set up data entry control table


 if %ProcessMode<2 do VTAB(.fLNRNW,.LN,.CIF)
	quit


VNEW(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) // Initialize arrays if %O=0
 
 do VDEF(.fLNRNW,.LN,.CIF)
 do VLOD(.fLNRNW,.LN,.CIF)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
VDEF(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 ;
VLOD(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) // Load data from disc - %O = (1-5)
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	type Public String %MODS,%REPEAT
	quit
	

VPR(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) // Display screen prompts
 set VO="27||13|0"
 set VO(0)="|0"
 set VO(1)=$C(2,6,13,1,0,0,0,0,0,0)_"01T Loan Number:"
 set VO(2)=$C(3,3,16,1,0,0,0,0,0,0)_"01T Renewal Option:"
 set VO(3)=$C(6,25,31,1,0,0,0,0,0,0)_"01T Adjustable Payment Parameters "
 set VO(4)=$C(8,7,22,0,0,0,0,0,0,0)_"01TPayment Change Method:"
 set VO(5)=$C(8,37,27,0,0,0,0,0,0,0)_"01TPayment Calculation Method:"
 set VO(6)=$C(9,7,22,0,0,0,0,0,0,0)_"01TPayment Change Offset:"
 set VO(7)=$C(9,39,25,0,0,0,0,0,0,0)_"01TPayment Change Frequency:"
 set VO(8)=$C(10,4,25,0,0,0,0,0,0,0)_"01TPayment Change Next Date:"
 set VO(9)=$C(10,41,23,0,0,0,0,0,0,0)_"01TFixed Principal Amount:"
 set VO(10)=$C(11,1,28,0,0,0,0,0,0,0)_"01TInt Annuity Compound Factor:"
 set VO(11)=$C(11,42,22,0,0,0,0,0,0,0)_"01TFixed Interest Amount:"
 set VO(12)=$C(12,52,12,0,0,0,0,0,0,0)_"01TP&I Payment:"
 set VO(13)=$C(13,9,20,0,0,0,0,0,0,0)_"01TBilling Date Offset:"
 set VO(14)=$C(13,38,26,0,0,0,0,0,0,0)_"01TRe-Amortization Frequency:"
 set VO(15)=$C(14,10,19,0,0,0,0,0,0,0)_"01TRecalculation Base:"
 set VO(16)=$C(14,40,24,0,0,0,0,0,0,0)_"01TMaximum Amount Increase:"
 set VO(17)=$C(15,3,26,0,0,0,0,0,0,0)_"01TAdjust Payment at Renewal:"
 set VO(18)=$C(15,40,24,0,0,0,0,0,0,0)_"01TMaximum Amount Decrease:"
 set VO(19)=$C(16,4,25,0,0,0,0,0,0,0)_"01TUnscheduled Prin Penalty:"
 set VO(20)=$C(16,45,19,0,0,0,0,0,0,0)_"01TMaximum % Increase:"
 set VO(21)=$C(17,7,22,0,0,0,0,0,0,0)_"01TPayoff Penalty Method:"
 set VO(22)=$C(17,45,19,0,0,0,0,0,0,0)_"01TMaximum % Decrease:"
 set VO(23)=$C(18,11,18,0,0,0,0,0,0,0)_"01TMaximum Loan Term:"
 set VO(24)=$C(18,40,24,0,0,0,0,0,0,0)_"01TMinimum Amount Increase:"
 set VO(25)=$C(19,12,17,0,0,0,0,0,0,0)_"01TPayment Due Date:"
 set VO(26)=$C(19,40,24,0,0,0,0,0,0,0)_"01TMinimum Amount Decrease:"
 set VO(27)=$C(20,10,19,0,0,0,0,0,0,0)_"01TPrepayment Allowed:"
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VDA1(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)  // Display screen data
 new V
 //
 set VO="54|28|13|0"
 set VO(28)=$C(2,20,12,2,0,0,0,0,0,0)_"01N"_fLNRNW.CID
 set VO(29)=$C(2,34,40,2,0,0,0,0,0,0)_"01T"_$E(CIF.NAM,1,40)
 set VO(30)=$C(3,20,3,2,0,0,0,0,0,0)_"01N"_fLNRNW.ROSEQ
 set VO(31)=$C(8,30,1,2,0,0,0,0,0,0)_"00N"_fLNRNW.PCHM
 set VO(32)=$C(8,65,3,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.PCM,1,3)
 set VO(33)=$C(9,30,3,2,0,0,0,0,0,0)_"00N"_fLNRNW.PCOFF
 set VO(34)=$C(9,65,12,2,0,0,0,0,0,0)_"00F"_$E(fLNRNW.PCFRE,1,12)
 set VO(35)=$C(10,30,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fLNRNW.PCHND)
 set V=$S(fLNRNW.FPA="":"",1:$J(fLNRNW.FPA,0,2)) set VO(36)=$C(10,65,12,2,0,0,0,0,0,0)_"00$"_$S(fLNRNW.FPA="":"",1:$J(fLNRNW.FPA,0,2))
 set VO(37)=$C(11,30,1,2,0,0,0,0,0,0)_"00N"_fLNRNW.IACF
 set V=$S(fLNRNW.FIA="":"",1:$J(fLNRNW.FIA,0,2)) set VO(38)=$C(11,65,12,2,0,0,0,0,0,0)_"00$"_$S(fLNRNW.FIA="":"",1:$J(fLNRNW.FIA,0,2))
 set V=$S(fLNRNW.PMTPI="":"",1:$J(fLNRNW.PMTPI,0,2)) set VO(39)=$C(12,65,12,2,0,0,0,0,0,0)_"00$"_$S(fLNRNW.PMTPI="":"",1:$J(fLNRNW.PMTPI,0,2))
 set VO(40)=$C(13,30,3,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.BLOFF,1,3)
 set VO(41)=$C(13,65,12,2,0,0,0,0,0,0)_"00F"_$E(fLNRNW.RAFRE,1,12)
 set VO(42)=$C(14,30,1,2,0,0,0,0,0,0)_"00N"_fLNRNW.PRCB
 set V=$S(fLNRNW.PMXDIC="":"",1:$J(fLNRNW.PMXDIC,0,2)) set VO(43)=$C(14,65,12,2,0,0,0,0,0,0)_"00$"_$S(fLNRNW.PMXDIC="":"",1:$J(fLNRNW.PMXDIC,0,2))
 set VO(44)=$C(15,30,1,2,0,0,0,0,0,0)_"00L"_$S(fLNRNW.RPMO:"Y",1:"N")
 set V=$S(fLNRNW.PMXDDC="":"",1:$J(fLNRNW.PMXDDC,0,2)) set VO(45)=$C(15,65,12,2,0,0,0,0,0,0)_"00$"_$S(fLNRNW.PMXDDC="":"",1:$J(fLNRNW.PMXDDC,0,2))
 set VO(46)=$C(16,30,6,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.UPPEN,1,6)
 set VO(47)=$C(16,65,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.PMXPIC
 set VO(48)=$C(17,30,12,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.EPPENMET,1,12)
 set VO(49)=$C(17,65,8,2,0,0,0,0,0,0)_"00N"_fLNRNW.PMXPDC
 set VO(50)=$C(18,30,8,2,0,0,0,0,0,0)_"00T"_$E(fLNRNW.TRMMX,1,8)
 set V=$S(fLNRNW.PMNDIC="":"",1:$J(fLNRNW.PMNDIC,0,2)) set VO(51)=$C(18,65,12,2,0,0,0,0,0,0)_"00$"_$S(fLNRNW.PMNDIC="":"",1:$J(fLNRNW.PMNDIC,0,2))
 set VO(52)=$C(19,30,10,2,0,0,0,0,0,0)_"00D"_$$DAT^%ZM(fLNRNW.DIST1ND)
 set V=$S(fLNRNW.PMNDDC="":"",1:$J(fLNRNW.PMNDDC,0,2)) set VO(53)=$C(19,65,12,2,0,0,0,0,0,0)_"00$"_$S(fLNRNW.PMNDDC="":"",1:$J(fLNRNW.PMNDDC,0,2))
 set VO(54)=$C(20,30,1,2,0,0,0,0,0,0)_"00N"_fLNRNW.PPF
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
	
	
VTAB(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 
 kill VSCRPP,REQ,%TAB,%MOD,%MODOFF,%MODGRP,%REPREQ,vtab
 set %MAX=27,VPT=2,VPB=20,PGM=$T(+0),DLIB="SYSDEV",DFID="LNRENEW,LN,CIF"
 set OLNTB=20030
 
 set VFSN("CIF")="zCIF",VFSN("LNRENEW")="zfLNRNW"
 //
 // 
	
	
 set %TAB(1)=$C(1,19,12)_"21N12401|1|[LNRENEW]CID|[ACN]"
 set %TAB(2)=$C(1,33,40)_"21T12401|1|[CIF]NAM"
 set %TAB(3)=$C(2,19,3)_"21N12402|1|[LNRENEW]ROSEQ|||||||||12"
 set %TAB(4)=$C(7,29,1)_"00N12429|1|[LNRENEW]PCHM|[STBLPCHM]"
 set %TAB(5)=$C(7,64,3)_"00T12428|1|[LNRENEW]PCM|[UTBLPCM]"
 set %TAB(6)=$C(8,29,3)_"00N12438|1|[LNRENEW]PCOFF"
 set %TAB(7)=$C(8,64,12)_"00F12427|1|[LNRENEW]PCFRE|[USRFRE]||do VP1^V01S411(.fLNRNW,.LN,.CIF)"
 set %TAB(8)=$C(9,29,10)_"00D12436|1|[LNRENEW]PCHND|||do VP2^V01S411(.fLNRNW,.LN,.CIF)"
 set %TAB(9)=$C(9,64,12)_"00$12413|1|[LNRENEW]FPA|||||||2"
 set %TAB(10)=$C(10,29,1)_"00N12417|1|[LNRENEW]IACF|[STBLIACF]"
 set %TAB(11)=$C(10,64,12)_"00$12412|1|[LNRENEW]FIA|||||||2"
 set %TAB(12)=$C(11,64,12)_"00$12407|1|[LNRENEW]PMTPI|||||||2"
 set %TAB(13)=$C(12,29,3)_"00T12408|1|[LNRENEW]BLOFF||if X?.N!(X=""1P"")|do VP3^V01S411(.fLNRNW,.LN,.CIF)"
 set %TAB(14)=$C(12,64,12)_"00F12444|1|[LNRENEW]RAFRE|[USRFRE]"
 set %TAB(15)=$C(13,29,1)_"00N12403|1|[LNRENEW]PRCB|[STBLPRCB]"
 set %TAB(16)=$C(13,64,12)_"00$12411|1|[LNRENEW]PMXDIC|||||||2"
 set %TAB(17)=$C(14,29,1)_"00L12414|1|[LNRENEW]RPMO"
 set %TAB(18)=$C(14,64,12)_"00$12413|1|[LNRENEW]PMXDDC|||||||2"
 set %TAB(19)=$C(15,29,6)_"00T12409|1|[LNRENEW]UPPEN|[UTBLLNPPN]"
 set %TAB(20)=$C(15,64,8)_"00N12415|1|[LNRENEW]PMXPIC"
 set %TAB(21)=$C(16,29,12)_"00T12402|1|[LNRENEW]EPPENMET|[UTBLLNPPN]"
 set %TAB(22)=$C(16,64,8)_"00N12417|1|[LNRENEW]PMXPDC"
 set %TAB(23)=$C(17,29,8)_"00T12404|1|[LNRENEW]TRMMX"
 set %TAB(24)=$C(17,64,12)_"00$12440|1|[LNRENEW]PMNDIC|||||||2"
 set %TAB(25)=$C(18,29,10)_"00D12402|1|[LNRENEW]DIST1ND"
 set %TAB(26)=$C(18,64,12)_"00$12441|1|[LNRENEW]PMNDDC|||||||2"
 set %TAB(27)=$C(19,29,1)_"00N12402|1|[LNRENEW]PPF|[STBLPPF]"
 do VTBL(.fLNRNW,.LN,.CIF)
	do ^DBSCRT8 	// data entry
	quit


VREQ   // Create REQ() array
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


VTBL(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //Create %TAB(array)
 	// 1 2 3  4 5   6   7-9 10-11
 	// DY,DX,SZ PT REQ TYPE DEL POS |NODE|ITEM NAME|TBL|FMT|PP|PRE|MIN|MAX|DEC

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit


  //user-defined post procs
 //
VP1(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //
 /*
 
    ---- Revision History------------------------------------------------
 
         05/26/05 - SWARNALATHA P - CR 15982
         Converted to PSL
 
    ---------------------------------------------------------------------
 */

 type Date DIST1ND,ICHND,SCHLD
 type Number INTOFF,PCHM
 type String DIST1FRE,INTFRE,PCM,PCMVAL

 if X.isNull() quit

 type RecordLN ln=Db.getRecord("LN","CID=:CID")

 set DIST1ND=ln.dist1nd
 if 'fLNRNW.dist1nd.isNull() set DIST1ND=fLNRNW.DIST1ND

 set DIST1FRE=ln.dist1fre
 if 'fLNRNW.dist1fre.isNull() set DIST1FRE=fLNRNW.DIST1FRE

 set PCHM=ln.pchm 
 if 'fLNRNW.PCHM.isNull() set PCHM=fLNRNW.PCHM

 set INTFRE=ln.intfre 
 if 'fLNRNW.INTFRE.isNull() set INTFRE=fLNRNW.INTFRE

 set ICHND=ln.ichnd 
 if 'fLNRNW.ICHND.isNull() set ICHND=fLNRNW.ICHND

 set INTOFF=ln.intoff 
 if 'fLNRNW.INTOFF.isNull() set INTOFF=fLNRNW.INTOFF

 set PCM=ln.pcm
 if 'fLNRNW.PCM.isNull() set PCM=fLNRNW.PCM

 set SCHLD=ln.schld
 set PCMVAL=$$PCMVAL^LNCDI(PCM)

 // Payment change frequency requires int/div change next date 
 if ICHND.isNull() do Runtime.setErrMSG("LNICNV", 3216) quit

 do PCFREF^LNPPC3(X,DIST1ND,DIST1FRE,PCHM,INTFRE,ICHND,SCHLD)
 // Payment change frequency does not match master frequency
 if ER.get() S RM=$$^MSG(3242) quit
VP2(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //
 /*
 
    ---- Revision History------------------------------------------------
 
         05/26/05 - SWARNALATHA P - CR 15982
         Converted to PSL
 
    ---------------------------------------------------------------------
 */
 
 type public Boolean ER
 type public String X

 type Date DIST1ND,ICHND
 type Number PCHM,PCOFF
 type String DIST1FRE,INTFRE,PCFRE,PCM

 if X.isNull() quit

 type RecordLN ln=Db.getRecord("LN","CID=:CID")

 set DIST1ND=ln.dist1nd 
 if 'fLNRNW.dist1nd.isNull() set DIST1ND=fLNRNW.DIST1ND

 set INTFRE=ln.intfre 
 if 'fLNRNW.intfre.isNull() set INTFRE=fLNRNW.INTFRE

 set PCFRE=ln.pcfre 
 if 'fLNRNW.PCFRE.isNull() set PCFRE=fLNRNW.PCFRE

 set ICHND=ln.ichnd 
 if 'fLNRNW.ICHND.isNull() set ICHND=fLNRNW.ICHND

 set DIST1FRE=ln.dist1fre 
 if 'fLNRNW.DIST1FRE.isNull() set DIST1FRE=fLNRNW.DIST1FRE

 set PCHM=ln.pchm 
 if 'fLNRNW.PCHM.isNull() set PCHM=fLNRNW.PCHM

 set PCOFF=ln.pcoff 
 if 'fLNRNW.PCOFF.isNull() set PCOFF=fLNRNW.PCOFF

 S PCM=ln.pcm 
 if 'fLNRNW.PCM.isNull() set PCM=fLNRNW.PCM

 // Payment change next date requires payment change frequency
 if PCFRE.isNull() do Runtime.setErrMSG("LNICNV", 3217) quit

 // Payment change offset required with payment change date
 if PCOFF.isNull() do Runtime.setErrMSG("LNICNV", 3237) quit

 do PCHNDF^LNPPC3(X,DIST1ND,INTFRE,PCFRE,ICHND,DIST1FRE,PCHM)
 // Payment change next date does not match master frequency
 if ER.get() set RM=$$^MSG(3241) quit

 quit
VP3(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF) //
 /*
 
    ---- Revision History------------------------------------------------
 
         05/26/05 - SWARNALATHA P - CR 15982
         Converted to PSL
 
    ---------------------------------------------------------------------
 */

 if %O do VPO1(.fLNRNW,.LN,.CIF)

 quit
VPO1(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)  // user library LN_BLOFF
 
 /*
 
    ---- Revision History------------------------------------------------
 
         05/26/05 - SWARNALATHA P - CR 15982
         Converted to PSL
 
    ---------------------------------------------------------------------
 */
 type public Boolean ER
 type public Date OBD,OBO,NBD
 type public String X,V
 
 if X'=V,LN.bndt,X="1P"!(X?.N) do { quit:ER
        // May not transfer from/to frequency "1P" on other than payment date
 	if X="1P"!(V="1P"),TJD'=LN.schld set ER=1,ET="LNBLOFF3" do ^UTLERR quit
 	
        // Find previous value of next billing date and billing offset
 	set OBD=$SELECT(UX("LN","BNDT").data():UX("LN","BNDT").piece("|",1),1:+LN.bndt)
 	set OBO=$SELECT(UX("LN","BLOFF").data():UX("LN","BLOFF").piece("|",1),1:V)
 
   	if '(X="1P"!(V="1P")) do { quit:ER
		// Determine whether or not change is allowed
 		// New billing offset must be greater than 0
 		if X'>0 set ER=1,ET="LNBLOFF4" do ^UTLERR quit
 
 		//Find (A) last billing date
 		set A=$SELECT(UX("LN","BLDT").data():UX("LN","BLDT").piece("|",2),1:LN.bldt)
 
 		// May not change billing offset if currently in offset period
 		if LN.bseq,A+OBO>TJD set ER=1,ET="LNBLOFF1" do ^UTLERR quit
 
 		// Invalid if change would put account in billing offset period
 		if OBD+OBO-X<TJD set ER=1,ET="LNBLOFF2" do ^UTLERR quit
        	}
 	set NBD=$SELECT(X="1P":LN.schnd,1:(OBD+OBO-X))
        do DEFAULT^DBSMACRO("LN.bndt",NBD,"1","0","0")
	}
 quit
 #ACCEPT DATE=11/05/03;pgm=screen compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit								// User defined post processor's


VRV(V,L) quit V_$J("",L-$L(V))
VREPRNT
 type Public RecordLNRENEW fLNRNW
 type Public RecordLN LN
 type Public RecordCIF CIF
 do VPR(.fLNRNW,.LN,.CIF)
 do VDA1(.fLNRNW,.LN,.CIF)
 do ^DBSPNT()
 quit

VW(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 do VDA1(.fLNRNW,.LN,.CIF)
 do ^DBSPNT(10)
 quit

VDAPNT(RecordLNRENEW fLNRNW,RecordLN LN,RecordCIF CIF)
 do VDA1(.fLNRNW,.LN,.CIF)
 do ^DBSPNT(0,2)
 quit

VDA
 type Public RecordLNRENEW fLNRNW
 type Public RecordLN LN
 type Public RecordCIF CIF
 do VDA1(.fLNRNW,.LN,.CIF)
 quit

	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
 
vSET(sn,di,X)
 type Public RecordLNRENEW fLNRNW
 if sn="LNRENEW" do vSET1(.fLNRNW,di,X)
 type Public RecordLN LN
 if sn="LN" do vSET2(.LN,di,X)
 type Public RecordCIF CIF
 if sn="CIF" do vSET3(.CIF,di,X)
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET1(RecordLNRENEW fLNRNW,di,X)
 do fLNRNW.setAuditFlag(1)
 set fLNRNW.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET2(RecordLN LN,di,X)
 do LN.setAuditFlag(1)
 set LN.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
vSET3(RecordCIF CIF,di,X)
 do CIF.setAuditFlag(1)
 set CIF.@di=X
 #ACCEPT Date=11/5/03;PGM=Screen Compiler
 quit
	
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
vREAD(fid,di)
 type Public RecordLNRENEW fLNRNW
 if fid="LNRENEW" quit $$vREAD1(.fLNRNW,di)
 type Public RecordLN LN
 if fid="LN" quit $$vREAD2(.LN,di)
 type Public RecordCIF CIF
 if fid="CIF" quit $$vREAD3(.CIF,di)
 quit ""
vREAD1(RecordLNRENEW fLNRNW,di)
 quit fLNRNW.@di
vREAD2(RecordLN LN,di)
 quit LN.@di
vREAD3(RecordCIF CIF,di)
 quit CIF.@di
	#ACCEPT DATE=11/05/03; PGM=Screen Compiler
	quit
