ZFIL	 // 
 // ORIG: myersk - 05/15/2000
 // DESC: Routines for Blank Fill and Zero Fill
 // 
 // ---- Comments --------------------------------------------------------
 // 
 // ---- Revision History ------------------------------------------------
 // 
        quit

        //--------------------------------------------------------------
BLK(VAL,N)     // fill the field with blank space
        //--------------------------------------------------------------
 
        if $L(VAL)>N quit $E(VAL,1,N)
         quit VAL_$E($J(" ",N),1,N-$L(VAL))

        //-------------------------------------------------------------
ZERO(VAL,N,DEC)         // fill the field with leading zeros
        //-------------------------------------------------------------
        new FCT,I
         if '$D(DEC) set FCT=1,DEC=0
         else  set FCT=10**DEC
         set VAL=$$^SCARND(VAL,,,,DEC)
         set VAL=VAL*FCT
         if $L(VAL)>N set RM="Value ~"_VAL_" larger than "_N do EXC set VAL=0
         for I=1:1:N-$L(VAL) set VAL="0"_VAL
         quit VAL
        //---------------------------------------------------------------
EXC     // log error to DAYEND
         if $G(RM)="" set RM=$G(ET)
         if $G(NOT)="" set NOT="*"
         do LOG^UTLEXC($T(+0),NOT,$G(DESC),$G(XCID,$G(CID)),$G(%ZTSEQ),$G(RM))
         kill ET,%ZTSEQ
         quit

vSIG()	quit "59892^37407^Laura Hillanbrand^1293"	// Signature - LTD^TIME^USER^SIZE
